### ISSUE TITLE
An unexpected error occurred while connecting.

### ISSUE THREAD

**Issue by gerrydoro** [microsoft/azuredatastudio#10122]
Issue Type: <b>Bug</b>

From renderer1.log

```
[2020-04-22 13:57:27.535] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:MOMDB|server:10.10.55.40\MSSQL2016|user:sa|databaseDisplayName:MOMDB|group:C777F06B-202E-4480-B475-FA416154D458
[2020-04-22 13:57:27.535] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:MOMDB|server:10.10.55.40\MSSQL2016|user:sa|databaseDisplayName:MOMDB|group:C777F06B-202E-4480-B475-FA416154D458
[2020-04-22 13:57:33.697] [renderer1] [info] Deleting connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:MOMDB|server:10.10.55.40\MSSQL2016|user:sa|databaseDisplayName:MOMDB|group:C777F06B-202E-4480-B475-FA416154D458
[2020-04-22 13:57:33.706] [renderer1] [error] OnConnectionComplete but no connection found 'connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:MOMDB|server:10.10.55.40\MSSQL2016|user:sa|databaseDisplayName:MOMDB|group:C777F06B-202E-4480-B475-FA416154D458' Connections = []
[2020-04-22 13:57:33.721] [renderer1] [error] Unexpected error occurred while connecting.: Error: Unexpected error occurred while connecting.
    at m.onConnectionComplete (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2153:841) [<root>]
    at e.onConnectionComplete (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5250:250) [<root>]
    at w.$onConnectionComplete (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:4481:977) [<root>]
    at g._doInvokeHandler (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:4570:363) [<root>]
    at g._invokeHandler (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:4570:55) [<root>]
    at g._receiveRequest (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:4568:739) [<root>]
    at g._receiveOneMessage (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:4567:518) [<root>]
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:4565:754 [<root>]
    at c.fire (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:206:102) [<root>]
    at v.fire (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:553:801) [<root>]
    at t.PersistentProtocol._receiveMessage (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:558:276) [<root>]
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:555:321 [<root>]
    at c.fire (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:206:102) [<root>]
    at g.acceptChunk (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:551:306) [<root>]
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:550:657 [<root>]
    at Socket.t (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:561:450) [<root>]
    at Socket.ZoneTask.invoke (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:485:48) [<root>]
    at Socket.emit (events.js:203:13) [<root>]
    at addChunk (_stream_readable.js:295:12) [<root>]
    at readableAddChunk (_stream_readable.js:276:11) [<root>]
    at Socket.Readable.push (_stream_readable.js:210:10) [<root>]
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17) [<root>]
```

Azure Data Studio version: azuredatastudio 1.16.1 (16801c522df68e63218b39ccb5b4a7431f9bf667, 2020-03-23T22:08:06.892Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.98GB (2.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
deletedb|Ale|0.0.3
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.46.0
dacpac|Mic|1.3.0
import|Mic|0.14.0
managed-instance-dashboard|Mic|0.4.1
profiler|Mic|0.11.0
schema-compare|Mic|1.3.0
vscodeintellicode|Vis|1.2.1

(1 theme extensions excluded)

</details>

**Comment by gerrydoro** [comment]
This happened when i tried to connect to a server with its SQL Server service stopped.
I don't know if this can be considered as a bug, the app asked me to file this issue.

**Comment by kburtram** [comment]
@gerrydoro thanks for filing the issue.  Perhaps we should have a better error message to handle this scenario, since it seems like a somewhat common experience that a user may try to connect to an offline server in some cases.

**Comment by kburtram** [comment]
Closing this as connections are expected to fail.  I looked at another issue today that was reporting a similar problem when the server shuts down while connected.  The fix for that should also improve the experience with this scenario.  Thanks for reporting this issue.
