### ISSUE TITLE
Issue on ADS startup

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#10291]
Latest master

```
  ERR Assertion Failed: argument is undefined or null: Error: Assertion Failed: argument is undefined or null
    at Object.assertIsDefined (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/base/common/types.js:86:19) [<root>]
    at PanelPart.createComposite (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/workbench/browser/parts/compositePart.js:89:149) [<root>]
    at PanelPart.doOpenComposite (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/workbench/browser/parts/compositePart.js:56:36) [<root>]
    at PanelPart.openComposite (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/workbench/browser/parts/compositePart.js:43:25) [<root>]
    at PanelPart.doOpenPanel (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/workbench/browser/parts/panel/panelPart.js:313:29) [<root>]
    at PanelPart.onDidRegisterPanels (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/workbench/browser/parts/panel/panelPart.js:110:38) [<root>]
    at file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/workbench/browser/parts/panel/panelPart.js:181:74 [<root>]
    at Emitter.fire (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/base/common/event.js:457:42) [<root>]
    at PanelRegistry.registerComposite (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/workbench/browser/composite.js:205:33) [<root>]
    at PanelRegistry.registerPanel (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/workbench/browser/panel.js:32:19) [<root>]
    at ViewsService.registerPanel (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/workbench/browser/parts/views/viewsService.js:375:67) [<root>]
    at ViewsService.registerViewletOrPanel (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/workbench/browser/parts/views/viewsService.js:331:30) [<root>]
    at ViewsService.onDidRegisterViewContainer (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/workbench/browser/parts/views/viewsService.js:98:22) [<root>]
    at file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/workbench/browser/parts/views/viewsService.js:38:89 [<root>]
    at Array.forEach (<anonymous>) [<root>]
    at new ViewsService (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/workbench/browser/parts/views/viewsService.js:38:59) [<root>]
    at InstantiationService._createInstance (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/platform/instantiation/common/instantiationService.js:88:20) [<root>]
    at InstantiationService._createServiceInstance (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/platform/instantiation/common/instantiationService.js:177:29) [<root>]
    at InstantiationService._createServiceInstanceWithOwner (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/platform/instantiation/common/instantiationService.js:165:29) [<root>]
    at InstantiationService._createAndCacheServiceInstance (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/platform/instantiation/common/instantiationService.js:156:43) [<root>]
    at InstantiationService._getOrCreateServiceInstance (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/platform/instantiation/common/instantiationService.js:113:29) [<root>]
    at Object.get (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/platform/instantiation/common/instantiationService.js:36:45) [<root>]
    at Workbench.initLayout (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/workbench/browser/layout.js:146:22) [<root>]
    at file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/workbench/browser/workbench.js:67:26 [<root>]
    at InstantiationService.invokeFunction (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/platform/instantiation/common/instantiationService.js:43:24) [<root>]
    at Workbench.startup (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/workbench/browser/workbench.js:61:38) [<root>]
    at DesktopMain.open (file:///C:/Users/amomidi/Documents/azuredatastudio-insiders/out/vs/workbench/electron-browser/desktop.main.js:61:52) [<root>]
````

**Comment by kburtram** [comment]
@aaomidi for some reason I'm not seeing this exception on startup.  Any other useful repro steps you can think of?

**Comment by aaomidi** [comment]
@kburtram I'm even seeing it on our test runs.

e.g.: https://github.com/microsoft/azuredatastudio/pull/10285/checks?check_run_id=651041062#step:12:33

**Comment by aaomidi** [comment]
Fixed by https://github.com/microsoft/vscode/commit/635fc326c9d98ddafeb7e0c847af87c78f096178
