### ISSUE TITLE
Failed to change Kernel 

### ISSUE THREAD

**Issue by camille-rodriguez** [microsoft/azuredatastudio#10429]
- Azure Data Studio Version:
1.17.1

Steps to Reproduce:

1. I run on ubuntu 20.04, and when installing the kernel for Spark | Scala, dependencies installed correctly but it failed to change kernel with this error code :
```
Failed to change kernel. Kernel SQL will be used. Error was: Notebook process exited prematurely with error code: 1. StdErr Output: Traceback (most recent call last):
  File "/home/crodriguez/azuredatastudio-python/0.0.1/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/home/crodriguez/azuredatastudio-python/0.0.1/lib/python3.6/site-packages/notebook/notebookapp.py", line 49, in <module>
    from zmq.eventloop import ioloop
  File "/home/crodriguez/azuredatastudio-python/0.0.1/lib/python3.6/site-packages/zmq/__init__.py", line 42, in <module>
    _load_libzmq()
  File "/home/crodriguez/azuredatastudio-python/0.0.1/lib/python3.6/site-packages/zmq/__init__.py", line 9, in _load_libzmq
    import sys, ctypes, platform, os
  File "/home/crodriguez/azuredatastudio-python/0.0.1/lib/python3.6/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```

**Comment by camille-rodriguez** [comment]
I tried to install libffi-dev and re-install the python environment, and it did not work. My workaround is to use the system python (3.8.2) and I was able to get the dependencies worked out. It looks like there is a python bug with 3.6, I was looking into this https://bugs.python.org/issue31652 , so maybe it would be good for AzureDataStudio to install a newer version than 3.6 when making a virtual environment.

**Comment by chlafreniere** [comment]
@camille-rodriguez thanks for the in-depth analysis here. Moving to the newest version of 3.6 is on our roadmap.

**Comment by stratosgear** [comment]
@camille-rodriguez: How did you "My workaround is to use the system python (3.8.2)"?

I have the same issue on arch!

**Comment by camille-rodriguez** [comment]
Hi @stratosgear !
So when you change the kernel (in my case, from SQL to Spark | Scala), the window that appears on the side lets you choose either to do a new installation type (default, 1st option), or to select an existing installation. The issue arises from the fact that if you choose New Python Installation, Azure Studio installs a version of python 3.6 that evidently fails for some of us. So, you can install python on your own (if not installed by default in your system), and choose that python install with the second option  "Use existing python location" and by selecting the proper location. 
![image](https://user-images.githubusercontent.com/42066843/82223409-3fe49100-98e8-11ea-85f5-466e63a95664.png)

I hope this was helpful!

**Comment by stratosgear** [comment]
Aaaahhh, you are talking about the notebook kernel, ok...

I get the exception on Data Studio startup when the postgres extension is loading.   

I was hoping for a way to "globally" instruct Data Studio to use another version of python.  

I have no: `"/usr/local/lib/python3.6/dist-packages/cx_Freeze/initscripts/__startup__.py"` files or paths on my system, so no idea where Data Studio tries to load those scripts!

So I guess I am stuck!  Thanks for coming back for this!

**Comment by MsSQLGirl** [comment]
I have similar issues when installing on Linux Ubuntu 20.04.

**Here's my error message:** 

Failed to change kernel. Kernel SQL will be used. Error was: Notebook process exited prematurely with error code: 1. StdErr Output: Traceback (most recent call last):
  File "/home/mssqlgirl/azuredatastudio-python/0.0.1/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/home/mssqlgirl/azuredatastudio-python/0.0.1/lib/python3.6/site-packages/notebook/notebookapp.py", line 49, in <module>
    from zmq.eventloop import ioloop
  File "/home/mssqlgirl/azuredatastudio-python/0.0.1/lib/python3.6/site-packages/zmq/__init__.py", line 42, in <module>
    _load_libzmq()
  File "/home/mssqlgirl/azuredatastudio-python/0.0.1/lib/python3.6/site-packages/zmq/__init__.py", line 9, in _load_libzmq
    import sys, ctypes, platform, os
  File "/home/mssqlgirl/azuredatastudio-python/0.0.1/lib/python3.6/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory


**The Output terminal shows the following**
Notebook dependencies installation is in progress
Downloading python package (0 / 557.49 MB)
Downloading python package (55.75 / 557.49 MB)
Downloading python package (111.51 / 557.49 MB)
Downloading python package (167.26 / 557.49 MB)
Downloading python package (223.01 / 557.49 MB)
Downloading python package (278.76 / 557.49 MB)
Downloading python package (334.50 / 557.49 MB)
Downloading python package (390.25 / 557.49 MB)
Downloading python package (446.00 / 557.49 MB)
Downloading python package (501.75 / 557.49 MB)
Downloading python package (557.49 / 557.49 MB)
Unpacking python package
Python download is complete
    > "/home/mssqlgirl/azuredatastudio-python/0.0.1/bin/python3" -m pip install --user "jupyter>=1.0.0" --extra-index-url https://prose-python-packages.azurewebsites.net
    stdout: Looking in indexes: https://pypi.org/simple, https://prose-python-packages.azurewebsites.net
    stdout: 
    stdout: Requirement already satisfied: jupyter>=1.0.0 in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (1.0.0)
    stdout: 
    stdout: Requirement already satisfied: qtconsole in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from jupyter>=1.0.0) (4.5.5)
    stdout: 
    stdout: Requirement already satisfied: notebook in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from jupyter>=1.0.0) (6.0.2)
    stdout: 
    stdout: Requirement already satisfied: ipykernel in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from jupyter>=1.0.0) (5.1.3)
    stdout: 
    stdout: Requirement already satisfied: nbconvert in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from jupyter>=1.0.0) (5.6.1)
    stdout: 
    stdout: Requirement already satisfied: jupyter-console in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from jupyter>=1.0.0) (6.0.0)
    stdout: 
    stdout: Requirement already satisfied: ipywidgets in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from jupyter>=1.0.0) (7.5.1)
    stdout: 
    stdout: Requirement already satisfied: jupyter-client>=4.1 in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from qtconsole->jupyter>=1.0.0) (5.3.4)
    stdout: 
    stdout: Requirement already satisfied: ipython-genutils in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from qtconsole->jupyter>=1.0.0) (0.2.0)
    stdout: 
    stdout: Requirement already satisfied: traitlets in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from qtconsole->jupyter>=1.0.0) (4.3.3)
    stdout: 
    stdout: Requirement already satisfied: pygments in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from qtconsole->jupyter>=1.0.0) (2.4.2)
    stdout: 
    stdout: Requirement already satisfied: jupyter-core in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from qtconsole->jupyter>=1.0.0) (4.6.1)
    stdout: 
    stdout: Requirement already satisfied: Send2Trash in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from notebook->jupyter>=1.0.0) (1.5.0)
    stdout: 
    stdout: Requirement already satisfied: terminado>=0.8.1 in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from notebook->jupyter>=1.0.0) (0.8.2)
    stdout: 
    stdout: Requirement already satisfied: tornado>=5.0 in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from notebook->jupyter>=1.0.0) (6.0.3)
    stdout: 
    stdout: Requirement already satisfied: prometheus-client in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from notebook->jupyter>=1.0.0) (0.7.1)
    stdout: 
    stdout: Requirement already satisfied: pyzmq>=17 in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from notebook->jupyter>=1.0.0) (18.1.0)
    stdout: 
    stdout: Requirement already satisfied: nbformat in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from notebook->jupyter>=1.0.0) (4.4.0)
    stdout: 
    stdout: Requirement already satisfied: jinja2 in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from notebook->jupyter>=1.0.0) (2.10.3)
    stdout: 
    stdout: Requirement already satisfied: ipython>=5.0.0 in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from ipykernel->jupyter>=1.0.0) (7.9.0)
    stdout: 
    stdout: Requirement already satisfied: bleach in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from nbconvert->jupyter>=1.0.0) (3.1.0)
    stdout: 
    stdout: Requirement already satisfied: entrypoints>=0.2.2 in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from nbconvert->jupyter>=1.0.0) (0.3)
    stdout: 
    stdout: Requirement already satisfied: testpath in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from nbconvert->jupyter>=1.0.0) (0.4.4)
    stdout: 
    stdout: Requirement already satisfied: pandocfilters>=1.4.1 in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from nbconvert->jupyter>=1.0.0) (1.4.2)
    stdout: 
    stdout: Requirement already satisfied: mistune<2,>=0.8.1 in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from nbconvert->jupyter>=1.0.0) (0.8.4)
    stdout: 
    stdout: Requirement already satisfied: defusedxml in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from nbconvert->jupyter>=1.0.0) (0.6.0)
    stdout: 
    stdout: Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from jupyter-console->jupyter>=1.0.0) (2.0.10)
    stdout: 
    stdout: Requirement already satisfied: widgetsnbextension~=3.5.0 in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from ipywidgets->jupyter>=1.0.0) (3.5.1)
    stdout: 
    stdout: Requirement already satisfied: python-dateutil>=2.1 in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from jupyter-client>=4.1->qtconsole->jupyter>=1.0.0) (2.8.1)
    stdout: 
    stdout: Requirement already satisfied: decorator in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from traitlets->qtconsole->jupyter>=1.0.0) (4.4.1)
    stdout: 
    stdout: Requirement already satisfied: six in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from traitlets->qtconsole->jupyter>=1.0.0) (1.13.0)
    stdout: 
    stdout: Requirement already satisfied: ptyprocess; os_name != "nt" in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from terminado>=0.8.1->notebook->jupyter>=1.0.0) (0.6.0)
    stdout: 
    stdout: Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from nbformat->notebook->jupyter>=1.0.0) (3.1.1)
    stdout: 
    stdout: Requirement already satisfied: MarkupSafe>=0.23 in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from jinja2->notebook->jupyter>=1.0.0) (1.1.1)
    stdout: 
    stdout: Requirement already satisfied: pexpect; sys_platform != "win32" in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from ipython>=5.0.0->ipykernel->jupyter>=1.0.0) (4.7.0)
    stdout: 
    stdout: Requirement already satisfied: jedi>=0.10 in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from ipython>=5.0.0->ipykernel->jupyter>=1.0.0) (0.15.1)
    stdout: 
    stdout: Requirement already satisfied: pickleshare in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from ipython>=5.0.0->ipykernel->jupyter>=1.0.0) (0.7.5)
    stdout: 
    stdout: Requirement already satisfied: setuptools>=18.5 in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from ipython>=5.0.0->ipykernel->jupyter>=1.0.0) (39.0.1)
    stdout: 
    stdout: Requirement already satisfied: backcall in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from ipython>=5.0.0->ipykernel->jupyter>=1.0.0) (0.1.0)
    stdout: 
    stdout: Requirement already satisfied: webencodings in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from bleach->nbconvert->jupyter>=1.0.0) (0.5.1)
    stdout: 
    stdout: Requirement already satisfied: wcwidth in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from prompt-toolkit<2.1.0,>=2.0.0->jupyter-console->jupyter>=1.0.0) (0.1.7)
    stdout: 
    stdout: Requirement already satisfied: pyrsistent>=0.14.0 in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook->jupyter>=1.0.0) (0.15.5)
    stdout: 
    stdout: Requirement already satisfied: importlib-metadata in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook->jupyter>=1.0.0) (0.23)
    stdout: 
    stdout: Requirement already satisfied: attrs>=17.4.0 in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook->jupyter>=1.0.0) (19.3.0)
    stdout: 
    stdout: Requirement already satisfied: parso>=0.5.0 in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from jedi>=0.10->ipython>=5.0.0->ipykernel->jupyter>=1.0.0) (0.5.1)
    stdout: 
    stdout: Requirement already satisfied: zipp>=0.5 in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from importlib-metadata->jsonschema!=2.5.0,>=2.4->nbformat->notebook->jupyter>=1.0.0) (0.6.0)
    stdout: 
    stdout: Requirement already satisfied: more-itertools in ./azuredatastudio-python/0.0.1/lib/python3.6/site-packages (from zipp>=0.5->importlib-metadata->jsonschema!=2.5.0,>=2.4->nbformat->notebook->jupyter>=1.0.0) (7.2.0)
    stdout: 
    stderr: WARNING: You are using pip version 19.3.1; however, version 20.1.1 is available.
    stderr: You should consider upgrading via the 'pip install --upgrade pip' command.
    stderr: 
Notebook dependencies installation is complete
... Creating /home/mssqlgirl/.local/share/jupyter/instances/55d3c8d7-6060-41d4-b50d-00ba3723ce27
... Creating /home/mssqlgirl/.local/share/jupyter/instances/55d3c8d7-6060-41d4-b50d-00ba3723ce27/config
... Creating /home/mssqlgirl/.local/share/jupyter/instances/55d3c8d7-6060-41d4-b50d-00ba3723ce27/data
... Creating /home/mssqlgirl/.local/share/jupyter/instances/55d3c8d7-6060-41d4-b50d-00ba3723ce27/config/custom
... Starting Notebook server
    > "/home/mssqlgirl/azuredatastudio-python/0.0.1/bin/python3" -m jupyter notebook --no-browser --no-mathjax --notebook-dir "/home/mssqlgirl" --port=9763 --NotebookApp.token=48b2e3b4e706df7063d4386aa961ad5be2a5d73f463cadaa
... Creating /home/mssqlgirl/.local/share/jupyter/instances/0eadf82c-cce6-43f6-aec2-fa55b73ea478
... Creating /home/mssqlgirl/.local/share/jupyter/instances/0eadf82c-cce6-43f6-aec2-fa55b73ea478/config
... Creating /home/mssqlgirl/.local/share/jupyter/instances/0eadf82c-cce6-43f6-aec2-fa55b73ea478/data
... Creating /home/mssqlgirl/.local/share/jupyter/instances/0eadf82c-cce6-43f6-aec2-fa55b73ea478/config/custom
... Starting Notebook server
    > "/home/mssqlgirl/azuredatastudio-python/0.0.1/bin/python3" -m jupyter notebook --no-browser --no-mathjax --notebook-dir "/home/mssqlgirl" --port=8998 --NotebookApp.token=c9bc0ff21ed3cd0f6900f9a659fef91a005175e8ab31b376
