### ISSUE TITLE
Welcome Page: No Past Resources Listed, Exceptions Thrown to Debug Console

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#10426]
I see the following exception being thrown in the debug console every time that I open the welcome page on my Mac. Not sure if others see the same thing (or if it really has any impact). Are other people able to see their past resources that were opened in ADS? 

Opening in May to make sure that this isn't a widespread issue and to get eyeballs on it.

ERR Cannot read property 'path' of undefined: TypeError: Cannot read property 'path' of undefined
    at Object.t.isAbsolutePath (file:///Applications/Azure Data Studio - RC1.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:537:215)
    at e.withProvider (file:///Applications/Azure Data Studio - RC1.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2226:367)
    at e.doResolveFile (file:///Applications/Azure Data Studio - RC1.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2227:599)
    at e.resolve (file:///Applications/Azure Data Studio - RC1.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2227:324)
    at t.createListEntries (file:///Applications/Azure Data Studio - RC1.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6199:806)
    at t.mapListEntries (file:///Applications/Azure Data Studio - RC1.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6201:150)
    at r (file:///Applications/Azure Data Studio - RC1.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6195:333)
    at file:///Applications/Azure Data Studio - RC1.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:6195:360
    at ZoneDelegate.invoke (/Applications/Azure Data Studio - RC1.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:388:26)
    at Zone.run (/Applications/Azure Data Studio - RC1.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:138:43)
    at /Applications/Azure Data Studio - RC1.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:872:34
    at ZoneDelegate.invokeTask (/Applications/Azure Data Studio - RC1.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:421:31)
    at Zone.runTask (/Applications/Azure Data Studio - RC1.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:188:47)
    at drainMicroTaskQueue (/Applications/Azure Data Studio - RC1.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:595:35)

**Comment by kburtram** [comment]
I no longer see these errors in the log from the Welcome page on the current build.
