### ISSUE TITLE
QPI Extension dashboard blank

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#10593]
1. Install QPI extension
2. View dashboard page, it's blank

Attempting to view other pages after that also fails - they're all blank. 

```
ERROR TypeError: Cannot read property 'find' of undefined
    at DashboardNavSection.layout (file:///C:/src/AzureDataStudio/out/sql/workbench/contrib/dashboard/browser/containers/dashboardNavSection.component.js:125:45)
    at TabComponent.set child [as child] (file:///C:/src/AzureDataStudio/out/sql/base/browser/ui/panel/tab.component.js:34:33)
    at checkAndUpdateQuery (c:\src\AzureDataStudio\node_modules\@angular\core\bundles\core.umd.js:11552:45)
```

**Comment by alanrenmsft** [comment]
This impacts all the contributed dashboard tabs that uses the NavSection container: Query Performance Insights and Managed Instance Dashboard. No workaround available for this issue.

@kenvanhyning , do you think this is a hotfix candidate?

**Comment by alanrenmsft** [comment]
closing the issue based on the offline sync with ken, this doesn't seem to be an issue that impacts a lot of users, the users can use the insider build for now.
