### ISSUE TITLE
An unexpected error occured while connecting

### ISSUE THREAD

**Issue by harlananelson** [microsoft/azuredatastudio#10906]
```
[2020-06-12 17:28:48.791] [renderer1] [error] OnConnectionComplete but no connection found 'untitled:notebook-editor-60' Connections = [connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:EDW|server:iuh-edw-sql-prod-01.database.windows.net|user:hnelson3@iuhealth.org|databaseDisplayName:EDW|group:C777F06B-202E-4480-B475-FA416154D458,notebook:h:\projects\EM-Data-Science\sql\Create_EM_DataScience_Cohort.ipynb]
[2020-06-12 17:28:48.858] [renderer1] [error] OnConnectionComplete but no connection found 'untitled:notebook-editor-132' Connections = [connection:providerName:MSSQL|applicationName:azdata|authenticationType:AzureMFA|database:EDW|server:iuh-edw-sql-prod-01.database.windows.net|user:hnelson3@iuhealth.org|databaseDisplayName:EDW|group:C777F06B-202E-4480-B475-FA416154D458,notebook:h:\projects\EM-Data-Science\sql\Create_EM_DataScience_Cohort.ipynb]
[2020-06-12 17:28:49.151] [renderer1] [error] Unexpected error occurred while connecting.: Error: Unexpected error occurred while connecting.
    at e.onConnectionComplete (file:///C:/Users/hnelson3/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2272:841) [<root>]
    at e.onConnectionComplete (file:///C:/Users/hnelson3/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5780:260) [<root>]
    at e.$onConnectionComplete (file:///C:/Users/hnelson3/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5037:977) [<root>]
    at e._doInvokeHandler (file:///C:/Users/hnelson3/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5128:464) [<root>]
    at e._invokeHandler (file:///C:/Users/hnelson3/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5128:156) [<root>]
    at e._receiveRequest (file:///C:/Users/hnelson3/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5126:817) [<root>]
    at e._receiveOneMessage (file:///C:/Users/hnelson3/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5125:623) [<root>]
    at file:///C:/Users/hnelson3/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5123:848 [<root>]
    at e.fire (file:///C:/Users/hnelson3/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:194:242) [<root>]
    at fire (file:///C:/Users/hnelson3/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:600:470) [<root>]
    at t.PersistentProtocol._receiveMessage (file:///C:/Users/hnelson3/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:604:921) [<root>]
    at file:///C:/Users/hnelson3/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:602:67 [<root>]
    at e.fire (file:///C:/Users/hnelson3/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:194:242) [<root>]
    at g.acceptChunk (file:///C:/Users/hnelson3/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:598:17) [<root>]
    at file:///C:/Users/hnelson3/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:597:393 [<root>]
    at Socket.t (file:///C:/Users/hnelson3/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:608:332) [<root>]
    at Socket.ZoneTask.invoke (c:\Users\hnelson3\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:485:48) [<root>]
    at Socket.emit (events.js:203:13) [<root>]
    at addChunk (_stream_readable.js:295:12) [<root>]
    at readableAddChunk (_stream_readable.js:276:11) [<root>]
    at Socket.Readable.push (_stream_readable.js:210:10) [<root>]
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17) [<root>]
```

**Comment by Charles-Gagnon** [comment]
Thank you for submitting this! This is the information we need currently so I'm going to close this out since we have a number of similar issues open already, let us know if you have anything further to add.
