### ISSUE TITLE
Notebook substring error

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#11138]
```
c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 TypeError: Cannot read property 'substring' of undefined
	at c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\notebook\dist\extension.js:217:445963
	at Array.filter (<anonymous>)
	at b.findAndExpandParentNode (c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\notebook\dist\extension.js:217:445941)
	at b.revealActiveDocumentInViewlet (c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\notebook\dist\extension.js:217:445535)
	at c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\notebook\dist\extension.js:217:444415
	at l.fire (c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:801)
	at p.setVisible (c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:629:29)
	at t.ExtHostTreeViews.$setVisible (c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:625:186)
	at g._doInvokeHandler (c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:914:477)
	at g._invokeHandler (c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:914:169)
	at g._receiveRequest (c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:912:855)
	at g._receiveOneMessage (c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:911:663)
	at c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:909:914
	at l.fire (c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:801)
	at v.fire (c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:242:849)
	at c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1077:375
	at l.fire (c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:801)
	at v.fire (c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:242:849)
	at t.PersistentProtocol._receiveMessage (c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:247:276)
	at c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:244:357
	at l.fire (c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:801)
	at p.acceptChunk (c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:240:393)
	at c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:239:753
	at Socket.t (c:\Users\amomidi\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:248:827)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
```

Likely caused at https://github.com/microsoft/azuredatastudio/blob/561b881200631cbe420f98249ead377ac17d3217/extensions/notebook/src/book/bookTreeView.ts#L264-L265

**Comment by MaddyDev** [comment]
Fixed with the search PR #11117
