### ISSUE TITLE
Impossible to add new Azure account

### ISSUE THREAD

**Issue by jmgnjetable** [microsoft/azuredatastudio#11180]
- Azure Data Studio Version:

Steps to Reproduce:

1. following the latest Azure Data Studio update, I tried to setup a new Azure AD connection (because my password had expired).
2. when I click on "Add an Account", Azure Data Studio opens a web page with the following link https://localhost:58329/signin?nonce=0q+qzCB/VlJuGu02ouse4w==
3. this link doesn't work due to the localhost in the URL.

I did not change anything apart from updating to the latest release.

**Comment by Charles-Gagnon** [comment]
@aaomidi 

What do you mean it didn't work "due to the localhost in the URL"? The default method we use is to start up a local web server that is used to fetch the token so this is expected. Is there something preventing you from doing this?

If so you then you can go back to the Device Code method by finding this setting in the settings UI and selecting it. 

![image](https://user-images.githubusercontent.com/28519865/86377347-1637bd00-bc3d-11ea-84b8-6ec3f08e0aa7.png)

After that you should see an option to choose the method when you add an account - choose `Azure Device Code`

![image](https://user-images.githubusercontent.com/28519865/86377679-7af31780-bc3d-11ea-95ce-1bd54636cce5.png)

**Comment by jmgnjetable** [comment]
hi @Charles-Gagnon thank you very much for your answer. This solved my problem. Not sure what happened and why the usual method was not working anymore, because I don't think I have changed anything on my side.

**Comment by Charles-Gagnon** [comment]
The Code Grant method is something we added fairly recently so if you hadn't updated in a while that's probably why. We used to only have the Device Code method. 

Did you end up going back to the Device Code method? The Code Grant is the preferred method for authenticating so if you had issues with that would you mind going into more details about the errors/unexpected behavior you encountered with that so we could see if it's something we can fix?

**Comment by aaomidi** [comment]
It'd also be helpful to know what was the error that you were getting with the localhost URL.

**Comment by jmgnjetable** [comment]
hi @Charles-Gagnon and @aaomidi unfortunately I am unable to reproduce anymore...

All I did before was click on add an account, then a browser window opened with the link with the localhost in the URL and then nothing happened I got the "this site is unaccesible" error from Google chrome. 

Now when I click on add an account, I can choose between the 2 methods, and when I select auth code grant, the webpage opens with the localhost in the URL, but now I am redirected correctly to https://login.microsoftonline.com/

I have not changed anything on my side, apart from activating the other auth method as you suggest (and now I have a linked Azure account).

I'd be happy to help more, let me know if there is anything I can do?

**Comment by jmgnjetable** [comment]
hi @Charles-Gagnon @aaomidi 
I have experienced again the issue today following the latest update.
ADS loses my previous Azure account and when I click on add a new account, and select Code grant, a browser window opens with localhost but then nothing happens

I have made the enclosed video to illustrate.

I'd be happy to provide you with more info, let me know

[Nouvel onglet - Google Chrome 2020-08-18 18-12-46.zip](https://github.com/microsoft/azuredatastudio/files/5091505/Nouvel.onglet.-.Google.Chrome.2020-08-18.18-12-46.zip)

**Comment by aaomidi** [comment]
Visit chrome://net-internals#hsts
Remove localhost from the HSTS list:

![image](https://user-images.githubusercontent.com/1465785/90549616-99f12e80-e143-11ea-937c-e8ecf0a9e2db.png)

**Comment by jmgnjetable** [comment]
@aaomidi I have done this and now it seems that I cannot add an azure account at all in ADS, not sure if related though

the Azure ribbon keeps writing "loading..." and when I click add an account I get an error saying I need to check the settings and activate a cloud account, but it looks active to me looking at the settings? 

![image](https://user-images.githubusercontent.com/67741263/90620057-46014b00-e212-11ea-8bf3-9495151622f4.png)
![image](https://user-images.githubusercontent.com/67741263/90620088-5285a380-e212-11ea-973f-ff88663e2c3c.png)

**Comment by jmgnjetable** [comment]
nevermind! I just ticked and unticked all the options several times, restarted ADS and was able to add again my account. the locahost issue is also gone.

**Comment by patoJamriska** [comment]
Hey Guys I been following several different posts with the same exact problem.
Basically the azureTab is stuck on showing loading , and when I go to try to add an account it says that I do not have a cloud account enabled. No matter what I do I can't get ADS to let me add an account.

On the logs the renderer[1] is the only one reporting this error.
`
[2020-10-19 17:34:26.296] [renderer1] [error] e is not iterable: TypeError: e is not iterable
	at p._initialize (c:\Program Files\Azure Data Studio - Insiders\resources\app\extensions\azurecore\dist\extension.js:166:33616)
	at p.initialize (c:\Program Files\Azure Data Studio - Insiders\resources\app\extensions\azurecore\dist\extension.js:166:33556)
	at c:\Program Files\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:693:948
	at a._withProvider (c:\Program Files\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:696:200)
	at a.$initialize (c:\Program Files\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:693:927)
	at g._doInvokeHandler (c:\Program Files\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:972:926)
	at g._invokeHandler (c:\Program Files\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:972:618)
	at g._receiveRequest (c:\Program Files\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:971:252)
	at g._receiveOneMessage (c:\Program Files\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:970:201)
	at c:\Program Files\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:968:161
	at l.fire (c:\Program Files\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:801)
	at v.fire (c:\Program Files\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:258:381)
	at c:\Program Files\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1152:963
	at l.fire (c:\Program Files\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:801)
	at v.fire (c:\Program Files\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:258:381)
	at t.PersistentProtocol._receiveMessage (c:\Program Files\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:263:451)
	at c:\Program Files\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:260:489
	at l.fire (c:\Program Files\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:801)
	at p.acceptChunk (c:\Program Files\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:255:851)
	at c:\Program Files\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:255:203
	at Socket.t (c:\Program Files\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:265:54)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
[2020-10-19 17:34:26.717] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2020-10-19 17:34:26.719] [renderer1] [error] Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at z.addProvider (file:///C:/Program Files/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:8771:217)
    at file:///C:/Program Files/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:8767:711
    at ZoneDelegate.invoke (C:\Program Files\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:388:26)
    at Zone.run (C:\Program Files\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:138:43)
    at C:\Program Files\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:872:34
    at ZoneDelegate.invokeTask (C:\Program Files\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:421:31)
    at Zone.runTask (C:\Program Files\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:188:47)
    at drainMicroTaskQueue (C:\Program Files\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:595:35)
    at ZoneTask.invokeTask [as invoke] (C:\Program Files\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:500:21)
    at invokeTask (C:\Program Files\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1540:14)
    at HTMLLIElement.globalZoneAwareCallback (C:\Program Files\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1577:21)
`

I have tried 1.17 and 1.24 insiders at this point. Everything seemed to be working just fine on 1.16 and decided to update and everything went to hell with the azure account after that.
