### ISSUE TITLE
Clicking Edit Data run button a few times can cause error

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#11259]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Edit Data a table
2. Click the Run button a few times relatively quickly (~every seconds or two)

Expected: Grid and document to be in a consistent state once the Run operation is done and no errors occur.

Actual: Grid shows all values as "NULL" and a few errors in console log.

![image](https://user-images.githubusercontent.com/599935/86974315-f74c9580-c12a-11ea-887a-48847eb35300.png)

**Comment by kburtram** [comment]
Clicking stop in this state cause this error:

```
  ERR Edit session does not exist.: Error: Edit session does not exist.
	at c:\Users\karlb\AppData\Local\Programs\Azure Data Studio - RC1\resources\app\extensions\mssql\dist\main.js:1:63842
	at c:\Users\karlb\AppData\Local\Programs\Azure Data Studio - RC1\resources\app\extensions\mssql\dist\main.js:1:64136
	at Immediate.<anonymous> (c:\Users\karlb\AppData\Local\Programs\Azure Data Studio - RC1\resources\app\extensions\mssql\dist\main.js:1:64495)
	at processImmediate (internal/timers.js:439:21)
```
