### ISSUE TITLE
Unable to authenticate MFA for Conditional Access

### ISSUE THREAD

**Issue by jp4u** [microsoft/azuredatastudio#11270]
Hi there, 

I am currently developing a solution for my company and I am on a time crunch. Any assistance would be highly appreciated. My current environment is a Mac, using Azure Data Studio and Visual Studio Code.

I set up a personal Azure portal using a free account which I am currently on a Premium 2 trial for Active Directory. Originally I was able to access the database using the credentials of a user I created called JP01. This user is part of a Database Admin group which was assigned to a sql server as an AAD Admin. This all works fine. I am able to connect via code (connection string) and Azure Data Studio. I only had to configure Azure to make it work.

However, I also added a Conditional Access Policy to whoever accesses Azure Sql Database in the Admin group must also perform MFA and receive grant access. For the most part this all works. I try to login (Azure Data Studio), it denies me, sends me to a login page which calls my authenticator app and I am able to approve it. The problem is even after I authenticate, I am still denied access.

If I lookup the user on Azure portal, it says that the user's conditional access was a success.

On Azure Data Studio I receive, after I authenticate:
Login failed for user 'token-identified principal'.

Programmatically I receive:
System.AggregateException: One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'.
Trace ID: ae3b2ad2-eeaf-4f2e-8783-526808d5a900
Correlation ID: b7f45074-f8b6-4813-9f0c-e578d067872c
Timestamp: 2020-07-07 16:30:39Z)))

Azure Data Studio Log:
Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user 'token-identified principal'.
at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool, SqlAuthenticationProviderManager sqlAuthProviderManager)
at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionFactory.<>c_DisplayClass40_0.<TryGetConnection>b1(Task`1 )
at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c_DisplayClass30_0.<<OpenAsync>b_0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 314
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 549
ClientConnectionId:95f719ed-a055-47fb-bf29-1a3576539286
Error Number:18456,State:1,Class:14

**Comment by kburtram** [comment]
@aaomidi do you have any suggestions or thoughts on this issue?

**Comment by aaomidi** [comment]
@jp4u It should've prompted you to authenticate again when you get that error, did it not?

**Comment by jp4u** [comment]
@aaomidi No it didn't I have been trying different combinations of conditional access for days now. I put a session timeout for 1 hr, and every time I try between that hour it denies me with the token principal. When the hour is up it asks me reauthenticate again, I hit the webpage it sends me to and authenticate on app then it says invalid token principal again.

**Comment by jp4u** [comment]
For conditional access, I have tried Azure Sql Database, using groups, MFA (one of selected) and 1 hr session timeout. I have also tried instead of Azure Aql Database all cloud apps.

**Comment by aaomidi** [comment]
I mean this error should cause ADS to prompt to reauthenticate: (AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '022907d3-0f1b-48f7-badc-1ba6abab6d66'.

**Comment by jp4u** [comment]
@aaomidi 
That error is in visual studio code.  I think that may not be possible for me to do at this time however since I am using .net core currently.

https://docs.microsoft.com/en-us/azure/azure-sql/database/active-directory-interactive-connect-azure-sql-db

I believe it says here. (Under "New Authentication Enum Value") I need to be using 4.7.2 .NET unless I am mistaken. Also, it appears that ActiveDirectoryPassword is not supported with MFA. However, this is code based and not connection string based. It would be great if I am wrong, please let me know.

Also, with Azure Data Studio, do you know why it will not let me pass through? I am doing a presentation on Monday and would love to show off the features that Azure provides for security.

**Comment by jp4u** [comment]
Azure Data Studio asks me to re-authenticate and after I do (login on website, which sends me a push notification through the app) it still says login failed for token principal.

**Comment by jp4u** [comment]
Hello just checking back up on this issue

**Comment by aaomidi** [comment]
Can you check with the latest insiders just to see if the issue is till there?

**Comment by jp4u** [comment]
@aaomidi What is the latest insiders? I am unfamiliar

**Comment by aaomidi** [comment]
It's the daily builds: https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main
