### ISSUE TITLE
Unable to Add Azure account to Linked Accounts in Azure Data Studio Insiders 

### ISSUE THREAD

**Issue by vnachimu** [microsoft/azuredatastudio#11493]
- Azure Data Studio Version:
azuredatastudio-macos-1.21.0-insider

Steps to Reproduce:

1.  After authenticating with Microsoft Azure Account, the browser throws an error saying "Failure when retrieving tokens".
![image](https://user-images.githubusercontent.com/42034164/88324557-79e76e80-cd41-11ea-8e77-b8c6997935e8.png)

**Comment by vnachimu** [comment]
Firefox web console reponse.
<img width="1138" alt="Screenshot 2020-07-24 at 12 16 14 AM" src="https://user-images.githubusercontent.com/42034164/88325782-06def780-cd43-11ea-941e-853c48e1f89e.png">

**Comment by IvanAlekseev** [comment]
Any update on this one? I have the same issue in stable version. Tried latest insiders build and got this error:
```
[2020-08-03 21:57:08.240] [renderer1] [error] Error while adding account: TypeError: Cannot read property 'canceled' of undefined
```

**Comment by kburtram** [comment]
@aaomidi do you know what's happening in this situation?

**Comment by kburtram** [comment]
Approved for shiproom for August pending a fix.

**Comment by aaomidi** [comment]
@IvanAlekseev which authentication method were you using? The one that opens up a browser page and logs you in or the one that you need to paste a code into the browser page?

**Comment by IvanAlekseev** [comment]
@aaomidi the one that opens browser window. I am logging in and this is the error I see in the end
![image](https://user-images.githubusercontent.com/23052247/89345827-fc582280-d69f-11ea-8802-f160927aa7f3.png)

**Comment by aaomidi** [comment]
Hmm that's weird, can you go to Help -> Toggle Developer Tools to see if you see any extra errors or information?

You can also go to Settings -> Enable PII Logging and turn that to on, that will print out the raw responses we get from Microsoft's OAuth servers.

**Comment by IvanAlekseev** [comment]
@aaomidi this is what I get in release version:
```
[Extension Host] TypeError: Cannot destructure property 'accessToken' of '(intermediate value)' as it is undefined.
	at d.promptForConsent (c:\Users\ivan.alekseev\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\azurecore\dist\extension.js:166:34325)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async d.login (c:\Users\ivan.alekseev\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\azurecore\dist\extension.js:166:36923)
C:\Users\ivan.alekse…t\zone-node.js:2280   ERR Error while adding account: Error: Failure when retrieving tokens
```

**Comment by aaomidi** [comment]
Can you enable PII logging and test this again? It should give you more specifics on the error.

**Comment by IvanAlekseev** [comment]
@aaomidi just downloaded latest insiders build and here is what I get in console:
```
C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 [Extension Host] Error: No access token returned from Microsoft OAuth -  (at Function.error (c:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\extensions\azurecore\dist\extension.js:16:65672))
console.<computed> @ C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280
t.log @ console.ts:24
$logExtensionHostMessage @ remoteConsoleUtil.ts:29
_doInvokeHandler @ rpcProtocol.ts:344
_invokeHandler @ rpcProtocol.ts:344
_receiveRequest @ rpcProtocol.ts:290
_receiveOneMessage @ rpcProtocol.ts:231
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:544
fire @ ipc.net.ts:440
_receiveMessage @ ipc.net.ts:702
(anonymous) @ ipc.net.ts:562
fire @ event.ts:544
acceptChunk @ ipc.net.ts:186
(anonymous) @ ipc.net.ts:186
t @ ipc.net.ts:836
ZoneDelegate.invokeTask @ C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421
Zone.runTask @ C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188
ZoneTask.invokeTask @ C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:496
ZoneTask.invoke @ C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:485
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280   ERR Cannot read property 'accountType' of undefined: TypeError: Cannot read property 'accountType' of undefined
    at e.renderElement (file:///C:/Users/ivan.alekseev/Downloads/azuredatastudio-windows-1.21.0-insider/resources/app/out/vs/workbench/workbench.desktop.main.js:2320:892)
    at e.renderElement (file:///C:/Users/ivan.alekseev/Downloads/azuredatastudio-windows-1.21.0-insider/resources/app/out/vs/workbench/workbench.desktop.main.js:2321:520)
    at W.renderElement (file:///C:/Users/ivan.alekseev/Downloads/azuredatastudio-windows-1.21.0-insider/resources/app/out/vs/workbench/workbench.desktop.main.js:794:719)
    at E.insertItemInDOM (file:///C:/Users/ivan.alekseev/Downloads/azuredatastudio-windows-1.21.0-insider/resources/app/out/vs/workbench/workbench.desktop.main.js:765:503)
    at E._splice (file:///C:/Users/ivan.alekseev/Downloads/azuredatastudio-windows-1.21.0-insider/resources/app/out/vs/workbench/workbench.desktop.main.js:761:591)
    at E.splice (file:///C:/Users/ivan.alekseev/Downloads/azuredatastudio-windows-1.21.0-insider/resources/app/out/vs/workbench/workbench.desktop.main.js:760:201)
    at file:///C:/Users/ivan.alekseev/Downloads/azuredatastudio-windows-1.21.0-insider/resources/app/out/vs/workbench/workbench.desktop.main.js:124:451
    at Array.forEach (<anonymous>)
    at t.CombinedSpliceable.splice (file:///C:/Users/ivan.alekseev/Downloads/azuredatastudio-windows-1.21.0-insider/resources/app/out/vs/workbench/workbench.desktop.main.js:124:438)
    at file:///C:/Users/ivan.alekseev/Downloads/azuredatastudio-windows-1.21.0-insider/resources/app/out/vs/workbench/workbench.desktop.main.js:800:756
    at t.EventBufferer.bufferEvents (file:///C:/Users/ivan.alekseev/Downloads/azuredatastudio-windows-1.21.0-insider/resources/app/out/vs/workbench/workbench.desktop.main.js:196:903)
    at K.splice (file:///C:/Users/ivan.alekseev/Downloads/azuredatastudio-windows-1.21.0-insider/resources/app/out/vs/workbench/workbench.desktop.main.js:800:723)
    at W.updateAccounts (file:///C:/Users/ivan.alekseev/Downloads/azuredatastudio-windows-1.21.0-insider/resources/app/out/vs/workbench/workbench.desktop.main.js:8371:948)
    at z.updateProviderAccounts (file:///C:/Users/ivan.alekseev/Downloads/azuredatastudio-windows-1.21.0-insider/resources/app/out/vs/workbench/workbench.desktop.main.js:8377:489)
    at file:///C:/Users/ivan.alekseev/Downloads/azuredatastudio-windows-1.21.0-insider/resources/app/out/vs/workbench/workbench.desktop.main.js:8373:358
    at c.fire (file:///C:/Users/ivan.alekseev/Downloads/azuredatastudio-windows-1.21.0-insider/resources/app/out/vs/workbench/workbench.desktop.main.js:194:475)
    at file:///C:/Users/ivan.alekseev/Downloads/azuredatastudio-windows-1.21.0-insider/resources/app/out/vs/workbench/workbench.desktop.main.js:1811:366
    at c.fire (file:///C:/Users/ivan.alekseev/Downloads/azuredatastudio-windows-1.21.0-insider/resources/app/out/vs/workbench/workbench.desktop.main.js:194:475)
    at e.fireAccountListUpdate (file:///C:/Users/ivan.alekseev/Downloads/azuredatastudio-windows-1.21.0-insider/resources/app/out/vs/workbench/workbench.desktop.main.js:8385:435)
    at file:///C:/Users/ivan.alekseev/Downloads/azuredatastudio-windows-1.21.0-insider/resources/app/out/vs/workbench/workbench.desktop.main.js:8381:530
C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 [Extension Host] rejected promise not handled within 1 second: TypeError: t is not iterable (cannot read property undefined) (at c:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1103:78)
console.<computed> @ C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280
t.log @ console.ts:24
$logExtensionHostMessage @ remoteConsoleUtil.ts:29
_doInvokeHandler @ rpcProtocol.ts:344
_invokeHandler @ rpcProtocol.ts:344
_receiveRequest @ rpcProtocol.ts:290
_receiveOneMessage @ rpcProtocol.ts:231
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:544
fire @ ipc.net.ts:440
_receiveMessage @ ipc.net.ts:702
(anonymous) @ ipc.net.ts:562
fire @ event.ts:544
acceptChunk @ ipc.net.ts:186
(anonymous) @ ipc.net.ts:186
t @ ipc.net.ts:836
ZoneDelegate.invokeTask @ C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421
Zone.runTask @ C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188
ZoneTask.invokeTask @ C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:496
ZoneTask.invoke @ C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:485
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 [Extension Host] stack trace: TypeError: t is not iterable (cannot read property undefined)	at c:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:646:517	at processTicksAndRejections (internal/process/task_queues.js:94:5)	at async Promise.all (index 0)	at async c:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\extensions\azurecore\dist\extension.js:209:25121 (at c:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1103:157)
console.<computed> @ C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280
t.log @ console.ts:24
$logExtensionHostMessage @ remoteConsoleUtil.ts:29
_doInvokeHandler @ rpcProtocol.ts:344
_invokeHandler @ rpcProtocol.ts:344
_receiveRequest @ rpcProtocol.ts:290
_receiveOneMessage @ rpcProtocol.ts:231
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:544
fire @ ipc.net.ts:440
_receiveMessage @ ipc.net.ts:702
(anonymous) @ ipc.net.ts:562
fire @ event.ts:544
acceptChunk @ ipc.net.ts:186
(anonymous) @ ipc.net.ts:186
t @ ipc.net.ts:836
ZoneDelegate.invokeTask @ C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421
Zone.runTask @ C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188
ZoneTask.invokeTask @ C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:496
ZoneTask.invoke @ C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:485
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 [[object Object]]t is not iterable (cannot read property undefined)
console.<computed> @ C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280
$onExtensionRuntimeError @ mainThreadExtensionService.ts:65
_doInvokeHandler @ rpcProtocol.ts:344
_invokeHandler @ rpcProtocol.ts:344
_receiveRequest @ rpcProtocol.ts:290
_receiveOneMessage @ rpcProtocol.ts:231
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:544
fire @ ipc.net.ts:440
_receiveMessage @ ipc.net.ts:702
(anonymous) @ ipc.net.ts:562
fire @ event.ts:544
acceptChunk @ ipc.net.ts:186
(anonymous) @ ipc.net.ts:186
t @ ipc.net.ts:836
ZoneDelegate.invokeTask @ C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421
Zone.runTask @ C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188
ZoneTask.invokeTask @ C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:496
ZoneTask.invoke @ C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:485
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
C:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 TypeError: t is not iterable (cannot read property undefined)
	at c:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:646:517
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async Promise.all (index 0)
	at async c:\Users\ivan.alekseev\Downloads\azuredatastudio-windows-1.21.0-insider\resources\app\extensions\azurecore\dist\extension.js:209:25121
```

**Comment by IvanAlekseev** [comment]
The same error `No access token returned from Microsoft OAuth` is now happening in the August release.

**Comment by aaomidi** [comment]
@IvanAlekseev Did you ever get a chance to turn on pii Logging in the settings?

**Comment by IvanAlekseev** [comment]
@aaomidi PII is enabled
![image](https://user-images.githubusercontent.com/23052247/90182409-d3bfdf00-dda9-11ea-89ae-14d6339b9fb8.png)

And this is the first error in console
![image](https://user-images.githubusercontent.com/23052247/90182355-bf7be200-dda9-11ea-92aa-5900d057f923.png)

**Comment by aaomidi** [comment]
Huh, so the {} print before that was supposed to be the data returned from the post request... I'm honestly not sure what's causing that to break.

**Comment by IvanAlekseev** [comment]
Here is the internals of {}
![image](https://user-images.githubusercontent.com/23052247/90182966-a889bf80-ddaa-11ea-9add-5b678829f7bc.png)
Can it be because of zscaler proxy?
Also I am able to connect using MFA in SSMS

**Comment by aaomidi** [comment]
It could definitely be because of zscaler proxy. Essentially something is modifying the post request from Microsoft oauth's service to ADS. This could potentially be a security feature setup by your org.

The way SSMS does oauth is a little different as it's on-demand per server. We try to load in your account in ADS. Essentially a tiny bit different. They also technically use a different client ID that may have been specifically allowed through the zscaler proxy.

**Comment by IvanAlekseev** [comment]
Thanks, I'll ask our security team to look into it. A bit more logging for that request would be nice, so I can share it with them

**Comment by aaomidi** [comment]
Yeah definitely. I'll see where I can add more logging.

Alternatively you can attach fiddler to see what are the requests being made.

**Comment by IvanAlekseev** [comment]
@aaomidi do I need to do any specific setup for Fiddler? It doesn't capture anything from ADS
![image](https://user-images.githubusercontent.com/23052247/90186796-b0e4f900-ddb0-11ea-9023-3bb5c535d894.png)

**Comment by aaomidi** [comment]
Hmm that callback does include the proper code...

**Comment by kburtram** [comment]
@IvanAlekseev you would need to set some environment variables prior to launching azuredatastudio to have the network traffic redirected to fiddler (for example, see http://blog.knor.net/2016/12/capture-network-traffic-in-nodejs-with-fiddler/).

**Comment by IvanAlekseev** [comment]
@kburtram @aaomidi It works now! So I went to change environment variables and found that `https_proxy` was already set to `http://127.0.0.1:9000`. I removed it, restarted ADS and I am able to connect now. And it works through fiddler as well when I set a variables as per article.
Thank you for your help!

**Comment by aaomidi** [comment]
Awesome news!

**Comment by kbocock-krg** [comment]
I cannot get this to work on mac big sur. It just hangs after I choose my azure login.
