### ISSUE TITLE
Undefined error when click on error in output channel 

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#11913]
- Azure Data Studio Version:

[91283:0821/114353.435627:INFO:CONSOLE(2280)] "%c  ERR color: #f33 Cannot read property 'element' of undefined: TypeError: Cannot read property 'element' of undefined
    at ErrorMessageDialog.open (file:///Users/llali-mac/work/azuredatastudio/out/sql/workbench/services/errorMessage/browser/errorMessageDialog.js:109:34)
    at ErrorMessageService.doShowDialog (file:///Users/llali-mac/work/azuredatastudio/out/sql/workbench/services/errorMessage/browser/errorMessageService.js:34:38)
    at ErrorMessageService.showDialog (file:///Users/llali-mac/work/azuredatastudio/out/sql/workbench/services/errorMessage/browser/errorMessageService.js:25:18)
    at TaskHistoryView.onSelected (file:///Users/llali-mac/work/azuredatastudio/out/sql/workbench/contrib/tasks/browser/tasksView.js:115:50)
    at file:///Users/llali-mac/work/azuredatastudio/out/sql/workbench/contrib/tasks/browser/tasksView.js:41:76
    at Emitter.fire (file:///Users/llali-mac/work/azuredatastudio/out/vs/base/common/event.js:456:38)
    at Emitter.fire (file:///Users/llali-mac/work/azuredatastudio/out/vs/base/common/event.js:459:41)
    at TreeModel.setSelection (file:///Users/llali-mac/work/azuredatastudio/out/vs/base/parts/tree/browser/treeModel.js:883:31)
    at Tree.setSelection (file:///Users/llali-mac/work/azuredatastudio/out/vs/base/parts/tree/browser/treeImpl.js:155:24)
    at TaskHistoryController.onLeftClick (file:///Users/llali-mac/work/azuredatastudio/out/vs/base/parts/tree/browser/treeDefaults.js:131:22)
    at TaskHistoryController.onLeftClick (file:///Users/llali-mac/work/azuredatastudio/out/sql/workbench/contrib/tasks/browser/tasksController.js:32:26)
    at TaskHistoryController.onMouseDown (file:///Users/llali-mac/work/azuredatastudio/out/vs/base/parts/tree/browser/treeDefaults.js:97:29)
    at TreeView.onMouseDown (file:///Users/llali-mac/work/azuredatastudio/out/vs/base/parts/tree/browser/treeView.js:884:37)

**Comment by udeeshagautam** [comment]
Seems intermittent as we we note able to repro for Sept Triage

**Comment by kburtram** [comment]
Closing older issues without recent repro reports.  I couldn't repro on the latest build.  Please reactive if the issue persists.
