### ISSUE TITLE
Unexpected Error Occurred while Connecting

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#11954]
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Open ADS
2. Double-click on a connection node

Expected: Node expands

Actual: Frequently hitting below prompt

```
An unexpected error occurred while connecting. Please [file an issue](command:workbench.action.openIssueReporter) with the title 'Unexpected Error Occurred while Connecting' and include the log file [C:\Users\karlb\AppData\Roaming\azuredatastudio\logs\20200825T113136\renderer1.log](command:workbench.action.openLogsFolder)
```

![image](https://user-images.githubusercontent.com/599935/91213611-b6064a00-e6c6-11ea-8d05-34d956d4d19a.png)

Error log contains below error
```
[2020-08-25 11:31:47.627] [renderer1] [error] OnConnectionComplete but no connection found 'file:///null' Connections = [connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:192.168.0.75|user:sa|group:C777F06B-202E-4480-B475-FA416154D458,dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:192.168.0.75|user:sa|group:C777F06B-202E-4480-B475-FA416154D458,connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:192.168.0.75|user:sa|group:C777F06B-202E-4480-B475-FA416154D458]
[2020-08-25 11:31:47.663] [renderer1] [error] Unexpected error occurred while connecting.: Error: Unexpected error occurred while connecting.
    at ConnectionStatusManager.onConnectionComplete (file:///C:/Users/karlb/repros/azuredatastudio/out/sql/platform/connection/common/connectionStatusManager.js:122:23) [<root>]
    at ConnectionManagementService.onConnectionComplete (file:///C:/Users/karlb/repros/azuredatastudio/out/sql/workbench/services/connection/browser/connectionManagementService.js:824:60) [<root>]
    at MainThreadDataProtocol.$onConnectionComplete (file:///C:/Users/karlb/repros/azuredatastudio/out/sql/workbench/api/browser/mainThreadDataProtocol.js:442:47) [<root>]
    at RPCProtocol._doInvokeHandler (file:///C:/Users/karlb/repros/azuredatastudio/out/vs/workbench/services/extensions/common/rpcProtocol.js:341:27) [<root>]
    at RPCProtocol._invokeHandler (file:///C:/Users/karlb/repros/azuredatastudio/out/vs/workbench/services/extensions/common/rpcProtocol.js:326:45) [<root>]
    at RPCProtocol._receiveRequest (file:///C:/Users/karlb/repros/azuredatastudio/out/vs/workbench/services/extensions/common/rpcProtocol.js:253:32) [<root>]
    at RPCProtocol._receiveOneMessage (file:///C:/Users/karlb/repros/azuredatastudio/out/vs/workbench/services/extensions/common/rpcProtocol.js:181:26) [<root>]
    at file:///C:/Users/karlb/repros/azuredatastudio/out/vs/workbench/services/extensions/common/rpcProtocol.js:65:52 [<root>]
    at Emitter.fire (file:///C:/Users/karlb/repros/azuredatastudio/out/vs/base/common/event.js:456:38) [<root>]
    at BufferedEmitter.fire (file:///C:/Users/karlb/repros/azuredatastudio/out/vs/base/parts/ipc/common/ipc.net.js:369:35) [<root>]
    at PersistentProtocol._receiveMessage (file:///C:/Users/karlb/repros/azuredatastudio/out/vs/base/parts/ipc/common/ipc.net.js:591:37) [<root>]
    at file:///C:/Users/karlb/repros/azuredatastudio/out/vs/base/parts/ipc/common/ipc.net.js:462:83 [<root>]
    at Emitter.fire (file:///C:/Users/karlb/repros/azuredatastudio/out/vs/base/common/event.js:456:38) [<root>]
    at ProtocolReader.acceptChunk (file:///C:/Users/karlb/repros/azuredatastudio/out/vs/base/parts/ipc/common/ipc.net.js:188:37) [<root>]
    at file:///C:/Users/karlb/repros/azuredatastudio/out/vs/base/parts/ipc/common/ipc.net.js:157:61 [<root>]
    at Socket.listener (file:///C:/Users/karlb/repros/azuredatastudio/out/vs/base/parts/ipc/node/ipc.net.js:17:40) [<root>]
    at Socket.ZoneTask.invoke (C:\Users\karlb\repros\azuredatastudio\node_modules\zone.js\dist\zone-node.js:485:48) [<root>]
    at Socket.emit (events.js:203:13) [<root>]
    at addChunk (_stream_readable.js:295:12) [<root>]
    at readableAddChunk (_stream_readable.js:276:11) [<root>]
    at Socket.Readable.push (_stream_readable.js:210:10) [<root>]
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17) [<root>]
```

**Comment by kburtram** [comment]
I'm also see connections getting into a "spinning forever" state pretty frequently with recent builds.

![image](https://user-images.githubusercontent.com/599935/91218936-b4408480-e6ce-11ea-8362-67f3f1f4b7c4.png)

**Comment by kburtram** [comment]
@Charles-Gagnon I'm seeing a lot of OE and Connection related errors that I don't recall seeing in August release.  Could you please confirm whether these are related to recent large refactoring in this area.

**Comment by kburtram** [comment]
Seeing this exception causing OE problems in current builds as well.  Not sure if this is all the same category of errors or distinct bugs.

```
[10576:0825/121953.130:INFO:CONSOLE(2280)] "%c  ERR color: #f33 Cannot read property 'isCloud' of undefined: TypeError: Cannot read property 'isCloud' of undefined
        at MssqlIconProvider.getConnectionIconId (c:\Users\karlb\repros\azuredatastudio\extensions\mssql\out\iconProvider.js:18:28)
        at ExtHostDataProtocol.$getConnectionIconId (c:\Users\karlb\repros\azuredatastudio\out\sql\workbench\api\common\extHostDataProtocol.js:336:50)
        at RPCProtocol._doInvokeHandler (c:\Users\karlb\repros\azuredatastudio\out\vs\workbench\services\extensions\common\rpcProtocol.js:341:27)
        at RPCProtocol._invokeHandler (c:\Users\karlb\repros\azuredatastudio\out\vs\workbench\services\extensions\common\rpcProtocol.js:326:45)
        at RPCProtocol._receiveRequest (c:\Users\karlb\repros\azuredatastudio\out\vs\workbench\services\extensions\common\rpcProtocol.js:253:32)
        at RPCProtocol._receiveOneMessage (c:\Users\karlb\repros\azuredatastudio\out\vs\workbench\services\extensions\common\rpcProtocol.js:190:26)
        at c:\Users\karlb\repros\azuredatastudio\out\vs\workbench\services\extensions\common\rpcProtocol.js:65:52
        at Emitter.fire (c:\Users\karlb\repros\azuredatastudio\out\vs\base\common\event.js:456:38)
        at BufferedEmitter.fire (c:\Users\karlb\repros\azuredatastudio\out\vs\base\parts\ipc\common\ipc.net.js:369:35)
        at c:\Users\karlb\repros\azuredatastudio\out\vs\workbench\services\extensions\node\extensionHostProcessSetup.js:145:41
        at Emitter.fire (c:\Users\karlb\repros\azuredatastudio\out\vs\base\common\event.js:456:38)
        at BufferedEmitter.fire (c:\Users\karlb\repros\azuredatastudio\out\vs\base\parts\ipc\common\ipc.net.js:369:35)
        at PersistentProtocol._receiveMessage (c:\Users\karlb\repros\azuredatastudio\out\vs\base\parts\ipc\common\ipc.net.js:591:37)
        at c:\Users\karlb\repros\azuredatastudio\out\vs\base\parts\ipc\common\ipc.net.js:462:83
        at Emitter.fire (c:\Users\karlb\repros\azuredatastudio\out\vs\base\common\event.js:456:38)
        at ProtocolReader.acceptChunk (c:\Users\karlb\repros\azuredatastudio\out\vs\base\parts\ipc\common\ipc.net.js:188:37)
        at c:\Users\karlb\repros\azuredatastudio\out\vs\base\parts\ipc\common\ipc.net.js:157:61
        at Socket.listener (c:\Users\karlb\repros\azuredatastudio\out\vs\base\parts\ipc\node\ipc.net.js:17:40)
        at Socket.emit (events.js:203:13)
        at addChunk (_stream_readable.js:295:12)
        at readableAddChunk (_stream_readable.js:276:11)
        at Socket.push (_stream_readable.js:210:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)", source: C:\Users\karlb\repros\azuredatastudio\node_modules\zone.js\dist\zone-node.js (2280)
```

**Comment by Charles-Gagnon** [comment]
Ack, I'll take a look. Don't think I've ran into this myself though so any extra information you're able to provide about the circumstances would be helpful. I'll at least try to add in some logging to try and help track down what's going on.

**Comment by kburtram** [comment]
@Charles-Gagnon I'll keep trying to get a better repro\root cause.  The issue seems to happen when I double-click on saved connections during early several seconds of startup, while tools service and extensions are loading.

**Comment by kburtram** [comment]
Closing older issues with recent repro reports.
