### ISSUE TITLE
Kusto extension errors on startup

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#11984]
![image](https://user-images.githubusercontent.com/28519865/91479678-af0e4180-e856-11ea-9e5b-464c742ab7bb.png)

**Comment by Charles-Gagnon** [comment]
@gupta1 @qifahs Can you look at this? It's pretty annoying to have this pop up every time I launch ADS from sources currently.

**Comment by Charles-Gagnon** [comment]
@gupta1 @qifahs What's the status on this? There's been multiple people who've asked about this - it would be nice to get this resolved quickly so people don't think something is broken with ADS.

**Comment by Charles-Gagnon** [comment]
Here's some more errors from the log :

```
[2020-08-28 08:21:58.641] [exthost] [error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
	at validateString (internal/validators.js:112:11)
	at Object.basename (path.js:671:5)
	at Object.getCommonLaunchArgsAndCleanupOldLogFiles (c:\src\AzureDataStudio\extensions\kusto\out\utils.js:64:37)
	at generateServerOptions (c:\src\AzureDataStudio\extensions\kusto\out\kustoServer.js:83:32)
	at KustoServer.start (c:\src\AzureDataStudio\extensions\kusto\out\kustoServer.js:32:33)
	at async activate (c:\src\AzureDataStudio\extensions\kusto\out\main.js:45:5)
	at async Promise.all (index 4)
	at async Promise.all (index 0)
```

**Comment by qifahs** [comment]
@gupta1 was out of office today. Investigating...
