### ISSUE TITLE
miaa creation fails on mac

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#12548]
with latest azdata bits on a dc created with very recent azdata, i run into this error when creating a miaa instance. Running the generated notebook from ADS does create the miaa instance successfully.

![image](https://user-images.githubusercontent.com/41588310/93839756-c87e8f80-fc42-11ea-97dd-a5e292352c99.png)
![image](https://user-images.githubusercontent.com/41588310/93839766-d207f780-fc42-11ea-8282-aec68cb3fca6.png)

This is the error capture from the 'Deployment' output channel.

    > azdata notebook run --path "/Users/arvranmac/Library/Application Support/azuredatastudio/User/globalStorage/microsoft.resource-deployment/nb-20200922023834.ipynb" --output-path "/Users/arvranmac/Library/Application Support/azuredatastudio/User/globalStorage/microsoft.resource-deployment" --timeout -1
    stderr: Traceback (most recent call last):
    stderr:   File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    stderr:     return _run_code(code, main_globals, None,
    stderr:   File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    stderr:     exec(code, run_globals)
    stderr:   File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/ipykernel_launcher.py", line 16, in <module>
    stderr:     app.launch_new_instance()
    stderr:   File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/traitlets/config/application.py", line 663, in launch_instance
    stderr:     app.initialize(argv)
    stderr:   File "<decorator-gen-124>", line 2, in initialize
    stderr:   File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    stderr:     return method(app, *args, **kwargs)
    stderr:   File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 582, in initialize
    stderr:     self.init_kernel()
    stderr:   File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 444, in init_kernel
    stderr:     kernel = kernel_factory(parent=self, session=self.session,
    stderr:   File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/traitlets/config/configurable.py", line 412, in instance
    stderr:     inst = cls(*args, **kwargs)
    stderr:   File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 85, in __init__
    stderr:     import appnope
    stderr: ModuleNotFoundError: No module named 'appnope'
    stderr: 
    stderr: ERROR: Kernel died before replying to kernel_info
    stderr: Traceback (most recent call last):
    stderr:   File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/azdata/cli/core/__init__.py", line 214, in invoke
    stderr:     cmd_result = self.invocation.execute(args)
    stderr:   File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/knack/invocation.py", line 208, in execute
    stderr:     cmd_result = parsed_args.func(params)
    stderr:   File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/knack/commands.py", line 139, in __call__
    stderr:     return self.handler(*args, **kwargs)
    stderr:   File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/knack/commands.py", line 246, in _command_handler
    stderr:     result = op(client, **command_args) if client else op(**command_args)
    stderr:   File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/azdata/cli/commands/notebook/custom.py", line 25, in run
    stderr:     notebook_output, notebook_html, results, exception = client.execute_notebook_batch(path, output_path=output_path, output_html=output_html, arguments=arguments, timeout=timeout)
    stderr:   File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/azdata/cli/commands/notebook/client.py", line 162, in execute_notebook_batch
    stderr:     out = ep.preprocess(nb, {'metadata': {'path': notebook_working_folder}})
    stderr:   File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 403, in preprocess
    stderr:     with self.setup_preprocessor(nb, resources, km=km):
    stderr:   File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    stderr:     return next(self.gen)
    stderr:   File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 345, in setup_preprocessor
    stderr:     self.km, self.kc = self.start_new_kernel(**kwargs)
    stderr:   File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 296, in start_new_kernel
    stderr:     kc.wait_for_ready(timeout=self.startup_timeout)
    stderr:   File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/jupyter_client/blocking/client.py", line 104, in wait_for_ready
    stderr:     raise RuntimeError('Kernel died before replying to kernel_info')
    stderr: RuntimeError: Kernel died before replying to kernel_info
    stderr: 
    >>> azdata notebook run --path "/Users/arvranmac/Library/Application Support/azuredatastudio/User/globalStorage/microsoft.resource-deployment/nb-20200922023834.ipynb" --output-path "/Users/arvranmac/Library/Application Support/azuredatastudio/User/globalStorage/microsoft.resource-deployment" --timeout -1    … exited with code: 1
	>>> azdata notebook run --path "/Users/arvranmac/Library/Application Support/azuredatastudio/User/globalStorage/microsoft.resource-deployment/nb-20200922023834.ipynb" --output-path "/Users/arvranmac/Library/Application Support/azuredatastudio/User/globalStorage/microsoft.resource-deployment" --timeout -1   … errored out: Process exited with code 1The task "Deploy Azure SQL managed instance - Azure Arc (preview)" has failed.

This error was reproducible by trying to run the same notebook from commandline directly, bypassing azdata

**Comment by ranasaria** [comment]
This can also be reproed from command line using that attached notebooks(s). Here is more info with --debug flag passed to azdata.

❯ azdata notebook run --path "/Users/arvranmac/hello.ipynb" --output-path "/Users/arvranmac/Downloads" --timeout -1 --debug
2020-09-21 20:22:46.0874 UTC | DEBUG | File logging enabled - writing logs to '/Users/arvranmac/.azdata/logs'.
2020-09-21 20:22:46.0876 UTC | DEBUG | Event: OutputProducer.OnOutput [<function OutputProducer.__init__.<locals>.<lambda> at 0x10fa15e50>]
2020-09-21 20:22:46.0876 UTC | DEBUG | Event: Cli.PreExecute []
2020-09-21 20:22:46.0877 UTC | DEBUG | Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x10f922c10>, <function OutputProducer.on_global_arguments at 0x10f9ab8b0>, <function CLIQuery.on_global_arguments at 0x10f9d6d30>]
2020-09-21 20:22:46.0878 UTC | DEBUG | Event: CommandInvoker.OnPreCommandTableTruncate [<function CliLogging.init_command_file_logging at 0x10fa0e700>]
2020-09-21 20:22:46.0907 UTC | DEBUG | None
2020-09-21 20:22:46.0908 UTC | DEBUG | profile base location: /Users/arvranmac/.azdata
2020-09-21 20:22:46.0908 UTC | DEBUG | profile location: /Users/arvranmac/.azdata/azdata-profile.json
2020-09-21 20:22:48.0173 UTC | DEBUG | No module named 'azdata.cli.core.__extensions__'
2020-09-21 20:22:48.0173 UTC | DEBUG | Skipping pre-package extensions, not found.
2020-09-21 20:22:48.0174 UTC | DEBUG | ext_dir /Users/arvranmac/.azdata/extensions
2020-09-21 20:22:48.0174 UTC | DEBUG | env_value None
2020-09-21 20:22:48.0174 UTC | DEBUG | default_value /Users/arvranmac/.azdata/extensions
2020-09-21 20:22:48.0174 UTC | DEBUG | edit_mode False
azdata_command_data_logger : command args: notebook run --path /Users/arvranmac/hello.ipynb --output-path /Users/arvranmac/Downloads --timeout -1 --debug
2020-09-21 20:22:48.0177 UTC | DEBUG | metadata file logging enabled - writing logs to "/Users/arvranmac/.azdata/commands".
2020-09-21 20:22:48.0177 UTC | DEBUG | Event: CommandInvoker.OnPreCommandTableCreate []
2020-09-21 20:22:48.0179 UTC | DEBUG | Event: CommandLoader.OnLoadArguments []
2020-09-21 20:22:48.0179 UTC | DEBUG | Event: CommandInvoker.OnPostCommandTableCreate []
2020-09-21 20:22:48.0252 UTC | DEBUG | Event: CommandInvoker.OnCommandTableLoaded []
2020-09-21 20:22:48.0253 UTC | DEBUG | Event: CommandInvoker.OnPreParseArgs []
2020-09-21 20:22:48.0253 UTC | DEBUG | Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x10f9ab940>, <function CLIQuery.handle_query_parameter at 0x10f9d6dc0>]
2020-09-21 20:22:48.0258 UTC | DEBUG | Controller endpoint https://40.65.237.56:30080
2020-09-21 20:22:48.0259 UTC | DEBUG | Attached optional services None
2020-09-21 20:22:48.0259 UTC | DEBUG | ['BILLING_MODEL_COMSUMPTION', 'CLUSTER_CONNECTION_MODE_DISCONNECTED', 'CUSTOM_OBJECT_NAME', 'DEFAULT_DATA_CONTROLLER_NAME', 'GUID_REGEX', 'INSTANCE_NAME', 'INSTANCE_TYPE', 'INSTANCE_TYPE_DATA_CONTROLLER', 'LOCATION', 'RESOURCE_GROUP_NAME', 'SUBSCRIPTION_ID', '__abstractmethods__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', 'acquire_token', 'api_client', 'create_app', 'create_cluster', 'create_mount', 'delete_app', 'delete_cluster', 'delete_instance', 'delete_mount', 'delete_registration_instance', 'endpoint', 'get_bdc_status', 'get_cluster', 'get_cluster_state', 'get_control_status', 'get_controller_logs', 'get_endpoints', 'get_instance', 'get_mount_status', 'is_ready', 'list_app', 'list_apps', 'list_deleted_resources', 'list_registration_instances', 'logs_post', 'metrics_post', 'refresh_mount', 'register_instance', 'register_instance_by_configuration', 'resource_crd_get', 'resource_spec_get', 'resource_types_get', 'set_authorization_header', 'signing_certificate_public_key_get', 'update_app', 'upgrade_bdc', 'upgrade_control_plane', 'usages_post']
traitlets : Starting kernel: ['/usr/local/Cellar/azdata-cli/20.2.0/libexec/bin/python', '-m', 'ipykernel_launcher', '-f', '/private/var/folders/lf/157nvn6n3412b1f6nq2x5g140000gn/T/tmpawr80y3k.json', '--HistoryManager.hist_file=:memory:']
traitlets : Connecting to: tcp://127.0.0.1:51358
traitlets : connecting shell channel to tcp://127.0.0.1:51355
traitlets : Connecting to: tcp://127.0.0.1:51355
traitlets : connecting iopub channel to tcp://127.0.0.1:51356
traitlets : Connecting to: tcp://127.0.0.1:51356
traitlets : connecting stdin channel to tcp://127.0.0.1:51357
traitlets : Connecting to: tcp://127.0.0.1:51357
traitlets : connecting heartbeat channel to tcp://127.0.0.1:51359
traitlets : connecting control channel to tcp://127.0.0.1:51358
traitlets : Connecting to: tcp://127.0.0.1:51358
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 582, in initialize
    self.init_kernel()
  File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 444, in init_kernel
    kernel = kernel_factory(parent=self, session=self.session,
  File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 85, in __init__
    import appnope
ModuleNotFoundError: No module named 'appnope'
2020-09-21 20:22:50.0723 UTC | ERROR | Kernel died before replying to kernel_info
Traceback (most recent call last):
  File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/azdata/cli/core/__init__.py", line 214, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/knack/invocation.py", line 208, in execute
    cmd_result = parsed_args.func(params)
  File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/knack/commands.py", line 139, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/knack/commands.py", line 246, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/azdata/cli/commands/notebook/custom.py", line 25, in run
    notebook_output, notebook_html, results, exception = client.execute_notebook_batch(path, output_path=output_path, output_html=output_html, arguments=arguments, timeout=timeout)
  File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/azdata/cli/commands/notebook/client.py", line 162, in execute_notebook_batch
    out = ep.preprocess(nb, {'metadata': {'path': notebook_working_folder}})
  File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 403, in preprocess
    with self.setup_preprocessor(nb, resources, km=km):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 345, in setup_preprocessor
    self.km, self.kc = self.start_new_kernel(**kwargs)
  File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 296, in start_new_kernel
    kc.wait_for_ready(timeout=self.startup_timeout)
  File "/usr/local/Cellar/azdata-cli/20.2.0/libexec/lib/python3.8/site-packages/jupyter_client/blocking/client.py", line 104, in wait_for_ready
    raise RuntimeError('Kernel died before replying to kernel_info')
RuntimeError: Kernel died before replying to kernel_info
azdata_command_data_logger : exit code: 1
2020-09-21 20:22:50.0736 UTC | INFO | command ran in 3.877 seconds.



[test_notebooks.zip](https://github.com/microsoft/azuredatastudio/files/5259059/test_notebooks.zip)

**Comment by ranasaria** [comment]
Moving this issue to arc platform team. The following will track this issue going forward:

https://sqlhelsinki.visualstudio.com/aris/_workitems/edit/17641/
