### ISSUE TITLE
ML Extension Adding a new package to a database does not work

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#12846]
- Azure Data Studio Version:
Version: 1.23.0-rc1 (user setup)
Commit: 7429407029af2e08d17a8928825815cffad94f17
Date: 2020-10-09T00:55:31.875Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

ML Extension 0.4.0

Steps to Reproduce: (This seems to be a regression)
1. Connect to a SQL MI server with ML enabled.
2. Launch ML extension.
3. Click on **Manage packages in database**.
4. Click on **Add New** tab.
5. Search for _glue_ package.
6. Click **Install**.

```
Installation will error with the following message: 
Installing glue 0.13: Failed to install glue 0.13. Error: Process exited with code: 1. output: Traceback (most recent call last):
File "<stdin>", line 4, in <module>
File "C:\Users\<<USER>>\azuredatastudio-python\0.0.1\lib\site-packages\sqlmlutils\packagemanagement\sqlpackagemanager.py", line 72, in install
self._install_from_pypi(package, upgrade, version, install_dependencies, scope, out_file=out_file)
File "C:\Users\<<USER>>\azuredatastudio-python\0.0.1\lib\site-packages\sqlmlutils\packagemanagement\sqlpackagemanager.py", line 150, in _install_from_pypi
target_package_file = pipdownloader.download_single()
File "C:\Users\<<USER>>\azuredatastudio-python\0.0.1\lib\site-packages\sqlmlutils\packagemanagement\pipdownloader.py", line 26, in download_single
_, pkgsdownloaded = self._download(False)
File "C:\Users\<<USER>>\azuredatastudio-python\0.0.1\lib\site-packages\sqlmlutils\packagemanagement\pipdownloader.py", line 44, in _download
raise RuntimeError("Failed to download any packages, pip returned error: " + error)
RuntimeError: Failed to download any packages, pip returned error: Traceback (most recent call last):

File "C:\Users\<<USER>>\azuredatastudio-python\0.0.1\lib\site-packages\sqlmlutils\packagemanagement\download_script.py", line 13, in <module>

from pip._internal import pep425tags

ImportError: cannot import name 'pep425tags'
```

**Comment by udeeshagautam** [comment]
Adding for Nov since this doesnt need port and we can refresh it before if we have a consistent repro. Not able to repro it.

**Comment by llali** [comment]
@MsSQLGirl  you probably have sqlmlutils 1.0.2 installed and that's why you get this error. I reported the bug to @JonathanZhu11 . If you uninstall it then ML extension will use 1.0.1 which works
