### ISSUE TITLE
Notebook failed to initialize due to conflicting PYTHONHOME environment variable.

### ISSUE THREAD

**Issue by guitarnana** [microsoft/azuredatastudio#12995]
- Azure Data Studio Version:
Version: 1.23.0
Commit: d296b6397e0acfddc57e9085e736e084969cdaeb
Date: 2020-10-13T23:03:09.799Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. set PYTHONHOME to c:\python37. Assuming you have python37 installed at c:\python37
2. install ML extension.
3. start ADS

ML extension will failed to start because it depends on notebook. Notebook failed to start because of the below error.
Note that I did not have any notebook opne in ADS. This is also a fresh install of ADS and ML extension.

![image](https://user-images.githubusercontent.com/922655/96520895-e8df4100-1224-11eb-83e6-bff9b82b4f3f.png)

```
[2020-10-19 14:53:26.265] [exthost] [info] extension host started
[2020-10-19 14:53:26.272] [exthost] [info] ExtensionService#_doActivateExtension Microsoft.azurecore {"startup":true,"extensionId":{"value":"Microsoft.azurecore","_lower":"microsoft.azurecore"},"activationEvent":"*"}
[2020-10-19 14:53:26.272] [exthost] [info] ExtensionService#loadCommonJSModule file:///e:/azuredatastudio-windows-1.23.0/resources/app/extensions/azurecore/dist/extension
[2020-10-19 14:53:26.403] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-10-19 14:53:26.403] [exthost] [info] ExtensionService#loadCommonJSModule file:///e:/azuredatastudio-windows-1.23.0/resources/app/extensions/git/dist/main
[2020-10-19 14:53:26.528] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"*"}
[2020-10-19 14:53:26.528] [exthost] [info] ExtensionService#loadCommonJSModule file:///e:/azuredatastudio-windows-1.23.0/resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2020-10-19 14:53:26.561] [exthost] [info] ExtensionService#_doActivateExtension Microsoft.notebook {"startup":true,"extensionId":{"value":"Microsoft.notebook","_lower":"microsoft.notebook"},"activationEvent":"*"}
[2020-10-19 14:53:26.561] [exthost] [info] ExtensionService#loadCommonJSModule file:///e:/azuredatastudio-windows-1.23.0/resources/app/extensions/notebook/dist/extension
[2020-10-19 14:53:26.937] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
[2020-10-19 14:53:26.937] [exthost] [info] ExtensionService#loadCommonJSModule file:///e:/azuredatastudio-windows-1.23.0/resources/app/extensions/search-result/dist/extension.js
[2020-10-19 14:53:26.954] [exthost] [info] ExtensionService#_doActivateExtension Microsoft.datavirtualization {"startup":true,"extensionId":{"value":"Microsoft.datavirtualization","_lower":"microsoft.datavirtualization"},"activationEvent":"*"}
[2020-10-19 14:53:26.954] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jarupatj/.azuredatastudio/extensions/microsoft.datavirtualization-1.10.0/out/src/extension
[2020-10-19 14:53:29.387] [exthost] [error] Activating extension Microsoft.notebook failed due to an error:
[2020-10-19 14:53:29.387] [exthost] [error] Error: Command failed: "C:\Users\jarupatj\azuredatastudio-python\0.0.1\python.exe" -c "import site;print(site.USER_SITE)"
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "C:\Python37\lib\_bootlocale.py", line 12, in getpreferredencoding
    if sys.flags.utf8_mode:
AttributeError: 'sys.flags' object has no attribute 'utf8_mode'
 
    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[2020-10-19 14:53:29.387] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-10-19 14:53:29.388] [exthost] [info] ExtensionService#loadCommonJSModule file:///e:/azuredatastudio-windows-1.23.0/resources/app/extensions/github/dist/extension.js
[2020-10-19 14:53:29.430] [exthost] [info] ExtensionService#_doActivateExtension Microsoft.mssql {"startup":true,"extensionId":{"value":"Microsoft.mssql","_lower":"microsoft.mssql"},"activationEvent":"*"}
[2020-10-19 14:53:29.430] [exthost] [info] ExtensionService#loadCommonJSModule file:///e:/azuredatastudio-windows-1.23.0/resources/app/extensions/mssql/dist/main
[2020-10-19 14:53:32.665] [exthost] [info] eager extensions activated
[2020-10-19 14:53:41.131] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"extensionId":{"value":"vscode.configuration-editing","_lower":"vscode.configuration-editing"},"activationEvent":"onLanguage:jsonc"}
[2020-10-19 14:53:41.131] [exthost] [info] ExtensionService#loadCommonJSModule file:///e:/azuredatastudio-windows-1.23.0/resources/app/extensions/configuration-editing/dist/configurationEditingMain
[2020-10-19 14:53:41.137] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"extensionId":{"value":"vscode.json-language-features","_lower":"vscode.json-language-features"},"activationEvent":"onLanguage:jsonc"}
[2020-10-19 14:53:41.138] [exthost] [info] ExtensionService#loadCommonJSModule file:///e:/azuredatastudio-windows-1.23.0/resources/app/extensions/json-language-features/client/dist/node/jsonClientMain
```

You will see the failure that it can't find utf8_mode because utf8_mode only available on python 3.7 and later
https://github.com/pyinstaller/pyinstaller/issues/3866

```
[2020-10-19 14:53:29.387] [exthost] [error] Error: Command failed: "C:\Users\jarupatj\azuredatastudio-python\0.0.1\python.exe" -c "import site;print(site.USER_SITE)"
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "C:\Python37\lib\_bootlocale.py", line 12, in getpreferredencoding
    if sys.flags.utf8_mode:
AttributeError: 'sys.flags' object has no attribute 'utf8_mode'
```

Looking closely, python that ADS uses are python36. However, since we have python37 as default by setting PYTHONHOME, this cause conflict.

```
C:\Users\jarupatj\azuredatastudio-python\0.0.1>python.exe
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by udeeshagautam** [comment]
Related issue : https://github.com/microsoft/azuredatastudio/issues/12995

**Comment by udeeshagautam** [comment]
@chlafreniere I have tagged it for backlog for now - but do you know if there is something from the Notebook Extn side that can be shared fto make the error more informative?

**Comment by chlafreniere** [comment]
@udeeshagautam was waiting on our friend who was running into this issue to get back to me on a potential fix that I had made 😄. Been verified now, so sent out the PR.

In terms of logging, there isn't anything extra at the moment that users can enable. We'll be vastly improving the logging story in the next couple of months.
