### ISSUE TITLE
Can't connect to database

### ISSUE THREAD

**Issue by RogueSensei** [microsoft/azuredatastudio#13036]
Issue Type: <b>Bug</b>

I can't connect to any of my databases. The connection appears to be successful but I cannot view any of my tables, stored procedures etc.
![image](https://user-images.githubusercontent.com/32780495/96844448-6c787800-1447-11eb-8ed9-4af9c2e5e1eb.png)
I have tried this both with extensions enabled and disabled and I've had no dice. I can connect just fine with SSMS:
![image](https://user-images.githubusercontent.com/32780495/96844647-a8abd880-1447-11eb-9a2a-21ed883d7bea.png)
Looking in the console I can see the following errors:
![image](https://user-images.githubusercontent.com/32780495/96845208-5b7c3680-1448-11eb-9e3e-8c49e5d03e4f.png)
![image](https://user-images.githubusercontent.com/32780495/96845264-6931bc00-1448-11eb-817e-07297f05828f.png)

I have repeatedly tried this for days checking for updates every day (of which there are none) but have not had a successful connection

Azure Data Studio version: azuredatastudio 1.23.0 (d296b6397e0acfddc57e9085e736e084969cdaeb, 2020-10-13T23:03:09.799Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (0.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment]
Is this a new issue since 1.23? This looks to be the same as https://github.com/microsoft/azuredatastudio/issues/12992, can you confirm if you go back to 1.22.1 or an earlier build that you can view the nodes correctly? https://github.com/microsoft/azuredatastudio/releases

**Comment by RogueSensei** [comment]
Issue #12992 looks to be the same issue, yes. I can also confirm that the nodes work correctly on 1.22.1
![image](https://user-images.githubusercontent.com/32780495/96903647-04995000-148e-11eb-9bbb-b70dc9af0e69.png)

**Comment by Charles-Gagnon** [comment]
Thanks - I'll close this as a duplicate then and can you please provide the information I asked for in that thread?

1. What type of server you're connecting to
1. Does this happen for all servers?
1. Any errors in the logs? (I'll post instructions in that thread)

**Comment by RogueSensei** [comment]
Cool, thanks. I'm away from my work computer for the evening so I apologise if the following information is a tad limited. I can check tomorrow if you require anything more detailed.

1. They're Azure Virtual Machines
2. Yes
3. As far as I'm aware those errors are all I've got, though I seem to be able to connect fine from SQL Server Management Studio

**Comment by RogueSensei** [comment]
Error in the `renderer1.log` is the same as what I saw in the inspector (apologies for providing late)
```
[2020-10-26 13:02:57.171] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2020-10-26 13:02:57.178] [renderer1] [error] Cannot read property 'isCloud' of null: TypeError: Cannot read property 'isCloud' of null
	at t.MssqlIconProvider.getConnectionIconId (c:\Users\Chris\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:411:37875)
	at d.$getConnectionIconId (c:\Users\Chris\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:697:248)
	at g._doInvokeHandler (c:\Users\Chris\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:969:707)
	at g._invokeHandler (c:\Users\Chris\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:969:399)
	at g._receiveRequest (c:\Users\Chris\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:968:59)
	at g._receiveOneMessage (c:\Users\Chris\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:966:886)
	at c:\Users\Chris\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:965:34
	at l.fire (c:\Users\Chris\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:475)
	at v.fire (c:\Users\Chris\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:259:381)
	at c:\Users\Chris\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1149:963
	at l.fire (c:\Users\Chris\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:475)
	at v.fire (c:\Users\Chris\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:259:381)
	at t.PersistentProtocol._receiveMessage (c:\Users\Chris\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:264:451)
	at c:\Users\Chris\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:261:489
	at l.fire (c:\Users\Chris\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:475)
	at p.acceptChunk (c:\Users\Chris\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:851)
	at c:\Users\Chris\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:203
	at Socket.t (c:\Users\Chris\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:266:54)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```
