### ISSUE TITLE
Cannot access or reopen a database which is "Auto Closed"

### ISSUE THREAD

**Issue by aisbergde** [microsoft/azuredatastudio#13202]
- Azure Data Studio Version:
1.23.0 (user setup)
but it did never work in any version

The following issue is closed and I can't comment there, thats why I open a new issue with the same topic
Cannot access a database with AUTO_CLOSE=ON #189
https://github.com/microsoft/azuredatastudio/issues/189

Steps to Reproduce:

sometimes (too often) databases on localdb become "auto-closed"
I can't find any way to reopen them using ADS
I can't use SSMS because it requires admin rights which I don't get on my PC. And SSMS in a Citrix environment which I am allowed to use can't connect to my localdb on my local PC.
=> The only way for me to access localdb which I know is ADS

I tried some settings in the databases to avoid to often to auto-close but it still sometimes happens. And then I have no chance to access these databases. I only can delete them and I can hope that I did a script of the content of these databases before to restore the databases and the content.

If it is not possible to use ADS to open an auto-closed database. Is there any other way which works without admin rights?

When I try to do anything with the auto closed databases I get:

```
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot open database "dwh_DataBaseName" requested by the login. The login failed.
Login failed for user 'EUROPE\mz12345'.
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass45_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass30_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 314
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 549
ClientConnectionId:5b74aae0-79c0-4556-aaf5-cb93fddae670
Error Number:4060,State:1,Class:11
```

**Comment by aisbergde** [comment]
Maybe the reason is that sometimes by some cleaning process which does the company on my PC the database files will be deleted if they are in temp folders.

When I connect to `Master` and run the query
`select * from repo_PerformanceAnalytics.dbo.aaa`
I get this error:

>14:09:21Started executing query at Line 1
>Msg 5120, Level 16, State 101, Line 1
>Unable to open the physical file "C:\Users\mz12345\AppData\Local\Temp\repo_PerformanceAnalytics.mdf". Operating system error 2: "2(Das System kann die angegebene Datei nicht finden.)".
>Total execution time: 00:00:00.013

And this file is really missing.

So I suggest to implement a better error message in case the database files are missing, especially on localdb issues. Then it would be easier to understand why a connection is not possible.

**Comment by Charles-Gagnon** [comment]
This doesn't really seem to be an issue with ADS - we display the error the engine gives us but often don't have any extra details about why the failure happened (such as files missing or the database being closed)

Have you tried storing the database files in a location that isn't going to be cleaned up? Or using something like Azure instead of your local machine?

**Comment by aisbergde** [comment]
I changed to create databases in a dedicated directory which should not be automatically cleaned up. And now I understand that the issue is the poor error message you get from the database engine. If there is no way to get a better error message then I also have no idea how this could be improved.
