### ISSUE TITLE
Cannot set AccessToken property error connecting with Integrated Auth

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#13213]
- Azure Data Studio Version:

Steps to Reproduce:

1. Add a connection using Integrated Auth
2. Close and reopen vscode
3. Expand Connection in OE

Expected: Connection expands sucessfully

Actual: Error about not being able to set AccessToken

![image](https://user-images.githubusercontent.com/599935/98070646-5d65d280-1e16-11eb-9fc5-a61f0eeca437.png)

**Comment by kburtram** [comment]
I get this exception stack when trying to open a query editor with the Integrated Auth connection
```
mssql: Failed to connect: System.InvalidOperationException: Cannot set the AccessToken property if the 'Integrated Security' connection string keyword has been set to 'true' or 'SSPI'.
   at Microsoft.Data.SqlClient.SqlConnection.CheckAndThrowOnInvalidCombinationOfConnectionOptionAndAccessToken(SqlConnectionString connectionOptions)
   at Microsoft.Data.SqlClient.SqlConnection.set_AccessToken(String value)
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection..ctor(String connectionString, RetryPolicy connectionRetryPolicy, RetryPolicy commandRetryPolicy, String azureAccountToken) in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 77
   at Microsoft.SqlTools.ServiceLayer.Connection.SqlConnectionFactory.CreateSqlConnection(String connectionString, String azureAccountToken) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\SqlConnectionFactory.cs:line 25
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 532
```
