### ISSUE TITLE
An unexpected error occurred while connecting.

### ISSUE THREAD

**Issue by KhairulHabibSamaon** [microsoft/azuredatastudio#13214]
[2020-11-04 15:09:04.935] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:09:04.936] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:09:04.936] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:09:08.730] [renderer1] [info] Adding connection with DB name connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:09:09.443] [renderer1] [info] Creating new connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:09:09.443] [renderer1] [info] Adding connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:09:09.443] [renderer1] [info] Successfully added connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:09:09.946] [renderer1] [error] Failed to create Object Explorer session
[2020-11-04 15:09:10.999] [renderer1] [info] Creating new connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:09:10.999] [renderer1] [info] Adding connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:09:10.999] [renderer1] [info] Successfully added connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:09:11.603] [renderer1] [warning] Got request to send an event to a dashboard that has not started listening
[2020-11-04 15:09:30.500] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:hauz-sql-server.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:admin|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:09:30.501] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:hauz-sql-server.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:admin|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:09:30.501] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:hauz-sql-server.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:admin|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:13:27.887] [renderer1] [info] Adding connection with DB name connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauz-sql-server.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:admin|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:13:29.817] [renderer1] [info] Creating new connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauz-sql-server.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:admin|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:13:29.817] [renderer1] [info] Adding connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauz-sql-server.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:admin|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:13:29.817] [renderer1] [info] Successfully added connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauz-sql-server.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:admin|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:13:30.233] [renderer1] [info] Creating new connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauz-sql-server.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:admin|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:13:30.233] [renderer1] [info] Adding connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauz-sql-server.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:admin|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:13:30.233] [renderer1] [info] Successfully added connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauz-sql-server.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:admin|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:13:30.467] [renderer1] [warning] Got request to send an event to a dashboard that has not started listening
[2020-11-04 15:16:05.890] [renderer1] [info] Creating new connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:16:05.890] [renderer1] [info] Adding connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:16:05.890] [renderer1] [info] Successfully added connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:17:14.430] [renderer1] [info] Deleting connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:17:14.430] [renderer1] [info] Deleting connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:18:02.045] [renderer1] [info] Creating new connection untitled:SQLQuery_1
[2020-11-04 15:18:02.045] [renderer1] [info] Adding connection untitled:SQLQuery_1
[2020-11-04 15:18:02.046] [renderer1] [info] Successfully added connection untitled:SQLQuery_1
[2020-11-04 15:18:11.758] [renderer1] [info] Creating new connection untitled:SQLQuery_1
[2020-11-04 15:18:11.758] [renderer1] [info] Adding connection untitled:SQLQuery_1
[2020-11-04 15:18:11.758] [renderer1] [info] Successfully added connection untitled:SQLQuery_1
[2020-11-04 15:22:07.960] [renderer1] [info] Deleting connection untitled:SQLQuery_1 (connecting)
[2020-11-04 15:22:25.198] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:22:25.198] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:22:25.199] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:22:26.461] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:22:26.461] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:22:26.461] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:22:27.074] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:22:27.074] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:22:27.074] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:22:32.560] [renderer1] [info] Deleting connection untitled:SQLQuery_1 (connecting)
[2020-11-04 15:22:32.560] [renderer1] [info] Deleting connection untitled:SQLQuery_1 (connecting)
[2020-11-04 15:22:33.858] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:22:33.858] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:22:33.858] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:22:37.756] [renderer1] [info] Deleting connection untitled:SQLQuery_1 (connecting)
[2020-11-04 15:22:37.756] [renderer1] [info] Deleting connection untitled:SQLQuery_1 (connecting)
[2020-11-04 15:22:37.756] [renderer1] [info] Deleting connection untitled:SQLQuery_1 (connecting)
[2020-11-04 15:24:33.069] [renderer1] [info] Deleting connection untitled:SQLQuery_1
[2020-11-04 15:24:33.071] [renderer1] [error] OnConnectionComplete but no connection found 'untitled:SQLQuery_1' Connections = [dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|group:C777F06B-202E-4480-B475-FA416154D458,dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458,connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:hauz-sql-server.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:admin|group:C777F06B-202E-4480-B475-FA416154D458,connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauz-sql-server.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:admin|group:C777F06B-202E-4480-B475-FA416154D458,dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauz-sql-server.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:admin|group:C777F06B-202E-4480-B475-FA416154D458,dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauz-sql-server.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:admin|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458,dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|group:C777F06B-202E-4480-B475-FA416154D458,connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458,connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|group:C777F06B-202E-4480-B475-FA416154D458]
[2020-11-04 15:24:33.113] [renderer1] [info] Deleting connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458
[2020-11-04 15:24:33.113] [renderer1] [error] OnConnectionComplete but no connection found 'connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458' Connections = [dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|group:C777F06B-202E-4480-B475-FA416154D458,dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458,connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:hauz-sql-server.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:admin|group:C777F06B-202E-4480-B475-FA416154D458,connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauz-sql-server.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:admin|group:C777F06B-202E-4480-B475-FA416154D458,dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauz-sql-server.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:admin|group:C777F06B-202E-4480-B475-FA416154D458,dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:hauz-sql-server.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:admin|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458,dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|group:C777F06B-202E-4480-B475-FA416154D458,connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:hauzdb-dev.cyotk7l1ngxc.ap-southeast-1.rds.amazonaws.com|user:daouda|group:C777F06B-202E-4480-B475-FA416154D458]
[2020-11-04 15:24:33.148] [renderer1] [error] Unexpected error occurred while connecting.: Error: Unexpected error occurred while connecting.
    at m.onConnectionComplete (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2405:316) [<root>]
    at e.onConnectionComplete (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5540:592) [<root>]
    at I.$onConnectionComplete (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5848:182) [<root>]
    at p._doInvokeHandler (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5970:202) [<root>]
    at p._invokeHandler (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5969:901) [<root>]
    at p._receiveRequest (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5968:510) [<root>]
    at p._receiveOneMessage (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5967:283) [<root>]
    at file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:5965:400 [<root>]
    at c.fire (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:213:801) [<root>]
    at fire (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:651:448) [<root>]
    at t.PersistentProtocol._receiveMessage (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:656:451) [<root>]
    at file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:653:533 [<root>]
    at c.fire (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:213:801) [<root>]
    at g.acceptChunk (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:648:897) [<root>]
    at file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:648:249 [<root>]
    at Socket.t (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:658:68) [<root>]
    at Socket.emit (events.js:223:5) [<root>]
    at addChunk (_stream_readable.js:309:12) [<root>]
    at readableAddChunk (_stream_readable.js:290:11) [<root>]
    at Socket.Readable.push (_stream_readable.js:224:10) [<root>]
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23) [<root>]

**Comment by cheenamalhotra** [comment]
Closing as stale, as no recent reports are received for this error.
