### ISSUE TITLE
Failed to change connection to newly created python kernel if Conda is installed

### ISSUE THREAD

**Issue by mosharafMS** [microsoft/azuredatastudio#13493]
- Azure Data Studio Version:

Steps to Reproduce:

1. Machine that has conda installed on it. 
2) Configure Python runtime and choose new python installation 
![image](https://user-images.githubusercontent.com/23546820/99728326-43b7c280-2a87-11eb-919d-21859247d8e1.png)

The installation doesn't report any error. these are the latest lines in the output 
Notebook dependencies installation is in progress
Notebook dependencies installation is complete
... Creating C:\Users\mosharaf\AppData\Roaming\jupyter\instances\ff413f18-84b7-45f0-9997-998da4b1da96
... Creating C:\Users\mosharaf\AppData\Roaming\jupyter\instances\ff413f18-84b7-45f0-9997-998da4b1da96\config
... Creating C:\Users\mosharaf\AppData\Roaming\jupyter\instances\ff413f18-84b7-45f0-9997-998da4b1da96\data
... Creating C:\Users\mosharaf\AppData\Roaming\jupyter\instances\ff413f18-84b7-45f0-9997-998da4b1da96\config\custom
... Starting Notebook server
    > "C:\Users\mosharaf\azuredatastudio-python\0.0.1\python.exe" "c:\Users\mosharaf\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\notebook\resources\pythonScripts\startNotebook.py" --no-browser --no-mathjax --notebook-dir "c:\Users\mosharaf" --port=8925 --NotebookApp.token=83bf979420bfbfd07577038bab6a02ff85387da571441c0c
... Creating C:\Users\mosharaf\AppData\Roaming\jupyter\instances\66ec6766-8a96-4326-bce2-011b5dfe802d
... Creating C:\Users\mosharaf\AppData\Roaming\jupyter\instances\66ec6766-8a96-4326-bce2-011b5dfe802d\config
... Creating C:\Users\mosharaf\AppData\Roaming\jupyter\instances\66ec6766-8a96-4326-bce2-011b5dfe802d\data
... Creating C:\Users\mosharaf\AppData\Roaming\jupyter\instances\66ec6766-8a96-4326-bce2-011b5dfe802d\config\custom
... Starting Notebook server
    > "C:\Users\mosharaf\azuredatastudio-python\0.0.1\python.exe" "c:\Users\mosharaf\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\notebook\resources\pythonScripts\startNotebook.py" --no-browser --no-mathjax --notebook-dir "c:\Users\mosharaf" --port=9320 --NotebookApp.token=63f484ebf923cda4202746f937e99d3cc713aca4a90bc94f
Notebook dependencies installation is in progress
Notebook dependencies installation is complete
... Creating C:\Users\mosharaf\AppData\Roaming\jupyter\instances\2b63194b-076f-4460-bd55-abba5c08952c
... Creating C:\Users\mosharaf\AppData\Roaming\jupyter\instances\2b63194b-076f-4460-bd55-abba5c08952c\config
... Creating C:\Users\mosharaf\AppData\Roaming\jupyter\instances\2b63194b-076f-4460-bd55-abba5c08952c\data
... Creating C:\Users\mosharaf\AppData\Roaming\jupyter\instances\2b63194b-076f-4460-bd55-abba5c08952c\config\custom
... Starting Notebook server
    > "C:\Users\mosharaf\azuredatastudio-python\0.0.1\python.exe" "c:\Users\mosharaf\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\notebook\resources\pythonScripts\startNotebook.py" --no-browser --no-mathjax --notebook-dir "c:\Users\mosharaf" --port=9071 --NotebookApp.token=978b452fefd99d8c49e18a936a55e68c122614c2e4a9d0e6

3) Open a new notebook and choose python as kernel

It fails with error 

Failed to change kernel. Kernel SQL will be used. Error was: Notebook process exited prematurely with error code: 1. StdErr Output: Traceback (most recent call last):
  File "c:\Users\mosharaf\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\notebook\resources\pythonScripts\startNotebook.py", line 1, in <module>
    import notebook.notebookapp
  File "C:\Users\mosharaf\AppData\Roaming\Python\Python36\site-packages\notebook\__init__.py", line 27, in <module>
    from .nbextensions import install_nbextension
  File "C:\Users\mosharaf\AppData\Roaming\Python\Python36\site-packages\notebook\nbextensions.py", line 18, in <module>
    from jupyter_core.paths import (
ModuleNotFoundError: No module named 'jupyter_core'

It seems it goes to the activated conda environment not the newly installed Python instance

**Comment by chlafreniere** [comment]
`ModuleNotFoundError: No module named 'jupyter_core'`

This seems quite interesting. Can you verify that you have the jupyter and ipykernel packages in your conda environment?

**Comment by mosharafMS** [comment]
Yes conda environments are all installed with jupyter.
However, it shouldn't have effect because this is a newly installed Python by data studio
