### ISSUE TITLE
Installing new ADS with Old DB project Extn gives a Toast Notif Error for undefined object

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#13622]
- Azure Data Studio Version:

Steps to Reproduce:

1. Have the ADS 1.24 installed with DB proj 4.1
2. Install New RC build to it
3. This creates the Workspaces tab (since the DB proect is installed however old)
4. click on the activity tab
5. Throws an error for cant read property toUpperCase of Undefined. Seems to be coming from Workspace stack s blow the image
6. Doesnt seem like a blocker and goes away if project is updated to latest. but seems like worth looking if it might be hiding some more issues

![image](https://user-images.githubusercontent.com/46980425/100918700-af3d5f00-348d-11eb-902d-c1eee914f3fd.png)

notificationsAlerts.ts:38 TypeError: Cannot read property 'toUpperCase' of undefined
	at c:\Program Files\Azure Data Studio - RC1\resources\app\extensions\data-workspace\dist\main.js:1:20496
	at Array.forEach (<anonymous>)
	at Object.registerProvider (c:\Program Files\Azure Data Studio - RC1\resources\app\extensions\data-workspace\dist\main.js:1:20371)
	at t.WorkspaceService.handleProjectProviderExtension (c:\Program Files\Azure Data Studio - RC1\resources\app\extensions\data-workspace\dist\main.js:1:19558)
	at t.WorkspaceService.ensureProviderExtensionLoaded (c:\Program Files\Azure Data Studio - RC1\resources\app\extensions\data-workspace\dist\main.js:1:19223)
	at t.WorkspaceService.getProjectProvider (c:\Program Files\Azure Data Studio - RC1\resources\app\extensions\data-workspace\dist\main.js:1:18320)
	at t.WorkspaceTreeDataProvider.getChildren (c:\Program Files\Azure Data Studio - RC1\resources\app\extensions\data-workspace\dist\main.js:1:9346)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)

**Comment by kisantia** [comment]
test one more time before closing

**Comment by udeeshagautam** [comment]
Validated. Closing since this error doesnt happen any more (as expected - this was only for the first release after WS changes).

Not waiting for shiproom since this doesnt need any changes.
