### ISSUE TITLE
Create Book import sys error

### ISSUE THREAD

**Issue by VasuBhog** [microsoft/azuredatastudio#13772]
- Azure Data Studio Version: 1.26.0-insider
Commit: b10b52e4fed689393414aeb18ceb57494fe0dcbf
Date: 2020-12-08T06:45:10.349Z (2 days ago)
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
Python Version: 3.6

Steps to Reproduce:

1. Open the Create Jupyter Book via Notebooks tab.
2. Run all cells
3. Error occurs in cell two (import sys)
 
I included most of the error output and excluded the middle traces.

```
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "<ipython-input-2-4a2654937271>", line 4, in <module>
    version, version_str = getJupyterBookVersion()
  File "<ipython-input-1-1d9929905f3a>", line 14, in getJupyterBookVersion
    version = tuple(int(x) for x in version_str)
  File "<ipython-input-1-1d9929905f3a>", line 14, in <genexpr>
    version = tuple(int(x) for x in version_str)
ValueError: invalid literal for int() with base 10: '/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-4a2654937271>", line 23, in <module>
    raise SystemExit(str(e))
SystemExit: invalid literal for int() with base 10: '/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/ultratb.py", line 1169, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py", line 1490, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-4a2654937271> in <module>
      3 try:
----> 4     version, version_str = getJupyterBookVersion()
      5     if version:

<ipython-input-1-1d9929905f3a> in getJupyterBookVersion()
     13             version_str = tuple(x.split(': ')[1].replace('.', ''))
---> 14             version = tuple(int(x) for x in version_str)
     15     return version, version_str

<ipython-input-1-1d9929905f3a> in <genexpr>(.0)
     13             version_str = tuple(x.split(': ')[1].replace('.', ''))
---> 14             version = tuple(int(x) for x in version_str)
     15     return version, version_str

ValueError: invalid literal for int() with base 10: '/'

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
    [... skipping hidden 1 frame]

<ipython-input-2-4a2654937271> in <module>
     22 except Exception as e:
---> 23     raise SystemExit(str(e))

SystemExit: invalid literal for int() with base 10: '/'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
    [... skipping hidden 1 frame]

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py in showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2036                            'the full traceback.\n']
   2037                     stb.extend(self.InteractiveTB.get_exception_only(etype,
-> 2038                                                                      value))
   2039                 else:
   2040                     try:

...

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/ultratb.py in find_recursion(etype, value, records)
    449     # first frame (from in to out) that looks different.
    450     if not is_recursion_error(etype, value, records):
--> 451         return len(records), 0
    452 
    453     # Select filename, lineno, func_name to track frames with

TypeError: object of type 'NoneType' has no len()
```

**Comment by barbaravaldez** [comment]
Hi @VasuBhog - I wasn't able to repro the issue using python 3.6.6. 
Let's discuss tomorrow to identify what could be causing the issue 😄

**Comment by chlafreniere** [comment]
@VasuBhog  can you still repro this?

**Comment by VasuBhog** [comment]
Just checked the latest insiders on Mac and got "getJupyterBookVersion" is not defined. Looks to be good on Windows, however.  
Will work with @barbaravaldez to see if she can repro.
