### ISSUE TITLE
"Atom One Dark Theme" Extension does not install

### ISSUE THREAD

**Issue by tmichael-ms** [microsoft/azuredatastudio#13847]
- Azure Data Studio Version: 1.25.1

Steps to Reproduce:

1. Try to install "Atom One Dark Theme" from the ADS Extensions repository.
2. Downloaded the vsix file and tried to install it.  Log with error is below.

12/17/2020 3:51:31 PM - Microsoft VSIX Installer
12/17/2020 3:51:31 PM - -------------------------------------------
12/17/2020 3:51:31 PM - Initializing Install...
12/17/2020 3:51:31 PM - Extension Details...
12/17/2020 3:51:31 PM - 	Identifier      : sqlops-theme-onedark
12/17/2020 3:51:31 PM - 	Name            : Atom One Dark
12/17/2020 3:51:31 PM - 	Author          : michael-wolfenden
12/17/2020 3:51:31 PM - 	Version         : 1.0.0
12/17/2020 3:51:31 PM - 	Description     : One Dark Theme based on Atom
12/17/2020 3:51:31 PM - 	Locale          : en-US
12/17/2020 3:51:31 PM - 	MoreInfoURL     : 
12/17/2020 3:51:31 PM - 	InstalledByMSI  : False
12/17/2020 3:51:31 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
12/17/2020 3:51:31 PM - 
12/17/2020 3:51:31 PM - 	Supported Products : 
12/17/2020 3:51:31 PM - 		Microsoft.VisualStudio.Code
12/17/2020 3:51:31 PM - 			Version : 
12/17/2020 3:51:31 PM - 
12/17/2020 3:51:31 PM - 	References      : 
12/17/2020 3:51:31 PM - 
12/17/2020 3:51:31 PM - Searching for applicable products...
12/17/2020 3:51:31 PM - Found installed product - Global Location
12/17/2020 3:51:31 PM - **VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.**
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by tmichael-ms** [comment]
Sorry, user error.  This is the error you get when just trying to open the .vsix file.  Using the proper steps.. Open command palette and selecting Extensions: Install from VSIX... worked.
