### ISSUE TITLE
Getting results from other tabs

### ISSUE THREAD

**Issue by kblok** [microsoft/azuredatastudio#14138]
Issue Type: <b>Bug</b>

When I run a script I'm getting results from scripts in other tabs.
I would love to give you more insights or steps to reproduce it, but it's quite erratic.

Azure Data Studio version: azuredatastudio 1.25.2 (4d4917d328ab7a7526817a0f0ef03237a79aa54d, 2021-01-20T22:47:41.882Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 7, 6|
|Memory (System)|32.00GB (0.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.6.0
import|Mic|1.2.0
profiler|Mic|0.11.0
schema-compare|Mic|1.8.0
sql-database-projects|Mic|0.5.1
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by abist** [comment]
@kblok You just need to copy the errors (if any), you can get rid of any personal data in the logs

**Comment by kblok** [comment]
how about this?

```
log.ts:197   ERR Error: Unable to read file '##REMOVED##')
    at Object.t.createErrorWithActions (errorsWithActions.ts:21) [<root>]
    at e.handleSetInputError (textFileEditor.ts:164) [<root>]
    at e.setInput (textFileEditor.ts:142) [<root>]
log.ts:197   ERR Error: [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/Users/neo/Downloads/saltandpepper'
log.ts:197   ERR [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/Users/neo/Downloads/saltandpepper'
console.ts:137 [Extension Host] Initialized Azure account extension storage.
console.ts:137 [Extension Host] logFile for MicrosoftSqlToolsServiceLayer is /Users/neo/Library/Application Support/azuredatastudio/logs/20210201T130600/exthost1/Microsoft.mssql/sqltools.log
console.ts:137 [Extension Host] This process (ui Extenstion Host) is pid: 58386
console.ts:137 [Extension Host] Old log files deletion report: {}
console.ts:137 [Extension Host] logFile for SqlToolsResourceProviderService is /Users/neo/Library/Application Support/azuredatastudio/logs/20210201T130600/exthost1/Microsoft.mssql/resourceprovider.log
console.ts:137 [Extension Host] This process (ui Extenstion Host) is pid: 58386
console.ts:137 [Extension Host] Old log files deletion report: {}
console.ts:137 [Extension Host] logFile for MicrosoftSqlToolsCredentials is /Users/neo/Library/Application Support/azuredatastudio/logs/20210201T130600/exthost1/Microsoft.mssql/credentialstore.log
console.ts:137 [Extension Host] This process (ui Extenstion Host) is pid: 58386
console.ts:137 [Extension Host] Old log files deletion report: {}
console.ts:137 [Extension Host] Initializing stored accounts []
console.ts:137 [Extension Host] (node:58386) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ console.ts:24
log.ts:197   ERR Error: [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '##REMOVED##'
log.ts:197   ERR [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '##REMOVED##'
log.ts:197   ERR Error: [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/Users/neo/Downloads/saltandpepper'
log.ts:197   ERR [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '/Users/neo/Downloads/saltandpepper'
log.ts:197   ERR Error: [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '##REMOVED##'
log.ts:197   ERR [File Watcher (node.js)] Error: ENOENT: no such file or directory, stat '##REMOVED##'
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Creating new connection file://##REMOVED##
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Adding connection file://##REMOVED##
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Successfully added connection file://##REMOVED##
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Adding connection with DB name file://providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:.|user:sa|group:undefined
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2319   ERR Cannot read property 'map' of undefined: TypeError: Cannot read property 'map' of undefined
    at p._updateDropDownList (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1499:413)
    at Object.render (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1499:87)
    at l.show (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:745:708)
    at a.showContextView (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2308:600)
    at p._showList (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1498:970)
    at HTMLInputElement.<anonymous> (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1496:363)
    at ZoneDelegate.invokeTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:421:31)
    at Zone.runTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:188:47)
    at ZoneTask.invokeTask [as invoke] (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:496:34)
    at invokeTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:1540:14)
    at HTMLInputElement.globalZoneAwareCallback (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:1566:17)
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Creating new connection file://##REMOVED##
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Adding connection file://##REMOVED##
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Successfully added connection file://##REMOVED##
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7657 Line (VALUES (1710, 7...): longer than 20000 characters, tokenization skipped.
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7657 Line (VALUES (1711, 7...): longer than 20000 characters, tokenization skipped.
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7657 Line (VALUES (1712, 7...): longer than 20000 characters, tokenization skipped.
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7657 Line (VALUES (1713, 7...): longer than 20000 characters, tokenization skipped.
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7657 Line (VALUES (1777, 7...): longer than 20000 characters, tokenization skipped.
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7657 Line (VALUES (1778, 7...): longer than 20000 characters, tokenization skipped.
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7657 Line (VALUES (1779, 7...): longer than 20000 characters, tokenization skipped.
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7657 Line (VALUES (1780, 7...): longer than 20000 characters, tokenization skipped.
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Creating new connection untitled:SQLQuery_2
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Adding connection untitled:SQLQuery_2
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Successfully added connection untitled:SQLQuery_2
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Deleting connection untitled:SQLQuery_2
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Creating new connection untitled:SQLQuery_2
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Adding connection untitled:SQLQuery_2
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Successfully added connection untitled:SQLQuery_2
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Deleting connection untitled:SQLQuery_2
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Deleting connection file://##REMOVED##
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Creating new connection file://##REMOVED##
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Adding connection file://##REMOVED##
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Successfully added connection file://##REMOVED##
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:462 [Extension Host] [Error - 1:19:13 PM] Request query/subset failed.
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:462 [Extension Host]   Message: Result set index cannot be less than 0 or greater than the number of result sets (Parameter 'resultSetIndex')  Code: 0 
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2319   ERR An unknown error occurred. Please consult the log for more details.
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2319   ERR Cannot read property 'map' of undefined: TypeError: Cannot read property 'map' of undefined
    at file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:8356:727
    at ZoneDelegate.invoke (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:388:26)
    at Zone.run (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:138:43)
    at /Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:872:34
    at ZoneDelegate.invokeTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:421:31)
    at Zone.runTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:188:47)
    at drainMicroTaskQueue (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:595:35)
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Creating new connection untitled:SQLQuery_2
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Adding connection untitled:SQLQuery_2
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Successfully added connection untitled:SQLQuery_2
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Creating new connection untitled:SQLQuery_3
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Adding connection untitled:SQLQuery_3
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Successfully added connection untitled:SQLQuery_3
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Deleting connection untitled:SQLQuery_3
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Deleting connection untitled:SQLQuery_2
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Creating new connection untitled:SQLQuery_4
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Adding connection untitled:SQLQuery_4
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Successfully added connection untitled:SQLQuery_4
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Adding connection with DB name connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:.|user:sa|group:undefined
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:462 [Extension Host] [Error - 6:17:59 PM] Request query/subset failed.
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:462 [Extension Host]   Message: Result set index cannot be less than 0 or greater than the number of result sets (Parameter 'resultSetIndex')  Code: 0 
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2319   ERR An unknown error occurred. Please consult the log for more details.
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2319   ERR Cannot read property 'map' of undefined: TypeError: Cannot read property 'map' of undefined
    at file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:8356:727
    at ZoneDelegate.invoke (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:388:26)
    at Zone.run (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:138:43)
    at /Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:872:34
    at ZoneDelegate.invokeTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:421:31)
    at Zone.runTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:188:47)
    at drainMicroTaskQueue (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:595:35)
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Creating new connection untitled:SQLQuery_2
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Adding connection untitled:SQLQuery_2
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Successfully added connection untitled:SQLQuery_2
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2319   ERR Cannot read property 'map' of undefined: TypeError: Cannot read property 'map' of undefined
    at p._updateDropDownList (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1499:413)
    at Object.render (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1499:87)
    at l.show (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:745:708)
    at a.showContextView (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2308:600)
    at p._showList (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1498:970)
    at HTMLInputElement.<anonymous> (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1496:363)
    at ZoneDelegate.invokeTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:421:31)
    at Zone.runTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:188:47)
    at ZoneTask.invokeTask [as invoke] (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:496:34)
    at invokeTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:1540:14)
    at HTMLInputElement.globalZoneAwareCallback (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:1566:17)
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2319   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2318  INFO Deleting connection untitled:SQLQuery_2
2/Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2319   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
```

**Comment by kburtram** [comment]
Closing this older issue which hasn't had recent repro reports.  Please let us know if you're still impacted by this issue on the current stable release.  Thanks!
