### ISSUE TITLE
Error showing Restore Database File Browser dialog

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#14379]
- Azure Data Studio Version: 1.26.0

Steps to Reproduce:

1. Connect to Server and open Restore Dialog
2. Switch to restore backup file and click browse for file "..." button

Expected: Remote Browser works without error

Actual: An error message pops up the first time.  Then the dialog doesn't render correct on subsequent launches.  A telemetry error shows in dev console.

![image](https://user-images.githubusercontent.com/599935/108634628-467fd600-742f-11eb-83b2-30fa7bdcdf78.png)

![image](https://user-images.githubusercontent.com/599935/108634640-54cdf200-742f-11eb-9247-bbed376077ed.png)

```
 ERR Cannot read property 'providerName' of undefined: TypeError: Cannot read property 'providerName' of undefined
    at e.addTelemetryForConnectionDisconnected (file:///C:/Users/kburt/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5561:443)
    at file:///C:/Users/kburt/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5564:716
    at ZoneDelegate.invoke (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:388:26)
    at Zone.run (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:138:43)
    at C:\Users\kburt\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:872:34
    at ZoneDelegate.invokeTask (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:421:31)
    at Zone.runTask (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:188:47)
    at drainMicroTaskQueue (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:595:35)
```

**Comment by kburtram** [comment]
FWIW, the error didn't repro after restarting ADS, so it's likely the bug is in the dashboard telemetry call and that is having a side-effect (at least with the rendering issue).  The first error still may be in the restore code, and what "broke" the connection, but I didn't see any exception from that error.

**Comment by kburtram** [comment]
Closing older issue without recent repro reports.
