### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by Simone-86828** [microsoft/azuredatastudio#14382]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Since the upgrade to 1.26.0 I can no longer connect to any server. Downloaded again the 1.25.3 and it works just fine.
Any particular change or is this a bug?

Please the error message I get here below:
Microsoft.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover, SqlAuthenticationMethod authType)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass47_0.<CreateReplaceConnectionContinuation>b__0(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass30_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 314
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 550
ClientConnectionId:00000000-0000-0000-0000-000000000000

Here is the about screen:
Version: 1.26.0
Commit: 995095f696fd9800e7e621d34daa895d57989ccd
Date: 2021-02-19T03:24:52.069Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Azure Data Studio version: azuredatastudio 1.26.0 (995095f696fd9800e7e621d34daa895d57989ccd, 2021-02-19T03:24:52.069Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 6, 6|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.6.0
import|Mic|1.2.0
profiler|Mic|0.11.0
server-report|Mic|0.2.3
whoisactive|Mic|0.1.4

</details>

**Comment by Charles-Gagnon** [comment]
Also - what type of server are you connecting to? SQL On-Prem (remote or localhost)/Azure/etc.

**Comment by Simone-86828** [comment]
Hello,
please find the requested logs attached.
I'm trying to connect to 4 different instances of on-prem SQL sry 2014 std.
Running Azure Data Studio on macOS Catalina (10.15.7), while SQL instances are on 3 different server VMs, all running Windows 2012 R2.
Any other info you need please ask.
Thank you

Best regards

[Console.log](https://github.com/microsoft/azuredatastudio/files/6024535/Console.log)
[20210222T195702.zip](https://github.com/microsoft/azuredatastudio/files/6024536/20210222T195702.zip)

**Comment by kburtram** [comment]
@Simone-86828 we update the SqlClient driver in this build, which always has possibility for regressions/side-effects.  Though we aren't seeing wide-spread connectivity problems related to the upgrade yet this morning.  The error is indicating a network related problem accessing the server.  

Have you ruled out that there may have been an intermittent network issue to these servers at the time you tested the new build (I assume this isn't the problem, but I'm not seeing anything to really go on with this issue yet)?  e.g. if you had time I wonder if trying to upgrade again to see if the problem persists.

**Comment by mas-dse-juremigi** [comment]
@kburtram 
I'm having the same issue. I reported it here:
https://github.com/microsoft/azuredatastudio/issues/14388

**Comment by kburtram** [comment]
@mas-dse-juremigi thanks for confirming!  Let's close the other issue as a duplicate and track the issue here.

**Comment by kburtram** [comment]
@mas-dse-juremigi are you also using a mac client?  can you provide any additional info about the servers you're connecting to?  is there anything interesting in the logs (besides the exception callstack) that could help determine what's happening here.

**Comment by Code-DJ** [comment]
@kburtram I am using mac client. I also get a connectivity error. Using Windows Authentication. It says run kinit but when I run it, it has no impact. Goes back to showing the following error:

```
Connection failed due to Kerberos error.
Help configuring Kerberos is available at https://aka.ms/sqlopskerberos
If you have previously connected you may need to re-run kinit.
```

**Comment by kburtram** [comment]
@Code-DJ it likes a different issue than the other ones.  But could also be related to the driver bump (though we did specifically test windows auth on mac, there were some changes in the driver in this area).  Just to connections are working fine on 1.25.3 and broke with today's update?

**Comment by Code-DJ** [comment]
@kburtram yes, it was working on 1.25.3 and then broke on 1.26. Also, when I compare the SqlException in my note to @Simone-86828 first note, it looks the same.

**Comment by Code-DJ** [comment]
@Charles-Gagnon On-Prem SQL Server 2019.

**Comment by cssuh** [comment]
@Code-DJ are you trying to run kinit through ADS or through Terminal?

**Comment by Code-DJ** [comment]
@cssuh through Terminal on ADS. Just tried it through iTerm2, same issue.

**Comment by cssuh** [comment]
after running kinit, does it give any messages?  Also, after running kinit, if you run klist, do you get a message containing the credentials issued and expire date?

**Comment by mas-dse-juremigi** [comment]
@kburtram  Yes, I am using a Mac. I am using On-Prem SQL Servers. kinit works without issue as I can authenticate with other services.  I have no issue connecting to the same sql servers using python, pyodbc + latest version of Microsoft ODBC drivers (which also authentication using kerberos).  Only Azure Data Studio is having issues.

**Comment by Code-DJ** [comment]
@cssuh 

kinit does not throw any errors. klist shows the following output:

```
Credentials cache: API:983E4737-ED75-4D12-8323-A20D9CAEE53C
        Principal: username@DOMAIN.COM

  Issued                Expires               Principal
Feb 22 16:14:26 2021  Feb 23 02:14:26 2021  krbtgt/DOMAIN.COM@DOMAIN.COM
```

**Comment by kburtram** [comment]
I created a test build that is the same as the 1.26.0 release, except that it contains the SqlClient 2.0.0 driver instead of the upgraded driver.  If anyone experiencing connectivity problems with 1.26.0 could please try one of the below builds to see if that resolves the problem.  This will help isolate the source of the issue.  Thanks!

macOS - https://azuredatastudiobuilds.blob.core.windows.net/test/1.26.0/azuredatastudio-macos-1.26.0-driver.zip
Windows ZIP - https://azuredatastudiobuilds.blob.core.windows.net/test/1.26.0/azuredatastudio-windows-1.26.0-driver.zip
Windows User Setup - https://azuredatastudiobuilds.blob.core.windows.net/test/1.26.0/azuredatastudio-windows-user-1.26.0-driver.exe
Windows System Setup - https://azuredatastudiobuilds.blob.core.windows.net/test/1.26.0/azuredatastudio-windows-system-1.26.0-driver.exe
Linux TAR.GZ - https://azuredatastudiobuilds.blob.core.windows.net/test/1.26.0/azuredatastudio-linux-1.26.0-driver.tar.gz
Linux RPM - https://azuredatastudiobuilds.blob.core.windows.net/test/1.26.0/azuredatastudio-linux-1.26.0-driver.rpm
Linux DEB - https://azuredatastudiobuilds.blob.core.windows.net/test/1.26.0/azuredatastudio-linux-1.26.0-driver.deb

**Comment by Code-DJ** [comment]
@kburtram I have verified the macOS zip file. It works fine.

BTW, on Windows I don't have any issues with 1.26. It connects fine using the Stable build.

**Comment by kburtram** [comment]
@Code-DJ @Simone-86828 thanks for confirming!

**Comment by Code-DJ** [comment]
@kburtram is this https://github.com/dotnet/SqlClient/pull/848 included in the upgraded Client version for ADS?

**Comment by Charles-Gagnon** [comment]
It is - we were using the latest 2.1.1 release which contains that fix. 

https://github.com/dotnet/SqlClient/releases/tag/v2.1.1

**Comment by Charles-Gagnon** [comment]
@Code-DJ @Simone-86828 

The SqlClient team said that this might be because of a known issue - https://github.com/dotnet/SqlClient/issues/868

Can you confirm whether you are attempting to connect to a non-default instance?

**Comment by Code-DJ** [comment]
@Charles-Gagnon I am connecting to a default instance. Here's one of the connections in the settings.json

```
{
    "options": {
        "server": "SERVERNAME",
        "database": "",
        "authenticationType": "Integrated",
        "user": "",
        "password": "",
        "applicationName": "azdata",
        "groupId": "6a44bfa1-a786-4cb9-93bd-e55a09b456c7",
        "databaseDisplayName": ""
    },
    "groupId": "6a44bfa1-a786-4cb9-93bd-e55a09b456c7",
    "providerName": "MSSQL",
    "savePassword": true,
    "id": "e33d6b64-68b7-45db-91ed-dfc98ff7010e"
},
```

I tried 2.1.1 with a .net project and the following connection string and get kerberos error. Don't get the error with 2.0.1

```
data source=SERVERNAME;initial catalog=DATABASENAME;trusted_connection=true
```

**Comment by Charles-Gagnon** [comment]
Would you mind opening an issue in the SqlClient repo with that information? We can track further progress on the issue there.

**Comment by karinazhou** [comment]
Hi @Code-DJ , please feel free to create an issue in [dotnet/sqlclient](https://github.com/dotnet/SqlClient/issues) so we can look further into it.

**Comment by Code-DJ** [comment]
@Charles-Gagnon @karinazhou done https://github.com/dotnet/SqlClient/issues/926

Thanks

**Comment by Code-DJ** [comment]
See https://github.com/dotnet/SqlClient/issues/926#issuecomment-784583820 for the fix. 2.1.1 changed the way it checks for SPN. It now includes the default port number in the name, so you have to include the default port number (1433) when setting the SPN.

**Comment by Charles-Gagnon** [comment]
Thanks @Code-DJ for following up with this!

@Simone-86828 @mas-dse-juremigi Could you see if their suggested fix helps you out as well?

**Comment by mas-dse-juremigi** [comment]
@Charles-Gagnon  I cannot test this as I don't manage our sql servers.

**Comment by Charles-Gagnon** [comment]
Are you using SQL auth or Integrated auth through kerberos?

**Comment by mas-dse-juremigi** [comment]
@Charles-Gagnon  I am using integrated through kerberos

**Comment by Code-DJ** [comment]
Folks, I have reopened https://github.com/dotnet/SqlClient/issues/926

**Comment by Simone-86828** [comment]
Hello everybody,
I'm connecting to named instances. I tried including the port number (with this syntax: server\instance:port) but I got the same error.
Auth is integrated through kerberos for me as well.

**Comment by jparadis2** [comment]
Same issue for me. Also happened when upgrading to 1.25.0 below was the ticket for that one:
https://github.com/microsoft/azuredatastudio/issues/13751

**Comment by karinazhou** [comment]
Hi,

If you are connecting with named instances that have `\` in the server name, this will fail on Linux due to one of the changes we made in Microsoft.Data.SqlClient v2.1.0-preview2. The hot fix for this will be out soon.

If you are using the default instances, that is related to the SPN generation change in the driver. We are currently working on the fix.

Thanks,

**Comment by Charles-Gagnon** [comment]
We'll be releasing a hotfix to roll back the driver change to unblock folks hitting this with ADS.

But for anyone running into this issue it would be helpful if you could go over to https://github.com/dotnet/SqlClient/issues/926 and comment there to try and track down this issue so that we're able to update to the new driver version in the future without breaking everyone again 😄

**Comment by kburtram** [comment]
Update 1.26.1 is available that rolls back the SQL Client driver.  Please let us know if there are still connectivity issues with the latest build.

**Comment by Code-DJ** [comment]
@kburtram @Charles-Gagnon FYI, the issue is resolved in SqlClient https://github.com/dotnet/SqlClient/issues/926

**Comment by kburtram** [comment]
@Code-DJ thanks for the update!  I'm not sure the exact plans for trying the driver update again at the moment.  The last two releases required hotfixing a driver rollback, so we may wait a little to try to avoid pulling in additional regressions next month.  I believe there are some fixes for AlwaysEncrypted Secure Enclaves we're trying to pickup with the driver update.

**Comment by kbardai** [comment]
I know this is closed, but I am a new user of ADS and am getting the same error as @Code-DJ is above...I am on version 1.26.1 on macOS Catalina 10.15.7.

The difference is, I am able to connect to 1 server (the first server I tried, for some reason, no idea why others don't connect, no difference in other servers, slight minor version difference, same AD credentials, work's without issue on windows using SSMS for example), but none others.  After running kinit and then klist inside ADS terminal I see my credentials and expiration date.  

These are on-prem SQL Server instances.

Any assistance would be helpful.

Thanks

```
Credentials cache: API:31ED75AF-9125-4C5A-8B62-AE4CF9EA0D38
        Principal: username@MYDOMAIN.COM

  Issued                Expires               Principal
Mar  1 13:57:35 2021  Mar  1 23:57:28 2021  krbtgt/MYDOMAIN.COM@MYDOMAIN.COM
```

```
Version: 1.26.1
Commit: 796abbdf5fdd341e3528e30a6b777c93e115eb02
Date: 2021-02-24T23:37:01.966Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

`ERR Kerberos connection failure. Message : Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.
ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error -  An unsupported mechanism was requested (unknown mech-code 0 for mech unknown).
   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)
   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)
   at Microsoft.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)
   at Microsoft.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)
   at Microsoft.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength) Message Details : Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.
ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error -  An unsupported mechanism was requested (unknown mech-code 0 for mech unknown).
   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)
   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)
   at Microsoft.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)
   at Microsoft.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)
   at Microsoft.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.SSPIError(String error, String procedure)
   at Microsoft.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
   at Microsoft.Data.SqlClient.TdsParser.SSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
   at Microsoft.Data.SqlClient.TdsParser.TdsLogin(SqlLogin rec, FeatureExtension requestedFeatures, SessionData recoverySessionData, Nullable`1 fedAuthFeatureExtensionData)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.Login(ServerInfo server, TimeoutTimer timeout, String newPassword, SecureString newSecurePassword)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass45_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass30_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 314
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 550
ClientConnectionId:3097f4fb-6034-47b0-a912-d81f9774dd80`
