### ISSUE TITLE
Loses connection and won't reconnect to local SQL Server

### ISSUE THREAD

**Issue by claxdal-gilbaneco** [microsoft/azuredatastudio#15438]
Issue Type: <b>Bug</b>

The same issue has happened the past 3 times I have used Azure Data Studio.  I create a lot of "new query" tabs as I need them by right-clicking the database and choosing "new query".

After about 10-15 iterations of "new query", creating query executing query and closing the tab, I click on the arrow to display information about a table. The arrow goes away and I get the spinning circle. I created a new tab but it wasn't connected and wouldn't allow me to connect.

My other applications, such as SSMS, are still connected and functional, but Azure data studio won't connect. Existing tabs that had been connected won't return results when executed, they just spin.

Azure Data Studio version: azuredatastudio 1.28.0 (13e362762762e5cb76a5c8afd2bc650f48c2d3d8, 2021-04-15T00:24:15.710Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (0.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.3.0
profiler|Mic|0.11.0

</details>

**Comment by claxdal-gilbaneco** [comment]
I forgot to include the renderer1.log as suggested by the tool.

[renderer1.log](https://github.com/microsoft/azuredatastudio/files/6468461/renderer1.log)

**Comment by kburtram** [comment]
This appears to be an relevant error in the log

```
[2021-05-12 14:39:17.509] [renderer1] [error] Cannot read property 'map' of undefined: TypeError: Cannot read property 'map' of undefined
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:8645:930
    at ZoneDelegate.invoke (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:388:26)
    at Zone.run (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:138:43)
    at C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:872:34
    at ZoneDelegate.invokeTask (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:421:31)
    at Zone.runTask (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:188:47)
    at drainMicroTaskQueue (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:595:35)
[2021-05-12 14:39:17.512] [renderer1] [error] Unexpected error occurred while connecting.: Error: Unexpected error occurred while connecting.
    at p.onConnectionComplete (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2495:841) [<root>]
    at e.onConnectionComplete (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5561:528) [<root>]
    at k.$onConnectionComplete (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:6203:956) [<root>]
    at p._doInvokeHandler (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5976:926) [<root>]
    at p._invokeHandler (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5976:618) [<root>]
    at p._receiveRequest (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5975:252) [<root>]
    at p._receiveOneMessage (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5974:6) [<root>]
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5972:136 [<root>]
    at c.fire (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:219:801) [<root>]
    at fire (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:660:601) [<root>]
    at t.PersistentProtocol._receiveMessage (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:665:704) [<root>]
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:662:738 [<root>]
    at c.fire (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:219:801) [<root>]
    at g.acceptChunk (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:658:17) [<root>]
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:657:360 [<root>]
    at Socket.t (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:667:506) [<root>]
    at Socket.emit (events.js:223:5) [<root>]
    at addChunk (_stream_readable.js:309:12) [<root>]
    at readableAddChunk (_stream_readable.js:290:11) [<root>]
    at Socket.Readable.push (_stream_readable.js:224:10) [<root>]
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23) [<root>]
[2021-05-12 14:50:17.735] [renderer1] [error] An unknown error occurred. Please
```

**Comment by cssuh** [comment]
@claxdal-gilbaneco how much time would you estimate has passed since you first connected to the database and when it gives you the spinning circle?

**Comment by caohai** [comment]
Closing this issue as a fix for connection expiration in query editor has been merged and will be in the October release (or you can try it with the latest insiders). Feel free to reopen or create new issue if it's not fixed.

For tracking the AAD token expiration issue with server/table node in SERVER view (object explorer view), please refer to #17087  
For tracking other AAD token expiration related issues please refer to this mega issue #17047
