### ISSUE TITLE
Remote Jupyter Book dialog "Add" button is disabled 

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#15524]
![bug](https://user-images.githubusercontent.com/34872381/118899851-8afefe80-b8c4-11eb-99f7-0d7e3a0337f7.png)

Cannot click on Add button after filling the dropdowns.
- Azure Data Studio Version:
Version: 1.29.0 (user setup)
Commit: 0f5cfdc2c8c2433028842e16dc5ac1a65da24292
Date: 2021-05-15T01:12:11.112Z
VS Code: 1.53.0
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:
1.Open Jupyter Remote Book
2. Fill dropdowns 
3. Add button is disabled

Console error:
workbench.desktop.main.js:2768 [[object Object]]Cannot read property 'filter' of undefined
$onExtensionRuntimeError @ workbench.desktop.main.js:2768
_doInvokeHandler @ workbench.desktop.main.js:2288
_invokeHandler @ workbench.desktop.main.js:2288
_receiveRequest @ workbench.desktop.main.js:2288
_receiveOneMessage @ workbench.desktop.main.js:2288
(anonymous) @ workbench.desktop.main.js:2288
fire @ workbench.desktop.main.js:85
fire @ workbench.desktop.main.js:156
_receiveMessage @ workbench.desktop.main.js:156
(anonymous) @ workbench.desktop.main.js:156
fire @ workbench.desktop.main.js:85
acceptChunk @ workbench.desktop.main.js:156
(anonymous) @ workbench.desktop.main.js:156
I @ workbench.desktop.main.js:3584
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
workbench.desktop.main.js:2768 TypeError: Cannot read property 'filter' of undefined
at t.RemoteBookDialog.fillLanguageDropdown (c:\Users\jukoesma\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\notebook\dist\extension.js:243:214890)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async c:\Users\jukoesma\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\notebook\dist\extension.js:243:211494

**Comment by barbaravaldez** [comment]
@MsSQLGirl, I'm opening this issue to see if more people run into this.

@MaddyDev and I were not able to repro the disabled "Add" button, but I do see the console error when opening the dialog for the first time.

**Comment by MsSQLGirl** [comment]
I still can repro this issue in my environment:
![image](https://user-images.githubusercontent.com/6405919/121094543-ab272c80-c7a3-11eb-8df4-e970992e97af.png)
Version: 1.30.0-insider (user setup)
Commit: d04451985c5fcab79a2c51ef5c5d90a703872432
Date: 2021-06-07T05:38:06.575Z
VS Code: 1.53.0
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by chlafreniere** [comment]
Moving to backlog since it's no longer repro'ing. Will investigate and likely close soon.

**Comment by chlafreniere** [comment]
Since no longer repro'ing, closing now. Please reopen if this reoccurs.

**Comment by lucyzhang929** [comment]
I am able to repro this issue on Windows ADS Stable and Insiders. There are no errors in my console logs.
