### ISSUE TITLE
Cannot connect to mssql server

### ISSUE THREAD

**Issue by prd0000** [microsoft/azuredatastudio#15706]
Hi,

I have been trying to connect to my local server, but I got this error., I don't understand how SSL got here at the first place, because I don't use SSL at all. It's just a local server, on my VBox. 

I have set all possible "encryption data" to disabled at advanced option, but it still use SSL. Is there any way to turn it off completely?

```
Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 31 - Encryption(ssl/tls) handshake failed)
 ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost)
   at Microsoft.Data.SqlClient.SNI.SNITCPHandle.EnableSsl(UInt32 options)
   at Microsoft.Data.SqlClient.SNI.SNIProxy.EnableSsl(SNIHandle handle, UInt32 options)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.ConsumePreLoginHandshake(Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean& marsCapable, Boolean& fedAuthRequired)
   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover, SqlAuthenticationMethod authType)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass47_0.<CreateReplaceConnectionContinuation>b__0(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass30_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 314
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 555
ClientConnectionId:fb0aed3b-e1e2-4c02-8b77-416d94cd5f25

```

**Comment by Charles-Gagnon** [comment]
Are you able to connect to this server using some other tool such as SSMS? 

And can you verify you have the `Security` -> `Encrypt` setting either empty or set to false in the advanced settings?

What version of the engine are you connecting to?

**Comment by prd0000** [comment]
> Are you able to connect to this server using some other tool such as SSMS?
> 
> And can you verify you have the `Security` -> `Encrypt` setting either empty or set to false in the advanced settings?
> 
> What version of the engine are you connecting to?

Yes.. I am working with DBeaver now just fine. I also work from SSMS on my Windows VM just fine. 

![image](https://user-images.githubusercontent.com/4971305/122157363-e822ab80-ce94-11eb-8f21-a01d1a4bd800.png)
![image](https://user-images.githubusercontent.com/4971305/122158215-70ee1700-ce96-11eb-830e-bd4d13ce6b05.png)

Using DBeaver
![image](https://user-images.githubusercontent.com/4971305/122158490-f70a5d80-ce96-11eb-9eba-3fd3d513d54b.png)


SSMS and version
![image](https://user-images.githubusercontent.com/4971305/122158701-49e41500-ce97-11eb-8599-7a6cab93d3ad.png)

**Comment by kburtram** [comment]
@prd0000 have you tried to set the "Trust Server Certificate" setting to "true" in the Advanced Options dialog?

**Comment by prd0000** [comment]
> @prd0000 have you tried to set the "Trust Server Certificate" setting to "true" in the Advanced Options dialog?

What's that has anything to do with no security? I don't use Certificate at all. 
But here is the result. It didn't change.


![image](https://user-images.githubusercontent.com/4971305/122526938-0cbd8580-d045-11eb-85ab-44609610f48f.png)
![image](https://user-images.githubusercontent.com/4971305/122526994-1d6dfb80-d045-11eb-90bb-8d20050e2e41.png)

**Comment by cheenamalhotra** [comment]
Hi @prd0000 

This looks like an issue with resolving common TLS protocol. SSL/TLS are often used interchangeably, and as your error occurs during Pre-Login Handshake phase, your Linux environment's OpenSSL configuration is not negotiable with target SQL Server.

Some tips to help resolve any possible issues:
1. Ensure TLS 1.2 is supported and enabled on target SQL Server as Linux OSes are have been disabling TLS 1.1 and TLS 1.0 by default.
2. Review default cipher suites on Linux and follow [recommended action](https://learn.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux#recommended-action), if not already.
3. If TLS 1.2 cannot be enabled on server side, you can try to set this in OpenSSL as a workaround:
    ```
    MinProtocol = TLSv1
    CipherString = DEFAULT@SECLEVEL=1
    ```

**Comment by cheenamalhotra** [comment]
Closing due to inactivity
