### ISSUE TITLE
"Failed to create Object Explorer session" when expanding Azure nodes

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#16643]
Seeing this on dev, insiders & RC1 

1. Try to expand server node for Azure connection
2. Get this error in the console and no nodes appear in OE

```
workbench.desktop.main.js:892   ERR Failed to create Object Explorer session
```

And seeing this in the STS logs : 

```
21-08-09 14:32:41.2799221 pid:19308 tid:10 sqltools Error: 0 : Microsoft.SqlServer.Management.Smo.UnknownPropertyException: Processors: unknown property.
   at Microsoft.SqlServer.Management.Smo.SqlPropertyMetadataProvider.PropertyNameToIDLookupWithException(String propertyName, PropertyAccessPurpose pap)
   at Microsoft.SqlServer.Management.Smo.PropertyCollection.LookupID(String propertyName, PropertyAccessPurpose pap)
   at Microsoft.SqlServer.Management.Smo.PropertyCollection.GetValueWithNullReplacement(String propertyName, Boolean throwOnNullValue, Boolean useDefaultOnMissingValue)
   at Microsoft.SqlServer.Management.Smo.PropertyCollection.GetValueWithNullReplacement(String propertyName)
   at Microsoft.SqlServer.Management.Smo.Server.get_Processors()
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableConnectionHelper.GetServerSystemInfo(IDbConnection connection) in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableConnectionHelper.cs:line 774
```

**Comment by Charles-Gagnon** [comment]
@aasimkhan30 It looks like this PR broke this. Could you investigate? 

https://github.com/microsoft/sqltoolsservice/pull/1220
