### ISSUE TITLE
issue with clicking on empty dropdown component

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#1694]
ERR Cannot read property 'element' of undefined: TypeError: Cannot read property 'element' of undefined
    at ListView.element (file:///E:/git/sqlopsstudio/out/vs/base/browser/ui/list/listView.js:161:37)
    at file:///E:/git/sqlopsstudio/out/vs/base/browser/ui/list/listWidget.js:1057:95
    at Array.map (native)
    at List.toListEvent (file:///E:/git/sqlopsstudio/out/vs/base/browser/ui/list/listWidget.js:1057:58)
    at file:///E:/git/sqlopsstudio/out/vs/base/browser/ui/list/listWidget.js:724:120
    at file:///E:/git/sqlopsstudio/out/vs/base/common/event.js:327:72
    at file:///E:/git/sqlopsstudio/out/vs/base/common/event.js:309:34
    at Emitter.fire (file:///E:/git/sqlopsstudio/out/vs/base/common/event.js:103:38)
    at FocusTrait.Trait.set (file:///E:/git/sqlopsstudio/out/vs/base/browser/ui/list/listWidget.js:144:28)
    at List.setFocus (file:///E:/git/sqlopsstudio/out/vs/base/browser/ui/list/listWidget.js:896:24)
    at SelectBoxList.layoutSelectDropDown (file:///E:/git/sqlopsstudio/out/vs/base/browser/ui/selectBox/selectBoxCustom.js:329:33)
    at SelectBoxList.renderSelectDropDown (file:///E:/git/sqlopsstudio/out/vs/base/browser/ui/selectBox/selectBoxCustom.js:291:18)
    at Object.render (file:///E:/git/sqlopsstudio/out/vs/base/browser/ui/selectBox/selectBoxCustom.js:269:61)
    at ContextView.show (file:///E:/git/sqlopsstudio/out/vs/base/browser/ui/contextview/contextview.js:94:46)
    at ContextViewService.showContextView (file:///E:/git/sqlopsstudio/out/vs/platform/contextview/browser/contextViewService.js:32:30)
    at SelectBoxList.showSelectDropDown (file:///E:/git/sqlopsstudio/out/vs/base/browser/ui/selectBox/selectBoxCustom.js:267:38)
    at HTMLSelectElement.<anonymous> (file:///E:/git/sqlopsstudio/out/vs/base/browser/ui/selectBox/selectBoxCustom.js:104:27)

**Comment by llali** [comment]
@alanrenmsft  this is is in the list box itself and not in the model view component. I can fix it in the base class but there are too many places that assumes drops down always has at least one item. what is your scenario? do you really need to have a drop down with no item in it?

**Comment by kburtram** [comment]
Closing older issues that aren't tied to concrete customer scenario.  Please log a bug if this API behavior is impacting a customer-facing use case.
