### ISSUE TITLE
Latest/recent ADS releases hang/unable to interact with gui on RHEL7.x

### ISSUE THREAD

**Issue by joshts0** [microsoft/azuredatastudio#16954]
- Azure Data Studio Version: 1.32.0 
- OS Version: RHEL 7.4 & 7.9

Steps to Reproduce:

1. Install ADS 1.32.0 on RHEL 7.4 (or any 7.x)
2. Run ADS - the gui will load, but you will be unable to click on or interface with anything.

From here: https://docs.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver15#supported-operating-systems

We state that ADS is supported on RHEL7.3 and 7.4, but we do mention that Redhat no longer supports these versions. "Versions 7.3 and 7.4 of RHEL are no longer supported by Red Hat. RHEL 7.3 support ended November 30, 2018, and RHEL 7.4 ended August 31, 2019."

I tried an old ADS version 1.17.1, which _does_ work, so I think somewhere along the way, we compiled it against a newer version of GLIBC that isn't available on RHEL7.

This is the output from running ADS... the GUI will load and is visible, but you are unable to click on or interface with anything, and unable to use the application at all and have to force kill it.

Note the "Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found "

This same error does not appear on an old version, 1.17.1 (I just picked a random old version to try, not sure specifically when/where this changed), and 1.17.1 _does_ work on RHEL7.

[me@rhel7azds ~]$ /usr/share/azuredatastudio/azuredatastudio --no-sandbox
Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/share/azuredatastudio/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at v (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:698)
    at bindings (/usr/share/azuredatastudio/resources/app/node_modules.asar/spdlog/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/share/azuredatastudio/resources/app/node_modules.asar/spdlog/index.js:3:35)
    at Module.u._compile (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:1315)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:101)
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:1722)
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10295)
    at l (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10314)
    at Object.errorback (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10435)
    at r.triggerErrorback (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10659)
    at /usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10365
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:1739)
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10295)
    at l (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10314)
    at r._loadModule (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10444)
    at r._resolve (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:6:452)
    at r.defineModule (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:6145)
    at r._relativeRequire (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:6831)
    at n (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:9420)
    at L.b (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:4532)
    at new Promise (<anonymous>)
    at L (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:4512)
    at r._createSpdLogLogger (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:5445)
    at new r (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:5261)
    at /usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:61:2017
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Q.startup (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:61:1827) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}
[createInstance] First service dependency of h at position 2 conflicts with 0 static arguments
[main 2021-08-31T21:16:02.271Z] update#setState idle
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/share/azuredatastudio/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at v (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:698)
    at bindings (/usr/share/azuredatastudio/resources/app/node_modules.asar/spdlog/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/share/azuredatastudio/resources/app/node_modules.asar/spdlog/index.js:3:35)
    at Module.u._compile (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:1315)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:101)
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:1722)
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10295)
    at l (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10314)
    at Object.errorback (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10435)
    at r.triggerErrorback (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10659)
    at /usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10365
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:1739)
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10295)
    at l (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10314)
    at r._loadModule (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10444)
    at r._resolve (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:6:452)
    at r.defineModule (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:6145)
    at r._relativeRequire (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:6831)
    at n (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:9420)
    at L.b (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:4532)
    at new Promise (<anonymous>)
    at L (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:4512)
    at r._createSpdLogLogger (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:5445)
    at new r (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:5261)
    at /usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:61:2017
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Q.startup (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:61:1827) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}

Does this issue occur when all extensions are disabled?: Yes

**Comment by Charles-Gagnon** [comment]
The error there looks very similar to https://github.com/microsoft/azuredatastudio/issues/3741 - @kburtram would you have someone on your team who could take a look at this to make sure we didn't regress anything there? I'm not sure where the fix for the previous issue was made so if you have context on that it might help see if there were any changes on the build machines again.

**Comment by Charles-Gagnon** [comment]
@joshts0 Have you tried 1.31.0 to see if this was an issue specifically with the last release (1.32.0)?

**Comment by joshts0** [comment]
@Charles-Gagnon ah yes thanks, it does look like maybe the same thing happened as with [#3741](https://github.com/microsoft/azuredatastudio/issues/3741).

So I did try 1.31.0, which also doesn't work... I just did some more testing though and I think I have some additional helpful information:


Version 1.28.0 - I can interact with the GUI and everything seemingly works (I didn't actually test _doing things_, but as far as interacting with the application, it seems to work). I think this is where things started to change on how/what is being built.. note there is no glibc errors... as we continue down the versions below, we start getting 1 message about glibc, and once we get to 1.31.1, we get more glibc errors, and that is when it stops working. See below.

```
[jsomers@jts-lin-rhel7azds tmp]$ /usr/share/azuredatastudio/azuredatastudio --no-sandbox
Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.
[main 2021-08-31T23:41:54.958Z] update#setState idle
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
Xlib:  extension "MIT-SHM" missing on display "localhost:10.0".
[main 2021-08-31T23:42:39.408Z] update#setState checking for updates
[main 2021-08-31T23:42:39.444Z] update#setState available for download

```

Version 1.29.0 - I can seemingly click around and interact with the GUI, but note the 1 single message for GLIBCXX_3.4.20
```
Installed:
  azuredatastudio.x86_64 0:1.29.0-1621041709.el7

Complete!
[jsomers@jts-lin-rhel7azds tmp]$ /usr/share/azuredatastudio/azuredatastudio --no-sandbox
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.

Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/share/azuredatastudio/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at v (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:12324)
    at bindings (/usr/share/azuredatastudio/resources/app/node_modules.asar/spdlog/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/share/azuredatastudio/resources/app/node_modules.asar/spdlog/index.js:3:35)
    at Module.u._compile (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:12878)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at t (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:101)
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:13285)
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10295)
    at c (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:10314)
    at Object.errorback (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:10435)
    at r.triggerErrorback (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10659)
    at /usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10365
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:13302)
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10295)
    at c (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:10314)
    at r._loadModule (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:10444)
    at r._resolve (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:452)
    at r.defineModule (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:6145)
    at r._relativeRequire (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:6831)
    at n (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:9420)
    at m (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:30:42384)
    at new Promise (<anonymous>)
    at y (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:30:42364)
    at p._createSpdLogLogger (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:30:43339)
    at new p (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:30:43144)
    at /usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:59:1655
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async z.startup (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:59:1434) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}
[main 2021-08-31T23:17:29.001Z] update#setState idle
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
(node:28727) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
(node:28727) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
[main 2021-08-31T23:18:00.351Z] update#setState checking for updates
[main 2021-08-31T23:18:00.759Z] update#setState available for download

```

Version 1.30.0 - same as above 1.29.0. One entry for GLIBC 3.4.20. Can seemingly click around and interact with GUI.


Version 1.31.1 - note the multiple outputs of "Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found " -- I think this is where it gets completely broken, and I can't interact with the GUI at all. I can SEE it, but can't click on anything.

```
Installed:
  azuredatastudio.x86_64 0:1.31.1-1627507142.el8

Complete!
[jsomers@jts-lin-rhel7azds tmp]$ /usr/share/azuredatastudio/azuredatastudio --no-sandbox
Warning: 'sandbox' is not in the list of known options, but still passed to Electron/Chromium.
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/share/azuredatastudio/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at v (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:698)
    at bindings (/usr/share/azuredatastudio/resources/app/node_modules.asar/spdlog/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/share/azuredatastudio/resources/app/node_modules.asar/spdlog/index.js:3:35)
    at Module.u._compile (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:1315)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:101)
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:1722)
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10295)
    at l (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10314)
    at Object.errorback (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10435)
    at r.triggerErrorback (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10659)
    at /usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10365
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:1739)
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10295)
    at l (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10314)
    at r._loadModule (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10444)
    at r._resolve (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:6:452)
    at r.defineModule (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:6145)
    at r._relativeRequire (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:6831)
    at n (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:9420)
    at L.b (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:4532)
    at new Promise (<anonymous>)
    at L (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:4512)
    at r._createSpdLogLogger (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:5445)
    at new r (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:5261)
    at /usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:61:2017
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Q.startup (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:61:1827) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}
[createInstance] First service dependency of h at position 2 conflicts with 0 static arguments
[main 2021-08-31T23:31:27.799Z] update#setState idle

libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/share/azuredatastudio/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at v (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:698)
    at bindings (/usr/share/azuredatastudio/resources/app/node_modules.asar/spdlog/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/share/azuredatastudio/resources/app/node_modules.asar/spdlog/index.js:3:35)
    at Module.u._compile (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:1315)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:101)
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:1722)
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10295)
    at l (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10314)
    at Object.errorback (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10435)
    at r.triggerErrorback (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10659)
    at /usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10365
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:1739)
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10295)
    at l (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10314)
    at r._loadModule (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10444)
    at r._resolve (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:6:452)
    at r.defineModule (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:6145)
    at r._relativeRequire (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:6831)
    at n (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:9420)
    at L.b (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:4532)
    at new Promise (<anonymous>)
    at L (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:4512)
    at r._createSpdLogLogger (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:5445)
    at new r (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:5261)
    at /usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:61:2017
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Q.startup (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:61:1827) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/share/azuredatastudio/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at v (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:698)
    at bindings (/usr/share/azuredatastudio/resources/app/node_modules.asar/spdlog/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/share/azuredatastudio/resources/app/node_modules.asar/spdlog/index.js:3:35)
    at Module.u._compile (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:1315)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:101)
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:1722)
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10295)
    at l (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10314)
    at Object.errorback (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10435)
    at r.triggerErrorback (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10659)
    at /usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10365
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:1739)
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10295)
    at l (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10314)
    at r._loadModule (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10444)
    at r._resolve (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:6:452)
    at r.defineModule (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:6145)
    at r._relativeRequire (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:6831)
    at n (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:9420)
    at L.b (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:4532)
    at new Promise (<anonymous>)
    at L (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:4512)
    at r._createSpdLogLogger (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:5445)
    at new r (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:5261)
    at /usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:61:2017
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Q.startup (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:61:1827) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}

```

**Comment by rkhjjs** [comment]
I too have exactly this problem.  CI cannot use any version newer than 1.28.0-1618447983.el7.

```
===========================================================================================
 Package           Arch     Version                  Repository                       Size
===========================================================================================
Downgrading:
 azuredatastudio   x86_64   1.28.0-1618447983.el7    /azuredatastudio-linux-1.28.0   439 M
```

**Comment by kburtram** [comment]
Closing this older issue which doesn't have recent repros.  Please let us know if you're still seeing problems using the latest stable build on RHEL 7.  Thanks!
