### ISSUE TITLE
Generate proj from swagger spec succeeds but error occurs 

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#17242]
Using https://editor.swagger.io/

```
ERR Cannot read property 'replace' of undefined: TypeError: Cannot read property 'replace' of undefined
    at s (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Microsoft…S%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:84:38364)
    at P.<anonymous> (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Microsoft…%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1597:3888)
    at l.fire (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Microsoft…VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:69:1732)
    at _.runner (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Microsoft…S%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:678:9897)
    at _.doRun (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Microsoft…S%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:77:18330)
    at _.onTimeout (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Microsoft…S%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:77:18296)
```

**Comment by Charles-Gagnon** [comment]
Doesn't repro for me either so I'll close this out.
