### ISSUE TITLE
import wizard error on "preview transformation" at FlatFileImportService.cs:line 246

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#17534]
Version: 1.33.0
Commit: 6783aa6967e8c6d086b6f04e5fbf527659981389
Date: 2021-10-26T17:27:01.229Z
VS Code: 1.58.0
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 21.1.0

Import extension v1.5.0

Steps to Reproduce:

[Book1.csv](https://github.com/microsoft/azuredatastudio/files/7438404/Book1.csv)

1. select first column (int) for derived column (csv attached)
2. enter a digit in the first row
3. click preview transformation
4. enter a digit in the second row to further refine the transformation
5. click preview transformation

> Error: System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.SqlServer.Prose.Import.BcpProcess.<LearnTransformation>b__85_0(String[] row)
>    at System.Linq.Enumerable.SelectListIterator`2.ToList()
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at Microsoft.SqlTools.FlatFileImport.Services.FlatFileImportService.HandleLearnTransformationRequest(LearnTransformationParams transGenParam, RequestContext`1 context) in D:\a\1\s\services\src\Microsoft.SqlTools.FlatFileImport.Services\FlatFileImportService.cs:line 246

![2021-10-28_19-15-10 (1)](https://user-images.githubusercontent.com/12227241/139362808-20228945-09a2-436a-9123-d669bb049eb3.gif)

**Comment by kburtram** [comment]
Moving to April, since (1) this is not an in-cycle regression (2) this is preview feature in Feb (3) no time before end of ask-mode due to other approved bugs.
