### ISSUE TITLE
Unable to create a project from AZURE SQL Database 

### ISSUE THREAD

**Issue by rangitoto72** [microsoft/azuredatastudio#17540]
Version: 1.33.0
Commit: 6783aa6967e8c6d086b6f04e5fbf527659981389
Date: 2021-10-26T17:27:01.229Z (5 days ago)
VS Code: 1.58.0
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 21.1.0

Steps to Reproduce:

1. Connect to Server ( MSSQL )
2. R/C Db select -> Create Project From Database
3. Select Server
4. Seelct Database
5. Select Location
6. Folder structure, doesnt mater what you select, same error on all.
7. Error in Azure Data studio: Extract Project files failed

Note: it creates the Folder, inside the folder is a file called DatabaseProjectXXXXXXX.sqlproj
That is all that is written to disk

In developer console.

 ERR The ng module u has already been destroyed.: Error: The ng module u has already been destroyed.
    at uInjector.NgModuleInjector.destroy (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/@angular/core/bundles/core.umd.js:3615:19) [<root>]
    at file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3227:6796 [<root>]
    at Array.forEach (<anonymous>) [<root>]
    at m.dispose (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3227:6783) [<root>]
    at dispose (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3227:13980) [<root>]
    at d.cancel (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3227:13832) [<root>]
    at R.closeDialog (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3227:22606) [<root>]
    at m.$closeDialog (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3227:24691) [<root>]
    at a._doInvokeHandler (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2589:11898) [<root>]
    at a._invokeHandler (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2589:11590) [<root>]
    at a._receiveRequest (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2589:10252) [<root>]
    at a._receiveOneMessage (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2589:9055) [<root>]
    at file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2589:7159 [<root>]
    at i.fire (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:129:1835) [<root>]
    at d.fire (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:176:16333) [<root>]
    at s._receiveMessage (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:176:21591) [<root>]
    at file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:176:18477 [<root>]
    at i.fire (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:129:1835) [<root>]
    at n.acceptChunk (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:176:13694) [<root>]
    at file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:176:13042 [<root>]
    at Socket.D (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3861:136280) [<root>]
    at Socket.emit (events.js:315:20) [<root>]
    at addChunk (internal/streams/readable.js:309:12) [<root>]
    at readableAddChunk (internal/streams/readable.js:284:9) [<root>]
    at Socket.Readable.push (internal/streams/readable.js:223:10) [<root>]
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) [<root>]

**Comment by rangitoto72** [comment]
Added logs

[Archive.zip](https://github.com/microsoft/azuredatastudio/files/7449451/Archive.zip)

**Comment by kisantia** [comment]
This looks like it might be a problem with extracting the schema. Can you try running [sqlpackage](https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver15) extract command and sharing the diagnostic file? Sql projects in ADS and sqlpackage are both wrappers around DacFx (the backend for database deployments), but there are more detailed logs when running sqlpackage so hopefully those logs can help with troubleshooting this issue.

example extract command:
`sqlpackage.exe /Action:Extract /ssn:[server] /sdn:[database] /tf:"C:\Temp\database.dacpac" /df:sqlpackage-extract.log
`

**Comment by rangitoto72** [comment]
When I run the command:

C:\Program Files\Microsoft SQL Server\150\DAC\bin>sqlpackage.exe /Action:Extract /ssn:xxxxx /sdn:xxxxxx /su:xxxxx /sp:xxxxxx /tf:"C:\Temp\database.dacpac" /df:sqlpackage-extract.log
Connecting to database 'xxxxx' on server 'xxxxxx'.
Extracting schema
Extracting schema from database
Time elapsed 0:00:20.03
*** An unexpected failure occurred: Object reference not set to an instance of an object..

it runs for 20 seconds.
No output to c:\temp (Folder is empty)

**Comment by kisantia** [comment]
@rangitoto72 can you please share the log file? There should be a stack trace in there that I can use to find where there error is coming from.

**Comment by kisantia** [comment]
closing because more info needed. Feel free to reopen if the log file can be provided
