### ISSUE TITLE
not able to connect to azure

### ISSUE THREAD

**Issue by alexpalex9** [microsoft/azuredatastudio#17803]
Issue Type: <b>Feature Request</b>

Logging to azure account with Azure Data Studio runs forever whereas it works perfectly for "Azure visual code"

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:45:15.872Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by kburtram** [comment]
@alexpalex9 are you still experiencing this issue on 1.35.0 release?  If so, are there any errors in the Help->Developer Console Log that are related to Azure?  Thanks!

**Comment by alexpalex9** [comment]
thank for the reply

I have updated my data studio but no improvement, here is the error log :
ERR Cannot read property 'accountType' of undefined: TypeError: Cannot read property 'accountType' of undefined
    at sa.renderElement (vscode-file://vscode-app/c:/Users/r392901/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:843:47248)
    at sa.renderElement (vscode-file://vscode-app/c:/Users/r392901/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:843:47902)
    at q.renderElement (vscode-file://vscode-app/c:/Users/r392901/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:255:1781)
    at y.insertItemInDOM (vscode-file://vscode-app/c:/Users/r392901/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:237:18408)
    at y._splice (vscode-file://vscode-app/c:/Users/r392901/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:237:14309)
    at y.splice (vscode-file://vscode-app/c:/Users/r392901/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:237:12596)
    at vscode-file://vscode-app/c:/Users/r392901/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:68:13347
    at Array.forEach (<anonymous>)
    at t.splice (vscode-file://vscode-app/c:/Users/r392901/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:68:13334)
    at vscode-file://vscode-app/c:/Users/r392901/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:255:8577
    at f.bufferEvents (vscode-file://vscode-app/c:/Users/r392901/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:129:4433)
    at Z.splice (vscode-file://vscode-app/c:/Users/r392901/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:255:8544)
    at F.updateAccounts (vscode-file://vscode-app/c:/Users/r392901/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3588:84135)
    at V.updateProviderAccounts (vscode-file://vscode-app/c:/Users/r392901/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3588:89579)
    at vscode-file://vscode-app/c:/Users/r392901/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3588:85405
    at n.fire (vscode-file://vscode-app/c:/Users/r392901/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:129:1712)
    at vscode-file://vscode-app/c:/Users/r392901/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:841:36243
    at n.fire (vscode-file://vscode-app/c:/Users/r392901/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:129:1712)
    at qc.fireAccountListUpdate (vscode-file://vscode-app/c:/Users/r392901/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3588:98122)
    at vscode-file://vscode-app/c:/Users/r392901/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3588:94235
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Gr.run (vscode-file://vscode-app/c:/Users/r392901/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:843:17205)

________________________________

**Comment by cssuh** [comment]
@alexpalex9 can you please follow these instructions so we can help identify the issue you're running into here?
We need more info to debug your Azure Active Directory issue. If you could attach your logs to the issue (ensure no private data is in them), it would help us fix the issue much faster.
- In the settings menu, find the setting titled `Azure: Logging Level` and select the `Verbose` option
- Run the process that produces your error
- Open command palette (Click **View** -> **Command Palette**)
- Run the command: **`Developer: Open Logs Folder`**
- Follow this path to find the Azure Accounts log file: `[default log folder]/exthost1/output_logging_[earliest timestamp]/#-Azure Acounts.log`
- Please attach the Azure-Accounts.log file to the issue.

**Comment by kburtram** [comment]
@cssuh are we able to make progress investigating this issue based on the provided call stack?  or do you need the additional details requested in the `Azure Acounts.log` file?

**Comment by cssuh** [comment]
I need more details from the `Azure Accounts.log` file to do some investigation

**Comment by alexpalex9** [comment]
`Azure Accounts.log` :

[Error]: Login failed - []
[Error]: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client - []
[Error]: Login failed - []
[Error]: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client - []

**Comment by alexpalex9** [comment]
I would guess that the proxy is the issue. (please note that proxy settings works fine with Azure Storage Explorer).

**Comment by kburtram** [comment]
@cssuh are we able to repro or diagnosis this issue (e.g confirm it's related to proxy settings, etc.)?  do you expect the upgrade to MSAL library to help address this bug?

**Comment by cheenamalhotra** [comment]
Since this is related to Proxy setup and we have multiple issues like these, I'll close this one and progress can be tracked with #17356
