### ISSUE TITLE
VS Notebook contributions error on startup

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#17999]
This doesn't seem to be a blocking issue for us, but we should either disable the features completely or fix them so they don't throw these errors 

```
contributions.ts:123 Unable to instantiate workbench contribution NotebookBreakpoints. Error: [createInstance] NotebookBreakpoints depends on UNKNOWN service debugService.
    at InstantiationService._createInstance (vscode-file://vscode-app/c:/src/AzureDataStudio-2/out/vs/platform/instantiation/common/instantiationService.js:72:27) [<root>]
    at InstantiationService.createInstance (vscode-file://vscode-app/c:/src/AzureDataStudio-2/out/vs/platform/instantiation/common/instantiationService.js:60:31) [<root>]
    at WorkbenchContributionsRegistry.safeCreateInstance (vscode-file://vscode-app/c:/src/AzureDataStudio-2/out/vs/workbench/common/contributions.js:82:38) [<root>]
    at WorkbenchContributionsRegistry.doInstantiateByPhase (vscode-file://vscode-app/c:/src/AzureDataStudio-2/out/vs/workbench/common/contributions.js:56:30) [<root>]
    at vscode-file://vscode-app/c:/src/AzureDataStudio-2/out/vs/workbench/common/contributions.js:46:62 [<root>]
    at C:\src\AzureDataStudio-2\node_modules\zone.js\dist\zone.js:872:34 [<root>]
    at drainMicroTaskQueue (C:\src\AzureDataStudio-2\node_modules\zone.js\dist\zone.js:595:35) [<root>]
safeCreateInstance @ contributions.ts:123
contributions.ts:123 Unable to instantiate workbench contribution NotebookCellPausing. Error: [createInstance] NotebookCellPausing depends on UNKNOWN service debugService.
    at InstantiationService._createInstance (vscode-file://vscode-app/c:/src/AzureDataStudio-2/out/vs/platform/instantiation/common/instantiationService.js:72:27) [<root>]
    at InstantiationService.createInstance (vscode-file://vscode-app/c:/src/AzureDataStudio-2/out/vs/platform/instantiation/common/instantiationService.js:60:31) [<root>]
    at WorkbenchContributionsRegistry.safeCreateInstance (vscode-file://vscode-app/c:/src/AzureDataStudio-2/out/vs/workbench/common/contributions.js:82:38) [<root>]
    at WorkbenchContributionsRegistry.doInstantiateByPhase (vscode-file://vscode-app/c:/src/AzureDataStudio-2/out/vs/workbench/common/contributions.js:56:30) [<root>]
    at vscode-file://vscode-app/c:/src/AzureDataStudio-2/out/vs/workbench/common/contributions.js:46:62 [<root>]
    at C:\src\AzureDataStudio-2\node_modules\zone.js\dist\zone.js:872:34 [<root>]
    at drainMicroTaskQueue (C:\src\AzureDataStudio-2\node_modules\zone.js\dist\zone.js:595:35) [<root>]
```

**Comment by chlafreniere** [comment]
Interesting. Is this due to the fact that we've disabled the debugger?

**Comment by Charles-Gagnon** [comment]
Yeah, this is just a general warning because these contributions ask for the debug service to be injected but we've removed that. The likely solution is just going to be removing these contributions for now since without the debugger I doubt they'll be able to function.

**Comment by chlafreniere** [comment]
Gotcha, thanks @Charles-Gagnon.
