### ISSUE TITLE
PowerShell notebook - OSError: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by dejan-shuki** [microsoft/azuredatastudio#18109]
Issue Type: <b>Bug</b>

1. Create New notebook
2. Switch kernel to PowerShell
3. Create new cell
4. type in Write-Host "test"

Traceback (most recent call last):
  File "C:\Users\dsunderic\AppData\Roaming\Python\Python39\site-packages\powershell_kernel\kernel.py", line 62, in do_execute
    self.__createProxy()
  File "C:\Users\dsunderic\AppData\Roaming\Python\Python39\site-packages\powershell_kernel\kernel.py", line 51, in __createProxy
    repl = subprocess_repl.SubprocessRepl([powershell_command, '-noninteractive', '-noprofile', '-File', '-'])
  File "C:\Users\dsunderic\AppData\Roaming\Python\Python39\site-packages\powershell_kernel\subprocess_repl.py", line 28, in __init__
    self.popen = Popen(cmd, bufsize=1,
  File "C:\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python\Python39\lib\subprocess.py", line 1443, in _execute_child
    _winapi.CloseHandle(ht)
OSError: [WinError 6] The handle is invalid

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:47:33.863Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (2.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azcli|Mic|0.3.0
powershell|ms-|2021.12.0

</details>

**Comment by chlafreniere** [comment]
@VasuBhog can you help here?

**Comment by VasuBhog** [comment]
Hi @dejan-shuki, sorry you are encountering an error. Would you be able to tell me the powershell_kernel version that you have installed?

**Comment by dejan-shuki** [comment]
When I execute $PSVersionTable in Terminal of of ADS, I get this:
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

**Comment by VasuBhog** [comment]
@dejan-shuki so the terminal uses a different version of the PowerShell that is via the integrated PS extension. For Notebook, we use Powershell kernel [found here](https://github.com/vors/jupyter-powershell). As such, it is important to make sure you are on our latest version of that python package. 

Steps to check Powershell kernel version:
1. Open Notebook you are currently having trouble with. 
2. Ensure the Powershell kernel is selected. 
3. Click the Manage Packages Icon - 
![Screen Shot 2022-01-19 at 1 56 13 PM](https://user-images.githubusercontent.com/23587151/150220515-b67941f3-751c-4c66-b125-1414457a0101.png)
4. In the Installed section search for powershell-kernel and ensure the version is latest to 0.1.4 (as shown below) - 
![image](https://user-images.githubusercontent.com/23587151/150220697-bf0f1de1-cd05-4f78-b1a1-b307c2ec66b9.png)
