### ISSUE TITLE
Can't open 'Edit Data' from a table in SQL server instance

### ISSUE THREAD

**Issue by feng-xiao** [microsoft/azuredatastudio#18173]
Issue Type: <b>Bug</b>

- Right click on a table from 'Connections' -> SQL Servers -> Select a table from any database
- Choose 'Edit Data' from the context menu
- Error occurred: An unexpected error occurred while connecting. Please file an issue with the title 'Unexpected Error Occurred while Connecting' and include the log file

Stacktrace: 
[2022-01-27 09:13:42.090] [renderer1] [error] Unexpected error occurred while connecting.: Error: Unexpected error occurred while connecting.
    at i.onConnectionComplete (file:///C:/Users/FengXiao/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:881:23345) [<root>]
    at As.onConnectionComplete (file:///C:/Users/FengXiao/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2554:31061) [<root>]
    at v.$onConnectionComplete (file:///C:/Users/FengXiao/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2602:59365) [<root>]
    at a._doInvokeHandler (file:///C:/Users/FengXiao/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2589:11898) [<root>]
    at a._invokeHandler (file:///C:/Users/FengXiao/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2589:11590) [<root>]
    at a._receiveRequest (file:///C:/Users/FengXiao/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2589:10252) [<root>]
    at a._receiveOneMessage (file:///C:/Users/FengXiao/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2589:9055) [<root>]
    at file:///C:/Users/FengXiao/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2589:7159 [<root>]
    at i.fire (file:///C:/Users/FengXiao/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:129:1835) [<root>]
    at d.fire (file:///C:/Users/FengXiao/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:176:16346) [<root>]
    at s._receiveMessage (file:///C:/Users/FengXiao/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:176:21604) [<root>]
    at file:///C:/Users/FengXiao/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:176:18490 [<root>]
    at i.fire (file:///C:/Users/FengXiao/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:129:1835) [<root>]
    at n.acceptChunk (file:///C:/Users/FengXiao/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:176:13707) [<root>]
    at file:///C:/Users/FengXiao/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:176:13055 [<root>]
    at Socket.D (file:///C:/Users/FengXiao/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3861:136281) [<root>]
    at Socket.emit (events.js:315:20) [<root>]
    at addChunk (internal/streams/readable.js:309:12) [<root>]
    at readableAddChunk (internal/streams/readable.js:284:9) [<root>]
    at Socket.Readable.push (internal/streams/readable.js:223:10) [<root>]
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) [<root>]

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:47:33.863Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (2.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
azuremonitor|Mic|0.1.4
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.12.0
sql-database-projects|Mic|0.14.1
azdata-sanddance|msr|3.3.0

</details>

**Comment by lewis-sanchez** [comment]
Hi @feng-xiao, is this still an issue you experience with Azure Data Studio when you try to edit data for a SQL database table? I followed your steps to reproduce the bug but wasn't able to able to trigger it.

**Comment by kburtram** [comment]
Closing based on the previous comment regarding no longer being able to repro.  Thanks!
