### ISSUE TITLE
Error in console first time opening the table designer

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#18401]
This only seems to happen the first time the table designer is opened, closing and re-opening it or opening other ones doesn't seem to cause the error to be thrown.

1. Right click on table and select `Design`

This error appears in the console : 

```
log.ts:301   ERR Cannot read property 'create' of undefined: TypeError: Cannot read property 'create' of undefined
    at createTextBuffer (vscode-file://vscode-app/c:/src/AzureDataStudio/out/vs/editor/common/model/textModel.js:53:24)
    at ModelServiceImpl.updateModel (vscode-file://vscode-app/c:/src/AzureDataStudio/out/vs/editor/common/services/modelServiceImpl.js:312:81)
    at DesignerScriptEditor.updateEditor (vscode-file://vscode-app/c:/src/AzureDataStudio/out/sql/workbench/browser/designer/designerScriptEditor.js:80:36)
    at vscode-file://vscode-app/c:/src/AzureDataStudio/out/sql/workbench/browser/designer/designerScriptEditor.js:35:22
    at ZoneDelegate.invoke (C:\src\AzureDataStudio\node_modules\zone.js\dist\zone.js:400:30)
    at Zone.run (C:\src\AzureDataStudio\node_modules\zone.js\dist\zone.js:160:47)
    at C:\src\AzureDataStudio\node_modules\zone.js\dist\zone.js:1318:38
    at ZoneDelegate.invokeTask (C:\src\AzureDataStudio\node_modules\zone.js\dist\zone.js:434:35)
    at Zone.runTask (C:\src\AzureDataStudio\node_modules\zone.js\dist\zone.js:205:51)
    at drainMicroTaskQueue (C:\src\AzureDataStudio\node_modules\zone.js\dist\zone.js:620:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by Charles-Gagnon** [comment]
@alanrenmsft FYI for triaging

**Comment by alanrenmsft** [comment]
@Charles-Gagnon are you able to reproduce this consistently on the first-time launch?

**Comment by alanrenmsft** [comment]
I've never run into this issue before. The fix for it is scoped we can decide whether to take it or not in tomorrow triage meeting.
