### ISSUE TITLE
Crash of mssql extension after upgrading ADS to 1.35.0

### ISSUE THREAD

**Issue by chriseaton** [microsoft/azuredatastudio#18668]
- MSSQL Extension Version: v0.1.0
- VSCode Version: Azure Data Studio 1.35.0
- OS Version: Rocky Linux 8.5 (CentOS-like) kernel 5.16.8-1 x86_64 GNU/Linux

Steps to Reproduce:

1. Start Azure Data Studio
2. Try to open connection to database.
3. Error:
    ![image](https://user-images.githubusercontent.com/5247568/156477734-d8368bf4-d1b8-4202-97a3-b41e3b90ba82.png)

**Comment by kburtram** [comment]
Thanks for reporting this issue.  I wasn't able to repro this on a fresh Rocky 8.5 installation.  It is possible there is some missing dependency for the SQL Tools Service child process, but without additional diagnostic information or a repro we can't investigate further.  Please let us know if you're still impacted by this issue and can provide additional log info (you could also try to run sqltoolsservice binary in the application extensions directory to see if its complaining of missing dependencies, etc.).

**Comment by festerman** [comment]
I have the exact same issue ...

Tried to get some logs out (Mssql:Tracing Level = All; Mssql:Log Debug Info = TRUE; and set loglevel to trace), but the exthost1/Microsoft.mssql log files stay empty ...

RunningSqlToolsResourceProviderService -- any one of the three included in the 1.35.0 download (versions 174, 207, 238)  -- a la  `/opt/azuredatastudio/resources/app/extensions/mssql/sqltoolsservice/Linux/3.0.0-release.174/SqlToolsResourceProviderService --log-file /tmp/tst.log --tracing-level All --autoflush-log` writes nothing to the logfile.

This works:

> Version: 1.34.0
> Commit: 83a4316cf89cbf961a0f09a72c861379cfd01fa9
> Date: 2021-12-15T20:44:12.556Z
> VS Code: 1.58.0
> Electron: 12.0.9
> Chrome: 89.0.4389.128
> Node.js: 14.16.0
> V8: 8.9.255.25-electron.0
> OS: Linux x64 5.17.5-arch1-1

 This one does not:

> Version: 1.35.0
> Commit: e9c8eb8564f537726b36b5f15c7f35e62f229284
> Date: 2022-02-23T17:19:52.501Z
> VS Code: 1.59.0
> Electron: 13.5.0
> Chrome: 91.0.4472.164
> Node.js: 14.16.0
> V8: 9.1.269.39-electron.0
> OS: Linux x64 5.17.5-arch1-1

and neither does 1.36.1 ...

**Comment by chriseaton** [comment]
Oh it's definitely an issue. I have to disable updates and stick w/ `1.34` - all the other versions after continue to crash with this same. Anyone else experiencing this, here's a [direct link to the working release](https://github.com/microsoft/azuredatastudio/releases/tag/1.34.0).

**Comment by fedespin79** [comment]
Confirm the error in 1.35, 1.36, 1.37 on Ubuntu 20.04. The error at connection is:

**EXTENSION LOG**
`[2022-06-18 ...] [exthost] [debug] ProxyResolver#resolveProxy cached https://vortex.data.microsoft.com/collect/v1 DIRECT 
Error: Error for stack trace
	at resolveProxy (/usr/share/azuredatastudio/resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:105:69)
	at /usr/share/azuredatastudio/resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:293:77
	at new Promise (<anonymous>)
	at _PacProxyAgent.resolveP [as resolver] (/usr/share/azuredatastudio/resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:293:54)
	at _PacProxyAgent.<anonymous> (/usr/share/azuredatastudio/resources/app/node_modules.asar/vscode-proxy-agent/out/agent.js:71:37)
	at Generator.next (<anonymous>)
	at /usr/share/azuredatastudio/resources/app/node_modules.asar/vscode-proxy-agent/out/agent.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (/usr/share/azuredatastudio/resources/app/node_modules.asar/vscode-proxy-agent/out/agent.js:4:12)
	at _PacProxyAgent.callback (/usr/share/azuredatastudio/resources/app/node_modules.asar/vscode-proxy-agent/out/agent.js:53:16)
	at _PacProxyAgent.addRequest (/usr/share/azuredatastudio/resources/app/node_modules.asar/vscode-proxy-agent/node_modules/agent-base/dist/src/index.js:184:38)
	at new ClientRequest (_http_client.js:306:16)
	at request (https.js:313:10)
	at Object.patched (/usr/share/azuredatastudio/resources/app/node_modules.asar/vscode-proxy-agent/out/index.js:297:24)
	at Object.n.request.<computed>.n.request (/usr/share/azuredatastudio/resources/app/extensions/mssql/dist/main.js:2:16966)
	at Function.e.makeRequest (/usr/share/azuredatastudio/resources/app/extensions/mssql/dist/main.js:2:1168499)
	at Gzip.cb (/usr/share/azuredatastudio/resources/app/extensions/mssql/dist/main.js:2:1302815)
	at Gzip.zlibBufferOnEnd (zlib.js:152:10)
	at Gzip.emit (events.js:315:20)
	at endReadableNT (internal/streams/readable.js:1327:12)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)
`

**WINDOWS LOG**
`[2022-06-18 ...] [renderer1] [error] Unfound provider 3: Error: Unfound provider 3
	at I._resolveProvider (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:82:27774)
	at I.$connect (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:82:31908)
	at i._doInvokeHandler (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:13568)
	at i._invokeHandler (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:13252)
	at i._receiveRequest (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:11890)
	at i._receiveOneMessage (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:10568)
	at /usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:8664
	at s.fire (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1712)
	at g.fire (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15852)
	at /usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:101:30118
	at s.fire (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1712)
	at g.fire (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15852)
	at l._receiveMessage (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:21118)
	at /usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17996
	at s.fire (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1712)
	at f.acceptChunk (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:13213)
	at /usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12561
	at Socket.E (/usr/share/azuredatastudio/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:101:13355)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)`

**Comment by chriseaton** [comment]
Here's what shows in the dev console. Tried on the latest 1.37. Still have to downgrade to 1.34, every version after fails. My entire team has to downgrade because all the newer versions fail on their workstations, even the folks using Windows 10.

![image](https://user-images.githubusercontent.com/5247568/174464631-451e0307-8889-492d-87b1-73c9c14e23df.png)

**Comment by cheenamalhotra** [comment]
@festerman @chriseaton @fedespin 
FYI, in case this is related to #18844 ... **v1.39** is coming up with a fix for Linux Kerberos connections, I would recommend trying!

**Comment by fedespin** [comment]
Yes, the version 1.39 fix this bug.
Thanks!!!
