### ISSUE TITLE
Chart viewer "copy as image" and "save as image" don't work for table chart type

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#1879]
- SQL Operations Studio Version: Master fbd5e81

Steps to Reproduce:
1. Run a query
2. Click the view as chart button
3. Click the "copy as image" or "save as image" buttons and choose a file name for the saved image if needed

Actual behavior: Nothing happens even after choosing a file (for save as image)
Expected behavior: The buttons should not be there if saving as an image is not supported, or all chart types should support saving as an image

```
Object {exception: TypeError: _this._chartComponent.getCanvasData is …, error: null, promise: _Base.Class.derive._creator, handler: undefined, id: 25, …}
zone-node.js:2251
TypeError: _this._chartComponent.getCanvasData is not a function
zone-node.js:2251
    at file:///Users/mairvine/code/sqlopsstudio/out/sql/parts/grid/views/query/chartViewer.component.js:152:50
    at Object.notifySuccess [as _notify] (file:///Users/mairvine/code/sqlopsstudio/out/vs/base/common/winjs.base.js:1185:59)
    at Object.enter (file:///Users/mairvine/code/sqlopsstudio/out/vs/base/common/winjs.base.js:867:30)
    at Promise_ctor._run (file:///Users/mairvine/code/sqlopsstudio/out/vs/base/common/winjs.base.js:1083:29)
    at Promise_ctor._completed (file:///Users/mairvine/code/sqlopsstudio/out/vs/base/common/winjs.base.js:1051:18)
    at _this.handlers.(anonymous function) (file:///Users/mairvine/code/sqlopsstudio/out/vs/base/parts/ipc/common/ipc.js:144:29)
    at ChannelClient.onMessage (file:///Users/mairvine/code/sqlopsstudio/out/vs/base/parts/ipc/common/ipc.js:202:17)
    at file:///Users/mairvine/code/sqlopsstudio/out/vs/base/parts/ipc/common/ipc.js:109:89
    at Emitter.fire (file:///Users/mairvine/code/sqlopsstudio/out/vs/base/common/event.js:103:38)
    at file:///Users/mairvine/code/sqlopsstudio/out/vs/base/parts/ipc/common/ipc.electron.js:12:60
    at Emitter.fire (file:///Users/mairvine/code/sqlopsstudio/out/vs/base/common/event.js:103:38)
    at EventEmitter.fn (file:///Users/mairvine/code/sqlopsstudio/out/vs/base/common/event.js:496:27)
    at ZoneDelegate.invokeTask (/Users/mairvine/code/sqlopsstudio/node_modules/zone.js/dist/zone-node.js:421:31)
    at Zone.runTask (/Users/mairvine/code/sqlopsstudio/node_modules/zone.js/dist/zone-node.js:188:47)
    at ZoneTask.invokeTask (/Users/mairvine/code/sqlopsstudio/node_modules/zone.js/dist/zone-node.js:496:34)
    at EventEmitter.ZoneTask.invoke (/Users/mairvine/code/sqlopsstudio/node_modules/zone.js/dist/zone-node.js:485:48)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:194:7)
```

**Comment by alanrenmsft** [comment]
this is already implemented
![image](https://github.com/microsoft/azuredatastudio/assets/13777222/57c5eff0-5a56-4345-a2f8-ec035df9da6d)
