### ISSUE TITLE
Unexpected Error Occurred while Connecting

### ISSUE THREAD

**Issue by perbauer** [microsoft/azuredatastudio#18873]
Issue Type: <b>Bug</b>

Below is the log file *\Roaming\azuredatastudio\logs\20220330T083930\renderer1.log;

[2022-03-30 08:39:37.959] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:jvshptTest1|server:vi8srvdba004|user:sa|databaseDisplayName:jvshptTest1|group:c5006a97-ae72-4fd6-b81d-596a79bbe529
[2022-03-30 08:39:37.960] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:jvshptTest1|server:vi8srvdba004|user:sa|databaseDisplayName:jvshptTest1|group:c5006a97-ae72-4fd6-b81d-596a79bbe529
[2022-03-30 08:39:37.960] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:jvshptTest1|server:vi8srvdba004|user:sa|databaseDisplayName:jvshptTest1|group:c5006a97-ae72-4fd6-b81d-596a79bbe529
[2022-03-30 08:39:38.712] [renderer1] [info] Creating new connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:jvshptTest1|server:vi8srvdba004|user:sa|databaseDisplayName:jvshptTest1|group:c5006a97-ae72-4fd6-b81d-596a79bbe529
[2022-03-30 08:39:38.713] [renderer1] [info] Adding connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:jvshptTest1|server:vi8srvdba004|user:sa|databaseDisplayName:jvshptTest1|group:c5006a97-ae72-4fd6-b81d-596a79bbe529
[2022-03-30 08:39:38.714] [renderer1] [info] Successfully added connection dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:jvshptTest1|server:vi8srvdba004|user:sa|databaseDisplayName:jvshptTest1|group:c5006a97-ae72-4fd6-b81d-596a79bbe529
[2022-03-30 08:39:53.558] [renderer1] [info] Creating new connection untitled:SQLQuery_1
[2022-03-30 08:39:53.559] [renderer1] [info] Adding connection untitled:SQLQuery_1
[2022-03-30 08:39:53.559] [renderer1] [info] Successfully added connection untitled:SQLQuery_1
[2022-03-30 08:40:46.003] [renderer1] [error] Error loading database names for query editor  {}
[2022-03-30 08:41:17.524] [renderer1] [error] Error loading database names for query editor  {}
[2022-03-30 08:43:27.809] [renderer1] [info] Creating new connection file:///c:/Users/PerB/OneDrive - HP Tronic/Projects/compare jämför artikelnummer Materiallista Strukturartiklar for Ledningssatser KS - JensH 2022-02/SP q_HPT_JamforMtrllstStrkt - funkar inte- compare M-lista S-artiklar Ledningssatser - 2022-03-17 r13.sql
[2022-03-30 08:43:27.810] [renderer1] [info] Adding connection file:///c:/Users/PerB/OneDrive - HP Tronic/Projects/compare jämför artikelnummer Materiallista Strukturartiklar for Ledningssatser KS - JensH 2022-02/SP q_HPT_JamforMtrllstStrkt - funkar inte- compare M-lista S-artiklar Ledningssatser - 2022-03-17 r13.sql
[2022-03-30 08:43:27.810] [renderer1] [info] Successfully added connection file:///c:/Users/PerB/OneDrive - HP Tronic/Projects/compare jämför artikelnummer Materiallista Strukturartiklar for Ledningssatser KS - JensH 2022-02/SP q_HPT_JamforMtrllstStrkt - funkar inte- compare M-lista S-artiklar Ledningssatser - 2022-03-17 r13.sql
[2022-03-30 08:43:37.646] [renderer1] [info] Disconnect request sent for file:///c:/Users/PerB/OneDrive - HP Tronic/Projects/compare jämför artikelnummer Materiallista Strukturartiklar for Ledningssatser KS - JensH 2022-02/SP q_HPT_JamforMtrllstStrkt - funkar inte- compare M-lista S-artiklar Ledningssatser - 2022-03-17 r13.sql - deleting connection
[2022-03-30 08:43:37.647] [renderer1] [info] Deleting connection file:///c:/Users/PerB/OneDrive - HP Tronic/Projects/compare jämför artikelnummer Materiallista Strukturartiklar for Ledningssatser KS - JensH 2022-02/SP q_HPT_JamforMtrllstStrkt - funkar inte- compare M-lista S-artiklar Ledningssatser - 2022-03-17 r13.sql
[2022-03-30 08:43:37.743] [renderer1] [error] Error loading database names for query editor  {}
[2022-03-30 08:43:47.441] [renderer1] [info] Creating new connection file:///c:/Users/PerB/OneDrive - HP Tronic/Projects/compare jämför artikelnummer Materiallista Strukturartiklar for Ledningssatser KS - JensH 2022-02/q_kskoppla q_kabellangd - inte alltid kabelId ifyllt 2022-03-17.sql
[2022-03-30 08:43:47.442] [renderer1] [info] Adding connection file:///c:/Users/PerB/OneDrive - HP Tronic/Projects/compare jämför artikelnummer Materiallista Strukturartiklar for Ledningssatser KS - JensH 2022-02/q_kskoppla q_kabellangd - inte alltid kabelId ifyllt 2022-03-17.sql
[2022-03-30 08:43:47.442] [renderer1] [info] Successfully added connection file:///c:/Users/PerB/OneDrive - HP Tronic/Projects/compare jämför artikelnummer Materiallista Strukturartiklar for Ledningssatser KS - JensH 2022-02/q_kskoppla q_kabellangd - inte alltid kabelId ifyllt 2022-03-17.sql
[2022-03-30 08:45:22.614] [renderer1] [info] Disconnect request sent for file:///c:/Users/PerB/OneDrive - HP Tronic/Projects/compare jämför artikelnummer Materiallista Strukturartiklar for Ledningssatser KS - JensH 2022-02/q_kskoppla q_kabellangd - inte alltid kabelId ifyllt 2022-03-17.sql - deleting connection
[2022-03-30 08:45:22.614] [renderer1] [info] Deleting connection file:///c:/Users/PerB/OneDrive - HP Tronic/Projects/compare jämför artikelnummer Materiallista Strukturartiklar for Ledningssatser KS - JensH 2022-02/q_kskoppla q_kabellangd - inte alltid kabelId ifyllt 2022-03-17.sql
[2022-03-30 08:45:22.694] [renderer1] [info] Disposing the query runner of: 'file:///c:/Users/PerB/OneDrive - HP Tronic/Projects/compare jämför artikelnummer Materiallista Strukturartiklar for Ledningssatser KS - JensH 2022-02/q_kskoppla q_kabellangd - inte alltid kabelId ifyllt 2022-03-17.sql'', call stack: Error
    at n.dispose (vscode-file://vscode-app/c:/05Prg/azuredatastudio/resources/app/out/vs/workbench/workbench.desktop.main.js:2262:55039) [<root>]
    at n.disposeQuery (vscode-file://vscode-app/c:/05Prg/azuredatastudio/resources/app/out/vs/workbench/workbench.desktop.main.js:2262:54936) [<root>]
    at processTicksAndRejections (internal/process/task_queues.js:93:5) [<root>]
    at async p.disposeQuery (vscode-file://vscode-app/c:/05Prg/azuredatastudio/resources/app/out/vs/workbench/workbench.desktop.main.js:2265:5742) [<root>]
[2022-03-30 08:45:22.698] [renderer1] [error] Error loading database names for query editor  {}
[2022-03-30 08:48:27.641] [renderer1] [info] Creating new connection file://%3F/c:/Users/PerB/OneDrive - HP Tronic/Projects/compare jämför artikelnummer Materiallista Strukturartiklar for Ledningssatser KS - JensH 2022-02/SP q_HPT_JamforMtrllstStrkt compare table Materiallista Strukturartiklar for Ledningssatser - JensH 2022-03-30 r14.sql
[2022-03-30 08:48:27.642] [renderer1] [info] Adding connection file://%3F/c:/Users/PerB/OneDrive - HP Tronic/Projects/compare jämför artikelnummer Materiallista Strukturartiklar for Ledningssatser KS - JensH 2022-02/SP q_HPT_JamforMtrllstStrkt compare table Materiallista Strukturartiklar for Ledningssatser - JensH 2022-03-30 r14.sql
[2022-03-30 08:48:27.642] [renderer1] [info] Successfully added connection file://%3F/c:/Users/PerB/OneDrive - HP Tronic/Projects/compare jämför artikelnummer Materiallista Strukturartiklar for Ledningssatser KS - JensH 2022-02/SP q_HPT_JamforMtrllstStrkt compare table Materiallista Strukturartiklar for Ledningssatser - JensH 2022-03-30 r14.sql
[2022-03-30 08:48:27.710] [renderer1] [error] OnConnectionComplete but no connection found 'file://%3f/c:/Users/PerB/OneDrive - HP Tronic/Projects/compare jämför artikelnummer Materiallista Strukturartiklar for Ledningssatser KS - JensH 2022-02/SP q_HPT_JamforMtrllstStrkt compare table Materiallista Strukturartiklar for Ledningssatser - JensH 2022-03-30 r14.sql' Connections = [connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:jvshptTest1|server:vi8srvdba004|user:sa|databaseDisplayName:jvshptTest1|group:c5006a97-ae72-4fd6-b81d-596a79bbe529,dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:jvshptTest1|server:vi8srvdba004|user:sa|databaseDisplayName:jvshptTest1|group:c5006a97-ae72-4fd6-b81d-596a79bbe529,file://%3F/c:/Users/PerB/OneDrive - HP Tronic/Projects/compare jämför artikelnummer Materiallista Strukturartiklar for Ledningssatser KS - JensH 2022-02/SP q_HPT_JamforMtrllstStrkt compare table Materiallista Strukturartiklar for Ledningssatser - JensH 2022-03-30 r14.sql]
[2022-03-30 08:48:27.714] [renderer1] [error] Unexpected error occurred while connecting.: Error: Unexpected error occurred while connecting.
    at g.onConnectionComplete (vscode-file://vscode-app/c:/05Prg/azuredatastudio/resources/app/out/vs/workbench/workbench.desktop.main.js:843:23305) [<root>]
    at Hs.onConnectionComplete (vscode-file://vscode-app/c:/05Prg/azuredatastudio/resources/app/out/vs/workbench/workbench.desktop.main.js:2278:31176) [<root>]
    at y.$onConnectionComplete (vscode-file://vscode-app/c:/05Prg/azuredatastudio/resources/app/out/vs/workbench/workbench.desktop.main.js:2329:69156) [<root>]
    at S._doInvokeHandler (vscode-file://vscode-app/c:/05Prg/azuredatastudio/resources/app/out/vs/workbench/workbench.desktop.main.js:2316:12730) [<root>]
    at S._invokeHandler (vscode-file://vscode-app/c:/05Prg/azuredatastudio/resources/app/out/vs/workbench/workbench.desktop.main.js:2316:12414) [<root>]
    at S._receiveRequest (vscode-file://vscode-app/c:/05Prg/azuredatastudio/resources/app/out/vs/workbench/workbench.desktop.main.js:2316:11076) [<root>]
    at S._receiveOneMessage (vscode-file://vscode-app/c:/05Prg/azuredatastudio/resources/app/out/vs/workbench/workbench.desktop.main.js:2316:9754) [<root>]
    at vscode-file://vscode-app/c:/05Prg/azuredatastudio/resources/app/out/vs/workbench/workbench.desktop.main.js:2316:7850 [<root>]
    at n.fire (vscode-file://vscode-app/c:/05Prg/azuredatastudio/resources/app/out/vs/workbench/workbench.desktop.main.js:129:1712) [<root>]
    at a.fire (vscode-file://vscode-app/c:/05Prg/azuredatastudio/resources/app/out/vs/workbench/workbench.desktop.main.js:176:16525) [<root>]
    at w._receiveMessage (vscode-file://vscode-app/c:/05Prg/azuredatastudio/resources/app/out/vs/workbench/workbench.desktop.main.js:176:21791) [<root>]
    at vscode-file://vscode-app/c:/05Prg/azuredatastudio/resources/app/out/vs/workbench/workbench.desktop.main.js:176:18669 [<root>]
    at n.fire (vscode-file://vscode-app/c:/05Prg/azuredatastudio/resources/app/out/vs/workbench/workbench.desktop.main.js:129:1712) [<root>]
    at p.acceptChunk (vscode-file://vscode-app/c:/05Prg/azuredatastudio/resources/app/out/vs/workbench/workbench.desktop.main.js:176:13886) [<root>]
    at vscode-file://vscode-app/c:/05Prg/azuredatastudio/resources/app/out/vs/workbench/workbench.desktop.main.js:176:13234 [<root>]
    at Socket.D (vscode-file://vscode-app/c:/05Prg/azuredatastudio/resources/app/out/vs/workbench/workbench.desktop.main.js:3860:163993) [<root>]
    at Socket.emit (events.js:315:20) [<root>]
    at addChunk (internal/streams/readable.js:309:12) [<root>]
    at readableAddChunk (internal/streams/readable.js:284:9) [<root>]
    at Socket.Readable.push (internal/streams/readable.js:223:10) [<root>]
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) [<root>]

Azure Data Studio version: azuredatastudio 1.35.1 (fab63efd307e54c063c8af03474bbb5d77f5fd11, 2022-03-15T18:03:38.261Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (20.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2

</details>

**Comment by abist** [comment]
@alanrenmsft Seems like an editor issue since the connection is succcessful -
```
[2022-03-30 08:40:46.003] [renderer1] [error] Error loading database names for query editor {}
[2022-03-30 08:41:17.524] [renderer1] [error] Error loading database names for query editor {}
```

**Comment by kburtram** [comment]
@perbauer is this error occurring with all connections or only particular ones?  I recall a while ago we had issues with files stored in OneDrive folder for some reason (but couldn't locate previous issue).  Could you please try to connect with a SQL file saved in a different location?

**Comment by perbauer** [comment]
I did a re-extract of all files in the azuredatastudio zip file yesterday and have since then not had any problem connecting. **Problem is solved**. Do not know what was wrong but perhaps some file got corrupted in the previous extract from zip. 
Thanks for your quick help everybody!
