### ISSUE TITLE
Intellisense not working for hungarian collation

### ISSUE THREAD

**Issue by kazinad** [microsoft/azuredatastudio#18892]
- Azure Data Studio Version: 1.35 and later
- OS Version: Windows 10

Steps to Reproduce:

1. Create a database with collation: Hungarian_Technical_CI_AS
2. Open a new query connecting to that database.
3. Test intellisense, does not show table and column names.

Does this issue occur when all extensions are disabled?: Yes

Please note that, this absolutely worked fine with version 1.34 and prior, so I have reverted to that version.

I found the following exception in the sqltools.log file:

```
22-03-31 17:52:47.9961298 pid:15040 tid:21 sqltools Error: 0 : Unknown exception during parsing Microsoft.Data.SqlClient.SqlException (0x80131904): The Collation specified by SQL Server is not supported.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.TdsParser.DrainData(TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.TdsParser.ThrowUnsupportedCollationEncountered(TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadStringWithEncoding(Int32 length, Encoding encoding, Boolean isPlp, String& value)
   at Microsoft.Data.SqlClient.TdsParser.TryReadSqlStringValue(SqlBuffer value, Byte type, Int32 length, Encoding encoding, Boolean isPlp, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.TdsParser.TryReadSqlValue(SqlBuffer value, SqlMetaDataPriv md, Int32 length, TdsParserStateObject stateObj, SqlCommandColumnEncryptionSetting columnEncryptionOverride, String columnName, SqlCommand command)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadColumnInternal(Int32 i, Boolean readHeaderOnly)
   at Microsoft.Data.SqlClient.SqlDataReader.GetValues(Object[] values)
   at Microsoft.SqlServer.Management.Smo.DataProvider.ReadInternal()
   at Microsoft.SqlServer.Management.Smo.DataProvider.SetConnectionAndQuery(ExecuteSql execSql, String query)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.GetDataProvider(StringCollection query, Object con, StatementBuilder sb, RetriveMode rm)
   at Microsoft.SqlServer.Management.Smo.ExecuteSql.ExecuteWithResults(StringCollection query, Object con, StatementBuilder sb)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.FillData(ResultType resultType, StringCollection sql, Object connectionInfo, StatementBuilder sb)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.FillDataWithUseFailure(SqlEnumResult sqlresult, ResultType resultType)
   at Microsoft.SqlServer.Management.Smo.SqlObjectBase.BuildResult(EnumResult result)
   at Microsoft.SqlServer.Management.Smo.DatabaseLevel.GetData(EnumResult res)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData()
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData(Request req, Object ci)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.GetData(Object connectionInfo, Request request)
   at Microsoft.SqlServer.Management.Smo.ExecutionManager.GetEnumeratorDataReader(Request req)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.GetInitDataReader(String[] fields, OrderBy[] orderby)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.ImplInitialize(String[] fields, OrderBy[] orderby)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.OnPropertyMissing(String propname, Boolean useDefaultValue)
   at Microsoft.SqlServer.Management.Smo.PropertyCollection.RetrieveProperty(Int32 index, Boolean useDefaultOnMissingValue)
   at Microsoft.SqlServer.Management.Smo.PropertyCollection.GetValueWithNullReplacement(String propertyName, Boolean throwOnNullValue, Boolean useDefaultOnMissingValue)
   at Microsoft.SqlServer.Management.Smo.PropertyCollection.GetValueWithNullReplacement(String propertyName)
   at Microsoft.SqlServer.Management.Smo.Database.get_DefaultSchema()
   at Microsoft.SqlServer.Management.SmoMetadataProvider.Database.get_DefaultSchemaName()
   at Microsoft.SqlServer.Management.SqlParser.Binder.DatabaseEx.get_DefaultSchemaName()
   at Microsoft.SqlServer.Management.SqlParser.Binder.DatabaseEx.get_DefaultSchema()
   at Microsoft.SqlServer.Management.SqlParser.Binder.SchemaEx.CreateUnnamedSchema(DatabaseEx database, SchemaEx defaultSchema)
   at Microsoft.SqlServer.Management.SqlParser.Binder.SchemaEx.CreateUnnamedSchema(DatabaseEx database)
   at Microsoft.SqlServer.Management.SqlParser.Binder.DatabaseEx.get_UnnamedSchema()
   at Microsoft.SqlServer.Management.SqlParser.Binder.BatchBindingContext..ctor(DatabaseEx database)
   at Microsoft.SqlServer.Management.SqlParser.Binder.BinderProvider.Binder.BindAll(IEnumerable`1 parseResults, String databaseName, BindMode bindMode)
   at Microsoft.SqlServer.Management.SqlParser.Binder.BinderProvider.Binder.Bind(IEnumerable`1 parseResults, String databaseName, BindMode bindMode)
   at Microsoft.SqlTools.ServiceLayer.LanguageServices.LanguageService.<>c__DisplayClass70_0.<ParseAndBind>b__1(IBindingContext bindingContext, CancellationToken cancelToken) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\LanguageServices\LanguageService.cs:line 987

```

**Comment by Charles-Gagnon** [comment]
Do you see the same issue if you use SSMS?

The error and callstack indicate this is an issue with SqlClient, and I found a very similar issue here : https://github.com/dotnet/SqlClient/issues/576

Could you open an issue there with these details and we can follow up with them to see if this is a known issue there?

**Comment by kazinad** [comment]
> Do you see the same issue if you use SSMS?

No. I can use that database everywhere else, even with azure database studio ver 1.35, and with my own application too, the only thing not working is intellisense with ver 1.35. Earlier versions worked fine.

**Comment by Charles-Gagnon** [comment]
I can repro this in ADS as well, but not with a simple test app. Opened an issue in the SqlClient repo to see if they have any ideas

https://github.com/dotnet/SqlClient/issues/1572

**Comment by Charles-Gagnon** [comment]
@kazinad The latest insiders builds should have this fix - if you have a chance could you test it out and verify it's fixed for you?

**Comment by kazinad** [comment]
@Charles-Gagnon I confirm, it is working good, thank you for the fix. I tested it with:

Version: 1.36.0-insider
Commit: b96fb5aa907451e54063d985e92f5708bf76369b
Date: 2022-04-05T05:50:43.453Z
VS Code: 1.59.0
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by Charles-Gagnon** [comment]
Thank you! The next stable release with this fix will be later this month.
