### ISSUE TITLE
Unexpected error while connecting

### ISSUE THREAD

**Issue by JeanPhilippeGeorge** [microsoft/azuredatastudio#18934]
Issue Type: <b>Bug</b>

From time to time I can not connect to databases. I can close and reopen Azure Data Studio to solve the problem. 
That solve the problem for 5' or days.
It seems to be completely random.
Sadly, no idea of how to reproduce :-(
Thanks and good luck

Azure Data Studio version: azuredatastudio 1.35.1 (fab63efd307e54c063c8af03474bbb5d77f5fd11, 2022-03-15T18:03:38.261Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (18.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.7
dacpac|Mic|1.8.0
powershell|ms-|2021.12.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.12.0
sql-assessment|Mic|0.6.1
vscodeintellicode|Vis|1.2.1

</details>

**Comment by kburtram** [comment]
@JeanPhilippeGeorge how does the application behave in this situation?  Do the connections in Servers explorer and Query Editor appear connected and just not work?  Or do they disconnect and not reconnect?  Are there any error messages in the "Help->Developer Tools" Console?  Thanks!

**Comment by JeanPhilippeGeorge** [comment]
@kburtram I think it depends. 

Some time some query editors continue to work and some shows disconnected and when trying to reconnect they fails. I think Server Explorer continue to work but it could be that it has already what I want to use in cache. 

Other time all query editors are disconnected and fail to reconnect.

As I have closed Azure Studio multiple times I don't have console log relevant to the problem, but I have attached two application logs which should be logs of the problem of yesterday.
And now that I know how to collect all of them and in what question you are interested I keep that in mind and will add these infos next time.

[20220405T092535.zip](https://github.com/microsoft/azuredatastudio/files/8425068/20220405T092535.zip)
[20220405T100949.zip](https://github.com/microsoft/azuredatastudio/files/8425069/20220405T100949.zip)

**Comment by kburtram** [comment]
@JeanPhilippeGeorge thanks for providing the logs.  I see the below exceptions being raised.  We'll investigate these code paths to try to determine what's happening here.

```
[2022-04-05 10:04:43.474] [renderer1] [info] Disposing the query runner of: 'untitled:SQLQuery_4'', call stack: Error
    at n.dispose (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2262:55039) [<root>]
    at n.disposeQuery (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2262:54936) [<root>]
    at processTicksAndRejections (internal/process/task_queues.js:93:5) [<root>]
    at async p.disposeQuery (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2265:5742) [<root>]
[2022-04-05 10:04:45.067] [renderer1] [error] TypeError: Cannot read property 'slice' of undefined
    at n.get batchSets [as batchSets] (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2262:50558)
    at $.set queryRunner [as queryRunner] (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3311:20421)
    at r.set queryRunner [as queryRunner] (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3344:1465)
    at r.onShow (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3344:1389)
    at m.showTab (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:304:66476)
    at w.showResults (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3344:7857)
    at w.setQueryRunner (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3344:2945)
    at w.set input [as input] (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3344:6623)
    at Bc.setInput (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3344:11875)
    at Mo.setInput (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3397:9965)
    at p.doSetInput (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3207:35571)
    at p.doOpenEditor (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3207:33974)
    at p.openEditor (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3207:33735)
    at vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3569:16743
    at Li.doShowEditor (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3569:16922)
    at Li.openEditor (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3569:16516)
    at ne (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3493:15310)
    at HTMLDivElement.<anonymous> (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3493:15559)
    at ZoneDelegate.invokeTask (C:\Users\jp\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:434:35)
    at Zone.runTask (C:\Users\jp\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:205:51)
    at ZoneTask.invokeTask [as invoke] (C:\Users\jp\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:516:38)
    at invokeTask (C:\Users\jp\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1656:18)
    at HTMLDivElement.globalZoneAwareCallback (C:\Users\jp\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1682:21)
	
[2022-04-05 10:12:39.213] [renderer1] [error] OnConnectionComplete but no connection found 'file:///null' Connections = [connection:providerName:MSSQL|applicationName:azdata|authenticationType:Integrated|database:|server:jp01|user:|group:C777F06B-202E-4480-B475-FA416154D458,connection:providerName:MSSQL|applicationName:azdata|authenticationType:Integrated|database:master|server:jp01|user:|group:C777F06B-202E-4480-B475-FA416154D458,dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:Integrated|database:TradeMasterKarkason|server:jp01|user:|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458,dashboard:providerName:MSSQL|applicationName:azdata|authenticationType:Integrated|database:TradeMasterKarkason|server:jp01|user:|databaseDisplayName:TradeMasterKarkason|group:C777F06B-202E-4480-B475-FA416154D458,untitled:SQLQuery_3,connection:providerName:MSSQL|applicationName:azdata|authenticationType:Integrated|database:TradeMasterKarkason|server:jp01|user:|databaseDisplayName:TradeMasterKarkason|group:C777F06B-202E-4480-B475-FA416154D458,untitled:SQLQuery_2,untitled:SQLQuery_1]
[2022-04-05 10:12:39.241] [renderer1] [error] Unexpected error occurred while connecting.: Error: Unexpected error occurred while connecting.
    at g.onConnectionComplete (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:843:23305) [<root>]
    at Hs.onConnectionComplete (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2278:31176) [<root>]
    at y.$onConnectionComplete (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2329:69156) [<root>]
    at S._doInvokeHandler (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2316:12730) [<root>]
    at S._invokeHandler (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2316:12414) [<root>]
    at S._receiveRequest (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2316:11076) [<root>]
    at S._receiveOneMessage (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2316:9754) [<root>]
    at vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2316:7850 [<root>]
    at n.fire (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:129:1712) [<root>]
    at a.fire (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:176:16525) [<root>]
    at w._receiveMessage (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:176:21791) [<root>]
    at vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:176:18669 [<root>]
    at n.fire (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:129:1712) [<root>]
    at p.acceptChunk (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:176:13886) [<root>]
    at vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:176:13234 [<root>]
    at Socket.D (vscode-file://vscode-app/c:/Users/jp/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3860:163993) [<root>]
    at Socket.emit (events.js:315:20) [<root>]
    at addChunk (internal/streams/readable.js:309:12) [<root>]
    at readableAddChunk (internal/streams/readable.js:284:9) [<root>]
    at Socket.Readable.push (internal/streams/readable.js:223:10) [<root>]
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) [<root>]
```

**Comment by cssuh** [comment]
@JeanPhilippeGeorge is this still happening for you in version 1.36.2?

**Comment by JeanPhilippeGeorge** [comment]
@cssuh I have not make a lot development these days, and so not used that much Azure Data Studio, but it seems to work perfectly :-)

Feel free to close the issue and I will open a new one if needed.

Thanks to the team for a great tool!
