### ISSUE TITLE
Machine Learning extension unit tests have a bunch of errors in test output

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#19043]
Seeing errors such as these : 

```
TypeError: modelBuilder.radioCardGroup is not a function
	at ModelSourcesComponent.registerComponent (/home/runner/work/azuredatastudio/azuredatastudio/extensions/machine-learning/out/views/models/modelSourcesComponent.js:9:2404)
```

```
	at ModelSourcesComponent.registerComponent (/home/runner/work/azuredatastudio/azuredatastudio/extensions/machine-learning/out/views/models/modelSourcesComponent.js:9:2404)
	at ModelSourcePage.registerComponent (/home/runner/work/azuredatastudio/azuredatastudio/extensions/machine-learning/out/views/models/modelSourcePage.js:9:309)
```

They don't seem to be failing the tests - it'd be good to verify why and fix it so that the tests don't display these errors even if it's not an actual test issue.

**Comment by Charles-Gagnon** [comment]
@llali
