### ISSUE TITLE
"Cannot read property previousSibling of null" error when selecting cells

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#19068]
1. Create new Notebook
2. Add two text cells
3. Click to select one, then click back and forth to select the other one multiple times

I'm seeing a bunch of these errors in the console. 

```
ERR Cannot read property 'previousSibling' of null: TypeError: Cannot read property 'previousSibling' of null
    at c.getNodeIndex (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio%20-%20RC1/resources/app/out/vs/workbench/workbench.desktop.main.js:3267:155338)
    at vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio%20-%20RC1/resources/app/out/vs/workbench/workbench.desktop.main.js:3267:154761
    at i.fire (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio%20-%20RC1/resources/app/out/vs/workbench/workbench.desktop.main.js:129:1712)
    at S.doModeUpdates (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio%20-%20RC1/resources/app/out/vs/workbench/workbench.desktop.main.js:997:12838)
    at S.set showMarkdown [as showMarkdown] (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio%20-%20RC1/resources/app/out/vs/workbench/workbench.desktop.main.js:997:12591)
    at c.toggleEditMode (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio%20-%20RC1/resources/app/out/vs/workbench/workbench.desktop.main.js:3267:158341)
    at c.ngOnChanges (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio%20-%20RC1/resources/app/out/vs/workbench/workbench.desktop.main.js:3267:155280)
```

**Comment by chlafreniere** [comment]
I've seen this multiple times in previous releases. Moving out.
