### ISSUE TITLE
Failure to retrieve data for index

### ISSUE THREAD

**Issue by katomic** [microsoft/azuredatastudio#19521]
Issue Type: <b>Bug</b>

Steps:
1. Connect to SQL2016 database. 
2. Expand Tables node.
3. Expand a table node that has an index
4. Right click on the index node, select [Properties]

--Additional Info
Doing the same above from SSMS (on the same pc) to same server, db, table and index works without issue.

--Expected outcome --
Index Properties window displays

--What actually happens --
Modal windows with title [ Microsoft SQL Server Manangement Studio ] and message below saying:

> Attempt to retrieve data for object failed for Server '--redacted--'.  (Microsoft.SqlServer.Smo)

--Clicking on the [ Show details ] button in the modal window displays the following in the Details panel: --

> ===================================

> 
> Attempt to retrieve data for object failed for Server '--redacted--'.  (Microsoft.SqlServer.Smo)
> 
> ------------------------------
> For help, click: https://go.microsoft.com/fwlink?ProdName=Microsoft+SQL+Server&ProdVer=15.0.18124.0+((SSMS_Rel).190524-1059)&EvtSrc=Microsoft.SqlServer.Management.Smo.ExceptionTemplates.FailedOperationExceptionText&EvtID=Attempt+to+retrieve+data+for+object+Server&LinkId=20476
> 
> ------------------------------
> Program Location:
> 
>    at Microsoft.SqlServer.Management.Smo.Server.GetSmoObject(Urn urn)
>    at Microsoft.SqlServer.Management.RelationalEngineTasks.IndexTaskFormComponent.CreateSmoObjectInstance()
>    at Microsoft.SqlServer.Management.TaskForms.SmoTaskFormComponent`1.get_Instance()
>    at Microsoft.SqlServer.Management.RelationalEngineTasks.IndexTaskFormComponent.CreatePropertyProvider()
>    at Microsoft.SqlServer.Management.TaskForms.SmoTaskFormComponent`1.OnInitialize()
>    at Microsoft.SqlServer.Management.RelationalEngineTasks.IndexTaskFormComponent.OnInitialize()
>    at Microsoft.SqlServer.Management.TaskForms.SmoTaskFormComponent`1.Initialize(ITaskManager taskManager, IPropertyDictionary properties)
>    at Microsoft.SqlServer.Management.TaskForms.TaskManager.InitializeTaskFormComponent(Object component, ITaskFormComponentInfo info)
>    at Microsoft.SqlServer.Management.TaskForms.TaskFormManager.InitializeTaskFormComponent(Object component, ITaskFormComponentInfo info)
>    at Microsoft.SqlServer.Management.TaskForms.TaskManager.InitializeTaskFormComponents(IList`1 taskFromComponentsInfo)
>    at Microsoft.SqlServer.Management.TaskForms.TaskFormManager.InitializeTaskFormComponents(IList`1 taskFromComponentsInfo)
>    at Microsoft.SqlServer.Management.TaskForms.TaskManager.Initialize(String moniker, IContext context, IList`1 taskFromComponents)
>    at Microsoft.SqlServer.Management.TaskForms.TaskFormManager.Initialize(String moniker, IContext context, ITaskFormInfo taskFormInfo)
>    at Microsoft.SqlServer.Management.TaskFormFactoryService.CreateTaskFormInstance(String taskFormMoniker, IContext context)
>    at Microsoft.SqlServer.Management.ActionHandlers.ShowTaskUIDialogActionHandler.RunTaskForm(IContext context)
>    at Microsoft.SqlServer.Management.ActionHandlers.DialogBasedActionHandler.RunTaskFormThread(Object contextObject)
> 
> ===================================
> 
> Invalid path: There is no collection of Index objects that is a child of Server. (Microsoft.SqlServer.Smo)
> 
> ------------------------------
> Program Location:
> 
>    at Microsoft.SqlServer.Management.Smo.SqlSmoObject.GetChildCollection(SqlSmoObject parent, String childUrnSuffix, String categorystr, ServerVersion srvVer)
>    at Microsoft.SqlServer.Management.Smo.SqlSmoObject.GetChildCollection(SqlSmoObject parent, XPathExpression levelFilter, Int32 filterIdx, ServerVersion srvVer)
>    at Microsoft.SqlServer.Management.Smo.Server.GetSmoObjectRec(Urn urn)
>    at Microsoft.SqlServer.Management.Smo.Server.GetSmoObject(Urn urn)
> 

Extension version: 0.0.3
Azure Data Studio version: azuredatastudio 1.36.2 (2299a76973585fa962cfd06e8acab4abb41567de, 2022-05-19T04:18:20.649Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (9.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kburtram** [comment]
This sounds like a bug in "Database Administration Tool for Windows" extension, if I understand correctly.

**Comment by Charles-Gagnon** [comment]
@kburtram Yeah - that's correct. I put it in august and will see if this is something easy to fix (we haven't updated ssmsmin in forever so doing that would be a good start...)
