### ISSUE TITLE
issue with database name in the task terminal not matching with the target database

### ISSUE THREAD

**Issue by NokSamLeong** [microsoft/azuredatastudio#19702]
Issue Type: <b>Bug</b>

I am using the backupProvider to perform a full backup on a database in the SQL migration extension. The backup is completed as expected. However, when I close the extension wizard, the tasks in the terminal doesn't show the name of the database I triggered backup for. Instead, it shows the name of the first database in the database list in the extension wizard. For example, in the case where there are 3 databases in the database list in the extension wizard, when I trigger backup for the database 2 and then exit to the main page, it will show that backup database completed for database 1 and resulting .bak file is the backup for the database 2 as expected. The expected behavior is for the the terminal to show the name of the database I trigger backup for while the current behavior is that the terminal is showing the name of the first database in the db list in the extension wizard. 

Azure Data Studio version: azuredatastudio Dev 1.37.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (16.60GB free)|
|Process Argv|. --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-renderer-backgrounding --disable-sync --metrics-recording-only --no-first-run --no-default-browser-check --user-data-dir=C:\\Users\\noksam\\Documents\\repo\\azuredatastudio/.profile-oss --inspect=5875 --no-cached-data --remote-debugging-port=9222 --remote-debugging-port=9222|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
@NokSamLeong can you provide a link the code you're using to trigger this back-up so we can repro locally?

**Comment by NokSamLeong** [comment]
> @NokSamLeong can you provide a link the code you're using to trigger this back-up so we can repro locally?

the file I modified: https://github.com/microsoft/azuredatastudio/blob/t-noleong/backupForMigration/extensions/sql-migration/src/wizard/databaseBackupPage.ts
the existing backup function: https://github.com/microsoft/azuredatastudio/blob/t-noleong/backupForMigration/src/sql/azdata.d.ts

**Comment by NokSamLeong** [comment]
steps to reproduce the bug.
1. open up the SQL Migration extension
2. click 'Migration to Azure SQL'
3. select 1+ databases, click next
4. select 'Azure SQL Manager Instance'
5. scroll down and click view/select
6. select all the database, click select and then next
7. select any of the subscription that would allow you to click next, then move on to the next page.
8. select 'offline migration, then next
9. select 'my database backups are on a networkshare'
10. scroll down to where you enter the networkshare path. Enter any network sharing path for all the databases.
11. click backup for all the databases.
12. then press cancel to close the wizard.
13. go to the task tab in the terminal. The task should show the same name for all the tasks.

**Comment by NokSamLeong** [comment]
I did comparison between my project and the backup dialog which also uses the same backup function. The bug insists even when the parameters are exactly the same. The biggest difference in the beginning of my debugging was that the Uri I get from the migration model doesnt have the backupId, databasename, and databaseDisplayName. I added those to my uri and it didnt help.

**Comment by NokSamLeong** [comment]
might need to checkout this commit (4efc72378e6dbfb23ae73031b13936970617ddce) instead of the newest commit to repro the bug because status checking that was added in the newest commit is blocking the task from showing up in the terminal.

**Comment by kburtram** [comment]
@NokSamLeong when I run through the repo steps above with the dev branch you linked me, I get the following exception when I click the Backup button.  Are you sure all the changes are pushed?  No entries are added to the Task panel and the busy spinner runs indefinitely after this exception, so I'm not able to see the issue you're encountering.

```
mainThreadExtensionService.ts:64 TypeError: Cannot read property '625c8fcd-8cc9-4c95-876f-b2a98f4707d4' of undefined
	at c:\Users\kburt\repos\azuredatastudio\extensions\sql-migration\out\wizard\databaseBackupPage.js:885:153
	at handleNotification (c:\Users\kburt\repos\azuredatastudio\extensions\mssql\node_modules\vscode-jsonrpc\lib\main.js:489:43)
	at processMessageQueue (c:\Users\kburt\repos\azuredatastudio\extensions\mssql\node_modules\vscode-jsonrpc\lib\main.js:260:17)
	at Immediate.<anonymous> (c:\Users\kburt\repos\azuredatastudio\extensions\mssql\node_modules\vscode-jsonrpc\lib\main.js:247:13)
	at processImmediate (internal/timers.js:461:21)
```

**Comment by NokSamLeong** [comment]
It should shows the task now if you pull the latest commit. Also it is expected behavior for now that the spinner go on indefinitely because of the listener issue.
