### ISSUE TITLE
Backup sets to restore list isn't populating

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#19783]
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Restore a database from BAK

Expected: Backups sets to restore list correctly populates

Actual: The list does not populate and an exception is shown in the dev console.

![image](https://user-images.githubusercontent.com/599935/174676225-c35afeb9-4b4a-42d0-8eb2-8b8ce0725fcd.png)

```
 Cannot read property 'includes' of undefined: TypeError: Cannot read property 'includes' of undefined
    at vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:1618:88596
    at i.fire (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:129:1712)
    at A.onValueChange (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:408:46277)
    at A.set value (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:408:41793)
    at A.set value [as value] (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:408:52129)
    at V.backupFileCheckboxChanged (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:1618:87104)
    at SlickGrid.<anonymous> (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:1618:79407)
    at Event.notify (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\slickgrid\slick.core.js:145:35)
    at trigger (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\slickgrid\slick.grid.js:1297:18)
    at Event.handleSelectedRangesChanged (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\slickgrid\slick.grid.js:1482:7)
    at Event.notify (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\slickgrid\slick.core.js:145:35)
    at E.setSelectedRanges (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:130:102845)
    at SlickGrid.setSelectedRows (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\slickgrid\slick.grid.js:3908:22)
    at f.setSelectedRows (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:188:8671)
    at V.updateBackupSetsToRestore (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:1618:96311)
    at vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:1618:74282
    at i.fire (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:129:1712)
    at h.updateBackupSetsToRestore (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:1604:55222)
    at h.onRestorePlanResponse (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:1604:54046)
    at vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2351:78422
    at ZoneDelegate.invoke (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:400:30)
    at Object.onInvoke (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4156:37)
    at ZoneDelegate.invoke (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:399:56)
    at Zone.run (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:160:47)
    at C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1318:38
    at ZoneDelegate.invokeTask (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:434:35)
    at Object.onInvokeTask (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4147:37)
    at ZoneDelegate.invokeTask (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:433:64)
    at Zone.runTask (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:205:51)
    at drainMicroTaskQueue (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:620:39)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by alanrenmsft** [comment]
closing the issue as the fix has been ported to release branch.
