### ISSUE TITLE
Unable to view database properties throught Central Management Servers connection pane

### ISSUE THREAD

**Issue by danielsbezerra** [microsoft/azuredatastudio#20033]
Database Administration Tool Extensions for Windows refers to this repo.
- Extendion Version: Database Administration Tool Extensions for Windows v0.0.4 (Preview)

- Azure Data Studio and OS Version:
Version: 1.37.0 (system setup)
Commit: d904740d93d7df76a0ba361f20e4351813b57645
Date: 2022-06-14T01:05:12.352Z
VS Code: 1.59.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000 (Windows 11)

Steps to Reproduce:

1. Right click on any database
2. Select "Properties"

Error msg:
===================================

Cannot show requested dialog.

===================================

Cannot show requested dialog. (SqlMgmt)

------------------------------
Program Location:

   at Microsoft.SqlServer.Management.SqlMgmt.DefaultLaunchFormHostedControlAllocator.AllocateDialog(XmlDocument initializationXml, IServiceProvider dialogServiceProvider, CDataContainer dc)
   at Microsoft.SqlServer.Management.SqlMgmt.DefaultLaunchFormHostedControlAllocator.Microsoft.SqlServer.Management.SqlMgmt.ILaunchFormHostedControlAllocator.CreateDialog(XmlDocument initializationXml, IServiceProvider dialogServiceProvider)
   at Microsoft.SqlServer.Management.SqlMgmt.LaunchForm.InitializeForm(XmlDocument doc, IServiceProvider provider, ISqlControlCollection control)
   at Microsoft.SqlServer.Management.SqlMgmt.LaunchForm..ctor(XmlDocument doc, IServiceProvider provider)
   at Microsoft.SqlServer.Management.UI.VSIntegration.ObjectExplorer.ToolMenuItemHelper.OnCreateAndShowForm(IServiceProvider sp, XmlDocument doc)
   at Microsoft.SqlServer.Management.SqlMgmt.RunningFormsTable.RunningFormsTableImpl.ThreadStarter.StartThread()

===================================

Object reference not set to an instance of an object. (SqlManagerUI)

------------------------------
Program Location:

   at Microsoft.SqlServer.Management.SqlManagerUI.CreateDatabaseData.DatabasePrototype.GetDatabaseDefaultInitFields(Server server)
   at Microsoft.SqlServer.Management.SqlManagerUI.CreateDatabaseData.DatabasePrototype..ctor(CDataContainer context)
   at Microsoft.SqlServer.Management.SqlManagerUI.DBPropSheet..ctor(CDataContainer context)

Does this issue occur when all extensions are disabled?: Yes/No

Database Administration Tool Extensions for Windows refers to this repo.

**Comment by danielsbezerra** [comment]
> 1. What type of server are you connecting to?
> 2. Does this happen across databases on multiple different servers?
> 3. Does this happen if you make a direct connect to the server/database in the server view and open the properties from there?(vs the CMS view)

1. Trying to connect to SQL Server 2016.
2. Yes, it happens on all SQL Server instances. 
3. No, It works perfectly using the direct connection. It fails only from the CMS view.
