### ISSUE TITLE
Cento7 with azure 1.37 causing system to become unusable , reboot required.

### ISSUE THREAD

**Issue by thecircleoflifefree** [microsoft/azuredatastudio#20061]
- Azure Data Studio Version: 1.37.0
- OS Version: Linux mymachine 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Machine: Centos 7

Steps to Reproduce:

1. download file
2. yum install the file
3. ensure as per guide that dependency libXScrnSaver is installed
4. run azuredatastudio

Its just stuck/hanging/freeze unable to do anything on the GUI until a pop up appears in order to "Force Quit".
If I'm fast enough when opening the tool and click say for example on the File dropdown, it does display, goes  stuck again, but this time the computer also goes stuck, had to hardreboot to recover

Does this issue occur when all extensions are disabled?: Yes

**Comment by thecircleoflifefree** [comment]
PD: tested 1.23.0 and no issues experienced

**Comment by justinw-SMC** [comment]
I've been able to reproduce this issue and attached the full log file
OS: CentOS Linux release 7.9.2009 (Core)
azuredatastudio --version = 1.37.0

I've tried `--disable-gpu` and `--disable-extensions` but the problem persists

Error snippet: 
```
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/share/azuredatastudio/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at v (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:698)
    at bindings (/usr/share/azuredatastudio/resources/app/node_modules.asar/spdlog/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/share/azuredatastudio/resources/app/node_modules.asar/spdlog/index.js:3:35)
    at Module.u._compile (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:1380)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at t (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:101)
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:1787)
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10282)
    at l (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10308)
    at Object.errorback (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10429)
    at r.triggerErrorback (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10646)
    at /usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10352
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:4:1804)
    at r.load (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:3:10282)
    at l (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10308)
    at r._loadModule (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:10438)
    at r._resolve (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:6:452)
    at r.defineModule (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:6142)
    at r._relativeRequire (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:6828)
    at n (/usr/share/azuredatastudio/resources/app/out/vs/loader.js:5:9414)
    at b (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:4542)
    at new Promise (<anonymous>)
    at k (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:4522)
    at n._createSpdLogLogger (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:5502)
    at new n (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:32:5318)
    at /usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:61:2239
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async oe.startup (/usr/share/azuredatastudio/resources/app/out/vs/code/electron-main/main.js:61:1925) {
  phase: 'loading',
  moduleId: 'spdlog',
  neededBy: [ '===anonymous3===' ]
}
```

[azure-error.log](https://github.com/microsoft/azuredatastudio/files/9163130/azure-error.log)

**Comment by justinw-SMC** [comment]
**The last stable version is 1.30.0**
This bug appears in [July 2021 Release Hotfix 1 (version 1.31.1)](https://github.com/microsoft/azuredatastudio/releases/tag/1.31.1)
It appears to be the same issue from 1.31.1 to 1.37.0.
Here are the `azuredatastudio --verbose` outputs:
[1_30_0.txt](https://github.com/microsoft/azuredatastudio/files/9163534/1_30_0.txt)
[1_31_1.txt](https://github.com/microsoft/azuredatastudio/files/9163535/1_31_1.txt)

**Comment by kburtram** [comment]
I am also encountering the error above regarding missing C++ runtime on CentOS 7.  `Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/user/Downloads/azuredatastudio-linux-x64/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)`.

According to this topic on Redhat site this version of the C++ runtime is not supported on this older operating system.  Sometime the build dependencies change as we need to update our build servers to new distros to stay in compliance. I'll check if it is possible to use an older version of GCC in our current build environment.  https://access.redhat.com/discussions/6886591

The relevant comment is quoted below for context.

```
---Masahiro Matsuya, Redhat
Hello, I'm afraid that libstdc++ library providing GLIBCXX_3.4.20 is not available in RHEL7. RHEL7 is in the 
maintenance phase currently. The full support phase ended in 2019. I recommend to use RHEL8. and the 
libstdc++ in RHEL8 provides GLIBCXX_3.4.20 feature.
```
