### ISSUE TITLE
"Unable to read file katex.min.css" error on markdown files

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#20091]
Open up markdown file (such as in a Jupyter book). This error appears in the console. I'm not seeing this in 1.37 stable

```
k {originalStack: "Error: Unable to read file 'c:\\Users\\chgagnon\\AppD…vs/workbench/workbench.desktop.main.js:855:21993)", zoneAwareStack: "Error: Unable to read file 'c:\\Users\\chgagnon\\AppD…nch/workbench.desktop.main.js:855:21993) [<root>]", stack: "Error: Unable to read file 'c:\\Users\\chgagnon\\AppD…nch/workbench.desktop.main.js:855:21993) [<root>]", message: "Unable to read file 'c:\\Users\\chgagnon\\AppData\\Loc…down-math\\node_modules\\katex\\dist\\katex.min.css')", fileOperationResult: 1, …}
fileOperationResult: 1
message: "Unable to read file 'c:\\Users\\chgagnon\\AppData\\Local\\Programs\\Azure Data Studio - RC1\\resources\\app\\extensions\\markdown-math\\node_modules\\katex\\dist\\katex.min.css' (Error: Unable to resolve nonexistent file 'c:\\Users\\chgagnon\\AppData\\Local\\Programs\\Azure Data Studio - RC1\\resources\\app\\extensions\\markdown-math\\node_modules\\katex\\dist\\katex.min.css')"
options: {etag: undefined}
originalStack: "Error: Unable to read file 'c:\\Users\\chgagnon\\AppData\\Local\\Programs\\Azure Data Studio - RC1\\resources\\app\\extensions\\markdown-math\\node_modules\\katex\\dist\\katex.min.css' (Error: Unable to resolve nonexistent file 'c:\\Users\\chgagnon\\AppData\\Local\\Programs\\Azure Data Studio - RC1\\resources\\app\\extensions\\markdown-math\\node_modules\\katex\\dist\\katex.min.css')\n    at new ZoneAwareError (C:\\Users\\chgagnon\\AppData\\Local\\Programs\\Azure Data Studio - RC1\\resources\\app\\node_modules.asar\\zone.js\\dist\\zone-error.js:99:37)\n    at new k (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio%20-%20RC1/resources/app/out/vs/workbench/workbench.desktop.main.js:850:18986)\n    at Ai.doReadFileStream (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio%20-%20RC1/resources/app/out/vs/workbench/workbench.desktop.main.js:855:21993)"
stack: "Error: Unable to read file 'c:\\Users\\chgagnon\\AppData\\Local\\Programs\\Azure Data Studio - RC1\\resources\\app\\extensions\\markdown-math\\node_modules\\katex\\dist\\katex.min.css' (Error: Unable to resolve nonexistent file 'c:\\Users\\chgagnon\\AppData\\Local\\Programs\\Azure Data Studio - RC1\\resources\\app\\extensions\\markdown-math\\node_modules\\katex\\dist\\katex.min.css')\n    at new k (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio%20-%20RC1/resources/app/out/vs/workbench/workbench.desktop.main.js:850:18986) [<root>]\n    at Ai.doReadFileStream (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio%20-%20RC1/resources/app/out/vs/workbench/workbench.desktop.main.js:855:21993) [<root>]"
zoneAwareStack: "Error: Unable to read file 'c:\\Users\\chgagnon\\AppData\\Local\\Programs\\Azure Data Studio - RC1\\resources\\app\\extensions\\markdown-math\\node_modules\\katex\\dist\\katex.min.css' (Error: Unable to resolve nonexistent file 'c:\\Users\\chgagnon\\AppData\\Local\\Programs\\Azure Data Studio - RC1\\resources\\app\\extensions\\markdown-math\\node_modules\\katex\\dist\\katex.min.css')\n    at new k (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio%20-%20RC1/resources/app/out/vs/workbench/workbench.desktop.main.js:850:18986) [<root>]\n    at Ai.doReadFileStream (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio%20-%20RC1/resources/app/out/vs/workbench/workbench.desktop.main.js:855:21993) [<root>]"
__proto__: Error
```

**Comment by chlafreniere** [comment]
@barbaravaldez can you see if you can repro this?

**Comment by barbaravaldez** [comment]
I can repro. The issue looks very similar to this other issue in vscode https://github.com/microsoft/vscode/issues/127761

**Comment by chlafreniere** [comment]
@barbaravaldez where did we land on this issue? Is it already fixed in main?

**Comment by barbaravaldez** [comment]
@chlafreniere I can still repro. There's another issue that is similar to this in vscode. i'm going to try that approach and see if it works

**Comment by chlafreniere** [comment]
@barbaravaldez what did you end up finding?

**Comment by barbaravaldez** [comment]
@chlafreniere Just found out the issue, the css file path wasn't updated

**Comment by Charles-Gagnon** [comment]
I haven't seen this since the original issue was fixed so closing for now
