### ISSUE TITLE
CMS view blank when no saved servers

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#20137]
1.37/RC1/Insiders

1. Install CMS extension
2. Make sure there are no saved extensions
3. Reload window

The CMS view is shown, but it's blank. 

![image](https://user-images.githubusercontent.com/28519865/180278309-87ba2696-edf7-4798-9cea-ab11b8f32c51.png)

Expected

![image](https://user-images.githubusercontent.com/28519865/180278538-830e6504-0dc3-4dc5-83dd-0a6795a04b35.png)

There's this error in the console 

```
  ERR O is not iterable: TypeError: O is not iterable
    at z.setChildren (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:307:21525)
    at z.doRefreshNode (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:307:20815)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async z.doRefreshSubTree (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:307:20367)
```

You can still add a server but it doesn't show up until the window is reloaded, at which point it shows up and seems to work normally.

**Comment by Charles-Gagnon** [comment]
Seems like same issue as https://github.com/microsoft/azuredatastudio/pull/20116

**Comment by alanrenmsft** [comment]
fix has been merged to release branch. closing the issue

**Comment by Charles-Gagnon** [comment]
Verified that issue no longer repros on RC1

**Comment by alanrenmsft** [comment]
yes, I did verify it.

**Comment by Charles-Gagnon** [comment]
Oh sorry, I meant that I went and verified it too just for extra confirmation 😁
