### ISSUE TITLE
Column and Index Properties not showing

### ISSUE THREAD

**Issue by WSESoft** [microsoft/azuredatastudio#20584]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

Hello Support Team,
 is this a common problem or is it fix already?

i am running..

Windows 11 Preview 25183 - 25193
Azure Data Studio Insider:

1. Connect to a local SQL Server 2019 Developer Edition
2. Open Table\Columns Menu
3. Selecting any item in Columns
4. Right click, selecting Properties

... Error Message appears as follows:

 
TITLE: Microsoft SQL Server Management Studio
------------------------------

Cannot show requested dialog.

------------------------------
ADDITIONAL INFORMATION:

Failed to retrieve data for this request. (SqlManagerUI)

For help, click: https://go.microsoft.com/fwlink?ProdName=Microsoft%20SQL%20Server&LinkId=20476

------------------------------

urn could not be resolved at level Column. (Microsoft.SqlServer.Management.Sdk.Sfc)

For help, click: https://go.microsoft.com/fwlink?ProdName=Microsoft%20SQL%20Server&LinkId=20476

------------------------------
BUTTONS:

OK
------------------------------

===================================

Cannot show requested dialog.

===================================

Failed to retrieve data for this request. (SqlManagerUI)

------------------------------
For help, click: https://go.microsoft.com/fwlink?ProdName=Microsoft%20SQL%20Server&LinkId=20476

------------------------------
Program Location:

   at Microsoft.SqlServer.Management.SqlManagerUI.ColumnPropertiesGeneral.Microsoft.SqlServer.Management.SqlMgmt.IPanelForm.OnInitialization()
   at Microsoft.SqlServer.Management.SqlMgmt.ViewSwitcherControlsManager.SetView(Int32 index, TreeNode node)
   at Microsoft.SqlServer.Management.SqlMgmt.ViewSwitcherControlsManager.SelectCurrentNode()
   at Microsoft.SqlServer.Management.SqlMgmt.ViewSwitcherControlsManager.InitializeUI(ViewSwitcherTreeView treeView, ISqlControlCollection viewsHolder, Panel rightPane)
   at Microsoft.SqlServer.Management.SqlMgmt.LaunchForm.InitializeForm(XmlDocument doc, IServiceProvider provider, ISqlControlCollection control)
   at Microsoft.SqlServer.Management.SqlMgmt.LaunchForm..ctor(XmlDocument doc, IServiceProvider provider)
   at Microsoft.SqlServer.Management.UI.VSIntegration.ObjectExplorer.ToolMenuItemHelper.OnCreateAndShowForm(IServiceProvider sp, XmlDocument doc)
   at Microsoft.SqlServer.Management.SqlMgmt.RunningFormsTable.RunningFormsTableImpl.ThreadStarter.StartThread()

===================================

urn could not be resolved at level Column. (Microsoft.SqlServer.Management.Sdk.Sfc)

------------------------------
For help, click: https://go.microsoft.com/fwlink?ProdName=Microsoft%20SQL%20Server&LinkId=20476

------------------------------
Program Location:

   at Microsoft.SqlServer.Management.Sdk.Sfc.ObjectLoadInfoManager.GetNextLevel(ObjectLoadInfo curent_oli, String s)
   at Microsoft.SqlServer.Management.Sdk.Sfc.ObjectLoadInfoManager.GetAllObjectsLoadInfo(StringCollection types)
   at Microsoft.SqlServer.Management.Sdk.Sfc.ObjectLoadInfoManager.GetAllObjectsLoadInfo(Urn urn, Object ci)
   at Microsoft.SqlServer.Management.Sdk.Sfc.ObjectCache.GetAllElements(Urn urn, ServerVersion ver, DatabaseEngineType databaseEngineType, DatabaseEngineEdition databaseEngineEdition, Object ci)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetObjectsFromCache(Urn urn, Object ci)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Environment.GetData(Request req, Object ci)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.GetData(Object connectionInfo, Request request)
   at Microsoft.SqlServer.Management.Sdk.Sfc.Enumerator.Process(Object connectionInfo, Request request)

Azure Data Studio version: azuredatastudio-insiders 1.40.0-insider (06c8e3d7a83f9c1079e1e930cbd3853418f58019, 2022-09-09T05:38:29.449Z)
OS version: Windows_NT x64 10.0.25197
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) M-5Y51 CPU @ 1.10GHz (4 x 1297)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (0.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
query-editor-boost|dre|0.4.1
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.4
agent|Mic|0.49.0
dacpac|Mic|1.10.1
import|Mic|1.5.0
powershell|ms-|2022.7.2
profiler|Mic|0.12.1
azdata-sanddance|msr|4.0.0

(1 theme extensions excluded)

</details>

**Comment by WSESoft** [comment]
This link is going nowhere:

https://go.microsoft.com/fwlink?ProdName=Microsoft%20SQL%20Server&LinkId=20476

**Comment by uaychaich** [comment]
Why is this issue close? 
Did They have a solution?
I still have this issue and i don't know how to fix.
