### ISSUE TITLE
Can't Generate Scripts on Azure SQL Server database connected via Azure AD MFA

### ISSUE THREAD

**Issue by tkdennis** [microsoft/azuredatastudio#20687]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

1. In the Connection pane, New Connection to master database a SQL Server hosted on Azure, AuthenticationType = "Azure Active Directory - Universal with MFA Support"
2. Expand databases
3. Right mouse button on selected database
4. select Generate Scripts...
Error dialog appears
TITLE: Microsoft SQL Server Management Studio
Cannot show requested dialog.
Unable to execute requested command.
Failed to connect to server sql-********-westus3.database.windows.net. (Microsoft.SqlServer.ConnectionInfo)
Cannot open server "******.com" requested by the login.  The login failed. (Microsoft SQL Server, Error: 40532)
For help, click: http://go.microsoft.com/fwlink?ProdName=Microsoft%20SQL%20Server&EvtSrc=MSSQLServer&EvtID=40532&LinkId=20476

   at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
   at Microsoft.SqlServer.Management.Common.ConnectionManager.PoolConnect()
   at Microsoft.SqlServer.Management.Common.ConnectionManager.GetServerInformation()
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.get_DatabaseEngineEdition()
   at Microsoft.SqlServer.Management.SqlScriptPublish.SqlScriptPublishModel.InitServer()
   at Microsoft.SqlServer.Management.SqlScriptPublish.SqlScriptPublishModel..ctor(SqlConnectionInfo sqlConnectionInfo, String databaseName, IScriptingOptions shellScriptingOptions)
   at Microsoft.SqlServer.Management.SqlScriptPublish.ScriptPublishWizard..ctor(XmlDocument doc, IServiceProvider site)

   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnect(WindowsIdentity impersonatedIdentity)
   at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (11.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-tool-ext-win|Mic|0.0.4
agent|Mic|0.49.0
asde-deployment|Mic|0.4.1
azcli|Mic|1.6.0
azuremonitor|Mic|0.1.4
cms|Mic|0.8.0
datavirtualization|Mic|1.12.0
import|Mic|1.5.0
managed-instance-dashboard|Mic|0.4.2
powershell|ms-|2022.7.2
profiler|Mic|0.11.0
query-history|Mic|0.4.0
schema-compare|Mic|1.16.0
sql-assessment|Mic|0.6.3
sql-dw|Mic|0.0.1
sql-prompt|Red|0.2.10
sql-search|Red|0.4.1

</details>

**Comment by Charles-Gagnon** [comment]
Confirmed this is an issue, while I investigate this here's a couple options

1. Use basic auth (seems like not an option for you specifically unfortunately, but in case others hit this)
2. Use SSMS itself - that should be working correctly
