### ISSUE TITLE
Table Designer Error - "An error occurred while initializing the table designer: Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by MrHippo85** [microsoft/azuredatastudio#20787]
Hi there

I am for some reason unable to use the Table Designer, as keep getting an "An error occurred while initializing the table designer: Object reference not set to an instance of an object" error.

Full error details:
   at Microsoft.Data.Tools.Sql.DesignServices.TableDesigner.TableDesigner..ctor(String connectionString, String accessToken, String schemaName, String tableName, Boolean isNewTable)
   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.CreateTableDesigner(TableInfo tableInfo) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 1545
   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass13_0.<<HandleInitializeTableDesignerRequest>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 87
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass12_0`1.<<HandleRequest>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 73

This seems to be happening regardless of whether I try and create a new table or edit an existing table using the Table Designer.

Version Info:
Version: 1.39.1 (user setup)
Commit: 7553f799e175f471b7590302dd65c997b838b29b
Date: 2022-08-30T01:11:13.047Z
VS Code: 1.62.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

Apologies in advance if this has been raised already - I couldn't find any duplicates when searching.

Many thanks

**Comment by alanrenmsft** [comment]
@caohai could you please follow up on this issue?

@MrHippo85 do you happen to have azure data studio insider build installed? please give it a try and see whether you are still seeing the same problem, it can be installed from here: https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main

**Comment by caohai** [comment]
@alanrenmsft Sure.
@MrHippo85 Can you share the sql server version you are using? Can you also try table designer on a different sql server and see if you still have this issue?

**Comment by MrHippo85** [comment]
Hi there @alanrenmsft / @caohai!

Thanks for getting back to me.

The SQL server version I am using is 12.0.2000.8. I have tried replicating the issue on ADS Insider and the same error message is displayed unfortunately.

I have also tried to use the Table Designer in an Azure Synapse server instance, but again, get the same message.

Many thanks for your assistance thus far - this would be a massive help if I can get this working, as it would avoid swapping between ADS and SSMS!

Cheers

**Comment by alanrenmsft** [comment]
@MrHippo85 is it an Azure SQL DB? what is the pricing tier of the database? please let us know all the information about the database (without personal/sensitive information) so that we can reproduce the issue.

**Comment by caohai** [comment]
@alanrenmsft I setup a Debian machine and did a quick test with my Azure SQL Server and couldn't repro.
![image](https://user-images.githubusercontent.com/21186993/195412990-72fcdc80-4943-4a91-baea-40213e711e9e.png)

**Comment by alanrenmsft** [comment]
@caohai Debian is for a different issue with query results exporting not with this issue.

**Comment by caohai** [comment]
> @caohai Debian is for a different issue with query results exporting not with this issue.

oops, mixed the two issues.....

**Comment by alanrenmsft** [comment]
also I just tried table designer with Azure Synapse, I was able to open table designer successfully. what is the spec for your Azure Synapse database? 

note that there is an issue with publishing changes for non-master databases: https://github.com/microsoft/azuredatastudio/issues/20839

**Comment by MrHippo85** [comment]
Hi there @alanrenmsft.

Thanks again for getting back to me.

Unfortunately, I am unable to provide the information requested, as I am using ADS within a corporate environment and do not have the required permissions to access the billing information nor spec of the databases we use in any detail. I am aware that we are on an Enterprise Agreement if this helps. I appreciate this is not very helpful!

I have had one of my colleagues try the same process and he has been able to access the Table Designer; however it took a very long time to load. I have noticed that when I try and open the Table Designer twice, the first time I get the error message I have mentioned, but the second time, I just get a "loading designer" spinning wheel. Nothing happens.

Is this a known issue? I am sure I have seen this elsewhere!

Cheers

**Comment by alanrenmsft** [comment]
@caohai could you please follow up?

**Comment by caohai** [comment]
As for the long loading time, there's one setting you can try out:
![image](https://user-images.githubusercontent.com/21186993/199800722-48bf93a8-13ac-4407-a855-c6c0cc7a7953.png)

I use a fairly low end Azure SQL Server for testing and haven't seen a similar issue...

For the error happening during opening the Table Designer **twice**, we have a fix related to initialization that might help. This fix should be merged into main today and you can either test with tomorrow's insider build or wait for this month's release.

**Comment by caohai** [comment]
Did you get a chance to try out the new version?

**Comment by ArrNNG** [comment]
Hi there,
I couldn‘t to use the Table Designer either.

<img width="642" alt="截屏2023-02-07 12 52 10" src="https://user-images.githubusercontent.com/57611350/217151436-3f51634c-bbe0-43da-b53a-8feafc6416d0.png">

Full error details:
```
at Microsoft.Data.Tools.Sql.DesignServices.TableDesigner.TableDesigner..ctor(String connectionString, String accessToken, String schemaName, String tableName, Boolean isNewTable, Int32 largeTableRowCount)
at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.CreateTableDesigner(TableInfo tableInfo) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 1800
at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass18_0.<<HandleInitializeTableDesignerRequest>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 99
--- End of stack trace from previous location ---
at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass17_0`1.<<HandleRequest>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 85
```

 Version Info:
> Version: 1.41.1
> Commit: 33dce95b152227c4f10f6251ab30690fe9895c0c
> Date: 2023-01-28T00:47:32.573Z
> VS Code: 1.67.0
> Electron: 19.1.8
> Chromium: 102.0.5005.167
> Node.js: 16.14.2
> V8: 10.2.154.15-electron.0
> OS: Darwin arm64 22.3.0

SQL Server Info:

> Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)   Aug 22 2017 17:04:49   Copyright (C) 2017 Microsoft Corporation  Express Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor)

**Comment by caohai** [comment]
> ```
> at Microsoft.Data.Tools.Sql.DesignServices.TableDesigner.TableDesigner..ctor(String connectionString, String accessToken, String schemaName, String tableName, Boolean isNewTable, Int32 largeTableRowCount)
>    at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.CreateTableDesigner(TableInfo tableInfo) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 1807
>    at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass18_0.<<HandleInitializeTableDesignerRequest>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 101
> --- End of stack trace from previous location ---
>    at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass17_0`1.<<HandleRequest>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 87
> ```
> 
> I also encounter the same problem, after checking, it seems that Azure Data Studio failed to initialize the TableDesigner class.
> 
> Error Started: https://github.com/microsoft/sqltoolsservice/blob/e63f571a7b4d0b86cc84edbf10a930cd1602cd46/src/Microsoft.SqlTools.ServiceLayer/TableDesigner/TableDesignerService.cs#L1807 Error Ended: https://github.com/microsoft/sqltoolsservice/blob/e63f571a7b4d0b86cc84edbf10a930cd1602cd46/src/Microsoft.SqlTools.ServiceLayer/TableDesigner/TableDesignerService.cs#L87
> 
> According to first line: at Microsoft.Data.Tools.Sql.DesignServices.TableDesigner.TableDesigner..ctor(String connectionString, String accessToken, String schemaName, String tableName, Boolean isNewTable, **Int32 largeTableRowCount**)
> 
> It seems that **Int32 largeTableRowCount** is not needed for the initilization.
> 
> It would be very helpful, if anyone could find the solution.

@Tao4free Is table designer loading failing consistently for you? Can you also share the version info? `largeTableRowCount` used to be an optional variable but we made some changes recently and it's no longer used.

**Comment by caohai** [comment]
> I have some useful testing on this. I tried the table designer on a database with several hundred tables. It took several minutes to load, but finally succeeded. It then took a very long time to save a new table. Succeeded, but several minutes is obviously unexpected. I then tried on another database (same server) with only 5 tables. The table designer loaded instantly. Developers, I suggest investigating if the issue might be related to number of tables or indexes, or possibly database size. It might be that the table designer function is collecting too much data, or collecting data inefficiently. Tested with on-site SQL Server 2019 with all currently available CU.

@sivan-koren Several minutes sounds a bit too long, I previously did some testing with a local db that has >1k tables (with fairly simple schema) and the publish time is ~10s. I'm wondering if the db you are having issue with has any specific objects causing this issue. It would be great if we can have a minimal reproducible example for it,

**Comment by Tao4free** [comment]
> > ```
> > at Microsoft.Data.Tools.Sql.DesignServices.TableDesigner.TableDesigner..ctor(String connectionString, String accessToken, String schemaName, String tableName, Boolean isNewTable, Int32 largeTableRowCount)
> >    at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.CreateTableDesigner(TableInfo tableInfo) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 1807
> >    at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass18_0.<<HandleInitializeTableDesignerRequest>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 101
> > --- End of stack trace from previous location ---
> >    at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass17_0`1.<<HandleRequest>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 87
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I also encounter the same problem, after checking, it seems that Azure Data Studio failed to initialize the TableDesigner class.
> > Error Started: https://github.com/microsoft/sqltoolsservice/blob/e63f571a7b4d0b86cc84edbf10a930cd1602cd46/src/Microsoft.SqlTools.ServiceLayer/TableDesigner/TableDesignerService.cs#L1807 Error Ended: https://github.com/microsoft/sqltoolsservice/blob/e63f571a7b4d0b86cc84edbf10a930cd1602cd46/src/Microsoft.SqlTools.ServiceLayer/TableDesigner/TableDesignerService.cs#L87
> > According to first line: at Microsoft.Data.Tools.Sql.DesignServices.TableDesigner.TableDesigner..ctor(String connectionString, String accessToken, String schemaName, String tableName, Boolean isNewTable, **Int32 largeTableRowCount**)
> > It seems that **Int32 largeTableRowCount** is not needed for the initilization.
> > It would be very helpful, if anyone could find the solution.
> 
> @Tao4free Is table designer loading failing consistently for you? Can you also share the version info? `largeTableRowCount` used to be an optional variable but we made some changes recently and it's no longer used.

@caohai 
Thanks for the confirm.
It still happens.
The version is latest one: 1.44.1

Error message here:
```
at Microsoft.Data.Tools.Sql.DesignServices.TableDesigner.TableDesigner..ctor(String connectionString, String accessToken, String schemaName, String tableName, Boolean isNewTable, TableDesignerOptions options)
   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.CreateTableDesigner(TableInfo tableInfo) in /_/src/Microsoft.SqlTools.ServiceLayer/TableDesigner/TableDesignerService.cs:line 1808
   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass18_0.<<HandleInitializeTableDesignerRequest>b__0>d.MoveNext() in /_/src/Microsoft.SqlTools.ServiceLayer/TableDesigner/TableDesignerService.cs:line 102
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass17_0`1.<<HandleRequest>b__0>d.MoveNext() in /_/src/Microsoft.SqlTools.ServiceLayer/TableDesigner/TableDesignerService.cs:line 88
```

**Comment by alanrenmsft** [comment]
@sivan-koren @Tao4free @ArrNNG is it possible for you guys to provide us the script to create a database that could reproduce the issue? please make sure to remove any sensitive information from the script.

**Comment by sivan-koren** [comment]
@alanrenmsft I can't share this database as it would take many months to scrub identifying information from the table and column names.

But I can offer some further findings that may be interesting, as I did script the creation of this db in various ways.
1. If indexes are not included, the table designer loads in ~5 seconds.
2. If indexes ARE included, the table designer loads in ~45 seconds.

I did not try scripting with the data.

Also, possibly interesting, on this database, some objects couldn't be recreated after scripting due to dependencies.

**Comment by jrineck** [comment]
I also am experiencing this same error
![image](https://github.com/microsoft/azuredatastudio/assets/1945389/7e3e716d-0e8d-4b64-ac65-9b444760263b)

Azure Data Studio version = 1.44.1
Database Connection to Managed Azure SQL Server DB

Trace:
` at Microsoft.Data.Tools.Sql.DesignServices.TableDesigner.TableDesigner..ctor(String connectionString, String accessToken, String schemaName, String tableName, Boolean isNewTable, Int32 largeTableRowCount)

   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.CreateTableDesigner(TableInfo tableInfo) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 1807

   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass18_0.<<HandleInitializeTableDesignerRequest>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 101

--- End of stack trace from previous location ---

   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass17_0`1.<<HandleRequest>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 87`

**Comment by Ableytner** [comment]
I also had the error **"An error occured while initializing the table designer: Failed to initialize the table model."** with the exact same Stack Trace. 

The solution for me was that I didn't have sufficient permission to create a new table. 
I only had **db_datareader** and **db_datawriter** but needed **db_owner**. After that, the error message disappeared and everything worked as expected.

**Comment by Siromani** [comment]
Here is another test what I did. I created an identical database my local machine and tried. It worked on the local but still fails to the one deployed in azure.

**Comment by rsiegel1954** [comment]
Any updates on this issue? I'm using v1.47.1 and can create and drop tables, but continue to get the  "Failed to initialize the table model" error.

**Comment by alanrenmsft** [comment]
@kisantia  @cheenamalhotra  FYI.
