### ISSUE TITLE
Hover text is broken

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#20903]
Post-merge

Hovering over functions or other T-SQL text causes a tooltip that just says "Loading..." to appear and the console is filled with these messages : 

```
mainThreadExtensionService.ts:80 Error: Message header must separate key and value using :
at c:\src\azuredatastudio\extensions\mssql\node_modules\vscode-jsonrpc\lib\messageReader.js:57:23
at Array.forEach (<anonymous>)
at MessageBuffer.tryReadHeaders (c:\src\azuredatastudio\extensions\mssql\node_modules\vscode-jsonrpc\lib\messageReader.js:54:17)
```

**Comment by Charles-Gagnon** [comment]
Closing this - it's due to the latest sqlparser I'm using locally so not an issue in ADS currently.
