### ISSUE TITLE
Cannot open Provided Books

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#20947]
Version: 1.40.0-insider (Universal)
Commit: de3683dd018b1f28744f9eb8797a825bb38d784c
Date: 2022-10-24T05:29:21.556Z
VS Code: 1.67.0
Electron: 17.4.5
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.6.0

 ERR command 'books.sqlserver2019' not found: Error: command 'books.sqlserver2019' not found
    at u._tryExecuteCommand (vscode-file://vscode-app/Applications/Azure%20Data%20Studio%20-%20Insiders-3.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2251:3529) [<root>]
    at u.executeCommand (vscode-file://vscode-app/Applications/Azure%20Data%20Studio%20-%20Insiders-3.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2251:3411) [<root>]
    at processTicksAndRejections (node:internal/process/task_queues:96:5) [<root>]
    at async k.runAction (vscode-file://vscode-app/Applications/Azure%20Data%20Studio%20-%20Insiders-3.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:352:30903) [<root>]
    at async k.run (vscode-file://vscode-app/Applications/Azure%20Data%20Studio%20-%20Insiders-3.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:352:30803) [<root>]
    at async b.runAction (vscode-file://vscode-app/Applications/Azure%20Data%20Studio%20-%20Insiders-3.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2018:15620) [<root>]

**Comment by kburtram** [comment]
@barbaravaldez I disabled downloading this as part of the build due to errors in the gulp tasks.  Let me reenable so we can see the specific error being generated.

**Comment by kburtram** [comment]
The attached PR shows the error I was hitting in the gulp scripts while downloading this pacakge https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=176290&view=logs&j=bd1e231b-cef9-51a2-e461-b67194c0a817&t=9cc46b07-0f4a-51e5-598b-b142e2b8a72a.  I recall a discussion that we may no longer need these notebooks embedded in the product long term, so may not be worth investigating if that is the case (I could be mistaken on the timeline here).

The relevant error is pasted below.

```
[extensions-ci] [16:13:19] Downloading extension: Microsoft.sqlservernotebook@0.5.0 ...
[extensions-ci] [16:13:21] The following tasks did not complete: extensions-ci
[extensions-ci] [16:13:21] Did you forget to signal async completion?
[extensions-ci] error Command failed with exit code 1.
[extensions-ci] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "extensions-ci" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
##[error]Bash exited with code '1'.
```

**Comment by kburtram** [comment]
@caohai could you please take a look to see what's going in the build scripts for the custom package download?

**Comment by barbaravaldez** [comment]
@caohai It looks like the opening Provided Books functionality is still broken on latest insiders. I'm not sure if this is only happening on macOS. Can you confirm?

**Comment by caohai** [comment]
@barbaravaldez The linked PR was only intended to fix the previously disabled extension downloading step.
I just tested the provided notebook with latest insider and the error msg is `command 'books.sqlserver2019' not found ` which I think is a separate issue.
