### ISSUE TITLE
ShowPlan XML link doesn't open execution plan editor

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#20964]
- Azure Data Studio Version: `insiders`

Steps to Reproduce:

1. Open a SQL query with some statements and run Estimated Plan command
2. Click the Show Plan XML link

Expected: Show Plan document is opened

Actual: Document opens then closes.  Below exception is raised in application log.

```
Cannot read properties of undefined (reading 'hidden'): TypeError: Cannot read properties of undefined (reading 'hidden')
    at showColumn (vscode-file://vscode-app/c:/Users/karlb/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1206:20829)
    at Object.eval [as updateDirectives] (ng:///w/s.ngfactory.js:634:24)
    at Object.updateDirectives (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12625:72)
    at checkAndUpdateView (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12151:14)
    at callViewAction (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12514:21)
```

**Comment by kburtram** [comment]
@aasimkhan30 I think this likely broke as part of the vscode refresh.  Could you please take a look?  Let me know if you don't have time and I can investigate.  Thanks!
