### ISSUE TITLE
New encrypt option defaults to true even if connection previously was saved with Encrypt = false

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#20971]
1. Open ADS stable
2. Create a connection and in the Advanced tab set Encrypt to false
3. Save the connection and exit ADS
4. Open up ADS dev/insiders (when the encrypt option change gets in insiders)
5. Edit the connection made in stable

Encrypt now shows in the main dialog area as expected, but it shows false even though encrypt is set to false in the options

![image](https://user-images.githubusercontent.com/28519865/197873755-447a7e11-cc0e-4f96-95f9-167b001c5908.png)

**Comment by jtsom** [comment]
Just had this occur to me. Installed latest insiders, never have used an "Encrypt" option, tried to connect to my local SQLEXPRESS database, which I was just connected to before the update. When I tried to connect, I received an error, the details of which are:

```
Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)
 ---> System.ComponentModel.Win32Exception (0x80090325): The certificate chain was issued by an authority that is not trusted.
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.SNIWritePacket(PacketHandle packet, UInt32& sniError, Boolean canAccumulate, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.WriteSni(Boolean canAccumulate)
   at Microsoft.Data.SqlClient.TdsParserStateObject.WritePacket(Byte flushMode, Boolean canAccumulate)
   at Microsoft.Data.SqlClient.TdsParser.TdsLogin(SqlLogin rec, FeatureExtension requestedFeatures, SessionData recoverySessionData, FederatedAuthenticationFeatureExtensionData fedAuthFeatureExtensionData, SqlConnectionEncryptOption encrypt)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.Login(ServerInfo server, TimeoutTimer timeout, String newPassword, SecureString newSecurePassword, SqlConnectionEncryptOption encrypt)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass48_0.<CreateReplaceConnectionContinuation>b__0(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass30_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 312
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 666
ClientConnectionId:85fb7641-30e0-46d1-b7a3-e3314ba0ffc0
Error Number:-2146893019,State:0,Class:20
```

**Comment by Charles-Gagnon** [comment]
@jtsom That part is intended, although we're working on how to best alert customers of these changes. 

What you're seeing is the change to default to `Encrypt = true` that was actually introduced last year in SqlClient v4 (see https://techcommunity.microsoft.com/t5/sql-server-blog/released-general-availability-of-microsoft-data-sqlclient-4-0/ba-p/2983346). We've been using v3 up to this point though, but recently updated to v5 and so got these additional changes. 

That means that for now any existing connections you have that aren't encrypted (such as to local machines for testing) you can just set the Encrypt option to false. This option has been moved to the top level of the connection dialog to make this easier : 

![image](https://user-images.githubusercontent.com/28519865/198080653-6494a986-da86-4976-ac85-be2276121b33.png)

**Comment by jtsom** [comment]
@Charles-Gagnon Thanks for the info. I think a problem is, the error dialog that pops up doesn't really say that this is the cause - it looks like more of a systemic problem:

![image](https://user-images.githubusercontent.com/13488/198081226-11a21291-9bbf-421a-bb46-700dcdedc9c1.png)

I read that and had no idea what happened. I had to come here, and luckily found this reported issue and turned off the Encrypt flag to successfully connect.

Also, this flag does not seem to persist with my "recent" connections.

**Comment by Charles-Gagnon** [comment]
Yeah, that's the part that we're discussing how to best surface to users - right now that error message is just from the engine and I agree is not the easiest to understand for many users who aren't familiar with these security features. 

The last part sounds like a bug though and not one that I can repro - if I set Encrypt=false and then connect the entry that shows up in recent connections also works fine. 

There may be multiple "duplicate" entries though from previous connections (with Encrypt not set) which would show up as Encrypt=true. If you clear the recent list and then connection from your saved connection again do you still see the issue?

**Comment by jtsom** [comment]
OK that was it, the older, duplicate connection didn't change, but the newer one was updated.

How do I update the saved connections? I tried setting to false, setting Server Group to Save to my local group - it added another entry, but didn't update the original, and I see no way to edit/delete entries.

Thanks.

**Comment by Charles-Gagnon** [comment]
If you right click on an entry in the server tree you should see "Edit Connection" - if you then change Encrypt to false in there and click Connect it should update that connection. 

(you could also delete the connection and then re-add it, making sure to specify "Encrypt=false")
