### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by gregchak** [microsoft/azuredatastudio#21174]
Issue Type: <b>Bug</b>

I don't know if its authentication in general or when the account is MFA, but I have issues where when I try to expand nodes, for example columns of a table, that I get an error saying it can't be retrieved.  Also it doesn't handle the expiration of an MFA authentication very well either.  A better example of how MFA auth should work would be Storage Explorer.  The way that works is considerably better and has a better user experience than Data Studio.  

An example error 
`Microsoft.SqlServer.Management.Common.ConnectionFailureException: Failed to connect to server {REMOVED}.
---> Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user '<token-identified principal>'. Token is expired.
at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnectImpl()
at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnect()
at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()

Error Number:18456,State:233,Class:14
--- End of inner exception stack trace ---
at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoWrapper.OpenConnection(SmoObjectBase smoObj) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoWrapper.cs:line 38
at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoQueryContext.GetObjectWithOpenedConnection[T](T smoObj) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoQueryContext.cs:line 169
at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoQueryContext.get_Database() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoQueryContext.cs:line 62
at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoQueryContext.CopyWithParent(SmoObjectBase parent) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoQueryContext.cs:line 133
at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoTreeNode.EnsureContextInitialized() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoTreeNode.cs:line 122
at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoTreeNode.GetContext() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoTreeNode.cs:line 108
at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.Nodes.TreeNode.GetContextAs[T]() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\Nodes\TreeNode.cs:line 313
at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.Nodes.TreeNode.PopulateChildren(Boolean refresh, String name, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\Nodes\TreeNode.cs:line 324
at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.Nodes.TreeNode.Expand(String name, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\Nodes\TreeNode.cs:line 250
at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.Nodes.TreeNode.Expand(CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\Nodes\TreeNode.cs:line 260
at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.ObjectExplorerService.<>c__DisplayClass35_0.<QueueExpandNodeRequest>b__0(IBindingContext bindingContext, CancellationToken cancelToken) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\ObjectExplorerService.cs:line 419
at Microsoft.SqlTools.ServiceLayer.LanguageServices.BindingQueue`1.<>c__DisplayClass34_1.<ProcessQueue>b__1() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\LanguageServices\BindingQueue.cs:line 381`

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (2.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cheenamalhotra** [comment]
Hi @gregchak 

Could you please test with the latest insiders build ([Link](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main))? We've made some improvements in this domain, do we're hopeful. Let us know if you continue to see issues, we can investigate more with you!

**Comment by gregchak** [comment]
I started using the build you recommended this morning.  Its a little more graceful but still erroring out and not refreshing my token.  I got this message when I ran my query:
```
Execution failed due to an unexpected error: 
	Failed to refresh Azure account token for connection
Total execution time: 00:00:00

```
And I got this when I tried to reconnect my query:
`Login failed for user '<token-identified principal>'. Token is expired.`

**Comment by gregchak** [comment]
Some extra info for my previous post.  It looks as if when I got that error it was because I needed to reauthenticate.  It wasn't able to refresh my token because I needed to authenticate.  I would have expected it to open my browser like it does for initial authentication when this happens. 

I do however still get the `Failed to retrieve data for this request.` issue when expanding nodes.  I'm still connected and can run queries, but I'm not able to expand nodes in the Servers window after a certain amount of time.  The only way to resolve is to disconnect and reconnect.  
![image](https://user-images.githubusercontent.com/5882933/201193440-8c347949-aea0-41a7-bd44-75296b3bd0cb.png)

**Comment by cheenamalhotra** [comment]
Thanks for the info and explanation. It looks like we might not be able to refresh access token when needed on an open connection in object explorer.

I will try to reproduce this scenario and get back to you!

**Comment by gregchak** [comment]
@cheenamalhotra is this available in the main release or still just in the insiders build?

**Comment by cheenamalhotra** [comment]
As of now in the insiders build, its targeted for January release, as in milestone.
