### ISSUE TITLE
Start up error on MacOS Ventura

### ISSUE THREAD

**Issue by bisd-mike** [microsoft/azuredatastudio#21261]
Issue Type: <b>Bug</b>

I'm tyring to get Azure Data Studio up and running on a new Macbook Pro with MacOS Ventura but I'm getting error messages on startup. They are,  "Couldn't start client SerilizationProvider", "Couldn't start client AzureResourceProvider" and "Failed to start SQL Tools Service". Another was similar but something about Server Tools not starting. Thanks, let me know if there is any other information needed.

Azure Data Studio version: azuredatastudio 1.40.0 (Universal) (3fbaa3de931ef433090fe3deb8c89cba99d7952b, 2022-11-11T22:47:49.772Z)
OS version: Darwin arm64 22.1.0
Restricted Mode: No
Preview Features: Disabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 3|
|Memory (System)|32.00GB (11.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alanrenmsft** [comment]
@bisd-mike I just tried it with same configuration as yours, but not able to reproduce the issue. please collect the logs and I can take a look.

**Comment by mattsonnhalter** [comment]
@alanrenmsft I am having the same issue. Came to the repo to see if someone else was reporting this issue as well.

I am on a new MBP M1 Pro 14" with a fresh install of macOS Ventura. I am able to reproduce the issue with the arm64 install of the latest version as well as the prior version here on Github but all of the data below and logs are from the latest version/universal version as listed below.

Version: 1.40.0 (Universal)
Commit: 3fbaa3de931ef433090fe3deb8c89cba99d7952b
Date: 2022-11-11T22:47:49.772Z
VS Code: 1.67.0
Electron: 17.4.11
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.14-electron.0
OS: Darwin arm64 22.1.0

The error messages that appear at the bottom-right of the screen appear very similar. 

- "Couldn't start client AzureResourceProvider"
- "Failed to start SQL Tools Service"
- "Couldn't start client SQL Tools Service"

The output at the bottom of the screen also shows....

"[Error - 12:42:07 AM] Starting client failed
Error: spawn Unknown system error -86
	at ChildProcess.spawn (node:internal/child_process:412:11)
	at Object.spawn (node:child_process:707:9)
	at /Applications/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/dist/main.js:2:1198775
	at processTicksAndRejections (node:internal/process/task_queues:96:5)"

Developer Tool Logs:
[console.log](https://github.com/microsoft/azuredatastudio/files/10064300/console.log)

**Comment by alanrenmsft** [comment]
@mattsonnhalter do you have the same issue if you use the Apple Silicon build?
https://github.com/microsoft/azuredatastudio#download-the-latest-azure-data-studio-release
![image](https://user-images.githubusercontent.com/13777222/203392589-3cf2e169-85bc-4a40-ac9d-e65e20c6d521.png)

**Comment by mattsonnhalter** [comment]
@alanrenmsft That worked. I used your provided link, selected the Apple Silicon version and I no longer get the errors that I was previously on startup. I tested connecting to a local SQL server instance in Docker too and everything worked. Appreciate the help. Please let me know if there's any testing etc. you'd like me to do in case it helps others.

**Comment by alanrenmsft** [comment]
@mattsonnhalter great to know, I will definitely reach out if I need help. 

@bisd-mike , I will investigate the issue and, in the meantime, please use the Apple Silicon build I mentioned above.

**Comment by TommyLeng** [comment]
<img width="1711" alt="image" src="https://user-images.githubusercontent.com/95701513/204075278-a1611a0e-1f64-41da-aeaa-9181f89b3a1e.png">

I got the same error. I am using m1 macbook pro too. The error still exists even I used the Apple Silicon build

**Comment by deejeexo** [comment]
I got the same error. M1 macbook pro [ventura]. The error still exists with universal and Apple Silicon build

**Comment by alanrenmsft** [comment]
@bisd-mike good to know, I am surprised that Rosetta 2 is not installed by default, I didn't have to do it on my m1 macbook.

**Comment by mattsonnhalter** [comment]
@alanrenmsft My understanding is Rosetta 2 only installs once you come across a piece of software that prompts it to be installed. It appears Azure Data Studio needs it but isn’t promoting for it?

**Comment by alanrenmsft** [comment]
@mattsonnhalter the ADS main app is available as native arm64 builds, but some backend services are still x64_x86 at the moment. it is on our radar to convert them to native arm64 as well.

**Comment by vignrajan** [comment]
> @alanrenmsft I am having the same issue. Came to the repo to see if someone else was reporting this issue as well.
> 
> I am on a new MBP M1 Pro 14" with a fresh install of macOS Ventura (13.0.1 22A400). I am able to reproduce the issue with the arm64 install of the latest version as well as the prior version here on Github but all of the data below and logs are from the latest version/universal version as listed below.
> 
> Version: 1.40.0 (Universal) Commit: [3fbaa3d](https://github.com/microsoft/azuredatastudio/commit/3fbaa3de931ef433090fe3deb8c89cba99d7952b) Date: 2022-11-11T22:47:49.772Z VS Code: 1.67.0 Electron: 17.4.11 Chromium: 98.0.4758.141 Node.js: 16.13.0 V8: 9.8.177.14-electron.0 OS: Darwin arm64 22.1.0
> 
> The error messages that appear at the bottom-right of the screen appear very similar.
> 
> * "Couldn't start client AzureResourceProvider"
> * "Failed to start SQL Tools Service"
> * "Couldn't start client SQL Tools Service"
> 
> The output at the bottom of the screen also shows....
> 
> "[Error - 12:42:07 AM] Starting client failed Error: spawn Unknown system error -86 at ChildProcess.spawn (node:internal/child_process:412:11) at Object.spawn (node:child_process:707:9) at /Applications/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/dist/main.js:2:1198775 at processTicksAndRejections (node:internal/process/task_queues:96:5)"
> 
> Developer Tool Logs: [console.log](https://github.com/microsoft/azuredatastudio/files/10064300/console.log)

I am getting same error while launching.

**Comment by alanrenmsft** [comment]
@vignrajan please refer to this comment:
https://github.com/microsoft/azuredatastudio/issues/21261#issuecomment-1329689643

it is documented here:
https://learn.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver16&tabs=redhat-install%2Credhat-uninstall#macos-installation

**Comment by adityamindcrew** [comment]
Hi @alanrenmsft , after running this command /usr/sbin/softwareupdate --install-rosetta --agree-to-license. getting Installing Rosetta 2 on this system is not supported. i hav e macBook Pro m1 chip. please help how can i resolve it.
