### ISSUE TITLE
Mac M1 running MS SQL on Docker, unable to connect from Azure Data Studio

### ISSUE THREAD

**Issue by dantoniazi** [microsoft/azuredatastudio#21367]
- Azure Data Studio Version: 1.40.1
- OS Version: MacOS 13.0.1 (Macbook Pro 2020, Chip Apple M1, Memory 8 GB)

Steps to Reproduce:

1. Download and install Docker Desktop for ARM (https://desktop.docker.com/mac/main/arm64/Docker.dmg)
2. Download Azure SQL Edge image (run the command: docker pull mcr.microsoft.com/azure-sql-edge)
3. Launch an instance of the image (run the command: docker run -e 'ACCEPT_EULA=1' -e 'MSSQL_SA_PASSWORD=Password123' -p 1433:1433 --name sqlserver -d mcr.microsoft.com/azure-sql-edge)
4. Once created and running properly, download Azure Data Studio for ARM (from https://go.microsoft.com/fwlink/?linkid=2215346)
5. Azure Data Studio -> New Connection -> Connection type: Microsoft SQL Server; Server: localhost; user: sa; password: Password123; Trust Server Certificate=True or False (it makes no difference)

This is the verbose log I got from Azure Data Studio:
Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - 30164676)
---> System.ComponentModel.Win32Exception (301646768): Unknown error: 301646768
at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at Microsoft.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boolean callerHasConnectionLock, Boolean asyncClose)
at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
at Microsoft.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
at Microsoft.Data.SqlClient.TdsParser.ConsumePreLoginHandshake(SqlConnectionEncryptOption encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean& marsCapable, Boolean& fedAuthRequired, Boolean tlsFirst)
at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, SqlConnectionString connectionOptions, Boolean withFailover)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
at Microsoft.Data.ProviderBase.DbConnectionFactory.<>c_DisplayClass48_0.<CreateReplaceConnectionContinuation>b0(Task`1 )
at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c_DisplayClass30_0.<<OpenAsync>b_0>d.MoveNext() in D:\a_work\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 316
--- End of stack trace from previous location ---
at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 709
ClientConnectionId:4d442c18-293e-4f3e-89ca-1fe78fc5b897
Error Number:301646768,State:0,Class:20

I tried “Trust Server Certificate=True” and the same error occurred. Besides, I also tried exactly the same steps on a Macbook Intel and everything worked like a charm. I got those errors just on Macbook M1.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by cheenamalhotra** [comment]
@dantoniazi 

Can you also try to set 'Encrypt' to 'false' to find out if this is related to any missing encryption support in Azure SQL Edge on Mac M1?

**Comment by dzsquared** [comment]
@cheenamalhotra - I've not had any issues connecting to Edge with encryption and trusting server certificate, including when trying to the repro steps from @dantoniazi - I'm puzzled

**Comment by dantoniazi** [comment]
> find out if this is re

Hi, 
I tried “Encrypt=False” but the error persists :(

**Comment by cheenamalhotra** [comment]
Closing this as external

**Comment by Veroh13** [comment]
@dantoniazi if you were not able to solve, here is a suggestion, maybe the ms-sql-server was not running in the docker. You have to check it's status before trying to connect with Azure.
