### ISSUE TITLE
Failed to get token error using AAD to connect to Azure SQL DB

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#21371]
- Azure Data Studio Version: `insiders`
- OS Version:

Steps to Reproduce:

1. Add an Azure Account
2. Try to connect to a SQL DB where account is configured as AAD Admin

Expected: Successful connection

Actual: "Error: Failed to get token" error is shown.

![image](https://user-images.githubusercontent.com/599935/206284653-bd781c6c-9e4e-4103-b277-74e5815003bb.png)

```
 WARN Connection providers incorrectly registered. Defaulting to SQL Azure resource,
log.ts:313   ERR Error: Failed to get token
	at t.AzureAccountProvider._getAccountSecurityToken (c:\Users\karlb\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\azurecore\dist\extension.js:2:519215)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by kburtram** [comment]
I'll take a look if this is related to the recent AAD metadata change I made or the MSAL update.

**Comment by kburtram** [comment]
I can repro this on build for `e89341f6bd2482931c1c029aa00e758f4fafa67e` which is prior to my AAD metadata update.  @cssuh could you please take a look or let me know if you need additional info to repro?

**Comment by kburtram** [comment]
This appears to be the key error from the log.

> [Error]: Failed to acquireTokenSilent - [{"errorCode":"invalid_request","errorMessage":"900023 - [2022-12-07 20:19:34Z]: AADSTS900023: Specified tenant identifier 'undefined' is neither a valid DNS name, nor a valid external domain.\r\nTrace ID: b20321e3-f272-47ad-bf70-40b9f6dd9100\r\nCorrelation ID: 277766bc-9f5c-49c9-a938-bd6a4217d0af\r\nTimestamp: 2022-12-07 20:19:34Z - Correlation ID: 277766bc-9f5c-49c9-a938-bd6a4217d0af - Trace ID: b20321e3-f272-47ad-bf70-40b9f6dd9100","subError":"","name":"ServerError"}]
> [Error]: Failed to silently acquire token, not InteractionRequiredAuthError - []
> [Error]: MSAL: getToken call failed - []

**Comment by cheenamalhotra** [comment]
It seems that tenant Id is not arriving with the token claims response payload which should is unexpected, as it should be present as documented: [Payload Claims](https://learn.microsoft.com/en-us/azure/active-directory/develop/id-tokens#payload-claims), would need more logs with both ADAL and MSAL individually so we can compare and find out what might be going on.

Added more logging to this branch: https://github.com/microsoft/azuredatastudio/tree/cheena/add-azure-logs

**Comment by cheenamalhotra** [comment]
I figured it's safe to fallback to 'common' tenant if tenant Id is not available from Token Claims, instead of randomly picking tenant as before. PR #21388 should address the issue.

**Comment by kburtram** [comment]
I'm still hitting this in main so I'll reopen until we investigate new logs.

**Comment by jchowbluekc** [comment]
I am also experiencing issues getting connected via AAD (with MFA) and i caught some errors in the dev console i would like to share.  I installed the insider version and in the "Connection details" i saw an option for "Refresh account credentials" but clicking it produces no effect.  
Version: 1.41.0-insider (user setup)
Commit: a4db7309afdda49c4fda178ed9f0d6657bca5115
Date: 2022-12-15T16:30:53.847Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044

Steps:
- Open Azure Data Studio
- Click on Help -> Toggle Developer Tools in toolbar
- Click "Create a connection"
- Enter server name
- Click Account drop down
- Click "Refresh account credentials"

Dev Console Logs Below:
` ERR Unexpected error populating initial Azure Account options : TypeError: Cannot read properties of undefined (reading 'map')
log.ts:313   ERR Unexpected error populating Azure Account dropdown : TypeError: Cannot read properties of undefined (reading 'map')
log.ts:313   ERR Unexpected error populating initial Azure Account options : TypeError: Cannot read properties of undefined (reading 'map')
bootstrap-window.js:259 [uncaught exception]: Error: ListError [SelectBoxCustom] Invalid index 0
b @ bootstrap-window.js:259
(anonymous) @ bootstrap-window.js:52
emit @ node:events:526
window.onerror @ node:electron/js2c/renderer_init:73
c.globals.onerror @ errorTelemetry.ts:20
bootstrap-window.js:262 Error: ListError [SelectBoxCustom] Invalid index 0
    at new c (list.ts:110:3) [<root>]
    at Q.setSelection (listWidget.ts:1529:11) [<root>]
    at o.setOptionsList (selectBoxCustom.ts:296:21) [<root>]
    at o.showSelectDropDown (selectBoxCustom.ts:471:8) [<root>]
    at HTMLSelectElement.<anonymous> (selectBoxCustom.ts:215:10) [<root>]
    at ZoneTask.invokeTask [as invoke] (C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:525:38) [<root>]
    at invokeTask (C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1727:22) [<root>]
    at globalCallback (C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1758:31) [<root>]
    at HTMLSelectElement.globalZoneAwareCallback (C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1794:20) [<root>]
b @ bootstrap-window.js:262
(anonymous) @ bootstrap-window.js:52
emit @ node:events:526
window.onerror @ node:electron/js2c/renderer_init:73
c.globals.onerror @ errorTelemetry.ts:20
C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1777 Uncaught c {originalStack: 'Error: ListError [SelectBoxCustom] Invalid index 0…p\\node_modules.asar\\zone.js\\dist\\zone.js:1794:20)', zoneAwareStack: 'Error: ListError [SelectBoxCustom] Invalid index 0…dules.asar\\zone.js\\dist\\zone.js:1794:20) [<root>]', stack: 'Error: ListError [SelectBoxCustom] Invalid index 0…dules.asar\\zone.js\\dist\\zone.js:1794:20) [<root>]', message: 'ListError [SelectBoxCustom] Invalid index 0'}
globalCallback @ C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1777
globalZoneAwareCallback @ C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1794
log.ts:313   ERR Cannot read properties of undefined (reading 'find'): TypeError: Cannot read properties of undefined (reading 'find')
    at HTMLAnchorElement.<anonymous> (vscode-file://vscode-app/c:/Users/chowj/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4019:90621)
    at _ZoneDelegate.invokeTask (C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:443:35)
    at Zone.runTask (C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:214:51)
    at ZoneTask.invokeTask [as invoke] (C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:525:38)
    at invokeTask (C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1727:22)
    at globalCallback (C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1758:31)
    at HTMLAnchorElement.globalZoneAwareCallback (C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1794:20)`
    
I tried to attach a copy of renderer1.log.  hope it attached.
[renderer1-clean.log](https://github.com/microsoft/azuredatastudio/files/10239893/renderer1-clean.log)

**Comment by cheenamalhotra** [comment]
Hi @jchowbluekc 

I've opened a new issue #21422 for investigating 'Refresh Account Credentials' behavior issues.

**Comment by cheenamalhotra** [comment]
Closing this as fixed and verified.

**Comment by peterbud** [comment]
I still experience this error, when I have only one tenant/subscription for the account (For acocunts with multiple subscriptions it works fine). I see the following in the log:
```
[renderer1] [error] fillInConnectionInputs : Could not find tenant with ID undefined for account XXX-XXX
[renderer1] [error] onAzureTenantSelected : Tenant list not found as expected, missing tenant on index -1
[renderer1] [error] fillInConnectionInputs : Could not find tenant with ID undefined for account XXX-XXX
[renderer1] [error] onAzureTenantSelected : Tenant list not found as expected, missing tenant on index -1
[renderer1] [warning] Connection providers incorrectly registered. Defaulting to SQL Azure resource,
[renderer1] [warning] Connection providers incorrectly registered. Defaulting to SQL Azure resource,
[renderer1] [error] Error: Failed to get token
```

Also interestingly enough, if I go to the Connections/AZURE expand the subsription, I can see the Azure SQL server, and I can connect to the database.

**Comment by cdunn1331** [comment]
Hi there,

I have a user getting the same error that @kburtram originally posted. Here is the Azure log:

[Error]: Failed to acquireTokenSilent - [{"errorCode":"endpoints_resolution_error","errorMessage":"Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.","subError":"","name":"ClientAuthError","correlationId":"f9753264-378c-41ac-b4a0-93bd345a1444"}]
[Error]: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter. - []
[Error]: Failed to silently acquire token, not InteractionRequiredAuthError - []
[Error]: MSAL: getToken call failed - []
[Error]: Failed to acquireTokenSilent - [{"errorCode":"endpoints_resolution_error","errorMessage":"Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.","subError":"","name":"ClientAuthError","correlationId":"1a3e572e-9476-4cfd-aacd-2b1003cf1319"}]
[Error]: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter. - []
[Error]: Failed to silently acquire token, not InteractionRequiredAuthError - []
[Error]: MSAL: getToken call failed - []
[Error]: Failed to acquireTokenSilent - [{"errorCode":"endpoints_resolution_error","errorMessage":"Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.","subError":"","name":"ClientAuthError","correlationId":"7c53f8a4-eb1c-4e70-a96d-7cf2bc50d91a"}]
[Error]: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter. - []
[Error]: Failed to silently acquire token, not InteractionRequiredAuthError - []
[Error]: MSAL: getToken call failed - []
[Error]: Failed to acquireTokenSilent - [{"errorCode":"endpoints_resolution_error","errorMessage":"Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.","subError":"","name":"ClientAuthError","correlationId":"de044672-a83f-4eb9-a87b-c3e30650cb89"}]
[Error]: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter. - []
[Error]: Failed to silently acquire token, not InteractionRequiredAuthError - []
[Error]: MSAL: getToken call failed - []
