### ISSUE TITLE
table designer error on Ledger table

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#21401]
Version: 1.40.1
Commit: 3a32679ab590c1023ab4de6f191769e7e127d25b
Date: 2022-11-22T18:22:25.529Z
VS Code: 1.67.0
Electron: 17.4.11
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.14-electron.0
OS: Darwin arm64 22.2.0

Steps to Reproduce:

1. Create Ledger table in database via T-SQL (script below)
2. Try to open table in Designer 

Does this issue occur when all extensions are disabled?: Yes/No

![image](https://user-images.githubusercontent.com/12227241/207083800-1822c342-dd30-43dc-8cae-f26553cf17ba.png)

```
   at Microsoft.SqlTools.ServiceLayer.TableDesigner.EnumUtil`1.GetName(T enumValue) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\EnumUtils.cs:line 34
   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.GetTableViewModel(TableInfo tableInfo) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 922
   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass18_0.<<HandleInitializeTableDesignerRequest>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 99
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass17_0`1.<<HandleRequest>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 85
```

**Comment by alanrenmsft** [comment]
@caohai as per the discussion with the ledger table team, we need to be able to open the table designer and it should be treated just like a normal table, new ledger features will not be exposed in table designer.

**Comment by caohai** [comment]
> @caohai as per the discussion with the ledger table team, we need to be able to open the table designer and it should be treated just like a normal table, new ledger features will not be exposed in table designer.

@alanrenmsft  sounds good I'll take a look this week.

**Comment by alanrenmsft** [comment]
@caohai any reason not to close this issue?
