### ISSUE TITLE
"Refresh account credentials" produces no effect in Connection Details pane

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#21422]
I am experiencing issues getting connected via AAD (with MFA) and i caught some errors in the dev console i would like to share.  I installed the insider version and in the "Connection details" i saw an option for "Refresh account credentials" but clicking it produces no effect.  

Version: 1.41.0-insider (user setup)
Commit: a4db7309afdda49c4fda178ed9f0d6657bca5115
Date: 2022-12-15T16:30:53.847Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044

Steps:
- Open Azure Data Studio
- Click on Help -> Toggle Developer Tools in toolbar
- Click "Create a connection"
- Enter server name
- Click Account drop down
- Click "Refresh account credentials"

Dev Console Logs Below:
` ERR Unexpected error populating initial Azure Account options : TypeError: Cannot read properties of undefined (reading 'map')
log.ts:313   ERR Unexpected error populating Azure Account dropdown : TypeError: Cannot read properties of undefined (reading 'map')
log.ts:313   ERR Unexpected error populating initial Azure Account options : TypeError: Cannot read properties of undefined (reading 'map')
bootstrap-window.js:259 [uncaught exception]: Error: ListError [SelectBoxCustom] Invalid index 0
b @ bootstrap-window.js:259
(anonymous) @ bootstrap-window.js:52
emit @ node:events:526
window.onerror @ node:electron/js2c/renderer_init:73
c.globals.onerror @ errorTelemetry.ts:20
bootstrap-window.js:262 Error: ListError [SelectBoxCustom] Invalid index 0
    at new c (list.ts:110:3) [<root>]
    at Q.setSelection (listWidget.ts:1529:11) [<root>]
    at o.setOptionsList (selectBoxCustom.ts:296:21) [<root>]
    at o.showSelectDropDown (selectBoxCustom.ts:471:8) [<root>]
    at HTMLSelectElement.<anonymous> (selectBoxCustom.ts:215:10) [<root>]
    at ZoneTask.invokeTask [as invoke] (C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:525:38) [<root>]
    at invokeTask (C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1727:22) [<root>]
    at globalCallback (C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1758:31) [<root>]
    at HTMLSelectElement.globalZoneAwareCallback (C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1794:20) [<root>]
b @ bootstrap-window.js:262
(anonymous) @ bootstrap-window.js:52
emit @ node:events:526
window.onerror @ node:electron/js2c/renderer_init:73
c.globals.onerror @ errorTelemetry.ts:20
C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1777 Uncaught c {originalStack: 'Error: ListError [SelectBoxCustom] Invalid index 0…p\\node_modules.asar\\zone.js\\dist\\zone.js:1794:20)', zoneAwareStack: 'Error: ListError [SelectBoxCustom] Invalid index 0…dules.asar\\zone.js\\dist\\zone.js:1794:20) [<root>]', stack: 'Error: ListError [SelectBoxCustom] Invalid index 0…dules.asar\\zone.js\\dist\\zone.js:1794:20) [<root>]', message: 'ListError [SelectBoxCustom] Invalid index 0'}
globalCallback @ C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1777
globalZoneAwareCallback @ C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1794
log.ts:313   ERR Cannot read properties of undefined (reading 'find'): TypeError: Cannot read properties of undefined (reading 'find')
    at HTMLAnchorElement.<anonymous> (vscode-file://vscode-app/c:/Users/chowj/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4019:90621)
    at _ZoneDelegate.invokeTask (C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:443:35)
    at Zone.runTask (C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:214:51)
    at ZoneTask.invokeTask [as invoke] (C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:525:38)
    at invokeTask (C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1727:22)
    at globalCallback (C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1758:31)
    at HTMLAnchorElement.globalZoneAwareCallback (C:\Users\chowj\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1794:20)`
    
I tried to attach a copy of renderer1.log.  hope it attached.
[renderer1-clean.log](https://github.com/microsoft/azuredatastudio/files/10239893/renderer1-clean.log)

_Originally posted by @jchowbluekc in https://github.com/microsoft/azuredatastudio/issues/21371#issuecomment-1353573856_

**Comment by cheenamalhotra** [comment]
Hi @jchowbluekc

Could you please update and test with the latest [insiders](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) build and let me know if this issue is resolved for you?

**Comment by jchowbluekc** [comment]
> Hi @jchowbluekc
> 
> Could you please update and test with the latest [insiders](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) build and let me know if this issue is resolved for you?

Thank you Cheena, i downloaded and installed the insider build from the link you provided. 
Unfortunately, i get the same result.
I will attach the renderer1.log and dev console output.

Version: 1.41.0-insider (user setup)
Commit: 112de46723e16423c251ac1b0543729ade744d05
Date: 2022-12-16T06:28:44.496Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
[dev-console-logs.txt](https://github.com/microsoft/azuredatastudio/files/10249581/dev-console-logs.txt)
[renderer1.clean.log](https://github.com/microsoft/azuredatastudio/files/10249582/renderer1.clean.log)

**Comment by cheenamalhotra** [comment]
Could you also please gather Azure logs?

**Comment by jchowbluekc** [comment]
I don't see an option of `Verbose` for log level
![image](https://user-images.githubusercontent.com/42943843/208435564-1891153b-5fbe-40e2-98e4-adeac14e0547.png)
Currently i have the log level set to `Trace`

**Comment by jchowbluekc** [comment]
also i do not see an "Azure Accounts.log" file in the output_logging_... dir
![image](https://user-images.githubusercontent.com/42943843/208464021-770bdd58-fbe5-4f7b-8e73-9531c209e484.png)

**Comment by jchowbluekc** [comment]
I updated Sql Server Management Studio to latest and I am able to connect using AAD with MFA, but I will keep trying with Azure Data Studio and update this thread

**Comment by cheenamalhotra** [comment]
@jchowbluekc 
You need to configure this in 'Settings': 

![image](https://user-images.githubusercontent.com/13396919/208485162-0e5acf31-7d56-4117-b2d8-3f55f88c2f0d.png)

Also please restart ADS once you modify the setting.
Thanks

**Comment by cheenamalhotra** [comment]
That is strange, Azure core extension is included with ADS, so it should not be missing..

Can you confirm you see the Azure core extension in this path?
C:\Users\<>\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\azurecore

If not, can you try re-installing ADS insiders?

**Comment by Charles-Gagnon** [comment]
Also check that it hasn't been disabled by accident - type `@builtin` in the search bar of the extension gallery view and see if it shows up there.

![image](https://user-images.githubusercontent.com/28519865/208748945-5de91d2e-a47b-4174-95b8-e21739f65abe.png)

**Comment by jchowbluekc** [comment]
weirdly the insider build i have installed doesn't show that extension.  I don't even see a category for features.
![image](https://user-images.githubusercontent.com/42943843/208776929-8250cd6e-1ac0-4166-b61b-e79635dc0f12.png)

**Comment by jchowbluekc** [comment]
> weirdly the insider build i have installed doesn't show that extension. I don't even see a category for features. ![image](https://user-images.githubusercontent.com/42943843/208776929-8250cd6e-1ac0-4166-b61b-e79635dc0f12.png)

scratch that.  i didn't see the @builtin filter

**Comment by Charles-Gagnon** [comment]
Yeah, builtin extensions won't show up unless you specifically type in `@builtin` in the search bar. 

Do you see it after doing that?

**Comment by jchowbluekc** [comment]
ok, that feature was disabled.  i have enabled it and was prompted to add an account.  
I still get rejected, but progress is progress.  I will install the current stable Azure Data Studio and check for that.

`Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user '<token-identified principal>'. The server is not currently configured to accept this token.
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass48_0.<CreateReplaceConnectionContinuation>b__0(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass30_0.<<OpenAsync>b__0>d.MoveNext() in /_/src/Microsoft.SqlTools.ManagedBatchParser/ReliableConnection/ReliableSqlConnection.cs:line 312
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 674
ClientConnectionId:6f2a8fef-f9f4-4fd7-8f2e-0fee57a82ca6
Error Number:18456,State:235,Class:14`

**Comment by jchowbluekc** [comment]
that was it.  thank you all for your help.
I re-installed current stable, checked that plugin is enabled, and was able to auth and connect.
Please mark this as resolved

**Comment by cheenamalhotra** [comment]
Closing as resolved, thanks @Charles-Gagnon for chiming in :)
