### ISSUE TITLE
dotnet Interactive notebooks effectively broken

### ISSUE THREAD

**Issue by clumnah** [microsoft/azuredatastudio#21435]
Issue Type: <b>Bug</b>

I have a few dotnet notebooks that i have run successfully in the past. Recently, I have upgraded ADS and VS Code. I am seeing issues on both macos ventura and Windows 11. 
On Windows 11, some notebooks open into a white screen. If I try to create a new notebook, i can add code blocks, but when i do, they seem to run indefinitely without anything happening. 
For instance, i created a new notebook and using a C# code cell, ran
SELECT @@SERVERNAME
I understand that this is TSQL and will not work in C#. I have also run it in a SQL code cell. In either case, it never finishes. I expect to get a message back about having to use the SQL Magic commands to create a connection. 

This Windows 11 VM is a brand new build as of today. 

Azure Data Studio version: azuredatastudio 1.40.1 (3a32679ab590c1023ab4de6f191769e7e127d25b, 2022-11-22T18:30:25.850Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (4 x 1997)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.98GB (2.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.4
agent|Mic|0.49.0
dacpac|Mic|1.11.0
import|Mic|1.5.4
profiler|Mic|0.11.0
dotnet-interactive-vscode|ms-|1.0.3504060
jupyter|ms-|2022.4.1021342353

</details>

**Comment by chlafreniere** [comment]
@corivera is this a known issue?

**Comment by corivera** [comment]
@clumnah Do you see the same issues when running the same steps in VS Code?

**Comment by corivera** [comment]
@chlafreniere No, this is the first I've heard of this issue.

**Comment by clumnah** [comment]
Negative. When i open the same notebook in VSCode, it opens fine. I do have other issues regarding the extention, which i reported, but I was asked to report it to a different project.

**Comment by clumnah** [comment]
When I open the same notebook on windows 11, Azure Data Studio opens the notebook to a blank screen. In vscode, the notebook opens fine. When I do the next steps, 

This runs fine
`#r "nuget:Microsoft.DotNet.Interactive.SqlServer,*-*"`

When I run this statement, it fails 
`#!connect mssql --kernel-name TPCCDemo "Persist Security Info=False; Integrated Security=true; Initial Catalog=tpcc_2000gb; Server=server.domain.com;"`
Error: System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'MicrosoftSqlToolsServiceLayer' with working directory 'c:\Users\chris.lumnah\Downloads\Rubrik Demos\Object Level Recovery'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Microsoft.DotNet.Interactive.SqlServer.ToolsServiceClient.StartSqlToolsService()
   at Microsoft.DotNet.Interactive.SqlServer.ToolsServiceClient.Initialize()
   at Microsoft.DotNet.Interactive.SqlServer.ToolsServiceKernel..ctor(String name, ToolsServiceClient client, String languageName)
   at Microsoft.DotNet.Interactive.SqlServer.MsSqlKernel..ctor(String name, String connectionString, ToolsServiceClient client)
   at Microsoft.DotNet.Interactive.SqlServer.MsSqlKernelConnector.CreateKernelAsync(String kernelName)
   at Microsoft.DotNet.Interactive.SqlServer.ConnectMsSqlCommand.ConnectKernelAsync(KernelInvocationContext context, InvocationContext commandLineContext)
   at Microsoft.DotNet.Interactive.CompositeKernel.<>c__DisplayClass26_0.<<AddKernelConnector>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 329
--- End of stack trace from previous location ---
   at System.CommandLine.NamingConventionBinder.CommandHandler.GetExitCodeAsync(Object returnValue, InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<AddMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.InvocationPipeline.<InvokeAsync>g__FullInvocationChainAsync|2_0(InvocationContext context)
   at System.CommandLine.Parsing.ParseResultExtensions.InvokeAsync(ParseResult parseResult, IConsole console)
   at Microsoft.DotNet.Interactive.Commands.DirectiveCommand.InvokeAsync(KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Commands\DirectiveCommand.cs:line 34
   at Microsoft.DotNet.Interactive.Kernel.HandleAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 325
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 60
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 75
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensions(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 130
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 73
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 41

**Comment by corivera** [comment]
Closing this issue since we discontinued support for the Interactive extension a while back.
