### ISSUE TITLE
Starting Client Failed

### ISSUE THREAD

**Issue by coltonhurst** [microsoft/azuredatastudio#21442]
### Error: Starting Client Failed

- Azure Data Studio Version: 1.40.1
- OS Version: Darwin arm64 22.2.0 (Mac OS Ventura 13.1 on Apple M1 Max)

Steps to Reproduce:

1. Fresh install of Mac OS Ventura (I just happened to run into this bug on a fresh copy)
2. Download .NET Core 7 SDK
3. Download .NET Core 6 SDK
4. Download latest version of Azure Data Studio
5. Run

### The Issue

There are two main issues preventing me from using Azure Data Studio

1. I'm getting an error saying the "starting client failed" with various errors popping up.
2. I am unable to connect to a local running instance of SQL Server. When running SQL Server in docker locally, I'm able to connect via another application (DBeaver) but not with Azure Data Studio... when adding the connection, the connection spinner spins endlessly.

### Extra Info

When running `dotnet --list-sdks` this is the output:
```
7.0.404 [/usr/local/share/dotnet/sdk]
8.0.101 [/usr/local/share/dotnet/sdk]
```

When running Azure Data Studio, this is the output shown (with screenshot):

```
[Error - 1:20:09 PM] Starting client failed
Error: spawn Unknown system error -86
	at ChildProcess.spawn (node:internal/child_process:412:11)
	at Object.spawn (node:child_process:707:9)
	at /Applications/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/dist/main.js:2:1198775
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

<img width="720" alt="1" src="https://user-images.githubusercontent.com/5691612/208256889-94efd4f2-a971-4339-9353-dd9333fcab1b.png">

When running Azure Data Studio (latest insiders version), this is the output shown (with screenshot):

```
[Error - 1:36:03 PM] Starting client failed
Error: spawn Unknown system error -86
	at ChildProcess.spawn (node:internal/child_process:413:11)
	at Object.spawn (node:child_process:709:9)
	at /Users/coltonhurst/Downloads/Azure Data Studio - Insiders.app/Contents/Resources/app/extensions/mssql/dist/main.js:2:665290
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

<img width="1042" alt="2" src="https://user-images.githubusercontent.com/5691612/208256878-65b4fd60-74e6-435f-884b-e6e63d9e0e62.png">

This is the output in the dev tools window after attempting to connect to a local runnning SQL Server instance (Using Azure Data studio, not the insiders edition). The spinner loads forever and no connection is made:

```
log.ts:301  INFO Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:127.0.0.1|user:sa|group:C777F06B-202E-4480-B475-FA416154D458
log.ts:301  INFO Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:127.0.0.1|user:sa|group:C777F06B-202E-4480-B475-FA416154D458
log.ts:301  INFO Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:127.0.0.1|user:sa|group:C777F06B-202E-4480-B475-FA416154D458
```

This is the output in the dev tools window after immediately starting the application (Using Azure Data studio, not the insiders edition):

```
css/common.css:1          Failed to load resource: net::ERR_FILE_NOT_FOUND
console.ts:137 [Extension Host] Initialized Azure account extension storage.
console.ts:137 [Extension Host] logFile for MicrosoftSqlToolsServiceLayer is /Users/coltonhurst/Library/Application Support/azuredatastudio/logs/20221217T135117/exthost1/Microsoft.mssql/sqltools.log
console.ts:137 [Extension Host] This process (ui Extension Host) is pid: 15144
console.ts:137 [Extension Host] Old log files deletion report: {}
console.ts:137 [Extension Host] [Error - 1:51:18 PM] Starting client failed
console.ts:137 [Extension Host] Error: spawn Unknown system error -86	at ChildProcess.spawn (node:internal/child_process:412:11)	at Object.spawn (node:child_process:707:9)	at /Applications/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/dist/main.js:2:1198775	at processTicksAndRejections (node:internal/process/task_queues:96:5)
notificationsAlerts.ts:42 Couldn't start client SQL Tools Service
onDidChangeNotification @ notificationsAlerts.ts:42
notificationsAlerts.ts:42 Failed to start SQL Tools Service
onDidChangeNotification @ notificationsAlerts.ts:42
mainThreadExtensionService.ts:111 Activating extension 'Microsoft.mssql' failed: spawn Unknown system error -86.
$onExtensionActivationError @ mainThreadExtensionService.ts:111
console.ts:137 [Extension Host] logFile for SqlToolsResourceProviderService is /Users/coltonhurst/Library/Application Support/azuredatastudio/logs/20221217T135117/exthost1/Microsoft.mssql/resourceprovider.log
console.ts:137 [Extension Host] This process (ui Extension Host) is pid: 15144
console.ts:137 [Extension Host] Old log files deletion report: {}
notificationsAlerts.ts:42 Couldn't start client AzureResourceProvider
onDidChangeNotification @ notificationsAlerts.ts:42
console.ts:137 [Extension Host] logFile for MicrosoftSqlToolsCredentials is /Users/coltonhurst/Library/Application Support/azuredatastudio/logs/20221217T135117/exthost1/Microsoft.mssql/credentialstore.log
console.ts:137 [Extension Host] This process (ui Extension Host) is pid: 15144
console.ts:137 [Extension Host] Old log files deletion report: {}
notificationsAlerts.ts:42 Couldn't start client SerilizationProvider
onDidChangeNotification @ notificationsAlerts.ts:42
log.ts:313   ERR An unknown error occurred. Please consult the log for more details.
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: spawn Unknown system error -86
b @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: spawn Unknown system error -86	at ChildProcess.spawn (node:internal/child_process:412:11)	at Object.spawn (node:child_process:707:9)	at /Applications/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/dist/main.js:2:1198775	at processTicksAndRejections (node:internal/process/task_queues:96:5)
b @ console.ts:137
mainThreadExtensionService.ts:79 [[object Object]]spawn Unknown system error -86
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
mainThreadExtensionService.ts:80 Error: spawn Unknown system error -86
	at ChildProcess.spawn (node:internal/child_process:412:11)
	at Object.spawn (node:child_process:707:9)
	at /Applications/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/dist/main.js:2:1198775
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:80
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: spawn Unknown system error -86
b @ console.ts:137
console.ts:137 [Extension Host] stack trace: Error: spawn Unknown system error -86	at ChildProcess.spawn (node:internal/child_process:412:11)	at Object.spawn (node:child_process:707:9)	at /Applications/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/dist/main.js:2:1198775	at processTicksAndRejections (node:internal/process/task_queues:96:5)
b @ console.ts:137
mainThreadExtensionService.ts:79 [[object Object]]spawn Unknown system error -86
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
mainThreadExtensionService.ts:80 Error: spawn Unknown system error -86
	at ChildProcess.spawn (node:internal/child_process:412:11)
	at Object.spawn (node:child_process:707:9)
	at /Applications/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/dist/main.js:2:1198775
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:80
```

Does this issue occur when all extensions are disabled?: Yes/No

(How do you suggest adding `azuredatastudio` as a command to my local path? Currently `azuredatastudio` is not recognized via the terminal.)

```
zsh: command not found: azuredatastudio
```

**Comment by alanrenmsft** [comment]
@coltonhurst for the `Starting Client Failed` issue, please refer to https://github.com/microsoft/azuredatastudio/issues/21261#issuecomment-1329689643, the requirement is also listed [here](https://learn.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver16#macos-installation)

the second issue might be caused by the first one, once the service is running, you should be able to connect.

**Comment by coltonhurst** [comment]
Perfect, thanks @alanrenmsft!
