### ISSUE TITLE
Azure Data Studio dropping db / server connections

### ISSUE THREAD

**Issue by agentwalker** [microsoft/azuredatastudio#21482]
- Azure Data Studio Version: 1.40.1
- OS Version: Windows 11

Steps to Reproduce:

1. Connect to a server 
2.Open up a query window for one of the db's on that server
3. leave the query window open for a length of time 15 > 30 mins
4. Attempt to re-run the query  - The query will not execute as the connection to to the db/server has dropped
5. Attempt to open a new query window - The window opens up no db's are listed at the top
6. waiting 30 seconds or so eventually reconnects 

Is there a setting somewhere thats forcing it to drop / sleep the connections when there's no activity for a period of time?

Does this issue occur when all extensions are disabled?: Yes

**Comment by kburtram** [comment]
The query editor connections are configured to send TCP KeepAlive messages on an idle connection, which should prevent the server from cleaning up the inactive connection.  There isn't anything on the client-side that would initiate a disconnect in this scenario.  If the computer hibernates then the KeepAlive messages won't be sent in which case the server could close the inactive connection.  

Do you know which type of server you're connecting to?  You can get this info by running `SELECT @@VERSION`, for example.  This could be helpful for us to repro the issue.

**Comment by agentwalker** [comment]
Thanks for the reply.

The SQL version is:  2016 SP2 13.0.5026

**Comment by kenvanhyning** [comment]
What auth type are you connecting to the server with?

**Comment by cheenamalhotra** [comment]
I tested below steps to mock user scenario:

1. Connect to SQL Server on-premise (connected via VPN) - as user is using SQL 2016 SP2
2. Run multiple queries.
3. Drop VPN connection - force disconnect from backend.
4. Reconnect VPN
5. Rerun queries, switch database, Ctrl + N to open a new query window

Everything worked fine for me, and ADS was able to reconnect connections.

@agentwalker 
Can you mention exact sequence that you took in order to reproduce the issue, if you were to force server disconnect by dropping network connection? Also can you try the same steps as I mentioned above to see if that works as expected or reproduces any issue at your end?

**Comment by agentwalker** [comment]
Thanks guys for the reply.

Just doing some more testing to make down the steps.

Tried opening the query window and leaving our for 30 mins, all was fine.

Tried the same for an hour and it was fine.

I'll try for longer and get back to you.
I'm wondering if it's too do with the way I'm starting the app.

We use a switch user statement, so it's not using the same user account I use on the local machine. This is done to get round an issue where the remote servers only have Windows authentication setup and they require a different account.

**Comment by agentwalker** [comment]
It does seem to be related to the user I'm switching to. My local dB connection didn't drop at all one I constantly used my default user. 

But the server connections did. So I suspect it's related to that

**Comment by cheenamalhotra** [comment]
Hi @agentwalker 

When you say using a 'switch user statement', do you mean running ADS as another user, e.g. using `runas` command? And this user is a local user account that has access to the remotely hosted server, where you want to login with Windows Integrated Authentication.. let me know if I missed any details here.

I will try to replicate this and see if I find something new but I'm not aware of any known issues with reconnect in this setup.

**Comment by agentwalker** [comment]
@cheenamalhotra yes that's correct, we have some servers that require a different user account to my local and they are only setup as Windows authentication, so using the runas is the only option at the moment.

It seems if I turn that off the connection to my local doesn't drop at all.

The remote servers do seem random, I've set a reminder to check every hour and most of the time it's fine then eventually it's dropped. I'm suspecting this might not be data studios fault, but either a issue with our server / VPN  were forced to use. I'm wondering if it's the VPN reconnecting randomly causing it.

Just at this stage don't want to have you looking down the wrong path 😁.

**Comment by agentwalker** [comment]
Got some more info for you guys.
The connection seemed to drop so I checked the output window which then showed a render error.

Opening the logs shows this.


` 2023-01-13 13:46:38.938] [renderer1] [warning] Editor ID Mismatch: undefined !== workbench.editor.queryEditor. This will cause bugs. Please ensure editorInput.editorId matches the registered id

[2023-01-13 13:46:38.938] [renderer1] [info] Creating new connection file:///c:/Users/Gary.Test/AppData/Local/Temp/Script_637986773581156126.sql

[2023-01-13 13:46:38.938] [renderer1] [info] Adding connection file:///c:/Users/Gary.Test/AppData/Local/Temp/Script_637986773581156126.sql

[2023-01-13 13:46:38.939] [renderer1] [info] Successfully added connection file:///c:/Users/Gary.Test/AppData/Local/Temp/Script_637986773581156126.sql

[2023-01-13 13:46:38.979] [renderer1] [error] Error: File not found

    at new v (vscode-file://vscode-app/c:/Users/Gary.Test/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:74:383) [<root>]

    at new L (vscode-file://vscode-app/c:/Users/Gary.Test/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:873:19228) [<root>]

    at Kd.handleSetInputError (vscode-file://vscode-app/c:/Users/Gary.Test/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3562:88715) [<root>]

    at async Kd.setInput (vscode-file://vscode-app/c:/Users/Gary.Test/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3562:87955) [<root>]

[2023-01-13 13:47:01.130] [renderer1] [info] Disconnect request sent for file:///c:/Users/Gary.Test/AppData/Local/Temp/Script_637986773581156126.sql - deleting connection

[2023-01-13 13:47:01.130] [renderer1] [info] Deleting connection file:///c:/Users/Gary.Test/AppData/Local/Temp/Script_637986773581156126.sql      `

**Comment by cheenamalhotra** [comment]
Thanks for the additional info @agentwalker 
Could you also enable and upload logs for the event when you experience this issue? I'm willing to see any helpful information from the MSSQL.log file.

**Comment by agentwalker** [comment]
[console.log.txt](https://github.com/microsoft/azuredatastudio/files/10427156/console.log.txt)
here the log from the console window when things start to get a little strange.

was going to post the MSQL log but there's the odd bit of sensitive data scattered around there, so not in a position to release the full file.

[renderer1.log](https://github.com/microsoft/azuredatastudio/files/10427252/renderer1.log)

**Comment by cheenamalhotra** [comment]
Can you find and extract any exceptions from the MSSQL log?

**Comment by agentwalker** [comment]
can't see anything obvious in the mssql logs that jump out as an error. but here's some of the log extract at around the same time as one of the console errors.
[mssql.log](https://github.com/microsoft/azuredatastudio/files/10432736/mssql.log)

**Comment by cheenamalhotra** [comment]
Thanks for attaching logs @agentwalker Appreciate all the help in aiding investigations!

Calling out below error from console.log you've attached above:

``` 
log.ts:301  INFO Creating new connection untitled:SQLQuery_7
log.ts:301  INFO Adding connection untitled:SQLQuery_7
log.ts:301  INFO Successfully added connection untitled:SQLQuery_7
mainThreadExtensionService.ts:79 [[object Object]]Unexpected token S in JSON at position 0
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
mainThreadExtensionService.ts:80 SyntaxError: Unexpected token S in JSON at position 0
	at JSON.parse (<anonymous>)
	at l.onData (c:\Users\gary.test\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:2:1122490)
	at Socket.<anonymous> (c:\Users\gary.test\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:2:1121849)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
...
[Continued errors]
$onExtensionRuntimeError @ mainThreadExtensionService.ts:80
mainThreadExtensionService.ts:79 [[object Object]]Message header must separate key and value using :
$onExtensionRuntimeError @ mainThreadExtensionService.ts:79
mainThreadExtensionService.ts:80 Error: Message header must separate key and value using :
```
This is the first time I'm looking at these errors and they indicate a corrupted incoming data stream, after connection is refreshed on the query editor. MSSQL log doesn't seem to capture any errors, so it likely an issue between STS and ADS communication channel.

@alanrenmsft are you aware of what could cause this stream corruption after refreshing connection on query editor?

**Comment by cheenamalhotra** [comment]
@agentwalker 

Could you also test this in the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) to confirm this issue continues to exist?
I noticed 'HandleCancelConnectRequest' being called in MSSQL logs which I've seen before was caused when refreshing connections, but we fixed it in insiders, just curious if it has a role here.

**Comment by agentwalker** [comment]
@cheenamalhotra sure, I'll download it this morning and give it a try today. 👍

**Comment by agentwalker** [comment]
Still testing the issue. 

But with the insider build there does appear to be an issue generating the list of 'Databases'. 'Security', 'Server Objects' when clicking to expand the server list.

it just sits there with the spinner constantly going.

If I then click another server to expand that list it finally expands the previous one and generates a warning in the output

[2023-01-18 11:20:41.512] [renderer1] [warning] Cannot find node status for session: productDb_master__Integrated_4cd4bc0b-1786-4a9a-8181-66d4b073a7ec and node path: productDb.

totally unrelated to this issue :)

**Comment by agentwalker** [comment]
Update

Well so far, using the insider build i've had no issues. Not see any sort of errors in the output window or the console. and the connections in the query windows don't seem to have dropped even after coming back to the computer after leaving it locked overnight.

So the changes in the insider build might have sorted it

**Comment by cheenamalhotra** [comment]
Thanks for testing @agentwalker ! Good to know your issue is resolved ❤️
The upcoming Jan stable release should also resolve the issue you described [above](https://github.com/microsoft/azuredatastudio/issues/21482#issuecomment-1386898986). :)

**Comment by cheenamalhotra** [comment]
I will proceed to close this issue as resolved in Jan milestone.
