### ISSUE TITLE
Unable to add Azure Account

### ISSUE THREAD

**Issue by achambery** [microsoft/azuredatastudio#21710]
Issue Type: <b>Bug</b>

1. Click "Add Account" Button under "Linked accounts" sub-page
2. Sign in to Azure account in browser using username/password

After following these steps, browser gets stuck loading while I can view the following error pop-up in Console logs:

  ERR Cannot read properties of undefined (reading 'accountType'): TypeError: Cannot read properties of undefined (reading 'accountType')
    at kl.renderElement (vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:881:69526)
    at kl.renderElement (vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:881:70180)
    at U.renderElement (vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:269:1826)
    at C.insertItemInDOM (vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:244:19186)
    at C._splice (vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:244:14963)
    at C.splice (vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:244:13182)
    at vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:68:67876
    at Array.forEach (<anonymous>)
    at t.splice (vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:68:67863)
    at vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:269:8601
    at y.bufferEvents (vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:136:5181)
    at Q.splice (vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:269:8568)
    at W.updateAccounts (vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:4020:60672)
    at z.updateProviderAccounts (vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:4020:66500)
    at vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:4020:61965
    at l.invoke (vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:136:145)
    at s.deliver (vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:136:2265)
    at r.fire (vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:136:1843)
    at vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:877:15926
    at l.invoke (vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:136:145)
    at s.deliver (vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:136:2265)
    at r.fire (vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:136:1843)
    at Du.fireAccountListUpdate (vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:4020:75075)
    at vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:4020:71192
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Ko.run (vscode-file://vscode-app/c:/Users/{USER}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:881:41278)

Azure Data Studio version: azuredatastudio 1.40.2 (661384637db384fe5d4e6224069adbe708580b16, 2022-12-22T22:17:02.658Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (20.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
azcli|Mic|1.7.0
azuremonitor|Mic|0.1.9
kusto|Mic|0.5.8
powershell|ms-|2022.12.1

</details>

**Comment by achambery** [comment]
[1-Azure Accounts.log](https://github.com/microsoft/azuredatastudio/files/10494624/1-Azure.Accounts.log)

Even with Verbose logging this does not appear to be very helpful. I have tried using Chrome, Firefox, and Edge for completing login but they all have the same result.

**Comment by achambery** [comment]
I have updated to the latest version of AzureDataStudio (1.41.1) and re-attempted to link my Azure account. The error still is happening but now an error window pops up and there is more information in the Azure debug logs (see attached)
![image](https://user-images.githubusercontent.com/28744847/216179249-08779444-5bab-42ac-915b-2256ec3d3528.png)
[1-Azure Accounts-public.log](https://github.com/microsoft/azuredatastudio/files/10562406/1-Azure.Accounts-public.log)

**Comment by nickylang** [comment]
Same issue here, Mac M2 Ventura

**Comment by mdiianni** [comment]
Same problem today on MacOs Ventura 13 Intel Core

**Comment by mdiianni** [comment]
Actually conducted the cleanup from the CLI and worked fine after removing and reinstalling.

**Comment by cheenamalhotra** [comment]
Issue has been fixed with #22140
