### ISSUE TITLE
Cosmos DB extension errors on launch

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#21780]
- Azure Data Studio Version: 1.41.1
- OS Version: Windows 11

Launch ADS and let Cosmos DB extension load:
```
[2023-01-30 10:36:29.962] [renderer1] [error] [Extension Host] TypeError: A dynamic import callback was not specified.
	at new NodeError (node:internal/errors:371:5)
	at importModuleDynamicallyCallback (node:internal/process/esm_loader:39:9)
	at vA (~\.azuredatastudio\extensions\microsoft.azure-cosmosdb-ads-extension-0.2.0\node_modules\@vscode\extension-telemetry\lib\telemetryReporter.node.min.js:10:16657)
	at wp (~\.azuredatastudio\extensions\microsoft.azure-cosmosdb-ads-extension-0.2.0\node_modules\@vscode\extension-telemetry\lib\telemetryReporter.node.min.js:10:17361)
	at xa.s [as _clientFactory] (~\.azuredatastudio\extensions\microsoft.azure-cosmosdb-ads-extension-0.2.0\node_modules\@vscode\extension-telemetry\lib\telemetryReporter.node.min.js:16:688)
	at xa.instantiateAppender (~\.azuredatastudio\extensions\microsoft.azure-cosmosdb-ads-extension-0.2.0\node_modules\@vscode\extension-telemetry\lib\telemetryReporter.node.min.js:10:16460)
	at hu.updateUserOptStatus (~\.azuredatastudio\extensions\microsoft.azure-cosmosdb-ads-extension-0.2.0\node_modules\@vscode\extension-telemetry\lib\telemetryReporter.node.min.js:10:10734)
	at new wa (~\.azuredatastudio\extensions\microsoft.azure-cosmosdb-ads-extension-0.2.0\node_modules\@vscode\extension-telemetry\lib\telemetryReporter.node.min.js:10:10189)
	at new hu (~\.azuredatastudio\extensions\microsoft.azure-cosmosdb-ads-extension-0.2.0\node_modules\@vscode\extension-telemetry\lib\telemetryReporter.node.min.js:16:789)
	at new TelemetryReporter (~\.azuredatastudio\extensions\microsoft.azure-cosmosdb-ads-extension-0.2.0\node_modules\@microsoft\ads-extension-telemetry\lib\telemetryReporter.js:62:35)
	at activate (~\.azuredatastudio\extensions\microsoft.azure-cosmosdb-ads-extension-0.2.0\out\extension.js:332:27)
```

- Azure Data Studio Version: Insiders
- OS Version: Windows 11

Launch ADS and let Cosmos DB extension load:
```
[2023-01-30 10:05:07.121] [renderer1] [error] [Extension Host] TypeError: Invalid host defined options
	at vA (~\.azuredatastudio-insiders\extensions\microsoft.azure-cosmosdb-ads-extension-0.2.0\node_modules\@vscode\extension-telemetry\lib\telemetryReporter.node.min.js:10:16657)
	at wp (~\.azuredatastudio-insiders\extensions\microsoft.azure-cosmosdb-ads-extension-0.2.0\node_modules\@vscode\extension-telemetry\lib\telemetryReporter.node.min.js:10:17361)
	at xa.s [as _clientFactory] (~\.azuredatastudio-insiders\extensions\microsoft.azure-cosmosdb-ads-extension-0.2.0\node_modules\@vscode\extension-telemetry\lib\telemetryReporter.node.min.js:16:688)
	at xa.instantiateAppender (~\.azuredatastudio-insiders\extensions\microsoft.azure-cosmosdb-ads-extension-0.2.0\node_modules\@vscode\extension-telemetry\lib\telemetryReporter.node.min.js:10:16460)
	at hu.updateUserOptStatus (~\.azuredatastudio-insiders\extensions\microsoft.azure-cosmosdb-ads-extension-0.2.0\node_modules\@vscode\extension-telemetry\lib\telemetryReporter.node.min.js:10:10734)
	at new wa (~\.azuredatastudio-insiders\extensions\microsoft.azure-cosmosdb-ads-extension-0.2.0\node_modules\@vscode\extension-telemetry\lib\telemetryReporter.node.min.js:10:10189)
	at new hu (~\.azuredatastudio-insiders\extensions\microsoft.azure-cosmosdb-ads-extension-0.2.0\node_modules\@vscode\extension-telemetry\lib\telemetryReporter.node.min.js:16:789)
	at new TelemetryReporter (~\.azuredatastudio-insiders\extensions\microsoft.azure-cosmosdb-ads-extension-0.2.0\node_modules\@microsoft\ads-extension-telemetry\lib\telemetryReporter.js:62:35)
	at activate (~\.azuredatastudio-insiders\extensions\microsoft.azure-cosmosdb-ads-extension-0.2.0\out\extension.js:332:27)
```

I believe this is only related to Telemetry, but extension team should verify functionality is intact.

**Comment by cheenamalhotra** [comment]
Opened issue for extension: https://github.com/Azure/azure-cosmosdb-ads-extension/issues/50
