### ISSUE TITLE
Scripting view definition Failed

### ISSUE THREAD

**Issue by ltsyen** [microsoft/azuredatastudio#21788]
Issue Type: <b>Bug</b>

1. Open up the 'Manage' dashboard by right clicking database -> 'Manage'
2. Filter for specific table or view
3. Script as Create

Error: 
Microsoft.SqlServer.Management.Common.ConnectionFailureException: Failed to connect to server xxx- ondemand.sql.azuresynapse.net.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user '<token-identified principal>'. Token is expired.
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(Boolean enlistOK)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnectImpl()
   at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnect()
   at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
ClientConnectionId:b6e968d3-eb6d-465b-b0bc-93ab30ab9c8b
Error Number:18456,State:233,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
   at Microsoft.SqlTools.ServiceLayer.Scripting.ScriptAsScriptingOperation.Execute() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Scripting\ScriptAsScriptingOperation.cs:line 84

Azure Data Studio version: azuredatastudio 1.41.1 (33dce95b152227c4f10f6251ab30690fe9895c0c, 2023-01-28T00:46:39.274Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD EPYC 7763 64-Core Processor                 (16 x 2445)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|64.00GB (33.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ltsyen** [comment]
Might be related to: 
- https://github.com/microsoft/azuredatastudio/issues/21774 
- https://github.com/microsoft/azuredatastudio/issues/21766

**Comment by aasimkhan30** [comment]
@lewis-sanchez, can you please take a look into this

**Comment by lewis-sanchez** [comment]
Hi @ltsyen, it looks like this issue is fixed in the latest insiders version of Azure Data Studio. Can you please install the latest insiders version and try to generate scripts there?

**Comment by ltsyen** [comment]
@lewis-sanchez in which PR has this issue been addressed? 
I'll check it out.

**Comment by ltsyen** [comment]
> Hi @ltsyen, it looks like this issue is fixed in the latest insiders version of Azure Data Studio. Can you please install the latest insiders version and try to generate scripts there?

Hi @lewis-sanchez , yesterday I got the same error when working in the insiders version. Forgot to take the errors log when it happened. 
If it happens again, I will take the logs and attach them here.
But it does not seem to be fixed ...

**Comment by cheenamalhotra** [comment]
@ltsyen 

For ref: https://github.com/microsoft/azuredatastudio/issues/21774#issuecomment-1457276049
Please enable `mssql.enableSqlAuthenticationProvider` setting to resolve issue (available in the latest insiders build).
