### ISSUE TITLE
Schema Compare cannot connect to remote Azure database (via Azure VPN)

### ISSUE THREAD

**Issue by jtsom** [microsoft/azuredatastudio#21819]
- Azure Data Studio Version:
```
Version: 1.42.0-insider (user setup)
Commit: 7a0790f365874002957c6070e83e2031d7c91556
Date: 2023-02-01T06:30:01.777Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
```
- OS Version:

Steps to Reproduce:

1. Connect to remote Azure  MSSQL database via VPN
2. Attempt to do schema compare, setting the azure database as the source

Never connects, spinners keep spinning. Errors are displayed in the dev console:

```
 INFO Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:DigitalOptometrics_HC|server:dodevlisten01.azuredev.digiopto.com|user:DigitalOptometricsTest|databaseDisplayName:DigitalOptometrics_HC|group:4b79ee71-7ce5-4527-a7ed-06deef2da168
log.ts:301  INFO Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:DigitalOptometrics_HC|server:dodevlisten01.azuredev.digiopto.com|user:DigitalOptometricsTest|databaseDisplayName:DigitalOptometrics_HC|group:4b79ee71-7ce5-4527-a7ed-06deef2da168
log.ts:301  INFO Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:DigitalOptometrics_HC|server:dodevlisten01.azuredev.digiopto.com|user:DigitalOptometricsTest|databaseDisplayName:DigitalOptometrics_HC|group:4b79ee71-7ce5-4527-a7ed-06deef2da168
console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading '_connectionStore') (at c:\Users\jtsombakos\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:35339)
C @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:475
_invokeHandler @ rpcProtocol.ts:460
_receiveRequest @ rpcProtocol.ts:374
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:575
deliver @ event.ts:779
fire @ event.ts:740
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
invoke @ event.ts:575
deliver @ event.ts:779
fire @ event.ts:740
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
L @ ipc.net.ts:60
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
console.ts:137 [Extension Host] stack trace: TypeError: Cannot read properties of undefined (reading '_connectionStore')
    at removeConnectionProfileCredentials (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2697:69359)
    at r (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:139:46753)
    at vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2436:37408
    at Array.map (<anonymous>)
    at o.$getConnections (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2436:37366)
    at y._doInvokeHandler (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2452:13206)
    at y._invokeHandler (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2452:12890)
    at y._receiveRequest (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2452:11514)
    at y._receiveOneMessage (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2452:10192)
    at vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2452:8301
    at l.invoke (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:136:145)
    at s.deliver (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:136:2265)
    at o.fire (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:136:1843)
    at f.fire (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:183:19638)
    at S._receiveMessage (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:183:24219)
    at vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:183:21753
    at l.invoke (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:136:145)
    at s.deliver (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:136:2265)
    at o.fire (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:136:1843)
    at o.acceptChunk (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:183:16466)
    at vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:183:15596
    at Socket.L (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4234:13006)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) (at c:\Users\jtsombakos\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:35418)
C @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:475
_invokeHandler @ rpcProtocol.ts:460
_receiveRequest @ rpcProtocol.ts:374
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:575
deliver @ event.ts:779
fire @ event.ts:740
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
invoke @ event.ts:575
deliver @ event.ts:779
fire @ event.ts:740
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
L @ ipc.net.ts:60
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
log.ts:313   ERR Cannot read properties of undefined (reading '_connectionStore'): TypeError: Cannot read properties of undefined (reading '_connectionStore')
    at removeConnectionProfileCredentials (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2697:69359)
    at r (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:139:46753)
    at vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2436:37408
    at Array.map (<anonymous>)
    at o.$getConnections (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2436:37366)
    at y._doInvokeHandler (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2452:13206)
    at y._invokeHandler (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2452:12890)
    at y._receiveRequest (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2452:11514)
    at y._receiveOneMessage (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2452:10192)
    at vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2452:8301
    at l.invoke (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:136:145)
    at s.deliver (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:136:2265)
    at o.fire (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:136:1843)
    at f.fire (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:183:19638)
    at S._receiveMessage (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:183:24219)
    at vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:183:21753
    at l.invoke (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:136:145)
    at s.deliver (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:136:2265)
    at o.fire (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:136:1843)
    at o.acceptChunk (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:183:16466)
    at vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:183:15596
    at Socket.L (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4234:13006)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading '_connectionStore') (at c:\Users\jtsombakos\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:35339)
C @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:475
_invokeHandler @ rpcProtocol.ts:460
_receiveRequest @ rpcProtocol.ts:374
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:575
deliver @ event.ts:779
fire @ event.ts:740
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
invoke @ event.ts:575
deliver @ event.ts:779
fire @ event.ts:740
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
L @ ipc.net.ts:60
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
console.ts:137 [Extension Host] stack trace: TypeError: Cannot read properties of undefined (reading '_connectionStore')
    at removeConnectionProfileCredentials (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2697:69359)
    at r (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:139:46753)
    at vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2436:37408
    at Array.map (<anonymous>)
    at o.$getConnections (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2436:37366)
    at y._doInvokeHandler (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2452:13206)
    at y._invokeHandler (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2452:12890)
    at y._receiveRequest (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2452:11514)
    at y._receiveOneMessage (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2452:10192)
    at vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2452:8301
    at l.invoke (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:136:145)
    at s.deliver (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:136:2265)
    at o.fire (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:136:1843)
    at f.fire (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:183:19638)
    at S._receiveMessage (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:183:24219)
    at vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:183:21753
    at l.invoke (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:136:145)
    at s.deliver (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:136:2265)
    at o.fire (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:136:1843)
    at o.acceptChunk (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:183:16466)
    at vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:183:15596
    at Socket.L (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:4234:13006)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) (at c:\Users\jtsombakos\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:35418)
C @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:475
_invokeHandler @ rpcProtocol.ts:460
_receiveRequest @ rpcProtocol.ts:374
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:575
deliver @ event.ts:779
fire @ event.ts:740
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
invoke @ event.ts:575
deliver @ event.ts:779
fire @ event.ts:740
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
L @ ipc.net.ts:60
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
```

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by cheenamalhotra** [comment]
Hi @jtsom 

> log.ts:313   ERR Cannot read properties of undefined (reading '_connectionStore'): TypeError: Cannot read properties of undefined (reading '_connectionStore')
    at removeConnectionProfileCredentials (vscode-file://vscode-app/c:/Users/jtsombakos/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2697:69359)

This issue has been fixed in main, but not yet rolled out in insiders, it will be hopefully available soon.

**Comment by cheenamalhotra** [comment]
HI @jtsom 

This issue is now addressed, closing as resolved.
