### ISSUE TITLE
Restore 'Backup Set' checkbox isn't checkable and raises exception in log

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#21887]
- Azure Data Studio Version: `1.41.1`

Steps to Reproduce:

1. Open backup dialog and select a database with a backup set available to restore
2. Click the checkbox next to the backup set row

Expected: Checkbox is checked when clicked

Actual: Checkbox is checked, and a slickgrid error is show in log

Log snippet
```
bootstrap-window.js:259 [uncaught exception]: TypeError: Cannot read properties of undefined (reading 'enabled')
b @ bootstrap-window.js:259
bootstrap-window.js:262 TypeError: Cannot read properties of undefined (reading 'enabled')
    at g.setCheckboxPropertyValue (vscode-file://vscode-app/c:/Users/kburt/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:337:8354)
    at g.toggleCellCheckbox (vscode-file://vscode-app/c:/Users/kburt/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:337:6289)
    at g.handleClick (vscode-file://vscode-app/c:/Users/kburt/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:337:5905)
    at SlickGrid.<anonymous> (vscode-file://vscode-app/c:/Users/kburt/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:337:5572)
    at Event.notify (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\slickgrid\slick.core.js:145:35)
    at trigger (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\slickgrid\slick.grid.js:1379:18)
    at HTMLDivElement.handleClick (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\slickgrid\slick.grid.js:2899:7)
    at HTMLDivElement.dispatch (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\jquery\dist\jquery.js:5429:27)
    at $event.dispatch (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\slickgrid\lib\jquery.event.drag-2.3.0.js:382:30)
    at elemData.handle (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\jquery\dist\jquery.js:5233:28)
    at _ZoneDelegate.invokeTask (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:443:35)
    at Zone.runTask (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:214:51)
    at ZoneTask.invokeTask [as invoke] (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:525:38)
    at invokeTask (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1727:22)
    at globalCallback (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1758:31)
    at HTMLDivElement.globalZoneAwareCallback (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1794:20)
b @ bootstrap-window.js:262
C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1777 Uncaught TypeError: Cannot read properties of undefined (reading 'enabled')
    at g.setCheckboxPropertyValue (checkboxSelectColumn.plugin.ts:242:28)
    at g.toggleCellCheckbox (checkboxSelectColumn.plugin.ts:136:9)
    at g.handleClick (checkboxSelectColumn.plugin.ts:114:8)
    at SlickGrid.<anonymous> (checkboxSelectColumn.plugin.ts:102:87)
    at Event.notify (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\slickgrid\slick.core.js:145:35)
    at trigger (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\slickgrid\slick.grid.js:1379:18)
    at HTMLDivElement.handleClick (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\slickgrid\slick.grid.js:2899:7)
    at HTMLDivElement.dispatch (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\jquery\dist\jquery.js:5429:27)
    at $event.dispatch (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\slickgrid\lib\jquery.event.drag-2.3.0.js:382:30)
    at elemData.handle (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\jquery\dist\jquery.js:5233:28)
    at _ZoneDelegate.invokeTask (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:443:35)
    at Zone.runTask (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:214:51)
    at ZoneTask.invokeTask [as invoke] (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:525:38)
    at invokeTask (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1727:22)
    at globalCallback (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1758:31)
    at HTMLDivElement.globalZoneAwareCallback (C:\Users\kburt\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone.js:1794:20)
```

![image](https://user-images.githubusercontent.com/599935/217697488-f4596056-878d-45cb-af51-7b14a0f79172.png)

**Comment by alanrenmsft** [comment]
@aasimkhan30 looks like the issue is caused by this PR https://github.com/microsoft/azuredatastudio/pull/20514, could you please take a look?
