### ISSUE TITLE
Azure SQL Migrate : Assesment error

### ISSUE THREAD

**Issue by gecaszo** [microsoft/azuredatastudio#21902]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1.Click on SQL Instance , Manage , Migrate to Azure SQL , choose database. 
2.error An error occurred while assessing the server .........
========================
message: Failed to run assessment.
stack: Error: Failed to run assessment.
	at c:\Users\xxx\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:2:1115003
	at c:\Users\xxx\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:2:1115297
	at Immediate.<anonymous> (c:\Users\xxx\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:2:1115658)
	at process.processImmediate (node:internal/timers:466:21)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alanrenmsft** [comment]
@brian-harris could your team please take a look?

**Comment by siyao-Siyang** [comment]
Assessment will generate logs in local. the location is /User/AppData/Roaming/azuredatastudio/logs/[dateTtimestamp]/exthost1/Microsoft.mssql/SqlAssessmentLogs. 

Could you share the logs to us?
