### ISSUE TITLE
Inconsistent sidebar tabs in Dashboard view

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#22067]
Manage dashboard sidebar extension tabs go away on navigation.. not sure whether they should be present or not.. seems to be affecting Azure SQL connections only. Authentication mode does not matter.

Steps to Reproduce:

1. Connect to an Azure SQL database/server
2. Right click > Manage (notice the sidebar contains Azure SQL Migration tab.
3. Navigate to any database or server name
4. Notice the sidebar loses extension tabs after navigation.
5. Reopening Manage does not bring them back.

![ManageTab](https://user-images.githubusercontent.com/13396919/221994374-b884404c-ca0a-436f-9450-17bc675ed2a4.gif)

**Azure Data Studio Version: 1.41.2 (user setup) - Insiders**
Commit: 0f0960d0e774e1ce903b79378addff96117c27a6
Date: 2023-02-08T20:16:49.071Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by alanrenmsft** [comment]
@cheenamalhotra are you still experiencing the same issue? I cannot reproduce it.

**Comment by cheenamalhotra** [comment]
I can reproduce it in 1.42-RC1 build.

```
[2023-03-07 14:58:27.194] [exthost] [error] RangeError: Maximum call stack size exceeded
	at c:\Users\~\.azuredatastudio-rc1\extensions\microsoft.sql-migration-1.4.0\dist\main.js:2:468008
	at Map.forEach (<anonymous>)
	at c.dispose (c:\Users\cmalhotra\.azuredatastudio-rc1\extensions\microsoft.sql-migration-1.4.0\dist\main.js:2:467993)
	at c:\Users\~\.azuredatastudio-rc1\extensions\microsoft.sql-migration-1.4.0\dist\main.js:2:468008
	at Map.forEach (<anonymous>)
```

![MigrationExt](https://user-images.githubusercontent.com/13396919/223573754-2c1f7db7-d16b-4905-90c1-159b351e1a18.gif)

**Comment by Charles-Gagnon** [comment]
@raymondtruong @brian-harris FYI

**Comment by brian-harris** [comment]
@Charles-Gagnon based on the video above, it appears they are connecting to SQL DB or SQL MI, in which case the SQL migration tab should not be showing up.  It should only display for on-prem sql connections... it seems it is disappearing / hidden due to this setting below in package.json.  For some reason the first time this connection is 'managed', the condition below is being met and temporarily shows the extension.
    "dashboard.tabs": [
      {
        "id": "migration-dashboard",
        },
        "when": "connectionProvider == 'MSSQL' && !mssql:iscloud  && mssql:engineedition != 8",
      }
