### ISSUE TITLE
error open new login dialog

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#22236]
I am not able to reproduce it now but I got the following error in the log, hopefully this can help us identify the root cause.

23-03-08 10:46:16.8386770 pid:2500 tid:13 sqltools Error: 0 : objectManagement/initializeLoginView : System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryFindConnection(String ownerUri, ConnectionInfo& connectionInfo) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 246
   at Microsoft.SqlTools.ServiceLayer.Security.SecurityService.HandleInitializeLoginViewRequest(InitializeLoginViewRequestParams parameters, RequestContext`1 requestContext) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Security\SecurityService.cs:line 261
   at Microsoft.SqlTools.Hosting.Protocol.MessageDispatcher.<>c__DisplayClass31_0`2.<<SetRequestHandler>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.SqlTools.Hosting\Hosting\Protocol\MessageDispatcher.cs:line 165

**Comment by caohai** [comment]
This means no connection was found for the connection uri. I haven't seen this error before myself.
https://github.com/microsoft/sqltoolsservice/pull/1918 should make the error msg more straightforward.

**Comment by alanrenmsft** [comment]
Added check to throw meaningful error
