### ISSUE TITLE
Import flat file wizard stuck on step 4

### ISSUE THREAD

**Issue by philipnye** [microsoft/azuredatastudio#22360]
Issue Type: <b>Bug</b>

1. Attempt to import an 18KB file with two columns and 650 rows. 
2. Go through steps 1-3 of the wizard fine, and have a strong AzureActiveDirectory connection - all other operations are working fine
3. Import wizard hangs on step 4, and never seems to complete

I note that I'm basically describing the same experience as in the closed issue #12624

Extension version: 1.5.4
Azure Data Studio version: azuredatastudio 1.41.2 (0f0960d0e774e1ce903b79378addff96117c27a6, 2023-02-08T20:16:49.071Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.82GB (0.57GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/nyep/Institute%20for%20Government/Data%20-%20General/UK%20government%20and%20politics/Ministers/Ministers%20database|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by philipnye** [comment]
Logs as requested - with edits just to remove connection details. Also attached is the file I'm trying to import using the import wizard. Thanks.
[console.log](https://github.com/microsoft/azuredatastudio/files/11146962/console.log)
[20230404T102453.zip](https://
[Westminster_Parliamentary_Constituency_to_European_Electoral_Regions_(December_2020)_Lookup_in_the_United_Kingdom.csv](https://github.com/microsoft/azuredatastudio/files/11146969/Westminster_Parliamentary_Constituency_to_European_Electoral_Regions_.December_2020._Lookup_in_the_United_Kingdom.csv)
github.com/microsoft/azuredatastudio/files/11146963/20230404T102453.zip)

**Comment by aasimkhan30** [comment]
@cheenamalhotra , based on logs it seems related to #22999

**Comment by cheenamalhotra** [comment]
Moving to July, as it seems like a random error than a consistent use-case, and we also haven't heard more reports on this.. 
However, I don't think this can be closed with #22999.

**Comment by philipnye** [comment]
Just tested this again on v1.43 and I'm afraid I'm still experiencing it!

I've attached new logs (I was trying to import the same file).

[console.log](https://github.com/microsoft/azuredatastudio/files/11433818/console.log)
[20230509T172621.zip](https://github.com/microsoft/azuredatastudio/files/11433819/20230509T172621.zip)

**Comment by philipnye** [comment]
Just to add: I've tested this with a handful of other CSVs (e.g. the attached) and having the same experience, so I don't think it's anything to do with the particular file I've been testing with.
[trees.csv](https://github.com/microsoft/azuredatastudio/files/11433986/trees.csv)

**Comment by cheenamalhotra** [comment]
Thanks for verifying.. I see below error:

```
[Error - 17:58:58] Request connection/listdatabases failed.
  Message: System.Exception: SpecifiedUri 'file:///c:/Users/nyep/OneDrive - Institute for Government/Desktop/console.log' does not have existing connection
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.ListDatabases(ListDatabasesParams listDatabasesParams) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 1080
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.<>c__DisplayClass86_0.<<HandleListDatabasesRequest>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 1312
  Code: 0 

```

@aasimkhan30 why would listdatabases call be made with file uri?

**Comment by jatkins23** [comment]
I'm still having this issue on the Mac version as well

**Comment by peterbud** [comment]
This is still not working - any information when the fix will be released?

**Comment by Joly0** [comment]
This issue is also affecting me. Is there a fix somehow?
