### ISSUE TITLE
Scripting connection invalid after waking up serverless DB

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#22445]
- Azure Data Studio Version: `main`
- 
Steps to Reproduce:

1. Connect to a sleeping Serverless database.

Expected: Server wakes up and is usable.

Actual: Server takes a long time to wake up and app in inconsistent state with the connection after it's established.  In this case, the scripting connection is corrupt and basic SMO functions fail to get metadata.  Failing with the "Cannot read properties of undefined (reading 'targetDatabaseEngineEdition').  Note the OE connect is working file.  Connection needs to be disconnected and reconnected to fix scripting connection.

![image](https://user-images.githubusercontent.com/599935/227600554-0e91c30d-ffc4-42f1-a345-e4ebf8596580.png)

**Comment by kburtram** [comment]
This is similar to https://github.com/microsoft/azuredatastudio/issues/22311 though the behavior is different enough I logged separately.  Though at a high-level the problem is the connections established to a serverless server that is in the process of resuming are unreliable and break the application in various ways.

**Comment by kburtram** [comment]
This is similar to https://github.com/microsoft/azuredatastudio/issues/22311 though the behavior is different enough I logged separately.  Though at a high-level the problem is the connections established to a serverless server that is in the process of resuming are unreliable and break the application in various ways.

**Comment by cheenamalhotra** [comment]
Same use-case, noting down another error I noticed on launching 'Table Designer' - which points to a potential bad initialization of STS services, and something went wrong after resume.

```
An error occurred while initializing the table designer: Failed to initialize the table model.
   at Microsoft.Data.Tools.Sql.DesignServices.TableDesigner.TableDesigner..ctor(String connectionString, String accessToken, String schemaName, String tableName, Boolean isNewTable, Int32 largeTableRowCount)
   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.CreateTableDesigner(TableInfo tableInfo) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 1807
   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass18_0.<<HandleInitializeTableDesignerRequest>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 101
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass17_0`1.<<HandleRequest>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 87
```

The error seems to persist on every 'New Table' attempt on the OE connection.

**Comment by smartguest** [comment]
It appears that during connection completion, when we attempt to get ServerHost info, we assign the hostInfo to Windows, and attempt to run the command "SELECT windows_release FROM sys.dm_os_windows_info" on the Serverless Database, which apparently is an invalid object on a serverless server.
