### ISSUE TITLE
Error: Only the invariant culture is supported in globalization-invariant mode.

### ISSUE THREAD

**Issue by reinaldocoelho** [microsoft/azuredatastudio#22730]
- Azure Data Studio Version: 1.43.0
- OS Version: Ubuntu 22.10

Steps to Reproduce:

1.Open Azure Data Studio
2.Connect to an on-primeses SQL Server
3. When try to connect, the error was showed
4. I also tried to set the following environment variable "export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true"

Does this issue occur when all extensions are disabled?: Yes

**Copied Details:**
```
System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-us is an invalid culture identifier.
   at System.Globalization.CultureInfo.GetCultureInfo(String name)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.InternalOpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass30_0.<<OpenAsync>b__0>d.MoveNext() in /_/src/Microsoft.SqlTools.ManagedBatchParser/ReliableConnection/ReliableSqlConnection.cs:line 313
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 698
```

**Image of error**
![image](https://user-images.githubusercontent.com/889634/232033766-2ca8b893-338a-418b-a124-af9cd6a5e10f.png)

**Comment by cheenamalhotra** [comment]
Invariant culture and Globalization Invariant mode are not supported by the underlying SqlClient driver.
Please try setting the env variable `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` to `0` or `false`.

**Comment by reinaldocoelho** [comment]
Same result using this config.

I tried to run with the follow command:
```export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0 && azuredatastudio```

Can I get details of what value of this parameter the Azure Data Studio was using on load?

Image when try to connect:
![image](https://user-images.githubusercontent.com/889634/232141082-2a8f3702-7b22-4eac-b2de-a0d54c927bc3.png)

**Comment by cheenamalhotra** [comment]
Azure Data Studio does not set this property and relies on system settings.

The backend service SqlToolsServiceLayer runs on your environment that establishes the connection using SqlClient driver. It's a .NET process and is potentially fetching globalization invariant mode configured on your environment. Can you check if globalization invariant mode is enabled globally on your system by any chance?

**Comment by reinaldocoelho** [comment]
The variable was Disabled:
![image](https://user-images.githubusercontent.com/889634/232172698-3ab08385-2175-45e3-8aa5-f0c1cd03982b.png)

Can the problem occurs because the Case Sensitive? I using on Linux, and the message alert to "en-us" all in lower case? 
![image](https://user-images.githubusercontent.com/889634/232172763-282ce453-39b9-45be-ba61-f9f671ec76b6.png)

I'm not understand what is going on, others dotnet programs (I program  with C#) was working fine.

**Comment by reinaldocoelho** [comment]
Solved the problem when setting the env on file `~/.bashrc`:

```bash
export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=0
```

Before I'm setting this on `~/.profile` but not working.
Thanks a lot for helping.

I hope this can help someone too.

**Comment by yogyogi** [comment]
I have a web api in .net 8.0. It contains EF Core. When I perform the migrations I see the same bug. 
First I ran `PM> dotnet ef migrations add Migration1` . Migration folder is created. Now I ran `PM> dotnet ef database update` I get the error. 

`PM> dotnet ef migrations add Migration1
Build started...
Build succeeded.
Done. To undo this action, use 'ef migrations remove'
PM> dotnet ef database update
Build started...
Build succeeded.
System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-us is an invalid culture identifier.
   at System.Globalization.CultureInfo.GetCultureInfo(String name)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext _, TState s)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation, Func`2 verifySucceeded)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-us is an invalid culture identifier.`

I opened the project file, found out that `<InvariantGlobalization>true</InvariantGlobalization>` so turned it false `<InvariantGlobalization>false</InvariantGlobalization>`. Now ran the migrations command `PM> dotnet ef database update` everything went good. 

So .NET 8.0 still has this problem. Kindly investigate.

**Comment by dhanunjay74** [comment]
yes me too getting the same error

**Comment by exedor** [comment]
I'm getting this error from VS 2022 whenever I try to make any change to a form in the application. It doesn't matter what the build settings are. The editor gives me that error even if I try to do something as simple as changing the Text property of a form or add a button. The form editor is completely worthless in the state this is in. I've tried changing the value in the csproj file from true to false and even deleting it. I cannot find a way to fix this. I don't get it. I can create a new project with the form template and everything is fine, Granted it is an unconventional project. I needed both webapi and windows forms in the same application. It was working fine at first. At some point (I'm guessing a VS update?) I lost the ability to use the form designer to make changes because of this error.
