### ISSUE TITLE
Cannot open flat file import through command prompt

### ISSUE THREAD

**Issue by AbbiePetcht** [Microsoft/azuredatastudio#2282]
- SQL Operations Studio Version:

Steps to Reproduce:

Try to open the flat file import though command prompt
![image](https://user-images.githubusercontent.com/25463959/44434034-f83ba480-a55d-11e8-9534-1ffbf9458cc6.png)

Actual result:
The dialog is not opened

**Comment by MattIrv** [comment]
Seems to be related to https://github.com/Microsoft/sqlopsstudio/issues/2234. 

```
  ERR Cannot read property 'connectionProfile' of null: TypeError: Cannot read property 'connectionProfile' of null
zone-node.js:2251
	at FlatFileWizard.<anonymous> (/Users/mairvine/code/sqlopsstudio/extensions/import/out/wizard/flatFileWizard.js:31:28)
	at Generator.next (<anonymous>)
	at __awaiter (/Users/mairvine/code/sqlopsstudio/extensions/import/out/wizard/flatFileWizard.js:11:71)
	at Promise (<anonymous>)
	at __awaiter (/Users/mairvine/code/sqlopsstudio/extensions/import/out/wizard/flatFileWizard.js:7:12)
	at FlatFileWizard.start (/Users/mairvine/code/sqlopsstudio/extensions/import/out/wizard/flatFileWizard.js:29:16)
at controllerBase_1.default.initializeFlatFileProvider.sqlops.tasks.registerTask.args (/Users/mairvine/code/sqlopsstudio/extensions/import/out/controllers/mainController.js:34:127)
	at ExtHostTasks.$executeContributedTask (/Users/mairvine/code/sqlopsstudio/out/sql/workbench/api/node/extHostTasks.js:52:39)
	at RPCProtocol._doInvokeHandler (/Users/mairvine/code/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:215:27)
	at RPCProtocol._invokeHandler (/Users/mairvine/code/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:200:54)
	at RPCProtocol._receiveRequest (/Users/mairvine/code/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:155:50)
	at RPCProtocol._receiveOneMessage (/Users/mairvine/code/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:138:26)
	at /Users/mairvine/code/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:75:92
	at /Users/mairvine/code/sqlopsstudio/out/vs/workbench/services/extensions/node/rpcProtocol.js:248:21
	at /Users/mairvine/code/sqlopsstudio/out/vs/base/common/event.js:341:70
	at Emitter.fire (/Users/mairvine/code/sqlopsstudio/out/vs/base/common/event.js:103:38)
	at Socket.<anonymous> (/Users/mairvine/code/sqlopsstudio/out/vs/base/parts/ipc/node/ipc.net.js:90:46)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
```

**Comment by MattIrv** [comment]
The workaround here is to right click on the database in Object Explorer and choose "Import wizard" in order to open the wizard

**Comment by kburtram** [comment]
Same underlying issue as https://github.com/Microsoft/azuredatastudio/issues/2537 so dup'ing
