### ISSUE TITLE
Could not load file or assembly 'System.Diagnostics.StackTrace' in main

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#22838]
- Azure Data Studio Version: Dev, main (doesn't seem to happen in Insiders!)
- OS Version: Windows 11

Noticed this is happening with recent update of STS to v4.7.0.17.
Works until v4.7.0.16 (https://github.com/microsoft/sqltoolsservice/compare/4.7.0.16...4.7.0.17)

@Benjin can you please check?

Steps to Reproduce:
1. Open any connection

Getting this error:

```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.StackTrace, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Diagnostics.StackTrace, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.Data.SqlClient.SqlConfigurableRetryLogicManager.get_ConnectionProvider()
   at Microsoft.Data.SqlClient.SqlConnection.get_RetryLogicProvider()
   at Microsoft.Data.SqlClient.SqlConnection.get_IsProviderRetriable()
   at Microsoft.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass30_0.<<OpenAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams)
```
![image](https://user-images.githubusercontent.com/13396919/234113945-af7fcda0-0654-4f96-a611-bc1d7f3087b6.png)

**Comment by Benjin** [comment]
I've been unable to repro this with the latest `main` on either Windows or macOS.  Does anyone else have a consistent repro?

**Comment by Charles-Gagnon** [comment]
@cheenamalhotra Were you perhaps using a locally built version of STS? If so did you ensure that all the build dependencies were there.

**Comment by cheenamalhotra** [comment]
Cleaning up the sts download folder did help, so it's possible I had a bad copy or incomplete download..
Closing as I can't repro anymore.
