### ISSUE TITLE
"cannot read properties of undefined" error when closing backup dialog

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#22883]
Insiders/main - does not repro on stable 1.43.0

1. Open up backup dialog (right click on Database node -> Backup)
2. Close the dialog

This error appears in the console

```
Cannot read properties of undefined (reading 'savePassword'): TypeError: Cannot read properties of undefined (reading 'savePassword')
    at ServerTreeView.disconnectConnection (vscode-file://vscode-app/c:/src/azuredatastudio/out/sql/workbench/contrib/objectExplorer/browser/serverTreeView.js:440:40)
    at vscode-file://vscode-app/c:/src/azuredatastudio/out/sql/workbench/contrib/objectExplorer/browser/serverTreeView.js:161:32
    at Listener.invoke (vscode-file://vscode-app/c:/src/azuredatastudio/out/vs/base/common/event.js:457:27)
    at PrivateEventDeliveryQueue.deliver (vscode-file://vscode-app/c:/src/azuredatastudio/out/vs/base/common/event.js:627:38)
    at Emitter.fire (vscode-file://vscode-app/c:/src/azuredatastudio/out/vs/base/common/event.js:592:37)
    at ConnectionManagementService._notifyDisconnected (vscode-file://vscode-app/c:/src/azuredatastudio/out/sql/workbench/services/connection/browser/connectionManagementService.js:1511:32)
    at vscode-file://vscode-app/c:/src/azuredatastudio/out/sql/workbench/services/connection/browser/connectionManagementService.js:1322:30
    at _ZoneDelegate.invoke (C:\src\azuredatastudio\node_modules\zone.js\dist\zone.js:409:30)
    at Object.onInvoke (C:\src\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4156:37)
    at _ZoneDelegate.invoke (C:\src\azuredatastudio\node_modules\zone.js\dist\zone.js:408:56)
    at Zone.run (C:\src\azuredatastudio\node_modules\zone.js\dist\zone.js:169:47)
    at C:\src\azuredatastudio\node_modules\zone.js\dist\zone.js:1326:38
    at _ZoneDelegate.invokeTask (C:\src\azuredatastudio\node_modules\zone.js\dist\zone.js:443:35)
    at Object.onInvokeTask (C:\src\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4147:37)
    at _ZoneDelegate.invokeTask (C:\src\azuredatastudio\node_modules\zone.js\dist\zone.js:442:64)
    at Zone.runTask (C:\src\azuredatastudio\node_modules\zone.js\dist\zone.js:214:51)
    at drainMicroTaskQueue (C:\src\azuredatastudio\node_modules\zone.js\dist\zone.js:632:39)
    at ZoneTask.invokeTask [as invoke] (C:\src\azuredatastudio\node_modules\zone.js\dist\zone.js:529:25)
    at invokeTask (C:\src\azuredatastudio\node_modules\zone.js\dist\zone.js:1727:22)
    at globalCallback (C:\src\azuredatastudio\node_modules\zone.js\dist\zone.js:1758:31)
    at HTMLAnchorElement.globalZoneAwareCallback (C:\src\azuredatastudio\node_modules\zone.js\dist\zone.js:1794:20)
```

**Comment by Charles-Gagnon** [comment]
@aasimkhan30 This seems to be caused by this PR : https://github.com/microsoft/azuredatastudio/pull/22535

Could you look into this?

**Comment by Charles-Gagnon** [comment]
@aasimkhan30 Take a look at https://github.com/microsoft/azuredatastudio/issues/23603 for another place I was seeing this as well

**Comment by Charles-Gagnon** [comment]
Well, just tried it again and now I'm not seeing the error here or with SELECT TOP 1000, so not sure what was happening previously. If I see this again I'll try to get some more information on a repro - in the meantime @aasimkhan30 feel free to close the PR if you want - although maybe instead of throwing there have it display a more specific error to the user so they know something went wrong (and it's easier to tell when it fails in the future)
