### ISSUE TITLE
Async server tree node expansion timeout not canceled on error

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#22917]
Note: An easy way to repro this is with a local docker instance so you can quickly turn it on/off

1. Add a connection and set the "Connection Timeout" advanced property to something low, like 5 seconds
2. Make the connection so the properties are saved
3. Disconnect
4. Turn off the server
5. Try to connect by expanding the node
6. Wait 5 seconds for it to time out (this happens as expected, error is shown and node is collapsed)

Expected :

Nothing else happens

Actual : 

The following error appears in the console after 45sec (the server tree timeout period)

```
ERR Object Explorer expansion timed out for '': Error: Object Explorer expansion timed out for ''
    at nodeUpdateTimeout (vscode-file://vscode-app/c:/src/azuredatastudio/out/sql/workbench/services/objectExplorer/browser/treeUpdateUtils.js:264:36) [<root>]
    at timer (C:\src\azuredatastudio\node_modules\zone.js\dist\zone.js:3155:47) [<root>]
    at data.args.<computed> (C:\src\azuredatastudio\node_modules\zone.js\dist\zone.js:3135:36) [<root>]
```

We should be cancelling this timeout if we get an error for a session .

**Comment by Charles-Gagnon** [comment]
@aasimkhan30
