### ISSUE TITLE
Cannot add similar connection in OE via ADS URI with Async Server Tree

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#23152]
- Azure Data Studio Version: Insiders
- OS Version: Windows 11

Steps to Reproduce:

1. Add a connection to any server/database in a group
2. Run below command on Windows to open ADS via URI with same connection params:
`azuredatastudio-insiders://connect?server=*****&user=*****&authenticationType=*****`

Connection dialog opens and when clicking on 'Connect' - OE doesn't show connection, and below error is seen in logs:

```
[renderer1] [error] Cannot read properties of undefined (reading 'groupId'): TypeError: Cannot read properties of undefined (reading 'groupId')
    at vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2888:36639
    at f.invoke (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:169:145)
    at l.deliver (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:169:2266)
```

**Comment by cheenamalhotra** [comment]
I can't reproduce this issue with new profiles - closing for now.
