### ISSUE TITLE
"update project from database" does not launch schema compare

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#23160]
Type: <b>Bug</b>

Have an SDK-style sql project open in the current folder and a SQL Server connected in OE.  When in the projects view, I can select "update project from database" and successfully open schema compare.  However when in OE, the database-level option does not open schema compare.

Errors from console:
console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'getProjectTargetVersion') (at console.<anonymous> (/Applications/Azure Data Studio - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:196310))
C @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:457
_invokeHandler @ rpcProtocol.ts:442
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:959
(anonymous) @ ipc.net.ts:832
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
T @ ipc.net.ts:70
emit @ node:events:526
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:190
console.ts:137 [Extension Host] stack trace: TypeError: Cannot read properties of undefined (reading 'getProjectTargetVersion')
    at t.UpdateProjectFromDatabaseDialog.handleUpdateButtonClick (/Users/drewsk/.azuredatastudio-insiders/extensions/microsoft.sql-database-projects-1.1.1/dist/extension.js:2:1383145)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /Users/drewsk/.azuredatastudio-insiders/extensions/microsoft.sql-database-projects-1.1.1/dist/extension.js:2:1372774 (at console.<anonymous> (/Applications/Azure Data Studio - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:196310))

Extension version: 1.19.0
Azure Data Studio version: azuredatastudio-insiders 1.45.0-insider (20f409adca5430a39c9ec57a09eb72cc27c7fc71, 2023-05-16T05:28:52.716Z)
OS version: Darwin arm64 22.5.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kisantia** [comment]
@Benjin @SakshiS-harma can one of you please investigate if this is also happening in the RC build?

**Comment by SakshiS-harma** [comment]
Let me take a look at it.
