### ISSUE TITLE
Schema compare source connection keeps spinning

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#23305]
- Azure Data Studio Version: 1.44.1-RC, Insiders
- OS Version: Windows 11

Steps to Reproduce:

1. Connect to on-premise SQL server
2. Launch schema compare
3. Click on `...` against source or target connection
4. Notice the continuously spinning source connection

![image](https://github.com/microsoft/azuredatastudio/assets/13396919/d0af33f6-8b5a-4775-a491-f74712c795f2)

Below error is observed in logs:
```
[2023-06-02 12:43:43.283] [renderer1] [info] Creating new connection connection:providerName:MSSQL|authenticationType:SqlLogin|database:master|server:localhost\MSSQLSERVER01|user:sa|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458
[2023-06-02 12:43:43.283] [renderer1] [info] Adding connection connection:providerName:MSSQL|authenticationType:SqlLogin|database:master|server:localhost\MSSQLSERVER01|user:sa|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458
[2023-06-02 12:43:43.283] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|authenticationType:SqlLogin|database:master|server:localhost\MSSQLSERVER01|user:sa|databaseDisplayName:master|group:C777F06B-202E-4480-B475-FA416154D458
[2023-06-02 12:44:18.550] [renderer1] [error] Cannot read properties of undefined (reading 'toLowerCase'): TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at c:\Users\cmalhotra\.azuredatastudio\extensions\microsoft.schema-compare-1.19.0\dist\extension.js:2:536884
    at Array.map (<anonymous>)
    at t.SchemaCompareDialog.getServerValues (c:\Users\cmalhotra\.azuredatastudio\extensions\microsoft.schema-compare-1.19.0\dist\extension.js:2:536628)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at t.SchemaCompareDialog.populateServerDropdown (c:\Users\cmalhotra\.azuredatastudio\extensions\microsoft.schema-compare-1.19.0\dist\extension.js:2:536045)

```

Doesn't seem to be reproducible consistently.

**Comment by kisantia** [comment]
@SakshiS-harma can you also please take a look at this issue? Not sure if it might be related to #23473

**Comment by SakshiS-harma** [comment]
@cheenamalhotra Did this issue happen when the source was already populated (before opening the dialog) or the source was picked in the dialog?

**Comment by SakshiS-harma** [comment]
@cheenamalhotra Sorry just checking on the same lines as before- did this issue happen when the source was already populated (before opening the dialog) or the source was picked in the dialog?
Also, did you see the issue again?

**Comment by cheenamalhotra** [comment]
Sorry missed notifications.. plz feel free to ping me directly in future 🙈 
I haven't noticed this recently, might have been something with connection profile issues.. 
I'd say if it's not reproducing we can close this.
