### ISSUE TITLE
Always disconnecting

### ISSUE THREAD

**Issue by axellpadilla-farinter** [microsoft/azuredatastudio#23316]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Type: <b>Bug</b>

Always disconnect from servers, takes a while, need to restart  to make it work.
This can happen with VS Code too, so looks like the MSSQL extension is the problem. This happens less without a VPN connection.

Azure Data Studio version: azuredatastudio 1.44.0 (31bee67f005648cdc9186f28ef39b4f1d6585e0f, 2023-05-19T16:53:04.348Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|9.86GB (0.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
query-editor-boost|dre|0.4.1
sql-server-diagnostic-book|ema|0.2.0
sql-data-inspector|ern|0.6.0
lz-scripts|Fai|1.3.0
ssmskeymap|kev|1.1.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.2
agent|Mic|0.49.0
azuredatastudio-postgresql|Mic|0.3.1
dacpac|Mic|1.13.0
import|Mic|1.5.5
managed-instance-dashboard|Mic|0.4.2
profiler|Mic|0.12.2
query-history|Mic|0.5.3
sql-dw|Mic|0.0.1
whoisactive|Mic|0.1.5
azdata-sanddance|msr|4.0.3
extra-sql-script-as|pac|0.5.0
schema-visualization|R0t|0.8.2
sql-prompt|Red|0.2.12
sql-search|Red|0.4.2
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

(2 theme extensions excluded)

</details>

**Comment by axellpadilla-farinter** [comment]
Just happened something similiar, a connection from another file was mixed with current file (conected to, even when there was no connection) and locked, this was after canceling "connect to"
[console.log](https://github.com/microsoft/azuredatastudio/files/11655773/console.log)
[20230605T120337.zip](https://github.com/microsoft/azuredatastudio/files/11655774/20230605T120337.zip)

**Comment by cheenamalhotra** [comment]
Seems like 'Canceling' is leading to an unexpected behavior, that connection status manager is losing connection info for file URI.

```
workbench.desktop.main.js:893  WARN Editor ID Mismatch: undefined !== workbench.editor.queryEditor. This will cause bugs. Please ensure editorInput.editorId matches the registered id
workbench.desktop.main.js:893  INFO Cancelling connection for URI file:///d:/Zona de Trabajo/Auditoria_/Exploracion_Movimientos/ETL Final Movimiento.sql
workbench.desktop.main.js:893  INFO Deleting connection file:///d:/Zona de Trabajo/Auditoria_/Exploracion_Movimientos/ETL Final Movimiento.sql (connecting)
workbench.desktop.main.js:893  INFO Found deleted connection management info for file:///d:/Zona de Trabajo/Auditoria_/Exploracion_Movimientos/ETL Final Movimiento.sql - removing
workbench.desktop.main.js:893  INFO Deleting connection file:///d:/Zona de Trabajo/Auditoria_/Exploracion_Movimientos/ETL Final Movimiento.sql
workbench.desktop.main.js:893  INFO Could not find connection management info for file:///d:/Zona de Trabajo/Auditoria_/Exploracion_Movimientos/ETL Final Movimiento.sql after connection
workbench.desktop.main.js:893   ERR Cannot read properties of undefined (reading 'connectHandler'): TypeError: Cannot read properties of undefined (reading 'connectHandler')
    at wa.tryAddActiveConnection (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2710:34986)
    at vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2710:22153
    at _ZoneDelegate.invoke (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:409:30)
    at Zone.run (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:169:47)
    at C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1326:38
    at _ZoneDelegate.invokeTask (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:443:35)
    at Zone.runTask (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:214:51)
    at drainMicroTaskQueue (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:632:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
2workbench.desktop.main.js:893  WARN Editor ID Mismatch: undefined !== workbench.editor.queryEditor. This will cause bugs. Please ensure editorInput.editorId matches the registered id
```

@alanrenmsft could you please take a look at the attached logs if this can be addressed by not removing connection info from query editor / file on Cancel?

**Comment by axellpadilla-farinter** [comment]
Hi guys, just wanted to add another case and logs,
This time, after leaving it some minutes, I lost the vpn connection at some time, after it comming back, the file run query doesnt work, status keeps at "executing query", even after trying to stop it, and to disconnect it, it also didnt work until i manually recycled the vpn connection, message was always "executing query", and buttons still show stop available:
![image](https://github.com/microsoft/azuredatastudio/assets/132957665/430669f4-b2c8-4eaf-8513-88df18473093)
[20230607T160408.zip](https://github.com/microsoft/azuredatastudio/files/11692391/20230607T160408.zip)
[console.log](https://github.com/microsoft/azuredatastudio/files/11692407/console.log)

**Comment by cheenamalhotra** [comment]
From the logs, I can see that below event is repeatedly trying even on failure to connect:
`get data for urn: Server[@Name='DWHDEV\DWHFARINTERDEV']/Database[@Name='BI_FARINTER']`

@alanrenmsft is that related with failing to press 'Cancel' icon?
Perhaps this is QE issue, so I'll let you investigate from here. The logs are attached in the comment above for investigation.

**Comment by axellpadilla-farinter** [comment]
Just adding, after some recent updates, or because I managed to work-around most of the problems, this bug seems less frecuent, I started using disconect instead of change connection, but also idle times doesnt seem to cause too much problems.

There is still that problem when you send a cancel query request, disconect, then it stays disconnected but continues to show "executing", also, sometimes, when changing from one .sql to another, somehow, the conection of the previous .sql remains on the new one.
