### ISSUE TITLE
Notebook trust extension tests are failing

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#23540]
The Notebook Trust extension test cases are all failing after the latest vscode source code refresh.  Since this is the only suite that is currently broken it is being disabled while being investigated so the other test cases can be reenabled.

```
    1) BooksTreeViewTests
       BookTreeViewProvider
         bookTreeViewProvider
           should set notebooks trusted to true on trustBook:

      AssertionError: Failed to set trust on trustBook
      + expected - actual

      -false
      +true
      
  	at Assertion.fail (extensions/notebook/node_modules/should/cjs/should.js:275:17)
  	at Assertion.value (extensions/notebook/node_modules/should/cjs/should.js:356:19)
  	at Context.<anonymous> (extensions/notebook/out/test/book/book.test.js:196:35)
  	at process.processImmediate (node:internal/timers:466:21)

  2) BookTrustManagerTests
       TrustingInFolder
         Trusting in Workspaces using the jupyter-book legacy version < 0.7.0
           should trust notebooks in a trusted book in a folder:
     AssertionError: Notebook 1 should be trusted
  	at Assertion.fail (extensions/notebook/node_modules/should/cjs/should.js:275:17)
  	at Assertion.value (extensions/notebook/node_modules/should/cjs/should.js:356:19)
  	at Context.<anonymous> (extensions/notebook/out/test/book/bookTrustManager.test.js:293:55)
  	at process.processImmediate (node:internal/timers:466:21)

  3) BookTrustManagerTests
       TrustingInFolder
         Trusting in Workspaces using the jupyter-book legacy version < 0.7.0
           should trust notebook after book has been added to a folder:
     AssertionError: Notebook should be trusted
  	at Assertion.fail (extensions/notebook/node_modules/should/cjs/should.js:275:17)
  	at Assertion.value (extensions/notebook/node_modules/should/cjs/should.js:356:19)
  	at Context.<anonymous> (extensions/notebook/out/test/book/bookTrustManager.test.js:311:65)
  	at process.processImmediate (node:internal/timers:466:21)

  4) BookTrustManagerTests
       TrustingInFolder
         Trusting in Workspaces using the jupyter-book legacy version < 0.7.0
           should NOT trust a notebook when removing all books from folders:
     AssertionError: Notebook should be trusted
  	at Assertion.fail (extensions/notebook/node_modules/should/cjs/should.js:275:17)
  	at Assertion.value (extensions/notebook/node_modules/should/cjs/should.js:356:19)
  	at Context.<anonymous> (extensions/notebook/out/test/book/bookTrustManager.test.js:320:54)
  	at process.processImmediate (node:internal/timers:466:21)

  5) BookTrustManagerTests
       TrustingInFolder
         Trusting in Workspaces using jupyter-book versions >= 0.7.0
           should trust notebooks in a trusted book in a folder:
     AssertionError: Notebook 1 should be trusted
  	at Assertion.fail (extensions/notebook/node_modules/should/cjs/should.js:275:17)
  	at Assertion.value (extensions/notebook/node_modules/should/cjs/should.js:356:19)
  	at Context.<anonymous> (extensions/notebook/out/test/book/bookTrustManager.test.js:293:55)
  	at process.processImmediate (node:internal/timers:466:21)

  6) BookTrustManagerTests
       TrustingInFolder
         Trusting in Workspaces using jupyter-book versions >= 0.7.0
           should trust notebook after book has been added to a folder:
     AssertionError: Notebook should be trusted
  	at Assertion.fail (extensions/notebook/node_modules/should/cjs/should.js:275:17)
  	at Assertion.value (extensions/notebook/node_modules/should/cjs/should.js:356:19)
  	at Context.<anonymous> (extensions/notebook/out/test/book/bookTrustManager.test.js:311:65)
  	at process.processImmediate (node:internal/timers:466:21)

  7) BookTrustManagerTests
       TrustingInFolder
         Trusting in Workspaces using jupyter-book versions >= 0.7.0
           should NOT trust a notebook when removing all books from folders:
     AssertionError: Notebook should be trusted
  	at Assertion.fail (extensions/notebook/node_modules/should/cjs/should.js:275:17)
  	at Assertion.value (extensions/notebook/node_modules/should/cjs/should.js:356:19)
  	at Context.<anonymous> (extensions/notebook/out/test/book/bookTrustManager.test.js:320:54)
  	at process.processImmediate (node:internal/timers:466:21)
```

**Comment by kburtram** [comment]
This PR disables these tests while enabling the other extension test cases https://github.com/microsoft/azuredatastudio/pull/23497.
