### ISSUE TITLE
Null ref error when closing query editor

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#23603]
1. Right click on a scriptable object and select "Script as Create" (this happens for other actions such as Select Top 1000 as well)
2. When new editor window opens up close it

This error appears in the console

``` 
ERR Cannot read properties of undefined (reading 'savePassword'): TypeError: Cannot read properties of undefined (reading 'savePassword')
    at e.ServerTreeView.disconnectConnection (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2625:41713)
    at vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2625:34772
    at a.invoke (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:180:145)
    at c.deliver (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:180:2680)
    at s.fire (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:180:2213)
    at wa._notifyDisconnected (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:97919)
    at vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:94445
```

**Comment by cheenamalhotra** [comment]
Same cause as #22883 - closing as duplicate.
