### ISSUE TITLE
Drag-and-Drop connection profile into groups is not working

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#23931]
- Azure Data Studio Version: Insiders, 1.45-RC1
- OS Version: Windows 11

Steps to Reproduce:

1. Create a connection
2. Create a server group
3. Drag connection to server group

Dragging fails with console error:

```
[error] No provider found for old URI : 'connection:providerName:MSSQL|authenticationType:Integrated|connectionName:New|server:localhost\MSSQLSERVER01|trustServerCertificate:true|groupId:C777F06B-202E-4480-B475-FA416154D458'
Error: Could not find provider for uri: connection:providerName:MSSQL|authenticationType:Integrated|connectionName:New|server:localhost\MSSQLSERVER01|trustServerCertificate:true|groupId:C777F06B-202E-4480-B475-FA416154D458
    at wa.changeConnectionUri (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Azure%20Data%20Studio%20-%20RC1/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:90841) [<root>]
    at wa.changeGroupIdForConnection (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Azure%20Data%20Studio%20-%20RC1/resources/app/out/vs/workbench/workbench.desktop.main.js:2384:89896) [<root>]
```

Issue got introduced with #23758 and #23791 in both builds.

**Comment by cheenamalhotra** [comment]
Fix verified in latest RC build.
