### ISSUE TITLE
Spinning wheel never stops

### ISSUE THREAD

**Issue by arnold-overby-SIM** [microsoft/azuredatastudio#24442]
Type: <b>Bug</b>

When connecting to an Azure SQL Server, the spinning wheel never stops.  
In the Output window:
2023-09-15 10:04:05.086 [error] editor input was null
2023-09-15 10:04:06.306 [error] TreeError [ServerTreeView] Data tree node not found: [object Object]: Error: TreeError [ServerTreeView] Data tree node not found: [object Object]
    at new I (vscode-file://vscode-app/c:/Users/{user-redacted}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:68:75822) [<root>]
    at e.AsyncServerTree.getDataNode (vscode-file://vscode-app/c:/Users/{user-redacted}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:826:20315) [<root>]
    at e.AsyncServerTree.getDataNode (vscode-file://vscode-app/c:/Users/{user-redacted}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:1297:10714) [<root>]
    at e.AsyncServerTree.rerender (vscode-file://vscode-app/c:/Users/{user-redacted}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:826:17775) [<root>]
    at vscode-file://vscode-app/c:/Users/{user-redacted}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2625:34947 [<root>]
    at l.invoke (vscode-file://vscode-app/c:/Users/{user-redacted}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:180:145) [<root>]
    at c.deliver (vscode-file://vscode-app/c:/Users/{user-redacted}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:180:2468) [<root>]
    at s.fire (vscode-file://vscode-app/c:/Users/{user-redacted}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:180:2001) [<root>]
    at e.ObjectExplorerService.sendUpdateNodeEvent (vscode-file://vscode-app/c:/Users/{user-redacted}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:917:33301) [<root>]
    at e.ObjectExplorerService.handleSessionCreated (vscode-file://vscode-app/c:/Users/{user-redacted}/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:917:32578) [<root>]

Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:37.945Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (0.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by arnold-overby-SIM** [comment]
> Hi @arnold-overby-SIM, were you connecting to an azure server? Please follow the github steps to provide any additional logs that might be relevant in this case.

Yes, when I referred to "...connecting to an Azure SQL Server", that is an azure server. 
Steps to reproduce:

1. Open Azure Data Studio
2. Observe server connections listed under Servers

Some Azure SQL servers show the green dot when connecting, with a spinning circle that never stops, and the node cannot be expanded to see Tables, Views, etc., although queries can be executed successfully.
Other Azure SQL servers with a green dot can be expanded to view Tables, Views, etc.
Observe Output window and see results similar to what was shared previously, starting with:
[error] TreeError [ServerTreeView] Data tree node not found: [object Object]: Error: TreeError [ServerTreeView] Data tree node not found: [object Object]

**Comment by anthonylevine** [comment]
This issue has been plaguing me for over a year now. I've disabled all plugins, and yet the first 2-3 times I open Azure Data Studio and double-click on the connection icon it will spin, turn green, but refuse to stop spinning, This prevents you from expanding the tables. I've attached both of the requested logs. Hopefully it helps as it;s super frustrating to have to open and close Studio a handful of times each restart. Thanks.

[VSCodeLogs.zip](https://github.com/user-attachments/files/16548596/VSCodeLogs.zip)
[console.log](https://github.com/user-attachments/files/16548597/console.log)

**Comment by jamie-steele** [comment]
I have been also experiencing this for over a year, both on on prem SQL servers and Azure Managed ones, I also do not get any errors when looking at the console.

**Comment by anthonylevine** [comment]
Here is an error I'm getting in the console that appears to be related: ![Image](https://github.com/user-attachments/assets/2e6e8abc-4bd1-454a-9991-dad8f323c59a)
