### ISSUE TITLE
Results don't display

### ISSUE THREAD

**Issue by ricmazz** [microsoft/azuredatastudio#24669]
Type: <b>Bug</b>

I just run a query and the result panel shows a row with the data as null, but has data to show and does't display correctly.
![image](https://github.com/microsoft/azuredatastudio/assets/27751107/23516fc1-5a03-4e5a-be7f-a1550a2b1ed5)

Azure Data Studio version: azuredatastudio 1.46.1 (ba29842b81dec01177415e53948ca2168e69c3f8, 2023-10-02T18:14:22.887Z)
OS version: Windows_NT x64 10.0.23475
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx   (4 x 2595)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|5.88GB (1.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by GridTrekkor** [comment]
I'm having a similar issue.  A query on a certain table never displays results correctly (other tables do work).  The column headers appear, but no data initially appears.  Scrolling up and down in the results sometimes shows data, but not all of it, and the first several rows never appear.

Here is an example of one console error

```
 ERR Text data outside of root node.
Line: 1
Column: 12
Char: F: Error: Text data outside of root node.
Line: 1
Column: 12
Char: F
    at error (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\sax\lib\sax.js:651:10) [<root>]
    at strictFail (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\sax\lib\sax.js:677:7) [<root>]
    at SAXParser.write (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\sax\lib\sax.js:1035:15) [<root>]
    at exports.Parser.Parser.parseString (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\xml2js\lib\parser.js:337:31) [<root>]
    at Parser.parseString (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\xml2js\lib\parser.js:5:59) [<root>]
    at exports.parseString (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\xml2js\lib\parser.js:383:19) [<root>]
    at Ce (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3600:52859) [<root>]
    at formatter (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3600:34481) [<root>]
    at appendCellHtml (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\slickgrid\slick.grid.js:1902:48) [<root>]
    at appendRowHtml (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\slickgrid\slick.grid.js:1851:13) [<root>]
    at renderRows (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\slickgrid\slick.grid.js:2438:9) [<root>]
    at SlickGrid.render (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\slickgrid\slick.grid.js:2509:7) [<root>]
    at o.invalidateRows (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:325:64418) [<root>]
    at ve.invalidateRange (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3600:50621) [<root>]
    at ve.renderGridDataRowsRange (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3600:50523) [<root>]
    at T.collectionChangedCallback (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3600:36887) [<root>]
    at D.r [as loadCompleteCallback] (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:139:39830) [<root>]
    at vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:139:39545 [<root>]
    at C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1326:38 [<root>]
    at drainMicroTaskQueue (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:632:39) [<root>]
```

**Comment by ylmFuchs** [comment]
I,ve had this happen to me too, with the same Error log.
` ERR Text data outside of root node.`
In my case it seems to be triggered by a nvarchar(max) column which has xml-like values in it, none of which are longer than 60-70 chars. 
If i query for every column except this one my results appear.

**Comment by cheenamalhotra** [comment]
Could you try the [latest insiders build](https://github.com/microsoft/azuredatastudio?tab=readme-ov-file#try-out-the-latest-insiders-build-from-main-branch)?

**Comment by ylmFuchs** [comment]
@cheenamalhotra this seems to have fixed the issue

**Comment by ricmazz** [comment]
@cheenamalhotra this seems to have fixed here too. , thks.
