### ISSUE TITLE
Opening 500 mb tsql files causes  Invalid string length. error

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#2467]
- SQL Operations Studio Version:

Steps to Reproduce:

1. Open a TSQL file which is 578 Mb in length. 

This at first gives the following message:

_AdventureWorks100.Sql: tokenization, wrapping and folding have been turned off for this large file in order to reduce memory usage and avoid freezing or crashing._

After the above message the file
(which also turns off all intellisense and color coding) and give an option to the user to forcibly enable the feature (which sets "editor.largeFileOptimizations": false ). If users continues with intellisense, tokenization, wrapping and folding off then the file opens correctly (without any highlighting).

Now if I proceed to run the TSQL, I get the following errors:
` INFO no standard startup: not the explorer viewlet
2D:\src\2\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:2280 Line (FROM 0x4D5A9000...): longer than 20k characters, tokenization skipped.
D:\src\2\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] debugger listening on port 5870
D:\src\2\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] debugger inspector at chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:5870/e1efd657-ee28-4815-a3b6-182e0cc1cb25
D:\src\2\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:2280 

**_[Extension Host] (node:3868) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated._** Use os.tmpdir() instead. (at writeOut (internal/process/warning.js:18:20))
console.(anonymous function) @ D:\src\2\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:2280
3D:\src\2\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:388 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
2D:\src\2\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:2280 Line (FROM 0x4D5A9000...): longer than 20k characters, tokenization skipped.
2D:\src\2\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:2280

   _**ERR Invalid string length: RangeError: Invalid string length**_
    at PieceTreeBase.getValueInRange2 (file:///D:/src/2/sqlopsstudio/out/vs/editor/common/model/pieceTreeTextBuffer/pieceTreeBase.js:401:37)
    at PieceTreeBase.getValueInRange (file:///D:/src/2/sqlopsstudio/out/vs/editor/common/model/pieceTreeTextBuffer/pieceTreeBase.js:367:30)
    at PieceTreeTextBuffer.getValueInRange (file:///D:/src/2/sqlopsstudio/out/vs/editor/common/model/pieceTreeTextBuffer/pieceTreeTextBuffer.js:61:36)
    at Function.ModelServiceImpl._computeEdits (file:///D:/src/2/sqlopsstudio/out/vs/editor/common/services/modelServiceImpl.js:379:84)
    at ModelServiceImpl.updateModel (file:///D:/src/2/sqlopsstudio/out/vs/editor/common/services/modelServiceImpl.js:335:59)
    at TextFileEditorModel.BaseTextEditorModel.updateTextEditorModel (file:///D:/src/2/sqlopsstudio/out/vs/workbench/common/editor/textEditorModel.js:116:31)
    at TextFileEditorModel.doUpdateTextModel (file:///D:/src/2/sqlopsstudio/out/vs/workbench/services/textfile/common/textFileEditorModel.js:337:22)
    at TextFileEditorModel.doLoadWithContent (file:///D:/src/2/sqlopsstudio/out/vs/workbench/services/textfile/common/textFileEditorModel.js:320:29)
    at TextFileEditorModel.loadWithContent (file:///D:/src/2/sqlopsstudio/out/vs/workbench/services/textfile/common/textFileEditorModel.js:271:25)
    at textFileService.resolveTextContent.then.result (file:///D:/src/2/sqlopsstudio/out/vs/workbench/services/textfile/common/textFileEditorModel.js:244:34)
    at Object.notifySuccess [as _notify] (file:///D:/src/2/sqlopsstudio/out/vs/base/common/winjs.base.js:1191:59)
    at Object.enter (file:///D:/src/2/sqlopsstudio/out/vs/base/common/winjs.base.js:867:30)
    at Promise_ctor._run (file:///D:/src/2/sqlopsstudio/out/vs/base/common/winjs.base.js:1089:29)
    at Promise_ctor._completed (file:///D:/src/2/sqlopsstudio/out/vs/base/common/winjs.base.js:1057:18)
    at IconvLiteDecoderStream.<anonymous> (file:///D:/src/2/sqlopsstudio/out/vs/editor/common/model/textModel.js:46:21)
    at ZoneDelegate.invokeTask (D:\src\2\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (D:\src\2\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:188:47)
    at ZoneTask.invokeTask (D:\src\2\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:496:34)
    at IconvLiteDecoderStream.ZoneTask.invoke (D:\src\2\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:485:48)
    at emitNone (events.js:111:20)
    at IconvLiteDecoderStream.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at ZoneDelegate.invokeTask (D:\src\2\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (D:\src\2\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:188:47)
    at ZoneTask.invokeTask (D:\src\2\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:496:34)
    at ZoneTask.invoke (D:\src\2\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:485:48)
    at data.args.(anonymous function) (D:\src\2\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:1338:25)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
D:\src\2\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:2280   

**_ERR Cannot read property 'value' of null: TypeError: Cannot read property 'value' of null_**
    at HistoryInputBox.get [as value] (file:///D:/src/2/sqlopsstudio/out/vs/base/browser/ui/inputbox/inputBox.js:154:35)
    at HistoryInputBox.addToHistory (file:///D:/src/2/sqlopsstudio/out/vs/base/browser/ui/inputbox/inputBox.js:405:22)
    at FindWidget._updateHistory (file:///D:/src/2/sqlopsstudio/out/vs/editor/contrib/find/findWidget.js:222:42)
    at file:///D:/src/2/sqlopsstudio/out/vs/base/common/async.js:272:28
    at Object.notifySuccess [as _notify] (file:///D:/src/2/sqlopsstudio/out/vs/base/common/winjs.base.js:1191:59)
    at Object.enter (file:///D:/src/2/sqlopsstudio/out/vs/base/common/winjs.base.js:867:30)
    at Promise_ctor._run (file:///D:/src/2/sqlopsstudio/out/vs/base/common/winjs.base.js:1089:29)
    at Promise_ctor._completed (file:///D:/src/2/sqlopsstudio/out/vs/base/common/winjs.base.js:1057:18)
    at file:///D:/src/2/sqlopsstudio/out/vs/base/common/async.js:277:23
D:\src\2\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:2280 WARNING: Promise with no error callback:82
D:\src\2\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:2280 Object
D:\src\2\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:2280 TypeError: Cannot read property 'value' of null
    at HistoryInputBox.get [as value] (inputBox.ts:251)
    at HistoryInputBox.addToHistory (inputBox.ts:549)
    at FindWidget._updateHistory (findWidget.ts:315)
    at async.ts:289
    at Object.notifySuccess [as _notify] (winjs.base.js:1191)
    at Object.enter (winjs.base.js:867)
    at Promise_ctor._run (winjs.base.js:1089)
    at Promise_ctor._completed (winjs.base.js:1057)
    at async.ts:295`

If the user turns editor.largeFileOptimizations to false and reopens the file they get this error:
`Unable to open 'AdventureWorks100.Sql': Invalid string length.`
and predictably the file fails to be opened.

**Comment by abist** [comment]
@ranasaria do you have the 500mb sql file drop somewhere?

**Comment by kburtram** [comment]
Closing older issues.  There are have been several improvements related to large file handling.  Please reactive if you are still impacted by this issue.
