### ISSUE TITLE
Publishing SQL Project is giving an error

### ISSUE THREAD

**Issue by cpichuka** [microsoft/azuredatastudio#24670]
Version: 1.47.0-insider (user setup)
Commit: f1467cdd72de9f22ef7e433df114523663b7dabe
Date: 2023-10-12T05:44:36.268Z
VS Code: 1.79.2
Electron: 22.3.25
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:
One of our PM is facing this issue
1. Publish the SQL Project, getting below error
> "C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\Users\\niball\\DB1\\testlocal\\testlocal.sqlproj" /p:NetCoreBuild=true /p:SystemDacpacsLocation="c:\\Users\\niball\\.azuredatastudio-insiders\\extensions\\microsoft.sql-database-projects-1.4.0\\BuildDirectory"

    stdout: MSBuild version 17.3.2+561848881 for .NET

    stdout:

    stdout: c:\Users\niball\DB1\testlocal\testlocal.sqlproj : error : Unable to resolve 'Microsoft.Build.Sql (= 0.1.10-preview)' for '.NETStandard,Version=v0.0'.

    stdout:

    stdout: c:\Users\niball\DB1\testlocal\testlocal.sqlproj : error MSB4236: The SDK 'Microsoft.Build.Sql/0.1.10-preview' specified could not be found.

    stdout:

    stdout:

    stdout: Build FAILED.

    stdout:

    stdout:

    stdout: c:\Users\niball\DB1\testlocal\testlocal.sqlproj : error : Unable to resolve 'Microsoft.Build.Sql (= 0.1.10-preview)' for '.NETStandard,Version=v0.0'.

    stdout: c:\Users\niball\DB1\testlocal\testlocal.sqlproj : error MSB4236: The SDK 'Microsoft.Build.Sql/0.1.10-preview' specified could not be found.

    stdout:     0 Warning(s)
    stdout:     2 Error(s)
    stdout:
    stdout:
    stdout: Time Elapsed 00:00:01.15
    stdout:
    >>> "C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\Users\\niball\\DB1\\testlocal\\testlocal.sqlproj" /p:NetCoreBuild=true /p:SystemDacpacsLocation="c:\\Users\\niball\\.azuredatastudio-insiders\\extensions\\microsoft.sql-database-projects-1.4.0\\BuildDirectory"    … exited with code: 1

    >>> "C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\Users\\niball\\DB1\\testlocal\\testlocal.sqlproj" /p:NetCoreBuild=true /p:SystemDacpacsLocation="c:\\Users\\niball\\.azuredatastudio-insiders\\extensions\\microsoft.sql-database-projects-1.4.0\\BuildDirectory"   … errored out: Process exited with code 1

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by cheenamalhotra** [comment]
Duplicate of https://github.com/microsoft/azuredatastudio/issues/24659? Please watch out for a newer build version.

**Comment by kisantia** [comment]
@cpichuka Can you try running dotnet nuget list source and make sure nuget.org is listed? If it isn't, please try adding it as mentioned in this comment: https://github.com/microsoft/azuredatastudio/issues/20240#issuecomment-1227478333

**Comment by cpichuka** [comment]
Tagging @nilabjaball as issue is happening on his instance.

**Comment by SrivenNookala** [comment]
@kisantia I would like to add that it's not working on the insiders build on macOS as well. I have checked that nuget.org is listed as well as per your earlier comment. Its working on the stable version however.

**Comment by kisantia** [comment]
are there any errors in the console? Can you also try changing the [build SDK](https://www.nuget.org/packages/Microsoft.Build.Sql) to the latest version 0.1.12-preview? I'm able to build and publish on the latest insiders on my mac, so unable to repro this.

Also try doing `dotnet build projName.sqlproj` from the terminal and check if that's working or not.

**Comment by cpichuka** [comment]
I am hitting this issue again on latest ADS

![image](https://github.com/microsoft/azuredatastudio/assets/89977091/38d6aa6c-0335-463a-982d-ca5908238409)


2023-11-17 08:47:15.933 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'github.copilot-chat' wants API proposal 'semanticSimilarity' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-11-17 08:47:17.935 [error] An unknown error occurred. Please consult the log for more details.
2023-11-17 08:47:22.697 [info] [perf] Render performance baseline is 77ms
2023-11-17 08:47:58.461 [error] An unknown error occurred. Please consult the log for more details.
2023-11-17 08:47:58.462 [error] XHR failed: Error: XHR failed
    at S.onerror [as __zone_symbol__ON_PROPERTYerror] (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:151:1408) [<root>]
    at XMLHttpRequest.wrapFn (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:815:43) [<root>]
    at ZoneTask.invokeTask [as invoke] (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:525:38) [<root>]
    at invokeTask (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1727:22) [<root>]
    at globalCallback (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1758:31) [<root>]
    at XMLHttpRequest.globalZoneAwareCallback (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1794:20) [<root>]
2023-11-17 08:47:58.716 [error] An unknown error occurred. Please consult the log for more details.
2023-11-17 08:47:58.716 [error] XHR failed: Error: XHR failed
    at S.onerror [as __zone_symbol__ON_PROPERTYerror] (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:151:1408) [<root>]
    at XMLHttpRequest.wrapFn (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:815:43) [<root>]
    at ZoneTask.invokeTask [as invoke] (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:525:38) [<root>]
    at invokeTask (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1727:22) [<root>]
    at globalCallback (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1758:31) [<root>]
    at XMLHttpRequest.globalZoneAwareCallback (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1794:20) [<root>]
2023-11-17 08:48:47.865 [error] Error: net::ERR_CONNECTION_REFUSED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49935)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
2023-11-17 08:48:47.887 [error] An unknown error occurred. Please consult the log for more details.
2023-11-17 08:48:47.888 [error] net::ERR_CONNECTION_REFUSED: Error: net::ERR_CONNECTION_REFUSED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49935)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
