### ISSUE TITLE
Unable to resolve nonexistent file ... javascript.code-snippets in SQL Editor

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#24785]
- Azure Data Studio Version: Dev, Insiders
- OS Version: Windows 11

When typing in query editor, it leads to below error in console log. Seems related with some builtin JS extension which is falsely activated in SQL Editor 🤔 

```
[error] Error: Unable to read file 'c:\Users\~\Code\GitHub\azuredatastudio\extensions\javascript\snippets\javascript.code-snippets' (Error: Unable to resolve nonexistent file 'c:\Users\~\Code\GitHub\azuredatastudio\extensions\javascript\snippets\javascript.code-snippets')
    at new FileOperationError (vscode-file://vscode-app/c:/Users/~/Code/GitHub/azuredatastudio/out/vs/platform/files/common/files.js:426:13) [<root>]
    at FileService.restoreReadError (vscode-file://vscode-app/c:/Users/~/Code/GitHub/azuredatastudio/out/vs/platform/files/common/fileService.js:480:20) [<root>]
    at FileService.doReadFileStream (vscode-file://vscode-app/c:/Users/~/Code/GitHub/azuredatastudio/out/vs/platform/files/common/fileService.js:469:28) [<root>]
    at async FileService.doReadFile (vscode-file://vscode-app/c:/Users/~/Code/GitHub/azuredatastudio/out/vs/platform/files/common/fileService.js:397:28) [<root>] file:///c%3A/Users/~/Code/GitHub/azuredatastudio/extensions/javascript/snippets/javascript.code-snippets
```

**Comment by Charles-Gagnon** [comment]
This is happening for Notebooks too - @cheenamalhotra @kisantia were you going to look into this? Not sure what the user impact is, but it's filling up the console logs with a ton of stuff which isn't great.

**Comment by Charles-Gagnon** [comment]
Should hopefully be as simple as bringing over https://github.com/microsoft/vscode/blob/main/extensions/javascript/snippets/javascript.code-snippets

**Comment by cheenamalhotra** [comment]
We're also missing https://github.com/microsoft/vscode/blob/release/1.82/extensions/javascript/syntaxes/Regular%20Expressions%20(JavaScript).tmLanguage file, is that something we should bring over too?

**Comment by kisantia** [comment]
sure don't think it'll hurt to bring it over since that file was there in the previous ADS release.
