### ISSUE TITLE
AzureMonitor ext - The provided authentication is not valid for this resource

### ISSUE THREAD

**Issue by wsmelton** [microsoft/azuredatastudio#24798]
Type: <b>Bug</b>

1. Install extension
2. Authenticate to Azure tenant to list resources
3. Drill into subscription
4. Right-click LAW
5. Select Manager
6. Enter name
7. Connect
8. Error received

```
System.Exception: The Log Analytics Workspace can not be reached. Please validate the Workspace ID, the correct tenant is selected, and that you have access to the workspace. 
Error Message: The provided authentication is not valid for this resource

   at Microsoft.Kusto.ServiceLayer.DataSource.Monitor.MonitorClient.LoadMetadata(Boolean refresh) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\DataSource\Monitor\MonitorClient.cs:line 64
   at Microsoft.Kusto.ServiceLayer.DataSource.Monitor.MonitorIntellisenseClient..ctor(MonitorClient monitorClient) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\DataSource\Monitor\MonitorIntellisenseClient.cs:line 17
   at Microsoft.Kusto.ServiceLayer.DataSource.DataSourceFactory.Create(ConnectionDetails connectionDetails, String ownerUri) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\DataSource\DataSourceFactory.cs:line 44
   at Microsoft.Kusto.ServiceLayer.Connection.ReliableDataSourceConnection..ctor(ConnectionDetails connectionDetails, RetryPolicy connectionRetryPolicy, RetryPolicy commandRetryPolicy, IDataSourceFactory dataSourceFactory, String ownerUri) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\DataSource\ReliableDataSourceConnection.cs:line 65
   at Microsoft.Kusto.ServiceLayer.Connection.DataSourceConnectionFactory.CreateDataSourceConnection(ConnectionDetails connectionDetails, String ownerUri) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\Connection\DataSourceConnectionFactory.cs:line 36
   at Microsoft.Kusto.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\Connection\ConnectionService.cs:line 402
```

The details for connection documented here are not all available in current version:
https://learn.microsoft.com/en-us/azure-data-studio/extensions/azure-monitor-logs-extension#connection-details

![image](https://github.com/microsoft/azuredatastudio/assets/11204251/078666f0-2b9a-45b4-b87a-531248a5e11b)

Clicking on Advanced... shows an empty window, nothing is loaded.

I am the owner of the subscription, and the Log Analytics Workspace. I can query this workspace from the portal or via Azure PowerShell with the same credential being used in ADS.

Extension version: 0.1.9
Azure Data Studio version: azuredatastudio-insiders 1.47.0-insider (9f6ec2fe0d866f8ce0d5a29feb41432d0d9ecf56, 2023-10-26T05:34:45.530Z)
OS version: Darwin arm64 21.6.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|32.00GB (0.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by theonlyames** [comment]
I am running into the same issue, on the USGovernment Cloud.

```
System.Exception: The Log Analytics Workspace can not be reached. Please validate the Workspace ID, the correct tenant is selected, and that you have access to the workspace. 
Error Message: The provided authentication is not valid for this resource

   at Microsoft.Kusto.ServiceLayer.DataSource.Monitor.MonitorClient.LoadMetadata(Boolean refresh) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\DataSource\Monitor\MonitorClient.cs:line 64
   at Microsoft.Kusto.ServiceLayer.DataSource.Monitor.MonitorIntellisenseClient..ctor(MonitorClient monitorClient) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\DataSource\Monitor\MonitorIntellisenseClient.cs:line 17
   at Microsoft.Kusto.ServiceLayer.DataSource.DataSourceFactory.Create(ConnectionDetails connectionDetails, String ownerUri) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\DataSource\DataSourceFactory.cs:line 44
   at Microsoft.Kusto.ServiceLayer.Connection.ReliableDataSourceConnection..ctor(ConnectionDetails connectionDetails, RetryPolicy connectionRetryPolicy, RetryPolicy commandRetryPolicy, IDataSourceFactory dataSourceFactory, String ownerUri) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\DataSource\ReliableDataSourceConnection.cs:line 65
   at Microsoft.Kusto.ServiceLayer.Connection.DataSourceConnectionFactory.CreateDataSourceConnection(ConnectionDetails connectionDetails, String ownerUri) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\Connection\DataSourceConnectionFactory.cs:line 36
   at Microsoft.Kusto.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\Connection\ConnectionService.cs:line 402
```

**Comment by elvovsky** [comment]
I also have the same issue on windows 10. Extension version 0.1.9 . Azure data studio 1.47.1

**Comment by devbar** [comment]
I have the same issue after working a couple of days successfull with the tool.

**Comment by robertplata** [comment]
I am experiencing the same issue - Azure Data Studio 1.47.1.  A co-worker was able to connect successfully on an older version of Azure Data Studio.

**Comment by richardswinbank** [comment]
I also have the same issue; ADS 1.48.0, Azure Monitor Logs v0.1.9, Windows 11 Pro v10.0.22631. @cheenamalhotra I see this was added to the backlog back in November &mdash; do you know when a fix might appear in a release please?

**Comment by wsmelton** [comment]
Upvoting or hitting the 👍🏻 on the original post I recall helps prioritize for this team

**Comment by blarsern** [comment]
Same problem her, i have no solution or workaround for this. 
Can't connect our log analytics anymore.
devbar solution does not work.

**Comment by asmithamk** [comment]
Also had this issue and found that @blarsern 's fix worked for me.  For at least the time being :-)

**Comment by robertplata** [comment]
" @blarsern 's fix worked for me. For at least the time being :-) " - ditto.  

I could not find any reference to accessTokenCache in https://learn.microsoft.com/en-us/azure-data-studio/azure-connectivity.  It would be nice to have this fix documented in Learn somewhere (?).

**Comment by ingest0x** [comment]
@blarsern suggestion also worked for me
