### ISSUE TITLE
"Open Notebook Folder" command fails after opening Jupyter Book folder

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#24876]
Version: 1.46.1 (user setup)
Commit: ba29842b81dec01177415e53948ca2168e69c3f8
Date: 2023-10-02T18:14:22.887Z
VS Code: 1.79.2
Electron: 22.3.25
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

1. Go to Notebooks viewlet
2. Click "Open Jupyter Book"
3. Select book folder to open (note, you can also create a new book instead if you don't have one available. The result is the same)
4. Click "Open Notebooks in Folder" button

This error appears

```
Error running command notebook.command.openNotebookFolder: e.replace is not a function. This is likely caused by the extension that contributes notebook.command.openNotebookFolder.
```

console log has this : 

```
ERR Cannot read properties of undefined (reading 'navigate'): TypeError: Cannot read properties of undefined (reading 'navigate')
    at $.isSomeCollapsible (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3617:30261)
    at $.determineAction (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3617:30077)
    at $.onTreeCollapseStateChange (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3617:29983)
    at $.update (vscode-file://vscode-app/c:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:3617:29903)
```

Other actions seem fine, it's just the open folder one that's broken.

**Comment by Charles-Gagnon** [comment]
@chlafreniere Found this during testing, but putting it in Feb milestone since it's not a regression. Feel free to move it if you think it belongs somewhere else
