### ISSUE TITLE
Connection Dialog generates an exception reading clipboard

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#2497]
- SQL Operations Studio Version: `master`

```
[34652:0910/190013.935:INFO:CONSOLE(2280)] "TypeError: Cannot read property 'onReady' of undefined
    at ConnectionManagementService.buildConnectionInfo (file:///D:/xplat/sqlopsstudio/out/sql/parts/connection/common/connectionManagementService.js:1226:49)
    at ConnectionWidget._handleClipboard (file:///D:/xplat/sqlopsstudio/out/sql/parts/connection/connectionDialog/connectionWidget.js:97:51)
    at ConnectionWidget.focusOnOpen (file:///D:/xplat/sqlopsstudio/out/sql/parts/connection/connectionDialog/connectionWidget.js:328:18)
    at ConnectionController.focusOnOpen (file:///D:/xplat/sqlopsstudio/out/sql/parts/connection/connectionDialog/connectionController.js:146:36)
    at file:///D:/xplat/sqlopsstudio/out/sql/parts/connection/connectionDialog/connectionDialogService.js:271:36
    at new Promise_ctor (file:///D:/xplat/sqlopsstudio/out/vs/base/common/winjs.base.js:1662:17)
    at ConnectionDialogService.doShowDialog (file:///D:/xplat/sqlopsstudio/out/sql/parts/connection/connectionDialog/connectionDialogService.js:269:20)
    at file:///D:/xplat/sqlopsstudio/out/sql/parts/connection/connectionDialog/connectionDialogService.js:213:23
    at new Promise_ctor (file:///D:/xplat/sqlopsstudio/out/vs/base/common/winjs.base.js:1662:17)
    at ConnectionDialogService.showDialogWithModel (file:///D:/xplat/sqlopsstudio/out/sql/parts/connection/connectionDialog/connectionDialogService.js:211:20)
    at file:///D:/xplat/sqlopsstudio/out/sql/parts/connection/connectionDialog/connectionDialogService.js:244:31
    at new ZoneAwarePromise (D:\xplat\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:891:29)
    at ConnectionDialogService.showDialog (file:///D:/xplat/sqlopsstudio/out/sql/parts/connection/connectionDialog/connectionDialogService.js:231:20)
    at file:///D:/xplat/sqlopsstudio/out/sql/parts/connection/common/connectionManagementService.js:182:47
    at new ZoneAwarePromise (D:\xplat\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:891:29)
    at ConnectionManagementService.showConnectionDialog (file:///D:/xplat/sqlopsstudio/out/sql/parts/connection/common/connectionManagementService.js:175:20)
    at file:///D:/xplat/sqlopsstudio/out/sql/parts/connection/common/connectionManagementService.js:81:27
    at Emitter.fire (file:///D:/xplat/sqlopsstudio/out/vs/base/common/event.js:148:38)
    at CapabilitiesService.handleConnectionProvider (file:///D:/xplat/sqlopsstudio/out/sql/services/capabilities/capabilitiesService.js:104:48)
    at Emitter.fire (file:///D:/xplat/sqlopsstudio/out/vs/base/common/event.js:151:41)
    at ConnectionProviderRegistryImpl.registerConnectionProvider (file:///D:/xplat/sqlopsstudio/out/sql/workbench/parts/connection/common/connectionProviderExtension.js:19:33)
    at handleCommand (file:///D:/xplat/sqlopsstudio/out/sql/workbench/parts/connection/common/connectionProviderExtension.js:100:32)
    at file:///D:/xplat/sqlopsstudio/out/sql/workbench/parts/connection/common/connectionProviderExtension.js:112:17
    at ExtensionPoint._handle (file:///D:/xplat/sqlopsstudio/out/vs/workbench/services/extensions/common/extensionsRegistry.js:67:17)
    at ExtensionPoint.acceptUsers (file:///D:/xplat/sqlopsstudio/out/vs/workbench/services/extensions/common/extensionsRegistry.js:55:18)
    at Function.ExtensionService._handleExtensionPoint (file:///D:/xplat/sqlopsstudio/out/vs/workbench/services/extensions/electron-browser/extensionService.js:832:28)
    at file:///D:/xplat/sqlopsstudio/out/vs/workbench/services/extensions/electron-browser/extensionService.js:431:38
    at Object.notifySuccess [as _notify] (file:///D:/xplat/sqlopsstudio/out/vs/base/common/winjs.base.js:1191:59)
    at Object.enter (file:///D:/xplat/sqlopsstudio/out/vs/base/common/winjs.base.js:867:30)
    at _Base.Class.derive._creator._run (file:///D:/xplat/sqlopsstudio/out/vs/base/common/winjs.base.js:1089:29)
    at _Base.Class.derive._creator._completed (file:///D:/xplat/sqlopsstudio/out/vs/base/common/winjs.base.js:1057:18)
    at ZoneDelegate.invoke (D:\xplat\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:388:26)
    at Zone.run (D:\xplat\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:138:43)
    at D:\xplat\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (D:\xplat\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (D:\xplat\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (D:\xplat\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:595:35)
    at <anonymous>", source: D:\xplat\sqlopsstudio\node_modules\zone.js\dist\zone-node.js (2280)
[34652:0910/190014.504:INFO:CONSOLE(2280)] "%c[Extension Host] %cdebugger listening on port 5870", source: D:\xplat\sqlopsstudio\node_modules\zone.js\dist\zone-node.js (2280)
```

**Comment by kburtram** [comment]
This is fixed on the latest builds.
