### ISSUE TITLE
I can't copy query results

### ISSUE THREAD

**Issue by SavitskiAlexey** [microsoft/azuredatastudio#24979]
Type: <b>Bug</b>

Making a selection in the table

Trying to copy data from a table

The data is not copied to the clipboard

Azure Data Studio version: azuredatastudio 1.47.0 (c7c2b2f21505562d21972d4c135119d00806db4f, 2023-11-07T17:19:19.203Z)
OS version: Darwin arm64 23.2.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by SavitskiAlexey** [comment]
[console.log](https://github.com/microsoft/azuredatastudio/files/13391248/console.log)
[Архив.zip](https://github.com/microsoft/azuredatastudio/files/13391249/default.zip)

**Comment by cheenamalhotra** [comment]
Hi @SavitskiAlexey 

I do see a NRE error in logs, but it seems there's no _SqlTools.log_ captured to know where NRE happened.. can you please set `Mssql: Tracing Level` setting to `All` then restart Azure Data Studio to capture detailed traces?

**Comment by SavitskiAlexey** [comment]
But I found a copying error in the logs 

[Error - 13:26:56] Request query/copy failed.
  Message: Object reference not set to an instance of an object.
  Code: 0 
[Error - 14:39:25] Request query/copy failed.
  Message: Object reference not set to an instance of an object.
  Code: 0 
[Error - 14:41:25] Request query/copy failed.
  Message: Object reference not set to an instance of an object.
  Code: 0

**Comment by SavitskiAlexey** [comment]
<img width="897" alt="image" src="https://github.com/microsoft/azuredatastudio/assets/102525058/d13ddee2-4dfd-4177-8099-dfa03
[console.log](https://github.com/microsoft/azuredatastudio/files/13411732/console.log)
63bffd4">
[Архив.zip](https://github.com/microsoft/azuredatastudio/files/13411734/default.zip)

**Comment by SavitskiAlexey** [comment]
[console.log](https://github.com/microsoft/azuredatastudio/files/13411765/console.log)

**Comment by SavitskiAlexey** [comment]
?

**Comment by cheenamalhotra** [comment]
Thanks for the logs @SavitskiAlexey 

I can find error from the logs now:
```
Error: 0 : query/copy : Object reference not set to an instance of an object.
   at Microsoft.SqlTools.ServiceLayer.QueryExecution.QueryExecutionService.HandleCopyResultsRequest(CopyResultsRequestParams requestParams, RequestContext`1 requestContext) in /_/src/Microsoft.SqlTools.ServiceLayer/QueryExecution/QueryExecutionService.cs:line 785
   at Microsoft.SqlTools.Hosting.Protocol.MessageDispatcher.<>c__DisplayClass35_0`2.<<SetRequestHandler>b__0>d.MoveNext() in /_/src/Microsoft.SqlTools.Hosting/Hosting/Protocol/MessageDispatcher.cs:line 163
```

It appears to be failing here: 
https://github.com/microsoft/sqltoolsservice/blob/15b57bf342c8b93b1feead462b171adba4271a16/src/Microsoft.SqlTools.ServiceLayer/QueryExecution/QueryExecutionService.cs#L785

Can you add this to your settings.json file (`F1 > Preferences: Open User Settings (JSON)`) and check if that helps?

```json
"queryEditor.results.copyRemoveNewLine": true
```

**Comment by SavitskiAlexey** [comment]
I added a line to the settings, restarted the application. 
It didn't help, I still can't copy the value from the table

**Comment by cheenamalhotra** [comment]
Can you also capture service side logging, by enabling this setting:

![image](https://github.com/microsoft/azuredatastudio/assets/13396919/79f3f3cf-3faa-4b21-9996-3930ad3fabe7)

You will notice traces in 'SQL Tools Service' output channel, where you wanna capture the Request/Response params and paste here.

**Comment by SavitskiAlexey** [comment]
Is there a solution? It's absolutely impossible to work with the database.

**Comment by SavitskiAlexey** [comment]
?

**Comment by cheenamalhotra** [comment]
Hi @SavitskiAlexey 

I am also testing on macOS arm64 (M2 pro) but cannot reproduce any issues.. can you try with the [latest insiders](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) build to see if recent fixes in XML data rendering help address your issue? Please install the Apple Silicon binary and let us know if that helped.

**Comment by SavitskiAlexey** [comment]
I installed the latest version for the apple processor, the error did not go away

**Comment by SavitskiAlexey** [comment]
?

**Comment by SavitskiAlexey** [comment]
?

**Comment by cheenamalhotra** [comment]
I just noticed this similar issue, can you check if your text size is a problem? 
https://github.com/microsoft/azuredatastudio/issues/24476#issuecomment-1733743280

**Comment by SavitskiAlexey** [comment]
Thanks, fixed it, it works now. 

Why did it work on the old version and stopped working after the update

**Comment by cheenamalhotra** [comment]
The way Copy worked before was changed recently to improve performance, and somehow didn't handle failed settings issues. Your setting was always wrong to say, it didn't come in the way of copy operation before.
