### ISSUE TITLE
Query History: Unexpected token when no queries in history

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#24993]
- Azure Data Studio Version: 1.47, latest
- OS Version: MacOS M2 pro 

Steps to Reproduce:

1. Start ADS with no queries in query history
2. I was prompted to provide password to access Azure Data Studio Safe Storage, which I did.. but it still failed with error:

```
2023-11-17 11:43:48.945 [error] [Extension Host] Error deserializing stored history items: SyntaxError: Unexpected token '�', "�gzH�����"... is not valid JSON
2023-11-17 11:43:52.101 [error] Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at EncryptionMainService.decrypt (/Users/cmalhotra/Documents/GitHub/azuredatastudio/out/vs/platform/encryption/electron-main/encryptionMainService.js:57:44)
    at Object.call (/Users/cmalhotra/Documents/GitHub/azuredatastudio/out/vs/base/parts/ipc/common/ipc.js:850:39)
    at ChannelServer.onPromise (/Users/cmalhotra/Documents/GitHub/azuredatastudio/out/vs/base/parts/ipc/common/ipc.js:287:35)
    at ChannelServer.onRawMessage (/Users/cmalhotra/Documents/GitHub/azuredatastudio/out/vs/base/parts/ipc/common/ipc.js:266:33)
    at UniqueContainer.value (/Users/cmalhotra/Documents/GitHub/azuredatastudio/out/vs/base/parts/ipc/common/ipc.js:217:73)
    at Emitter._deliver (/Users/cmalhotra/Documents/GitHub/azuredatastudio/out/vs/base/common/event.js:851:26)
    at Emitter._deliverQueue (/Users/cmalhotra/Documents/GitHub/azuredatastudio/out/vs/base/common/event.js:862:22)
    at Emitter.fire (/Users/cmalhotra/Documents/GitHub/azuredatastudio/out/vs/base/common/event.js:885:22)
    at UniqueContainer.value (/Users/cmalhotra/Documents/GitHub/azuredatastudio/out/vs/base/common/event.js:98:93)
    at Emitter._deliver (/Users/cmalhotra/Documents/GitHub/azuredatastudio/out/vs/base/common/event.js:851:26)
    at Emitter.fire (/Users/cmalhotra/Documents/GitHub/azuredatastudio/out/vs/base/common/event.js:880:22)
    at UniqueContainer.value (/Users/cmalhotra/Documents/GitHub/azuredatastudio/out/vs/base/common/event.js:117:106)
    at Emitter._deliver (/Users/cmalhotra/Documents/GitHub/azuredatastudio/out/vs/base/common/event.js:851:26)
    at Emitter.fire (/Users/cmalhotra/Documents/GitHub/azuredatastudio/out/vs/base/common/event.js:880:22)
    at fn (/Users/cmalhotra/Documents/GitHub/azuredatastudio/out/vs/base/common/event.js:413:44)
    at IpcMainImpl.wrappedListener (/Users/cmalhotra/Documents/GitHub/azuredatastudio/out/vs/base/parts/ipc/electron-main/ipcMain.js:25:21)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88632)
    at WebContents.emit (node:events:513:28)
    at WebContents.callbackTrampoline (node:internal/async_hooks:130:17)
2023-11-17 11:43:55.281 [error] [Extension Host] An error occurred when fetching encryption keys: TypeError: Cannot read properties of undefined (reading 'toString')
```

![image](https://github.com/microsoft/azuredatastudio/assets/13396919/3ea56498-6a67-4d3f-b76b-a743c2cdc22b)

**Comment by Charles-Gagnon** [comment]
Have you been swapping between 1.46 and 1.47? If so this behavior, while unfortunate, is expected since the key conversion I mentioned in the previous fix is only one-way, so you end up with the storage file being persisted with different keys in each.

**Comment by Charles-Gagnon** [comment]
For further clarification - here's the steps I expect to happen when this error occurs. 

1. Open up ADS 1.47, it creates the file and encrypts it with keys stored in the Electron secret storage
   * If it finds keys in the keytar storage (keychain/credman/etc.) then it will move those into Electron secret storage **and delete them from the keytar location**
3. Open up ADS 1.46 - it tries to fetch the keys but they don't exist (since they never existed or were deleted by 1.47). It creates new keys and then creates a new file encrypted with those keys
4. Open up ADS 1.47 again - it now tries to use the keys it had stored previously but they're no longer valid so you get junk back when decrypting the string and thus the JSON parsing fails

**Comment by cheenamalhotra** [comment]
On Mac, I think the trigger is related to running ADS in dev mode. As soon as I start a dev session this error pops up, and then stable/insiders also start showing the same error.

That's probably why not many are noticing this issue.

On Windows, I just installed the extension and only once it showed the error, so that might be related to migration of keys.

**Comment by Charles-Gagnon** [comment]
@cheenamalhotra Since this seems to be mostly occurring when also running dev mode, can we close this for now? Or at least put it in the backlog. There hasn't been any customer reported issues yet and I'm only seeing ~35 errors parsing the file a day (out of ~6k daily users, and the exact cause of the parsing failure is unknown so it could be some other issue causing those) so it doesn't seem to be affecting most people.
