### ISSUE TITLE
Expanding tables on a database with huge amount of tables gives: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Balkoth** [microsoft/azuredatastudio#25026]
Version: 1.47.0 (system setup)
Commit: c7c2b2f21505562d21972d4c135119d00806db4f
Date: 2023-11-07T17:17:45.669Z
VS Code: 1.82.0
Electron: 25.8.4
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Try to open the tables node on a database which has a huge amount of tables (f.e. Microsoft Dynamics SQL database)
2. Node expanding gets aborted and the following is reported:
```
2023-11-22 10:42:27.034 [error] Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at v.setChildren (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:861:23685)
    at v.doRefreshNode (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:861:21558)
    at async v.doRefreshSubTree (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:861:21050)
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by cheenamalhotra** [comment]
@Balkoth 

How many tables do you have in this database?

**Comment by Balkoth** [comment]
According to the database: 202359

**Comment by Balkoth** [comment]
Problem still exists:

2024-09-05 07:47:06.405 [error] Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at v.setChildren (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:861:23685)
    at v.doRefreshNode (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:861:21558)
    at async v.doRefreshSubTree (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:861:21050)

**Comment by Balkoth** [comment]
Will this ever be fixed? I mean you are propagating this as a replacement for SSMS, and this product fails to basically do an essential task it is designed to.

**Comment by Balkoth** [comment]
It's nice that the replacement for SSMS has bugs like this still open after reporting them a year ago.

**Comment by Balkoth** [comment]
```
2024-12-13 09:42:24.853 [error] Maximum call stack size exceeded: RangeError: Maximum call stack size exceeded
    at v.setChildren (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:861:23685)
    at v.doRefreshNode (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:861:21558)
    at async v.doRefreshSubTree (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:861:21050)
```
