### ISSUE TITLE
Script as Create/Alter etc. not working without password

### ISSUE THREAD

**Issue by alvise** [microsoft/azuredatastudio#25048]
- Azure Data Studio Version: 1.47
- OS Version: macOS 14.1.1

Steps to Reproduce:

1. Connect to a MSSQL without password
2. Select Script as Create/Alter etc. from the context menu on a stored procedure

it gives the error:

```
Microsoft.SqlServer.Management.Common.ConnectionFailureException: Failed to connect to server ***.***.*.***.
 ---> System.InvalidOperationException: Either Credential or both 'User ID' and 'Password' (or 'UID' and 'PWD') connection string keywords must be specified, if 'Authentication=Sql Password'.
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.<>c__DisplayClass153_0.<TryOpenWithRetry>b__0()
   at Microsoft.Data.SqlClient.SqlRetryLogicProvider.Execute[TResult](Object sender, Func`1 function)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpenWithRetry(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnectImpl()
   at Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnect()
   at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
   at Microsoft.SqlTools.SqlCore.Scripting.ScriptAsScriptingOperation.Execute() in /_/src/Microsoft.SqlTools.SqlCore/Scripting/ScriptAsScriptingOperation.cs:line 85
```

**Comment by smartguest** [comment]
This is a limitation with the ServerConnection class as defined here: https://learn.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.common.serverconnection?view=sql-smo-160 

If we provide a connection profile/string with no password, it leads to a SqlConnection that does not have a password, with a connection string that doesn't have a password property at all. This in turn leads to a ServerConnection that does not have the property in it's connection string or it's properties. Put simply, the current classes inside STS do not support blank password for Server connections.
