### ISSUE TITLE
Field containing invalid html fails to render grid results

### ISSUE THREAD

**Issue by bakman2** [microsoft/azuredatastudio#25270]
- Azure Data Studio Version:
```
Version: 1.47.1
Commit: b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e
Date: 2024-01-10T00:30:19.136Z (2 wks ago)
```
- OS Version:  Darwin arm64 23.3.0

Steps to Reproduce:

1. select * from sometable
2. table has a field containing raw html that is incorrectly formatted.

Result:

grid/rows are initially displayed and then immediately disappear with error:
```
2024-01-27 11:33:22.948 [error] Unmatched closing tag: html
Line: 0
Column: 23190
Char: >: Error: Unmatched closing tag: html
Line: 0
Column: 23190
Char: >
    at error (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/sax/lib/sax.js:651:10) [<root>]
    at strictFail (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/sax/lib/sax.js:677:7) [<root>]
    at closeTag (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/sax/lib/sax.js:879:7) [<root>]
    at SAXParser.write (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/sax/lib/sax.js:1436:13) [<root>]
    at exports.Parser.Parser.parseString (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/xml2js/lib/parser.js:337:31) [<root>]
    at Parser.parseString (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/xml2js/lib/parser.js:5:59) [<root>]
    at exports.parseString (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/xml2js/lib/parser.js:383:19) [<root>]
    at Ce (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3600:52888) [<root>]
    at formatter (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3600:34481) [<root>]
    at appendCellHtml (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/slickgrid/slick.grid.js:1902:48) [<root>]
    at appendRowHtml (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/slickgrid/slick.grid.js:1851:13) [<root>]
    at renderRows (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/slickgrid/slick.grid.js:2438:9) [<root>]
    at SlickGrid.render (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/slickgrid/slick.grid.js:2509:7) [<root>]
    at o.invalidateRows (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:325:64418) [<root>]
    at ve.invalidateRange (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3600:50621) [<root>]
    at ve.renderGridDataRowsRange (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3600:50523) [<root>]
    at T.collectionChangedCallback (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3600:36887) [<root>]
    at D.r [as loadCompleteCallback] (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:139:39830) [<root>]
    at vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:139:39545 [<root>]
    at /Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:1326:38 [<root>]
    at drainMicroTaskQueue (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:632:39) [<root>]
2024-01-27 11:33:33.079 [error] Cannot read properties of null (reading 'lastChild'): TypeError: Cannot read properties of null (reading 'lastChild')
    at ensureCellNodesInRowsCache (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/slickgrid/slick.grid.js:2270:46)
    at cleanUpAndRenderCells (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/slickgrid/slick.grid.js:2338:9)
    at render (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/slickgrid/slick.grid.js:2504:11)
    at SlickGrid.resizeCanvas (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/slickgrid/slick.grid.js:2143:7)
    at o.resizeCanvas (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:325:65834)
    at o.layout (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:325:66385)
    at ve.layout (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:3600:48114)
    at C._runner (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:328:32090)
    at C.execute (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:229:35190)
    at ht (vscode-file://vscode-app/Applications/Azure%20Data%20Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:229:35414)
    at timer (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:3155:47)
    at _ZoneDelegate.invokeTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:443:35)
    at Zone.runTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:214:51)
    at ZoneTask.invokeTask (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:525:38)
    at ZoneTask.invoke (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:514:52)
    at data.args.<computed> (/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone.js:3135:36)
```

Does this issue occur when all extensions are disabled?: Yes (not using extensions)

**Comment by kisantia** [comment]
Could be similar to https://github.com/microsoft/azuredatastudio/issues/25004. @bakman2 can you try the [latest insiders build](https://github.com/microsoft/azuredatastudio?tab=readme-ov-file#try-out-the-latest-insiders-build-from-main-branch) and see if this is fixed?

**Comment by kisantia** [comment]
Closing as this is expected to be fixed. Please reopen if this is not fixed in the latest insiders build.
