### ISSUE TITLE
Table Design not working on Azure-SQL Tables

### ISSUE THREAD

**Issue by ralphke** [microsoft/azuredatastudio#25408]
Type: <b>Bug</b>

When using the current ADS Version: 1.49.0-insider (user setup) and trying to right click on a table to get to the degin of a table dialog, I get this error message:

   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.CreateTableDesigner(TableInfo tableInfo) in /_/src/Microsoft.SqlTools.ServiceLayer/TableDesigner/TableDesignerService.cs:line 1821
   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass20_0.<<HandleInitializeTableDesignerRequest>b__0>d.MoveNext() in /_/src/Microsoft.SqlTools.ServiceLayer/TableDesigner/TableDesignerService.cs:line 106
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass19_0`1.<<HandleRequest>b__0>d.MoveNext() in /_/src/Microsoft.SqlTools.ServiceLayer/TableDesigner/TableDesignerService.cs:line 92

Azure Data Studio version: azuredatastudio-insiders 1.49.0-insider (c511fdb40754b6c617f53632e5c17a4785e2390c, 2024-02-23T06:42:48.118Z)
OS version: Windows_NT x64 10.0.22631
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (17.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
kusto|Mic|0.5.8

</details>

**Comment by cheenamalhotra** [comment]
HI @ralphke 

The latest update resolves this issue, please update to:

Version: 1.49.0-insider (user setup)
Commit: 9c4f37f1f335528bb9e4033ad24c783d5e2db083
Date: 2024-02-26T16:04:58.597Z
VS Code: 1.82.0
Electron: 25.9.8
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

Thanks!

**Comment by ralphke** [comment]
Hi @cheenamalhotra ,
This build indeed fixes the issue.
Version: 1.49.0-insider (user setup)
Commit: a258a74d571e1eaaacfad543490dc5287e02b520
Date: 2024-02-27T06:43:23.744Z

Thanks :-)
