### ISSUE TITLE
Error when trying to connect 

### ISSUE THREAD

**Issue by garrynewman** [microsoft/azuredatastudio#25434]
Type: <b>Bug</b>

I have two ADX clusters on my account, one connects fine but the other doesn't. They have the same permissions etc.

The only real difference, which is a long shot, is that the one that won't connect has a `-` character in it.

```
[0]Kusto.Cloud.Platform.Utils.UtilsArgumentException: Invalid Kusto connection scheme: '' when using API 'Query'
Timestamp=2024-02-28T09:13:45.8544604Z
MachineName=GARRYPC2023
ProcessName=MicrosoftKustoServiceLayer
ProcessId=70292
ThreadId=27440
AppDomainName=MicrosoftKustoServiceLayer
ActivityStack=(Empty activity stack)
MethodName=
ArgumentName=
Details=

   at Kusto.Data.Net.Client.KustoClientFactory.CreateCslQueryProvider(KustoConnectionStringBuilder builder)
   at Microsoft.Kusto.ServiceLayer.DataSource.Kusto.KustoClient.Initialize(DataSourceConnectionDetails connectionDetails) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\DataSource\Kusto\KustoClient.cs:line 44
   at Microsoft.Kusto.ServiceLayer.DataSource.Kusto.KustoClient..ctor(DataSourceConnectionDetails connectionDetails, String ownerUri) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\DataSource\Kusto\KustoClient.cs:line 38
   at Microsoft.Kusto.ServiceLayer.DataSource.DataSourceFactory.Create(ConnectionDetails connectionDetails, String ownerUri) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\DataSource\DataSourceFactory.cs:line 36
   at Microsoft.Kusto.ServiceLayer.Connection.ReliableDataSourceConnection..ctor(ConnectionDetails connectionDetails, RetryPolicy connectionRetryPolicy, RetryPolicy commandRetryPolicy, IDataSourceFactory dataSourceFactory, String ownerUri) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\DataSource\ReliableDataSourceConnection.cs:line 65
   at Microsoft.Kusto.ServiceLayer.Connection.DataSourceConnectionFactory.CreateDataSourceConnection(ConnectionDetails connectionDetails, String ownerUri) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\Connection\DataSourceConnectionFactory.cs:line 36
   at Microsoft.Kusto.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.Kusto.ServiceLayer\Connection\ConnectionService.cs:line 402
```

Extension version: 0.5.8
Azure Data Studio version: azuredatastudio 1.47.1 (b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e, 2024-01-10T02:15:02.628Z)
OS version: Windows_NT x64 10.0.22631
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-14900K (32 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.83GB (39.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by madiele** [comment]
I had the same error when connecting using the browse tab and looking for the server in azure
it seems the problem is with the fact that it will populate the server field like this:

??????.westeurope.kusto.windows.net

but it should actually be like this

https://??????.westeurope.kusto.windows.net

by manually fixing the server field the issue goes away
