### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by arkdvd** [microsoft/azuredatastudio#25490]
Type: <b>Bug</b>

I am trying to publish to new Azure Sql database through DAPAC and get "Object reference not set to an instance of an object".

I got one table to deploy (no other objects). 
Edited .sqlproj for following details :
    reference Master db 
    set target DSP : Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider
    sdk:  Microsoft.Build.Sql
    Version=0.1.12-preview

Extension version: 1.14.0
Azure Data Studio version: azuredatastudio 1.48.0 (4970733324ef8254b7c22a5dc55af7f8a1dea93f, 2024-02-27T00:05:08.293Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Disabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1250P (16 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.67GB (1.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by arkdvd** [comment]
Publish errors out even with Version=0.1.14-preview 

[0.1.14-preview](https://www.nuget.org/packages/Microsoft.Build.Sql/0.1.14-preview)

**Comment by arkdvd** [comment]
@kisantia : Could you please lmk if this is any way related to visual studio ( will removing visual studio help).  I understand this error as more generic one.

**Comment by arkdvd** [comment]
I see this error in renderer.log file :

2024-03-11 20:16:31.977 [error] TreeError [ServerTreeView] Tree input not set: Error: TreeError [ServerTreeView] Tree input not set
    at new T (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:69:13338) [<root>]
    at v._updateChildren (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:861:17336) [<root>]
    at v.setInput (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:861:16986) [<root>]
    at U.handleOnCapabilitiesRegistered (vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2645:32102) [<root>]
    at vscode-file://vscode-app/c:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:72:9891 [<root>]
    at timer (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:3155:47) [<root>]
    at data.args.<computed> (C:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:3135:36) [<root>]
