### ISSUE TITLE
After update and restart it Data Studio says its not installed again and again

### ISSUE THREAD

**Issue by plppp2001** [microsoft/azuredatastudio#25523]
We have written the needed data into your clipboard because it was too large 
Type: <b>Bug</b>

[2024-03-20T11:05:51.008Z] Executing command: '"C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version'
[2024-03-20T11:05:53.162Z] stdout: azure-cli                         2.58.0

core                              2.58.0
telemetry                          1.1.0

Extensions:
arcdata                          Unknown

Dependencies:
msal                              1.26.0
azure-mgmt-resource             23.1.0b2

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\PaulA\.azure\cliextensions'

Python (Windows) 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:13:08) [MSC v.1937 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal

Your CLI is up-to-date.
[2024-03-20T11:05:53.163Z] Executing command: 'az extension update --name arcdata'
[2024-03-20T11:05:53.793Z] stderr: ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: Expected 1 module to load starting with 'azext_': got []. Please delete C:\Users\PaulA\.azure\cliextensions\arcdata and install the extension again.
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 518, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 426, in load_command_table
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 320, in _update_command_table_from_extensions
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 307, in _filter_modname
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/__init__.py", line 308, in get_extension_modname
AssertionError: Expected 1 module to load starting with 'azext_': got []. Please delete C:\Users\PaulA\.azure\cliextensions\arcdata and install the extension again.
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
[2024-03-20T11:05:53.794Z] Unexpected exit code from command: ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: Expected 1 module to load starting with 'azext_': got []. Please delete C:\Users\PaulA\.azure\cliextensions\arcdata and install the extension again.
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 518, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 426, in load_command_table
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 320, in _update_command_table_from_extensions
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 307, in _filter_modname
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/__init__.py", line 308, in get_extension_modname
AssertionError: Expected 1 module to load starting with 'azext_': got []. Please delete C:\Users\PaulA\.azure\cliextensions\arcdata and install the extension again.
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues (1)
[2024-03-20T11:05:53.794Z] Could not find Azure CLI. Error: Unexpected exit code from command: ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: Expected 1 module to load starting with 'azext_': got []. Please delete C:\Users\PaulA\.azure\cliextensions\arcdata and install the extension again.
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 518, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 426, in load_command_table
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 320, in _update_command_table_from_extensions
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 307, in _filter_modname
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/__init__.py", line 308, in get_extension_modname
AssertionError: Expected 1 module to load starting with 'azext_': got []. Please delete C:\Users\PaulA\.azure\cliextensions\arcdata and install the extension again.
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues (1)
[2024-03-20T11:05:53.794Z] No Azure CLI is available, run the command 'Azure CLI: Install' to enable the features that require it.
[2024-03-20T11:05:53.801Z] Prompting the user to accept the following: Could not find Azure CLI, install it now? If not then some features will not be able to function.
[2024-03-20T11:06:01.379Z] User Response on prompt to install Azure CLI: undefined

Extension version: 1.8.0
Azure Data Studio version: azuredatastudio 1.44.0 (31bee67f005648cdc9186f28ef39b4f1d6585e0f, 2023-05-19T16:53:04.348Z)
OS version: Windows_NT x64 10.0.22631
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.69GB (16.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>
to send. Please paste.

**Comment by JamesDBartlett3** [comment]
Just chiming in to say that I am also experiencing this issue. Output from ADS terminal:

> Your CLI is up-to-date.
> [2024-03-28T16:36:00.808Z] Executing command: 'az extension update --name arcdata'
> [2024-03-28T16:36:12.830Z] stderr: WARNING: Unable to load extension 'arcdata: Expected 1 module to load starting with 'azext_': got []. Please delete C:\Users\jbartlett\.azure\cliextensions\arcdata and install the extension again.'. Use --debug for more information.
> WARNING: Default enabled including preview versions for extension installation now. Disabled in May 2024. Use '--allow-preview true' to enable it specifically if needed. Use '--allow-preview false' to install stable version only. 
> ERROR: The command failed with an unexpected error. Here is the traceback:
> ERROR: 'NoneType' object has no attribute 'get'
> Traceback (most recent call last):
>   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
>   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 664, in execute
>   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 731, in _run_jobs_serially
>   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 701, in _run_job
>   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 334, in __call__
>   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
>   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/extension/custom.py", line 35, in update_extension_cmd
>   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/operations.py", line 420, in update_extension
>   File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/extension/__init__.py", line 133, in get_version
> AttributeError: 'NoneType' object has no attribute 'get'

Possible culprit: I do have a D:\ drive on this machine, but it's just a USB flash drive with nothing but music on it, so I'm not sure why ADS is trying to run build scripts from there. Perhaps there's an environment variable not being properly set?

Here's my ADS & system info:

> Azure Data Studio
> Version: 1.48.0 (system setup)
> Commit: 4970733324ef8254b7c22a5dc55af7f8a1dea93f
> Date: 2024-02-27T00:05:08.293Z (1 mo ago)
> VS Code: 1.82.0
> Electron: 25.9.8
> Chromium: 114.0.5735.289
> Node.js: 18.15.0
> V8: 11.4.183.29-electron.0
> OS: Windows_NT x64 10.0.19045
