### ISSUE TITLE
tables designer loading will not be completed.

### ISSUE THREAD

**Issue by jgy2808** [microsoft/azuredatastudio#25617]
Type: <b>Performance Issue</b>

Connection > Tables > select one and right click > click Designer > open new loading designer window > This loading will not be completed...
Please check this report.
Thank you.

Azure Data Studio version: azuredatastudio 1.48.0 (4970733324ef8254b7c22a5dc55af7f8a1dea93f, 2024-02-27T00:05:08.293Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Disabled
Modes:

Extensions: none

**Comment by bam65y** [comment]
I have a similar issue.  Table Designer won't load but first I get the following error 

![image](https://github.com/microsoft/azuredatastudio/assets/40204347/1d734922-ebfb-4e9c-b923-987cb2bb1ab2)

with the following details:

   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.CreateTableDesigner(TableInfo tableInfo) in /_/src/Microsoft.SqlTools.ServiceLayer/TableDesigner/TableDesignerService.cs:line 1821
   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass20_0.<<HandleInitializeTableDesignerRequest>b__0>d.MoveNext() in /_/src/Microsoft.SqlTools.ServiceLayer/TableDesigner/TableDesignerService.cs:line 106
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass19_0`1.<<HandleRequest>b__0>d.MoveNext() in /_/src/Microsoft.SqlTools.ServiceLayer/TableDesigner/TableDesignerService.cs:line 92

I'm running on a Mac

Version: 1.48.0
Commit: 4970733324ef8254b7c22a5dc55af7f8a1dea93f
Date: 2024-02-26T20:59:15.629Z
VS Code: 1.82.0
Electron: 25.9.8
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.4.0
