### ISSUE TITLE
Create New Connection Error

### ISSUE THREAD

**Issue by jtsom** [microsoft/azuredatastudio#25814]
Type: <b>Bug</b>

When clicking the Create Connection button in the Server list, an error is displayed: "Cannot read properties of null (reading 'fullName')"

Error in console:
```
workbench.desktop.main.js:1531 TypeError: Cannot read properties of null (reading 'fullName')
    at C.run (workbench.desktop.main.js:1303:6535)
    at handler (workbench.desktop.main.js:1103:23346)
    at o.invokeFunction (workbench.desktop.main.js:918:453)
    at S._tryExecuteCommand (workbench.desktop.main.js:2322:17644)
    at S.executeCommand (workbench.desktop.main.js:2322:17001)
    at h.run (workbench.desktop.main.js:1103:22992)
    at T.runAction (workbench.desktop.main.js:227:50726)
    at T.run (workbench.desktop.main.js:227:50629)
    at A.onClick (workbench.desktop.main.js:1527:24011)
    at HTMLLIElement.<anonymous> (workbench.desktop.main.js:383:24102)
    at _ZoneDelegate.invokeTask (C:\Users\jtsombakos\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:443:35)
    at Zone.runTask (C:\Users\jtsombakos\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:214:51)
    at ZoneTask.invokeTask [as invoke] (C:\Users\jtsombakos\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:525:38)
    at invokeTask (C:\Users\jtsombakos\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1727:22)
    at globalCallback (C:\Users\jtsombakos\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1758:31)
    at HTMLLIElement.globalZoneAwareCallback (C:\Users\jtsombakos\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1794:20)
onDidChangeNotification @ workbench.desktop.main.js:1531
(anonymous) @ workbench.desktop.main.js:1531
_deliver @ workbench.desktop.main.js:139
_deliverQueue @ workbench.desktop.main.js:139
fire @ workbench.desktop.main.js:139
addNotification @ workbench.desktop.main.js:1531
error @ workbench.desktop.main.js:2403
(anonymous) @ workbench.desktop.main.js:2418
_deliver @ workbench.desktop.main.js:139
_deliverQueue @ workbench.desktop.main.js:139
fire @ workbench.desktop.main.js:139
run @ workbench.desktop.main.js:227
await in run (async)
onClick @ workbench.desktop.main.js:1527
(anonymous) @ workbench.desktop.main.js:383
_ZoneDelegate.invokeTask @ C:\Users\jtsombakos\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:443
Zone.runTask @ C:\Users\jtsombakos\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:214
ZoneTask.invokeTask @ C:\Users\jtsombakos\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:525
invokeTask @ C:\Users\jtsombakos\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1727
globalCallback @ C:\Users\jtsombakos\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1758
globalZoneAwareCallback @ C:\Users\jtsombakos\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone.js:1794
```
Azure Data Studio version: azuredatastudio 1.49.0 (6e6d22ddd74bbb4fbe344ed80b93b53489fe0239, 2024-08-01T05:19:02.202Z)
OS version: Windows_NT x64 10.0.22631
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (11.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
schema-compare|Mic|1.21.0
ADS-add-columns|sof|0.0.12
vscodeintellicode|Vis|1.3.1

</details>

**Comment by kburtram** [comment]
@jtsom I wasn't able to repro myself.  Are there any other details that would help determine what's going on?  e.g., Do you have any other connections saved already or is this the first connection?  Is this a clean install or a regression upgrading from previous version?  Is there anything being displayed in the UI when the error occurs?

**Comment by jtsom** [comment]
I do have several other connections saved. I did exit ADS and re-launch, and clicking the New Connection button did work, and not show the error. Something must have just been mucked up and the restart cleared it up. Thanks.

If it happens again, I will create another issue.

**Comment by kburtram** [comment]
Thanks for following up.  I'll see if I can figure out what's going on from call stack.
