### ISSUE TITLE
TimeSeries chart does not render correctly.

### ISSUE THREAD

**Issue by rgward** [Microsoft/azuredatastudio#2851]
- Azure Data Studio Version: 1.0.0

Steps to Reproduce:

1. Run the following query

select 'Counter', getdate(), 100
go

2. Choose from the chart options TimeSeries

Nothing is displayed.

This has worked all the way up to August Public Preview 0.32.8. It appears to have broken starting with Sept Insiders Build 0.33.7

**Comment by MattIrv** [comment]
```
 ERR "timeSeries" is not a chart type.: Error: "timeSeries" is not a chart type.
    at Chart.<anonymous> (/Users/mairvine/code/sqlopsstudio/node_modules/chart.js/src/core/core.controller.js:336:13)
    at Object.each (/Users/mairvine/code/sqlopsstudio/node_modules/chart.js/src/helpers/helpers.core.js:108:9)
    at Chart.buildOrUpdateControllers (/Users/mairvine/code/sqlopsstudio/node_modules/chart.js/src/core/core.controller.js:318:12)
    at Chart.update (/Users/mairvine/code/sqlopsstudio/node_modules/chart.js/src/core/core.controller.js:391:28)
    at Graph.set [as data] (file:///Users/mairvine/code/sqlopsstudio/out/sql/parts/query/editor/charting/insights/graphInsight.js:108:34)
    at Graph.set [as options] (file:///Users/mairvine/code/sqlopsstudio/out/sql/parts/query/editor/charting/insights/graphInsight.js:190:27)
    at Insight.set [as options] (file:///Users/mairvine/code/sqlopsstudio/out/sql/parts/query/editor/charting/insights/insight.js:52:46)
    at ChartView.buildOptions (file:///Users/mairvine/code/sqlopsstudio/out/sql/parts/query/editor/charting/chartView.js:157:38)
    at Object.set (file:///Users/mairvine/code/sqlopsstudio/out/sql/parts/query/editor/charting/chartView.js:67:34)
    at file:///Users/mairvine/code/sqlopsstudio/out/sql/parts/query/editor/charting/chartView.js:227:63
    at Emitter.fire (file:///Users/mairvine/code/sqlopsstudio/out/vs/base/common/event.js:148:38)
    at HTMLSelectElement.<anonymous> (file:///Users/mairvine/code/sqlopsstudio/out/vs/base/browser/ui/selectBox/selectBoxNative.js:26:36)
```

**Comment by kburtram** [comment]
@anthonydresser when I run the repo with #2985 merged I see the below output.  I would expect the x-axis to have the date value.  Is this correct?

<img width="1076" alt="screen shot 2018-10-23 at 1 59 46 pm" src="https://user-images.githubusercontent.com/599935/47390353-0926a480-d6cc-11e8-8da5-e07a6f74c7e3.png">

**Comment by kburtram** [comment]
Now I see the below chart from the repro SQL.  @rgward please reactive if this doesn't look as expected.  I'll publish an updated build on Friday for further validation (or you can build the fix from master in the meantime).

<img width="1085" alt="screen shot 2018-10-24 at 6 28 40 pm" src="https://user-images.githubusercontent.com/599935/47470490-d3141e00-d7ba-11e8-83bc-0b562a98cde0.png">
