### ISSUE TITLE
Error when click on databases in server pane

### ISSUE THREAD

**Issue by delta8** [microsoft/azuredatastudio#3343]
- Azure Data Studio Version 1.3.4 Insider:

Steps to Reproduce:

1. Select Server from Server Pane
2. Connect to Server of Choice
3.Click on Databases
4. Get Error "Failed to connect to server xxxxx"
5.  however I am able to query on the database.

**Comment by kburtram** [comment]
@delta8 is this using a connection with AAD authentication?

**Comment by MattIrv** [comment]
I'm running into this error now and I'm investigating how to get a consistent repro. I'm using a guest account so it may have something to do with that

**Comment by MattIrv** [comment]
Stack trace:
```
18-12-06 11:48:53.3640850 pid:88143 tid:27 sqltools Error: 0 : Failed getting smo objects. parent:<servername>.database.windows.net/Databases querier: Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SqlDatabaseQuerier error:Failed to connect to server <servername>.database.windows.net. inner:Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'. stacktrace:   at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
   at Microsoft.SqlServer.Management.Common.ConnectionManager.PoolConnect()
   at Microsoft.SqlServer.Management.Common.ConnectionManager.GetServerInformation()
   at Microsoft.SqlServer.Management.Common.ConnectionManager.get_DatabaseEngineEdition()
   at Microsoft.SqlServer.Management.Smo.ExecutionManager.GetDatabaseEngineEdition()
   at Microsoft.SqlServer.Management.Smo.Database.get_DatabaseEngineEdition()
   at Microsoft.SqlServer.Management.Smo.Database.GetPropertyMetadataProvider()
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.get_Properties()
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.AddObjectPropsFromDataReader(IDataReader reader, Boolean skipIfDirty, Int32 startColIdx, Int32 endColIdx)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.AddObjectPropsFromDataReader(IDataReader reader, Boolean skipIfDirty)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.Microsoft.SqlServer.Management.Sdk.Sfc.ISqlSmoObjectInitialize.InitializeFromDataReader(IDataReader reader)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.CreateNewObjectFromRow(AbstractCollectionBase childColl, Type childType, IDataReader reader, Int32 columnIdx, Boolean isOrderedByID, Boolean skipOrderChecking)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitObjectsFromEnumResultsRec(SqlSmoObject currentSmoObject, XPathExpression levelFilter, Int32 filterIdx, IDataReader reader, Int32 columnIdx, Object[] parentRow, Boolean forScripting, List`1 urnList, Int32 startLeafIdx)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitObjectsFromEnumResults(Urn levelFilter, IDataReader reader, Boolean forScripting, List`1 urnList, Int32 startLeafIdx, Boolean skipServer)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.DoDatabaseSpecialCase(Request levelQuery, Urn levelFilter, Boolean forScripting, List`1 urnList, Int32 startLeafIdx)
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitChildLevel(Urn levelFilter, ScriptingPreferences sp, Boolean forScripting, IEnumerable`1 extraFields)
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.InitializeChildCollection(Boolean refresh, ScriptingPreferences sp, String filterQuery, IEnumerable`1 extraFields)
   at Microsoft.SqlServer.Management.Smo.SmoCollectionBase.ClearAndInitialize(String filterQuery, IEnumerable`1 extraFields)
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SqlDatabaseQuerier.Query(SmoQueryContext context, String filter, Boolean refresh, IEnumerable`1 extraProperties) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoQueryModel.cs:line 31
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoChildFactoryBase.OnExpandPopulateNonFolders(IList`1 allChildren, TreeNode parent, Boolean refresh, String name, CancellationToken cancellationToken) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoChildFactoryBase.cs:line 127
18-12-06 11:48:53.3656200 pid:88143 tid:27 sqltools Error: 0 : Failed expanding oe children. parent:<servername>.database.windows.net/Databases error:Failed to connect to server <servername>.database.windows.net. inner:Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'. stacktrace:   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoChildFactoryBase.OnExpandPopulateNonFolders(IList`1 allChildren, TreeNode parent, Boolean refresh, String name, CancellationToken cancellationToken) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoChildFactoryBase.cs:line 148
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoChildFactoryBase.Expand(TreeNode parent, Boolean refresh, String name, Boolean includeSystemObjects, CancellationToken cancellationToken) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoChildFactoryBase.cs:line 36
18-12-06 11:48:53.3659820 pid:88143 tid:27 sqltools Error: 0 : Failed populating oe children. error:Failed to connect to server <servername>.database.windows.net. inner:Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'. stacktrace:   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoChildFactoryBase.Expand(TreeNode parent, Boolean refresh, String name, Boolean includeSystemObjects, CancellationToken cancellationToken) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoChildFactoryBase.cs:line 43
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.Nodes.TreeNode.PopulateChildren(Boolean refresh, String name, CancellationToken cancellationToken) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\Nodes\TreeNode.cs:line 346
18-12-06 11:48:53.3676320 pid:88143 tid:10 sqltools Verbose: 0 : Sending message of id[], of type[Event] and method[objectexplorer/expandCompleted]
18-12-06 11:56:00.8419610 pid:88143 tid:10 sqltools Verbose: 0 : Received message with id[6], of type[Request] and method[connection/buildconnectioninfo] , and contents[18-12-06 11:48:53.3640850 pid:88143 tid:27 sqltools Error: 0 : Failed getting smo objects. parent:<servername>.database.windows.net/Databases querier: Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SqlDatabaseQuerier error:Failed to connect to server <servername>.database.windows.net. inner:Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'. stacktrace:   at Microsoft.SqlServer.Management.Common.ConnectionManager.Connect()
   at Microsoft.SqlServer.Management.Common.ConnectionManager.PoolConnect()
   at Microsoft.SqlServer.Management.Common.ConnectionManager.GetServerInformation()
   at Microsoft.SqlServer.Management.Common.ConnectionManager.get_DatabaseEngineEdition()
   at Microsoft.SqlServer.Management.Smo.ExecutionManager.GetDatabaseEngineEdition()
   at Microsoft.SqlServer.Management.Smo.Database.get_DatabaseEngineEdition()
   at Microsoft.SqlServer.Management.Smo.Database.GetPropertyMetadataProvider()
   at Microsoft.SqlServer.Management.Smo.SqlSmoObject.get_Properties()]
```

**Comment by kburtram** [comment]
@MattIrv is this something we should fix for Dec release?

**Comment by MattIrv** [comment]
I don’t think this fix will make it for December. Still not entirely sure what’s going wrong, it will likely require digging around in SMO a bit to figure it out

**Comment by kburtram** [comment]
@MattIrv thanks!  We have until end of day tomorrow if you find a fix and think it's low risk, otherwise, I'll assume this is targeting January.

**Comment by MattIrv** [comment]
Debugged this and I understand what's happening now. It's less impact than I thought because it only affects AAD users that only have access to master or another system database but do not have access to all databases. For some reason SMO tries to connect to the first database that we find as part of listing all databases, and since the user doesn't have access to it the connection fails. Unfortunately the fix may be in SMO

**Comment by longzheng** [comment]
Also running into this issue after switching to AAD.

**Comment by kburtram** [comment]
Closing this older issue since I cannot currently repro and we've made several related bug fixes in our AAD implementation.  Please let us know if you're still experiencing problems from this issue.  Thanks!
