### ISSUE TITLE
Notebook: Could not display contents: Error: Notebook provider does not exist

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#3364]
D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:388 ERROR Error: Uncaught (in promise): Error: Notebook provider does not exist
Error: Notebook provider does not exist
    at NotebookService.doWithProvider (file:///D:/ads/azuredatastudio/out/sql/services/notebook/notebookServiceImpl.js:112:39)
    at NotebookService.<anonymous> (file:///D:/ads/azuredatastudio/out/sql/services/notebook/notebookServiceImpl.js:85:55)
    at step (file:///D:/ads/azuredatastudio/out/sql/services/notebook/notebookServiceImpl.js:35:23)
    at Object.next (file:///D:/ads/azuredatastudio/out/sql/services/notebook/notebookServiceImpl.js:16:53)
    at file:///D:/ads/azuredatastudio/out/sql/services/notebook/notebookServiceImpl.js:10:71
    at new ZoneAwarePromise (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:891:29)
    at __awaiter (file:///D:/ads/azuredatastudio/out/sql/services/notebook/notebookServiceImpl.js:6:12)
    at NotebookService.getOrCreateNotebookManager (file:///D:/ads/azuredatastudio/out/sql/services/notebook/notebookServiceImpl.js:74:20)
    at NotebookComponent.<anonymous> (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:203:71)
    at step (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:54:23)
    at Object.next (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:35:53)
    at file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:29:71
    at new ZoneAwarePromise (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:891:29)
    at __awaiter (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:25:12)
    at NotebookComponent.loadModel (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:196:20)
    at NotebookComponent.<anonymous> (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:174:55)
    at step (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:54:23)
    at Object.next (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:35:53)
    at file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:29:71
    at new ZoneAwarePromise (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:891:29)
    at __awaiter (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:25:12)
    at NotebookComponent.doLoad (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:168:20)
    at NotebookComponent.ngOnInit (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:89:18)
    at checkAndUpdateDirectiveInline (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:10822:19)
    at checkAndUpdateNodeInline (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12245:17)
    at checkAndUpdateNode (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12184:16)
    at debugCheckAndUpdateNode (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12887:59)
    at debugCheckDirectivesFn (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12828:13)
    at Object.eval [as updateDirectives] (ng:///ModuleClass/NotebookComponent_Host.ngfactory.js:23:5)
    at Object.debugUpdateDirectives [as updateDirectives] (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12813:21)
    at checkAndUpdateView (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12151:14)
    at callWithDebugContext (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:13213:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12753:12)
    at ViewRef_.detectChanges (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:10225:63)
    at D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:5082:63
    at Array.forEach (<anonymous>)
    at ApplicationRef_.tick (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:5082:25)
    at ApplicationRef_._loadComponent (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:5058:14)
    at ApplicationRef_.bootstrap (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:5046:14)
    at ModuleClass.ngDoBootstrap (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.module.js:26:24)
    at PlatformRef_._moduleDoBootstrap (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4831:32)
    at D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4790:27
    at ZoneDelegate.invoke (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:388:26)
    at Object.onInvoke (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4156:37)
    at ZoneDelegate.invoke (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:387:32)
    at Zone.run (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:138:43)
    at D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421:31)
    at Object.onInvokeTask (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4147:37)
    at ZoneDelegate.invokeTask (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:420:36)
    at Zone.runTask (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:595:35)
    at <anonymous>
    at NotebookService.doWithProvider (file:///D:/ads/azuredatastudio/out/sql/services/notebook/notebookServiceImpl.js:112:39)
    at NotebookService.<anonymous> (file:///D:/ads/azuredatastudio/out/sql/services/notebook/notebookServiceImpl.js:85:55)
    at step (file:///D:/ads/azuredatastudio/out/sql/services/notebook/notebookServiceImpl.js:35:23)
    at Object.next (file:///D:/ads/azuredatastudio/out/sql/services/notebook/notebookServiceImpl.js:16:53)
    at file:///D:/ads/azuredatastudio/out/sql/services/notebook/notebookServiceImpl.js:10:71
    at new ZoneAwarePromise (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:891:29)
    at __awaiter (file:///D:/ads/azuredatastudio/out/sql/services/notebook/notebookServiceImpl.js:6:12)
    at NotebookService.getOrCreateNotebookManager (file:///D:/ads/azuredatastudio/out/sql/services/notebook/notebookServiceImpl.js:74:20)
    at NotebookComponent.<anonymous> (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:203:71)
    at step (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:54:23)
    at Object.next (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:35:53)
    at file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:29:71
    at new ZoneAwarePromise (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:891:29)
    at __awaiter (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:25:12)
    at NotebookComponent.loadModel (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:196:20)
    at NotebookComponent.<anonymous> (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:174:55)
    at step (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:54:23)
    at Object.next (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:35:53)
    at file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:29:71
    at new ZoneAwarePromise (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:891:29)
    at __awaiter (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:25:12)
    at NotebookComponent.doLoad (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:168:20)
    at NotebookComponent.ngOnInit (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:89:18)
    at checkAndUpdateDirectiveInline (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:10822:19)
    at checkAndUpdateNodeInline (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12245:17)
    at checkAndUpdateNode (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12184:16)
    at debugCheckAndUpdateNode (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12887:59)
    at debugCheckDirectivesFn (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12828:13)
    at Object.eval [as updateDirectives] (ng:///ModuleClass/NotebookComponent_Host.ngfactory.js:23:5)
    at Object.debugUpdateDirectives [as updateDirectives] (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12813:21)
    at checkAndUpdateView (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12151:14)
    at callWithDebugContext (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:13213:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12753:12)
    at ViewRef_.detectChanges (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:10225:63)
    at D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:5082:63
    at Array.forEach (<anonymous>)
    at ApplicationRef_.tick (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:5082:25)
    at ApplicationRef_._loadComponent (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:5058:14)
    at ApplicationRef_.bootstrap (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:5046:14)
    at ModuleClass.ngDoBootstrap (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.module.js:26:24)
    at PlatformRef_._moduleDoBootstrap (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4831:32)
    at D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4790:27
    at ZoneDelegate.invoke (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:388:26)
    at Object.onInvoke (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4156:37)
    at ZoneDelegate.invoke (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:387:32)
    at Zone.run (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:138:43)
    at D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421:31)
    at Object.onInvokeTask (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4147:37)
    at ZoneDelegate.invokeTask (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:420:36)
    at Zone.runTask (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:595:35)
    at <anonymous>
    at resolvePromise (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:814:31)
    at Deferred.reject (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:724:17)
    at NotebookComponent.<anonymous> (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:184:54)
    at step (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:54:23)
    at Object.throw (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:35:53)
    at rejected (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/notebook.component.js:27:65)
    at ZoneDelegate.invoke (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:388:26)
    at Object.onInvoke (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4156:37)
    at ZoneDelegate.invoke (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:387:32)
    at Zone.run (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:138:43)
    at D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421:31)
    at Object.onInvokeTask (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4147:37)
    at ZoneDelegate.invokeTask (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:420:36)
    at Zone.runTask (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:595:35)
    at <anonymous>

Steps to Reproduce:

1. No big data cluster connected
2. Open a Notebook saved with PySpark result

**Comment by YurongHe** [comment]
Is fixed by Raj's merge.
