### ISSUE TITLE
 Error: Uncaught (in promise): TypeError: Cannot read property 'isInErrorState' of undefined

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#3366]
D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:388 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'isInErrorState' of undefined
TypeError: Cannot read property 'isInErrorState' of undefined
    at NotebookModel.<anonymous> (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:356:54)
    at step (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:45:23)
    at Object.next (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:26:53)
    at file:///D:/ads/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:20:71
    at new ZoneAwarePromise (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:891:29)
    at __awaiter (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:16:12)
    at file:///D:/ads/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:352:93
    at ZoneDelegate.invoke (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:388:26)
    at Object.onInvoke (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4156:37)
    at ZoneDelegate.invoke (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:387:32)
    at Zone.run (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:138:43)
    at D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421:31)
    at Object.onInvokeTask (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4147:37)
    at ZoneDelegate.invokeTask (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:420:36)
    at Zone.runTask (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:595:35)
    at ZoneTask.invokeTask (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:500:21)
    at Socket.ZoneTask.invoke (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:485:48)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
    at NotebookModel.<anonymous> (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:356:54)
    at step (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:45:23)
    at Object.next (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:26:53)
    at file:///D:/ads/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:20:71
    at new ZoneAwarePromise (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:891:29)
    at __awaiter (file:///D:/ads/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:16:12)
    at file:///D:/ads/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:352:93
    at ZoneDelegate.invoke (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:388:26)
    at Object.onInvoke (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4156:37)
    at ZoneDelegate.invoke (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:387:32)
    at Zone.run (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:138:43)
    at D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421:31)
    at Object.onInvokeTask (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4147:37)
    at ZoneDelegate.invokeTask (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:420:36)
    at Zone.runTask (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:595:35)
    at ZoneTask.invokeTask (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:500:21)
    at Socket.ZoneTask.invoke (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:485:48)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
    at resolvePromise (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:814:31)
    at resolvePromise (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:771:17)
    at D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:873:17
    at ZoneDelegate.invokeTask (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421:31)
    at Object.onInvokeTask (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4147:37)
    at ZoneDelegate.invokeTask (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:420:36)
    at Zone.runTask (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:595:35)
    at ZoneTask.invokeTask (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:500:21)
    at Socket.ZoneTask.invoke (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:485:48)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

Steps to Reproduce:

1. Don't connect to any big data cluster
2. Open a notebook with PySpark result

**Comment by YurongHe** [comment]
Is fixed by raj's merge.
