### ISSUE TITLE
Each data element must implement a unique 'id' property

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#3624]
Repro:
- Connect to SQL DB
- Open Home tab by select manage 
- Edit the home page by moving things around

Try to open SQL Agent tab, nothing is displayed.

Issue Type: <b>Bug</b>

ERROR Error: Each data element must implement a unique 'id' property
    at ensureIdUniqueness (D:\ads\azuredatastudio\node_modules\slickgrid\slick.dataview.js:121:17)
    at DataView.setItems (D:\ads\azuredatastudio\node_modules\slickgrid\slick.dataview.js:137:7)
    at JobsViewComponent.onJobsAvailable (file:///D:/ads/azuredatastudio/out/sql/parts/jobManagement/views/jobsView.component.js:346:27)
    at JobsViewComponent.onFirstVisible (file:///D:/ads/azuredatastudio/out/sql/parts/jobManagement/views/jobsView.component.js:192:22)
    at JobsViewComponent.JobManagementView.ngAfterContentChecked (file:///D:/ads/azuredatastudio/out/sql/parts/jobManagement/views/jobManagementView.js:49:30)
    at callProviderLifecycles (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:11165:18)
    at callElementProvidersLifecycles (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:11143:13)
    at callLifecycleHooksChildrenFirst (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:11127:17)
    at checkAndUpdateView (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12154:5)
    at callViewAction (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12514:21)
    at execEmbeddedViewsAction (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12472:17)
    at checkAndUpdateView (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12152:5)
    at callViewAction (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12514:21)
    at execEmbeddedViewsAction (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12472:17)
    at checkAndUpdateView (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12152:5)
    at callViewAction (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12514:21)
    at execEmbeddedViewsAction (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12472:17)
    at checkAndUpdateView (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12152:5)
    at callWithDebugContext (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:13213:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12753:12)
    at ViewRef_.detectChanges (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:10225:63)
    at TabComponent.set [as active] (file:///D:/ads/azuredatastudio/out/sql/base/browser/ui/panel/tab.component.js:59:30)
    at file:///D:/ads/azuredatastudio/out/sql/base/browser/ui/panel/panel.component.js:122:45
    at ZoneDelegate.invoke (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:388:26)
    at Object.onInvoke (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4156:37)
    at ZoneDelegate.invoke (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:387:32)
    at Zone.run (D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:138:43)
    at NgZone.run (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4024:62)
    at PanelComponent.selectTab (file:///D:/ads/azuredatastudio/out/sql/base/browser/ui/panel/panel.component.js:116:28)
    at Object.eval [as handleEvent] (ng:///PanelModule/PanelComponent.ngfactory.js:38:24)
    at handleEvent (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:11921:138)
    at callWithDebugContext (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:13213:42)
    at Object.debugHandleEvent [as handleEvent] (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12801:12)
    at dispatchEvent (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:8821:21)
    at D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:10749:20
    at SafeSubscriber.schedulerFn [as _next] (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:3870:36)
    at SafeSubscriber.__tryOrUnsub (D:\ads\azuredatastudio\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.next (D:\ads\azuredatastudio\node_modules\rxjs\Subscriber.js:185:22)
    at Subscriber._next (D:\ads\azuredatastudio\node_modules\rxjs\Subscriber.js:125:26)
    at Subscriber.next (D:\ads\azuredatastudio\node_modules\rxjs\Subscriber.js:89:18)
    at EventEmitter.Subject.next (D:\ads\azuredatastudio\node_modules\rxjs\Subject.js:55:25)
    at EventEmitter.emit (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:3844:76)
    at TabHeaderComponent.selectTab (file:///D:/ads/azuredatastudio/out/sql/base/browser/ui/panel/tabHeader.component.js:57:30)
    at Object.eval [as handleEvent] (ng:///PanelModule/TabHeaderComponent.ngfactory.js:103:24)
    at handleEvent (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:11921:138)
    at callWithDebugContext (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:13213:42)
    at Object.debugHandleEvent [as handleEvent] (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12801:12)
    at dispatchEvent (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:8821:21)
    at D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:9413:20
    at HTMLSpanElement.<anonymous> (D:\ads\azuredatastudio\node_modules\@angular\platform-browser\bundles\platform-browser.umd.js:2696:53)
console.(anonymous function) @ D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:2280

----

other exception:
D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:2280 ERROR TypeError: Cannot read property 'setScrollDimensions' of undefined
    at WidgetContent.resetScrollDimensions (file:///D:/ads/azuredatastudio/out/sql/parts/dashboard/contents/widgetContent.component.js:155:37)
    at file:///D:/ads/azuredatastudio/out/sql/parts/dashboard/contents/widgetContent.component.js:220:27
    at SafeSubscriber.schedulerFn [as _next] (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:3870:36)
    at SafeSubscriber.__tryOrUnsub (D:\ads\azuredatastudio\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.next (D:\ads\azuredatastudio\node_modules\rxjs\Subscriber.js:185:22)
    at Subscriber._next (D:\ads\azuredatastudio\node_modules\rxjs\Subscriber.js:125:26)
    at Subscriber.next (D:\ads\azuredatastudio\node_modules\rxjs\Subscriber.js:89:18)
    at EventEmitter.Subject.next (D:\ads\azuredatastudio\node_modules\rxjs\Subject.js:55:25)
    at EventEmitter.emit (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:3844:76)
    at t._dragStop (D:\ads\azuredatastudio\node_modules\angular2-grid\bundles\NgGrid.umd.min.js:1:16098)
    at t.mouseUpEventHandler (D:\ads\azuredatastudio\node_modules\angular2-grid\bundles\NgGrid.umd.min.js:1:9793)
    at Object.eval [as handleEvent] (ng:///ModuleClass/WidgetContent.ngfactory.js:128:42)
    at handleEvent (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:11921:138)
    at callWithDebugContext (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:13213:42)
    at Object.debugHandleEvent [as handleEvent] (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12801:12)
    at dispatchEvent (D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:8821:21)
    at D:\ads\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:9413:20
    at HTMLDivElement.<anonymous> (D:\ads\azuredatastudio\node_modules\@angular\platform-browser\bundles\platform-browser.umd.js:2696:53)
Azure Data Studio version: azuredatastudio 1.3.8 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz (48 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|255.93GB (179.76GB free)|
|Process Argv|D:\ads\azuredatastudio\.build\electron\azuredatastudio.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.9.1

</details>

**Comment by kburtram** [comment]
Closing older issues.  Please reactivate if you're still impacted by this.
