### ISSUE TITLE
Agent/Slickgrid: Resizing slickgrid columns breaks agent

### ISSUE THREAD

**Issue by abist** [Microsoft/azuredatastudio#3636]
- Azure Data Studio Version: master

Steps to Reproduce: Resize any column

Error stack trace - 

```
TypeError: data.grid.getColumnWidths is not a function
    at SlickGrid.<anonymous> (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/out/sql/parts/jobManagement/views/jobsView.component.js:360:43)
    at Event.notify (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\slickgrid\slick.core.js:145:35)
    at trigger (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\slickgrid\slick.grid.js:1264:18)
    at HTMLDivElement.<anonymous> (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\slickgrid\slick.grid.js:1086:15)
    at HTMLDivElement.dispatch (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\jquery\dist\jquery.js:5110:27)
    at HTMLDivElement.$event.dispatch (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/node_modules/slickgrid/lib/jquery.event.drag-2.3.0.js:382:30)
    at HTMLDivElement.<anonymous> (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/node_modules/slickgrid/lib/jquery.event.drag-2.3.0.js:267:60)
    at Function.each (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\jquery\dist\jquery.js:368:19)
    at jQuery.fn.init.each (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\jquery\dist\jquery.js:157:17)
    at Object.hijack (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/node_modules/slickgrid/lib/jquery.event.drag-2.3.0.js:261:61)
    at HTMLDocument.handler (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/node_modules/slickgrid/lib/jquery.event.drag-2.3.0.js:217:34)
    at HTMLDocument.dispatch (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\jquery\dist\jquery.js:5110:27)
    at HTMLDocument.$event.dispatch (file:///C:/Users/adbist/Desktop/SQL_Tools/sqlopsstudio/node_modules/slickgrid/lib/jquery.event.drag-2.3.0.js:382:30)
    at HTMLDocument.elemData.handle (C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\jquery\dist\jquery.js:4918:28)
console.(anonymous function) @ C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:2280
onError @ index.js:44
(anonymous) @ index.js:170
ZoneDelegate.invokeTask @ C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:421
Zone.runTask @ C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:188
ZoneTask.invokeTask @ C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:496
ZoneTask.invoke @ C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\node_modules\zone.js\dist\zone-node.js:485
emitOne @ events.js:116
emit @ events.js:211
window.onerror @ C:\Users\adbist\Desktop\SQL_Tools\sqlopsstudio\.build\electron\resources\electron.asar\renderer\init.js:142
```

**Comment by abist** [comment]
@anthonydresser Any idea about this?
