### ISSUE TITLE
Reference to database and/or server name in 'model.sys.assemblies' is not supported in this version of SQL Server.

### ISSUE THREAD

**Issue by sadjadbp** [Microsoft/azuredatastudio#3839]
Steps to Reproduce:

1. Updated to the latest inside version 1.4.3 and now cannot connect to my Azure SQL DBs they all fail with

Reference to database and/or server name in 'model.sys.assemblies' is not supported in this version of SQL Server.

System.Data.SqlClient.SqlException (0x80131904): Reference to database and/or server name in 'model.sys.assemblies' is not supported in this version of SQL Server.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableConnectionHelper.ExecuteReader(IDbConnection conn, String commandText, Action`1 readResult, Action`1 initializeCommand, Predicate`1 catchException) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ReliableConnection\ReliableConnectionHelper.cs:line 393
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableConnectionHelper.<>c__DisplayClass22_0.<IsSqlDwDatabase>b__0(String commandText) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ReliableConnection\ReliableConnectionHelper.cs:line 496
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableConnectionHelper.IsSqlDwDatabase(IDbConnection connection) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ReliableConnection\ReliableConnectionHelper.cs:line 508
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.IsSqlDwConnection(IDbConnection conn) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ReliableConnection\ReliableSqlConnection.cs:line 119
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ReliableConnection\ReliableSqlConnection.cs:line 304
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 521
ClientConnectionId:ed582e63-b20b-4399-9a3e-7d6e57cb9063
Error Number:40515,State:1,Class:15

**Comment by YurongHe** [comment]
@sadjadbp thank you for report the issue. I have fixed the issue. The fix is merged into SQLToolService repro now. Waiting for the official build to release.
