### ISSUE TITLE
Query results contain duplicate messages and results

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#3917]
- Azure Data Studio Version: `master` (today's insider build)

Steps to Reproduce:

1. Run a query

Expected: correct rendering

Actual: Messages and results can sometime be duplicated.  This has inconsistent repro, but we need to fix the code paths to avoid this type of problem.

![image](https://user-images.githubusercontent.com/599935/52366665-296e3b00-29ff-11e9-87ab-4e98c07d98cd.png)

**Comment by kburtram** [comment]
@anthonydresser could you please prioritize getting the remain query editor rendering issues fixed for the Feb release?  We can't keep shipping with this type of bug in our most core scenarios.

**Comment by kburtram** [comment]
Here's what I see in the Dev Console.  Note rerunning the query does not remove the extra results\messages controls.

```
 ERR Cannot read property 'queryRunner' of undefined: TypeError: Cannot read property 'queryRunner' of undefined
    at QueryResultsView.set [as input] (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:304656:82)
    at QueryResultsEditor.setInput (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:304876:36)
    at QueryEditor._onResultsEditorCreated (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:190594:40)
    at file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:190274:23
    at CompletePromise_ctor.CompletePromise_then [as then] (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:17893:49)
    at QueryEditor._showQueryResultsEditor (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:190273:18)
    at file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:190162:103
    at Emitter.fire (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:20051:38)
    at QueryInput.showQueryResultsEditor (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:162001:98)
    at QueryInput.runQuery (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:162064:18)
    at QueryInput.onConnectSuccess (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:162102:26)
    at file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:331558:51
    at ZoneDelegate.invoke (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:388:26)
    at Zone.run (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:138:43)
    at C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:595:35)
    at ZoneTask.invokeTask (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:500:21)
    at Socket.ZoneTask.ZoneTask.cancelFn.invoke (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:485:48)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 WARNING: Promise with no error callback:69
C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Object
C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 TypeError: Cannot read property 'queryRunner' of undefined
    at QueryResultsView.set [as input] (workbench.main.js:304656)
    at QueryResultsEditor.setInput (workbench.main.js:304876)
    at QueryEditor._onResultsEditorCreated (workbench.main.js:190594)
    at workbench.main.js:190274
    at CompletePromise_ctor.CompletePromise_then [as then] (workbench.main.js:17893)
    at QueryEditor._showQueryResultsEditor (workbench.main.js:190273)
    at workbench.main.js:190162
    at Emitter.fire (workbench.main.js:20051)
    at QueryInput.showQueryResultsEditor (workbench.main.js:162001)
    at QueryInput.runQuery (workbench.main.js:162064)
    at QueryInput.onConnectSuccess (workbench.main.js:162102)
    at workbench.main.js:331558
    at ZoneDelegate.invoke (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:388)
    at Zone.run (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:138)
    at C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:872
    at ZoneDelegate.invokeTask (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421)
    at Zone.runTask (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188)
    at drainMicroTaskQueue (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:595)
    at ZoneTask.invokeTask (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:500)
    at Socket.ZoneTask.ZoneTask.cancelFn.invoke (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:485)
    at emitOne (events.js:116)
    at Socket.emit (events.js:211)
    at addChunk (_stream_readable.js:263)
    at readableAddChunk (_stream_readable.js:250)
    at Socket.Readable.push (_stream_readable.js:208)
    at Pipe.onread (net.js:594)
C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 WARNING: Promise with no error callback:70
C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Object
C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 TypeError: Cannot read property 'queryRunner' of undefined
    at QueryResultsView.set [as input] (workbench.main.js:304656)
    at QueryResultsEditor.setInput (workbench.main.js:304876)
    at QueryEditor._onResultsEditorCreated (workbench.main.js:190594)
    at workbench.main.js:190274
    at CompletePromise_ctor.CompletePromise_then [as then] (workbench.main.js:17893)
    at QueryEditor._showQueryResultsEditor (workbench.main.js:190273)
    at workbench.main.js:190162
    at Emitter.fire (workbench.main.js:20051)
    at QueryInput.showQueryResultsEditor (workbench.main.js:162001)
    at QueryInput.runQuery (workbench.main.js:162064)
    at QueryInput.onConnectSuccess (workbench.main.js:162102)
    at workbench.main.js:331558
    at ZoneDelegate.invoke (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:388)
    at Zone.run (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:138)
    at C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:872
    at ZoneDelegate.invokeTask (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421)
    at Zone.runTask (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188)
    at drainMicroTaskQueue (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:595)
    at ZoneTask.invokeTask (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:500)
    at Socket.ZoneTask.ZoneTask.cancelFn.invoke (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:485)
    at emitOne (events.js:116)
    at Socket.emit (events.js:211)
    at addChunk (_stream_readable.js:263)
    at readableAddChunk (_stream_readable.js:250)
    at Socket.Readable.push (_stream_readable.js:208)
    at Pipe.onread (net.js:594)
```
