### ISSUE TITLE
Issue with SQL Server Agent extension

### ISSUE THREAD

**Issue by kevchant** [Microsoft/azuredatastudio#4056]
Issue Type: <b>Bug</b>

I was trying to add a job to SQL Server 2019 on Linux which is in a container using the SQL Server Agent extension and it doesn't appear to be working, even though I can run T-SQL to do it just fine.

I know it might just be because it's still being worked on because it's a Previes. Giving feedback on here because I'm not sure who manages the extension.

Azure Data Studio version: azuredatastudio 1.3.9 (cacf0777c747046af6839de3688d709b10ef9fca, 2019-01-14T23:30:09.442Z)
OS version: Windows_NT x64 10.0.15063

**Comment by kburtram** [comment]
@abist could you please look into this?

**Comment by kburtram** [comment]
@kevchant you may try upgrading to the Feb 1.4.5 release which had some improvements to the agent feature.

**Comment by abist** [comment]
@kevchant Could you elaborate the experience right now? Does the extension start and not work?

**Comment by kevcunnane** [comment]
It will fail due to missing APIs

**Comment by kburtram** [comment]
@abist I'm getting the below error trying to create a job with default values (only providing a job name).

```
D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:2280 Unhandled Promise rejection: Cannot read property 'name' of undefined ; Zone: <root> ; Task: Promise.then ; Value: Error: Cannot read property 'name' of undefined
	at JobDialog.getDropdownValue (d:\xplat\azuredatastudio\extensions\agent\out\dialogs\agentDialog.js:58:87)
	at JobDialog.updateModel (d:\xplat\azuredatastudio\extensions\agent\out\dialogs\jobDialog.js:588:40)
	at DialogImpl.agentDialog_1.AgentDialog.initializeDialog.__awaiter.dialog.registerCloseValidator [as _closeValidator] (d:\xplat\azuredatastudio\extensions\agent\out\dialogs\jobDialog.js:95:22)
	at DialogImpl.validateClose (d:\xplat\azuredatastudio\out\sql\workbench\api\node\extHostModelViewDialog.js:163:45)
	at ExtHostModelViewDialog.$validateDialogClose (d:\xplat\azuredatastudio\out\sql\workbench\api\node\extHostModelViewDialog.js:457:27)
	at RPCProtocol._doInvokeHandler (d:\xplat\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:216:27)
	at RPCProtocol._invokeHandler (d:\xplat\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:201:54)
	at RPCProtocol._receiveRequest (d:\xplat\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:156:50)
	at RPCProtocol._receiveOneMessage (d:\xplat\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:139:26)
	at d:\xplat\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:76:92
	at d:\xplat\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:249:21
	at d:\xplat\azuredatastudio\out\vs\base\common\event.js:441:70
	at Emitter.fire (d:\xplat\azuredatastudio\out\vs\base\common\event.js:148:38)
	at acceptChunk (d:\xplat\azuredatastudio\out\vs\base\parts\ipc\node\ipc.net.js:100:46)
	at Socket.Protocol.Protocol.firstDataChunk._socketDataListener (d:\xplat\azuredatastudio\out\vs\base\parts\ipc\node\ipc.net.js:126:17)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20) TypeError: Cannot read property 'name' of undefined
	at JobDialog.getDropdownValue (d:\xplat\azuredatastudio\extensions\agent\out\dialogs\agentDialog.js:58:87)
	at JobDialog.updateModel (d:\xplat\azuredatastudio\extensions\agent\out\dialogs\jobDialog.js:588:40)
	at DialogImpl.agentDialog_1.AgentDialog.initializeDialog.__awaiter.dialog.registerCloseValidator [as _closeValidator] (d:\xplat\azuredatastudio\extensions\agent\out\dialogs\jobDialog.js:95:22)
	at DialogImpl.validateClose (d:\xplat\azuredatastudio\out\sql\workbench\api\node\extHostModelViewDialog.js:163:45)
	at ExtHostModelViewDialog.$validateDialogClose (d:\xplat\azuredatastudio\out\sql\workbench\api\node\extHostModelViewDialog.js:457:27)
	at RPCProtocol._doInvokeHandler (d:\xplat\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:216:27)
	at RPCProtocol._invokeHandler (d:\xplat\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:201:54)
	at RPCProtocol._receiveRequest (d:\xplat\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:156:50)
	at RPCProtocol._receiveOneMessage (d:\xplat\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:139:26)
	at d:\xplat\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:76:92
	at d:\xplat\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:249:21
	at d:\xplat\azuredatastudio\out\vs\base\common\event.js:441:70
	at Emitter.fire (d:\xplat\azuredatastudio\out\vs\base\common\event.js:148:38)
	at acceptChunk (d:\xplat\azuredatastudio\out\vs\base\parts\ipc\node\ipc.net.js:100:46)
	at Socket.Protocol.Protocol.firstDataChunk._socketDataListener (d:\xplat\azuredatastudio\out\vs\base\parts\ipc\node\ipc.net.js:126:17)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```

**Comment by kevchant** [comment]
Well it's the evening here in the Netherlands, but since so many of you are looking I thought I better check. I've just ran the brand new Docker update from today, and updated Azure Data Studio. It's still happening when you click on OK to create the job. All you get is the waiting circle on the button...

**Comment by kburtram** [comment]
@kevchant thanks for confirming, that's the same behavior I'm seeing.  We'll investigate and try to get an extension update out ASAP.
