### ISSUE TITLE
ERR ViewDestroyedError: Attempt to use a destroyed view: detectChanges: Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#4180]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open and close few notebooks.
2. Got error when open SQL notebook and got error: "Kernel is dead"
D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:2280 Failed to change kernel: Canceled
console.(anonymous function) @ D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:2280
NotificationsAlerts.onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
Emitter.fire @ event.ts:228
NotificationsModel.notify @ notifications.ts:113
NotificationService.notify @ notificationService.ts:52
NotebookComponent.handleModelError @ notebook.component.ts:319
(anonymous) @ notebook.component.ts:263
Emitter.fire @ event.ts:228
NotebookModel.notifyError @ notebookModel.ts:377
(anonymous) @ notebookModel.ts:490
ZoneDelegate.invoke @ D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:388
Zone.run @ D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:138
(anonymous) @ D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:872
ZoneDelegate.invokeTask @ D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421
Zone.runTask @ D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188
drainMicroTaskQueue @ D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:595
ZoneTask.invokeTask @ D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:500
ZoneTask.invoke @ D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:485
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:2280   ERR ViewDestroyedError: Attempt to use a destroyed view: detectChanges: Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges
    at viewDestroyedError (d:\3\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:8665:12)
    at Object.debugUpdateDirectives [as updateDirectives] (d:\3\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12810:15)
    at checkAndUpdateView (d:\3\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12151:14)
    at callWithDebugContext (d:\3\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:13213:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (d:\3\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12753:12)
    at ViewRef_.detectChanges (d:\3\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:10225:63)
    at NotebookComponent.handleContentChanged (file:///D:/3/azuredatastudio/out/sql/parts/notebook/notebook.component.js:384:29)
    at file:///D:/3/azuredatastudio/out/sql/parts/notebook/notebook.component.js:297:83
    at Emitter.fire (file:///D:/3/azuredatastudio/out/vs/base/common/event.js:228:38)
    at NotebookModel.onCellChange (file:///D:/3/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:943:41)
    at CellModel.sendChangeToNotebook (file:///D:/3/azuredatastudio/out/sql/parts/notebook/models/cell.js:366:40)
    at CellModel.fireOutputsChanged (file:///D:/3/azuredatastudio/out/sql/parts/notebook/models/cell.js:362:18)
    at CellModel.clearOutputs (file:///D:/3/azuredatastudio/out/sql/parts/notebook/models/cell.js:358:18)
    at CellModel.setFuture (file:///D:/3/azuredatastudio/out/sql/parts/notebook/models/cell.js:351:18)
    at CellModel.<anonymous> (file:///D:/3/azuredatastudio/out/sql/parts/notebook/models/cell.js:264:34)
    at step (file:///D:/3/azuredatastudio/out/sql/parts/notebook/models/cell.js:35:23)
    at Object.next (file:///D:/3/azuredatastudio/out/sql/parts/notebook/models/cell.js:16:53)
    at fulfilled (file:///D:/3/azuredatastudio/out/sql/parts/notebook/models/cell.js:7:58)
    at ZoneDelegate.invoke (D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:388:26)
    at Zone.run (D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:138:43)
    at D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:595:35)
    at ZoneTask.invokeTask (D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:500:21)
    at Socket.ZoneTask.invoke (D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:485:48)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:2280   ERR No adapter found: Error: No adapter found
	at ExtHostNotebook._getAdapter (d:\3\azuredatastudio\out\sql\workbench\api\node\extHostNotebook.js:335:23)
	at ExtHostNotebook.$disposeFuture (d:\3\azuredatastudio\out\sql\workbench\api\node\extHostNotebook.js:227:31)
	at RPCProtocol._doInvokeHandler (d:\3\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:408:27)
	at RPCProtocol._invokeHandler (d:\3\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:393:45)
	at RPCProtocol._receiveRequest (d:\3\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:325:32)
	at RPCProtocol._receiveOneMessage (d:\3\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:255:26)
	at d:\3\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:134:69
	at d:\3\azuredatastudio\out\vs\base\common\event.js:527:70
	at Emitter.fire (d:\3\azuredatastudio\out\vs\base\common\event.js:228:38)
	at acceptChunk (d:\3\azuredatastudio\out\vs\base\parts\ipc\node\ipc.net.js:104:46)
	at Socket.Protocol.Protocol.firstDataChunk._socketDataListener (d:\3\azuredatastudio\out\vs\base\parts\ipc\node\ipc.net.js:130:17)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)

**Comment by kevcunnane** [comment]
@chlafreniere I thought we fixed a similar issue?

**Comment by chlafreniere** [comment]
@kevcunnane We fixed a similar issue but this one is from a different codepath, (that fix was in outputArea). We'll need to do something like the following:

if (!(this._changeRef['destroyed'])) {
this._changeRef.detectChanges();
}

Still debugging why my machine doesn't want to launch ADS, so I'm not terribly helpful at the moment, I'm afraid ☹️.
