### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#4206]
- Azure Data Studio Version:

Steps to Reproduce:

1. open and close sql notebook few times
2. got exception:
    TypeError: Cannot read property '0' of undefined
    at NotebookModel.setProviderIdForKernel (file:///D:/3/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:885:77)
    at NotebookModel.doChangeKernel (file:///D:/3/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:584:18)
    at NotebookModel.loadKernelInfo (file:///D:/3/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:687:26)
    at NotebookModel.<anonymous> (file:///D:/3/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:513:34)
    at step (file:///D:/3/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:48:23)
    at Object.next (file:///D:/3/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:29:53)
    at file:///D:/3/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:23:71
    at new ZoneAwarePromise (D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:891:29)
    at __awaiter (file:///D:/3/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:19:12)
    at file:///D:/3/azuredatastudio/out/sql/parts/notebook/models/notebookModel.js:505:92
    at ZoneDelegate.invoke (D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:388:26)
    at Object.onInvoke (d:\3\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4156:37)
    at ZoneDelegate.invoke (D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:387:32)
    at Zone.run (D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:138:43)
    at D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421:31)
    at Object.onInvokeTask (d:\3\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4147:37)
    at ZoneDelegate.invokeTask (D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:420:36)
    at Zone.runTask (D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:595:35)
    at ZoneTask.invokeTask (D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:500:21)
    at Socket.ZoneTask.invoke (D:\3\azuredatastudio\node_modules\zone.js\dist\zone-node.js:485:48)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

**Comment by rajmusuku** [comment]
I too observed this issue today.
