### ISSUE TITLE
sqlNotebook:  Cannot read property 'shutdownAll' of undefined: TypeError: Cannot read property 'shutdownAll' of undefined

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#4207]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open sql notebook and close it
ERR Cannot read property 'shutdownAll' of undefined: TypeError: Cannot read property 'shutdownAll' of undefined
	at JupyterSessionManager.shutdownAll (d:\3\azuredatastudio\extensions\notebook\out\jupyter\jupyterSessionManager.js:143:37)
	at JupyterNotebookManager.dispose (d:\3\azuredatastudio\extensions\notebook\out\jupyter\jupyterNotebookManager.js:37:34)
	at JupyterNotebookProvider.handleNotebookClosed (d:\3\azuredatastudio\extensions\notebook\out\jupyter\jupyterNotebookProvider.js:42:21)
	at ExtHostNotebook.$handleNotebookClosed (d:\3\azuredatastudio\out\sql\workbench\api\node\extHostNotebook.js:81:34)
	at RPCProtocol._doInvokeHandler (d:\3\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:408:27)
	at RPCProtocol._invokeHandler (d:\3\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:393:45)
	at RPCProtocol._receiveRequest (d:\3\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:325:32)
	at RPCProtocol._receiveOneMessage (d:\3\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:255:26)
	at d:\3\azuredatastudio\out\vs\workbench\services\extensions\node\rpcProtocol.js:134:69
	at d:\3\azuredatastudio\out\vs\base\common\event.js:527:70
	at Emitter.fire (d:\3\azuredatastudio\out\vs\base\common\event.js:228:38)
	at acceptChunk (d:\3\azuredatastudio\out\vs\base\parts\ipc\node\ipc.net.js:104:46)
	at Socket.Protocol.Protocol.firstDataChunk._socketDataListener (d:\3\azuredatastudio\out\vs\base\parts\ipc\node\ipc.net.js:130:17)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)

**Comment by Charles-Gagnon** [comment]
@YurongHe - it looks like you fixed this issue, if so can you close it out?

**Comment by chlafreniere** [comment]
This was fixed by Yurong's previous PR.
