### ISSUE TITLE
Could not start session: EPERM: operation not permitted, mkdir 

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#4215]
Issue Type: <b>Bug</b>

Receiving a pair of errors after opening a notebook right after upgrade to today's insider build.

This seems to be replacing the previous behavior I was seeing in bug #4174 

Could not start session: EPERM: operation not permitted, mkdir 'c:\Program Files\Azure Data Studio\resources\app\extensions\notebook\jupyter_config'

Starting local Notebook server failed with error EPERM: operation not permitted, mkdir 'c:\Program Files\Azure Data Studio\resources\app\extensions\notebook\jupyter_config'

![image](https://user-images.githubusercontent.com/8250560/53500594-8178ea00-3a5f-11e9-8217-b59191eb0b71.png)

Full Console Log:

SqlTools Log file is: C:/Users/viharp/AppData/Roaming/azuredatastudio/mssql/sqltools_1551280346155.log
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280  INFO no standard startup: not the explorer viewlet
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Extension 'Microsoft.sql-vnext cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] debugger listening on port 62918
/C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:220417 Extension Host
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Debugger listening on ws://127.0.0.1:62918/2c7030ec-0e18-43e5-aed5-8b0e8e8aac51
For help see https://nodejs.org/en/docs/inspector

C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Activating extension 'vscode.git' failed: undefinedundefined is not defined. (at Object.showMessage (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50173:37))
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Activating extension `vscode.git` failed:  undefinedundefined is not defined (at c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:24558:25)
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Here is the error stack:  ReferenceError: undefinedundefined is not defined
	at Object.e.exports (c:\Program Files\Azure Data Studio\resources\app\extensions\git\dist\main.js:1:122727)
	at r (c:\Program Files\Azure Data Studio\resources\app\extensions\git\dist\main.js:1:313)
	at n (c:\Program Files\Azure Data Studio\resources\app\extensions\git\dist\main.js:1:1112)
	at Object.<anonymous> (c:\Program Files\Azure Data Studio\resources\app\extensions\git\dist\main.js:1:1122)
	at Object.<anonymous> (c:\Program Files\Azure Data Studio\resources\app\extensions\git\dist\main.js:55:3)
	at Module.NodeScriptLoader._initNodeRequire.Module._compile (c:\Program Files\Azure Data Studio\resources\app\out\vs\loader.js:724:45)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.Module._load (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50788:33)
	at Function.load (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:49972:33)
	at Function.load [as _load] (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:46588:37)
	at Module.require (module.js:586:17)
	at require (internal/module.js:11:18)
	at Function.nodeRequire [as __$__nodeRequire] (c:\Program Files\Azure Data Studio\resources\app\out\vs\loader.js:1688:32)
	at loadCommonJSModule (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50617:25)
	at ExtHostExtensionService._doActivateExtension (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50359:17)
	at ExtHostExtensionService._activateExtension (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50316:25)
	at Object.actualActivateExtension (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50183:34)
	at ExtensionsActivator._activateExtension (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:24556:78)
	at c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:24542:74
	at Array.map (<anonymous>)
	at ExtensionsActivator._activateExtensions (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:24542:42)
	at ExtensionsActivator._activateExtensions (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:24544:25)
	at ExtensionsActivator.activateByEvent (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:24455:25)
	at ExtHostExtensionService._activateByEvent (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50235:36)
	at ExtHostExtensionService._handleEagerExtensions (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50423:18)
	at c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50585:50
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:188:7) (at c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:24559:25)
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Activating extension 'vscode.git' failed: undefinedundefined is not defined.
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280
/C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:220417 Extension Host
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Debugger attached.

C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280  WARN UNRESPONSIVE extension host, 'Microsoft.mssql' took 95% of 614.804ms, saved PROFILE here: 'C:\Users\viharp\AppData\Local\Temp\exthost-eb43e3.cpuprofile' Array(2)
/C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:220417 Extension Host
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Debugger listening on ws://127.0.0.1:62918/2c7030ec-0e18-43e5-aed5-8b0e8e8aac51
For help see https://nodejs.org/en/docs/inspector

/C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:220417 Extension Host
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Debugger attached.

C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280  WARN UNRESPONSIVE extension host, 'Microsoft.mssql' took 100% of 11787.628ms, saved PROFILE here: 'C:\Users\viharp\AppData\Local\Temp\exthost-32cdf9.cpuprofile' Array(1)
/C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:220417 Extension Host
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Debugger listening on ws://127.0.0.1:62918/2c7030ec-0e18-43e5-aed5-8b0e8e8aac51
For help see https://nodejs.org/en/docs/inspector

C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Activating extension 'Microsoft.import' failed: Cannot find module 'htmlparser2'. (at Object.showMessage (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50173:37))
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Activating extension `Microsoft.import` failed:  Cannot find module 'htmlparser2' (at c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:24558:25)
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Here is the error stack:  Error: Cannot find module 'htmlparser2'
	at Function.Module._resolveFilename (module.js:543:15)
	at Function.Module._load (module.js:473:25)
	at Function.Module._load (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50788:33)
	at Function.load (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:49972:33)
	at Function.load [as _load] (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:46588:37)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (c:\Program Files\Azure Data Studio\resources\app\out\vs\loader.js:692:36)
	at Object.<anonymous> (C:\Users\viharp\.azuredatastudio\extensions\microsoft.import-0.6.0\out\wizard\pages\deployPlanPage.js:16:16)
	at Object.<anonymous> (C:\Users\viharp\.azuredatastudio\extensions\microsoft.import-0.6.0\out\wizard\pages\deployPlanPage.js:277:3)
	at Module.NodeScriptLoader._initNodeRequire.Module._compile (c:\Program Files\Azure Data Studio\resources\app\out\vs\loader.js:724:45)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.Module._load (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50788:33)
	at Function.load (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:49972:33)
	at Function.load [as _load] (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:46588:37)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (c:\Program Files\Azure Data Studio\resources\app\out\vs\loader.js:692:36)
	at Object.<anonymous> (C:\Users\viharp\.azuredatastudio\extensions\microsoft.import-0.6.0\out\wizard\dataTierApplicationWizard.js:20:26)
	at Object.<anonymous> (C:\Users\viharp\.azuredatastudio\extensions\microsoft.import-0.6.0\out\wizard\dataTierApplicationWizard.js:351:3)
	at Module.NodeScriptLoader._initNodeRequire.Module._compile (c:\Program Files\Azure Data Studio\resources\app\out\vs\loader.js:724:45)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.Module._load (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50788:33)
	at Function.load (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:49972:33)
	at Function.load [as _load] (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:46588:37)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (c:\Program Files\Azure Data Studio\resources\app\out\vs\loader.js:692:36)
	at Object.<anonymous> (C:\Users\viharp\.azuredatastudio\extensions\microsoft.import-0.6.0\out\controllers\mainController.js:14:37)
	at Object.<anonymous> (C:\Users\viharp\.azuredatastudio\extensions\microsoft.import-0.6.0\out\controllers\mainController.js:45:3)
	at Module.NodeScriptLoader._initNodeRequire.Module._compile (c:\Program Files\Azure Data Studio\resources\app\out\vs\loader.js:724:45)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.Module._load (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50788:33)
	at Function.load (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:49972:33)
	at Function.load [as _load] (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:46588:37)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (c:\Program Files\Azure Data Studio\resources\app\out\vs\loader.js:692:36)
	at Object.<anonymous> (C:\Users\viharp\.azuredatastudio\extensions\microsoft.import-0.6.0\out\main.js:7:26)
	at Object.<anonymous> (C:\Users\viharp\.azuredatastudio\extensions\microsoft.import-0.6.0\out\main.js:35:3)
	at Module.NodeScriptLoader._initNodeRequire.Module._compile (c:\Program Files\Azure Data Studio\resources\app\out\vs\loader.js:724:45)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.Module._load (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50788:33)
	at Function.load (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:49972:33)
	at Function.load [as _load] (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:46588:37)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:11:18)
	at Function.nodeRequire [as __$__nodeRequire] (c:\Program Files\Azure Data Studio\resources\app\out\vs\loader.js:1688:32)
	at loadCommonJSModule (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50617:25)
	at ExtHostExtensionService._doActivateExtension (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50359:17)
	at ExtHostExtensionService._activateExtension (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50316:25)
	at Object.actualActivateExtension (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50183:34)
	at ExtensionsActivator._activateExtension (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:24556:78)
	at c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:24542:74
	at Array.map (<anonymous>)
	at ExtensionsActivator._activateExtensions (c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:24542:42)
	at c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:24545:30
	at <anonymous> (at c:\Program Files\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:24559:25)
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Activating extension 'Microsoft.import' failed: Cannot find module 'htmlparser2'.
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] logFile for MicrosoftSqlToolsServiceLayer.exe is C:\Users\viharp\AppData\Roaming\azuredatastudio\mssql\sqltools_9244.log (at Object.getCommonLaunchArgsAndCleanupOldLogFiles (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\out\utils.js:90:13))
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] This process (ui Extenstion Host) is pid: 9244 (at Object.getCommonLaunchArgsAndCleanupOldLogFiles (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\out\utils.js:91:13))
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Old log files deletion report: {} (at Object.getCommonLaunchArgsAndCleanupOldLogFiles (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\out\utils.js:94:13))
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [93m[main 7:13:43 AM][0m cannot find session vharpl___Integrated_C777F06B-202E-4480-B475-FA416154D458
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] logFile for SqlToolsResourceProviderService.exe is C:\Users\viharp\AppData\Roaming\azuredatastudio\mssql\resourceprovider_9244.log (at Object.getCommonLaunchArgsAndCleanupOldLogFiles (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\out\utils.js:90:13))
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] This process (ui Extenstion Host) is pid: 9244 (at Object.getCommonLaunchArgsAndCleanupOldLogFiles (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\out\utils.js:91:13))
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Old log files deletion report: {} (at Object.getCommonLaunchArgsAndCleanupOldLogFiles (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\out\utils.js:94:13))
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] logFile for MicrosoftSqlToolsCredentials.exe is C:\Users\viharp\AppData\Roaming\azuredatastudio\mssql\credentialstore_9244.log (at Object.getCommonLaunchArgsAndCleanupOldLogFiles (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\out\utils.js:90:13))
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] This process (ui Extenstion Host) is pid: 9244 (at Object.getCommonLaunchArgsAndCleanupOldLogFiles (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\out\utils.js:91:13))
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Old log files deletion report: {} (at Object.getCommonLaunchArgsAndCleanupOldLogFiles (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\out\utils.js:94:13))
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Starting local Notebook server failed with error EPERM: operation not permitted, mkdir 'c:\Program Files\Azure Data Studio\resources\app\extensions\notebook\jupyter_config'
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:388 Could not start session: EPERM: operation not permitted, mkdir 'c:\Program Files\Azure Data Studio\resources\app\extensions\notebook\jupyter_config'
ZoneDelegate.invoke @ C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:388
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Starting local Notebook server failed with error EPERM: operation not permitted, mkdir 'c:\Program Files\Azure Data Studio\resources\app\extensions\notebook\jupyter_config'
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:388 Could not start session: EPERM: operation not permitted, mkdir 'c:\Program Files\Azure Data Studio\resources\app\extensions\notebook\jupyter_config'

Azure Data Studio version: azuredatastudio 1.5.0-insider (12a1ac1a7d667d1bbb8752f61c893d2fab1a6115, 2019-02-27T03:31:00.390Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (2.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
admin-pack|Mic|0.0.1
agent|Mic|0.36.1
import|Mic|0.6.0
profiler|Mic|0.6.0
server-report|Mic|0.1.4
sql-vnext|Mic|0.10.3
whoisactive|Mic|0.1.1

(1 theme extensions excluded)

</details>

**Comment by vickyharp** [comment]
Following the hint from the error message, I ran as admin and it works fine in that case. Does repro again if I re-run as non-admin so it's not a one time thing.

**Comment by kevcunnane** [comment]
Raj is fixing this. The error is that files were being written to the extension directory. This works for external extensions but not those built-in to azure data studio as it’s in a non-writeable folder. The fix will be to write configuration to a known write safe directory. Should be resolved by tomorrow’s build, apologies for the inconvenience.
