### ISSUE TITLE
Extension gallery not populating with "unhandled promise rejection"

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#4230]
I clicked over to the Extensions tab and have a never ending loading indicator, with an unhandled promise rejection in the console log.

![image](https://user-images.githubusercontent.com/8250560/53570777-3ba34b00-3b5f-11e9-991f-11534ed70b53.png)

Unhandled Promise rejection: Canceled ; Zone: <root> ; Task: Promise.then ; Value: Error: Canceled
    at Object.canceled (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:20099:21)
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:24367:31
    at Emitter.fire (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:21584:38)
    at MutableToken.cancel (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:24080:35)
    at CancellationTokenSource.cancel (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:24137:29)
    at class_1.cancel (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:24381:24)
    at FoldingController.onModelContentChanged (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:125100:47)
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:125036:101
    at Emitter.fire (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:21584:38)
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:139588:114
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:91046:71
    at Emitter.fire (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:21584:38)
    at DidChangeContentEmitter.endDeferredEmit (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:93240:39)
    at TextModel.pushEditOperations (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:91731:36)
    at ModelServiceImpl.updateModel (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:142819:19)
    at TextFileEditorModel.BaseTextEditorModel.updateTextEditorModel (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:175497:31)
    at TextFileEditorModel.doUpdateTextModel (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:285243:22)
    at TextFileEditorModel.doLoadWithContent (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:285226:29)
    at TextFileEditorModel.loadWithContent (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:285177:25)
    at TextFileEditorModel.loadFromFile.options.textFileService.resolveTextContent.then.result (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:285150:34)
    at ZoneDelegate.invoke (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:388:26)
    at Zone.run (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:138:43)
    at C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:595:35)
    at ZoneTask.invokeTask (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:500:21)
    at ZoneTask.ZoneTask.cancelFn.invoke (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:485:48)
    at data.args.(anonymous function) (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:1338:25)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) Canceled: Canceled
    at Object.canceled (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:20099:21)
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:24367:31
    at Emitter.fire (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:21584:38)
    at MutableToken.cancel (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:24080:35)
    at CancellationTokenSource.cancel (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:24137:29)
    at class_1.cancel (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:24381:24)
    at FoldingController.onModelContentChanged (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:125100:47)
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:125036:101
    at Emitter.fire (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:21584:38)
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:139588:114
    at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:91046:71
    at Emitter.fire (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:21584:38)
    at DidChangeContentEmitter.endDeferredEmit (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:93240:39)
    at TextModel.pushEditOperations (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:91731:36)
    at ModelServiceImpl.updateModel (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:142819:19)
    at TextFileEditorModel.BaseTextEditorModel.updateTextEditorModel (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:175497:31)
    at TextFileEditorModel.doUpdateTextModel (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:285243:22)
    at TextFileEditorModel.doLoadWithContent (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:285226:29)
    at TextFileEditorModel.loadWithContent (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:285177:25)
    at TextFileEditorModel.loadFromFile.options.textFileService.resolveTextContent.then.result (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:285150:34)
    at ZoneDelegate.invoke (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:388:26)
    at Zone.run (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:138:43)
    at C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:595:35)
    at ZoneTask.invokeTask (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:500:21)
    at ZoneTask.ZoneTask.cancelFn.invoke (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:485:48)
    at data.args.(anonymous function) (C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:1338:25)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280

**Comment by kburtram** [comment]
I wasn't able to repro this on the latest insider build.  This was probably a regression from the 1.30 VS Code merge.  Please reactive if the issue persists.
