### ISSUE TITLE
Activating extension `vscode.git` failed:  undefinedundefined is not defined

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#4235]
Call stack and error in developer tool:

Issue Type: <b>Bug</b>

SqlTools Log file is: C:/Users/yuronhe/AppData/Roaming/azuredatastudio/mssql/sqltools_1551375821721.log
C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280  INFO no standard startup: not the explorer viewlet
C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] debugger listening on port 53777
/C:/icm/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:220417 Extension Host
C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Debugger listening on ws://127.0.0.1:53777/d69a7390-048a-4a8d-aeea-cb8364f5e9e4
For help see https://nodejs.org/en/docs/inspector

/C:/icm/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:220417 Extension Host
C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Debugger attached.

workbench.main.js:220417 Extension Host
C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Debugger listening on ws://127.0.0.1:53777/d69a7390-048a-4a8d-aeea-cb8364f5e9e4
For help see https://nodejs.org/en/docs/inspector

C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Activating extension 'vscode.git' failed: undefinedundefined is not defined. (at Object.showMessage (c:\icm\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50173:37))
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280
log @ workbench.main.js:30522
ExtensionHostProcessWorker._logExtensionHostMessage @ workbench.main.js:220608
(anonymous) @ workbench.main.js:220425
ZoneDelegate.invokeTask @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421
Zone.runTask @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188
ZoneTask.invokeTask @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:496
ZoneTask.ZoneTask.cancelFn.invoke @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:485
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
ZoneDelegate.invokeTask @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421
Zone.runTask @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188
ZoneTask.invokeTask @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:496
ZoneTask.ZoneTask.cancelFn.invoke @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:485
data.args.(anonymous function) @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:1338
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Activating extension 'vscode.git' failed: undefinedundefined is not defined.
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280
ExtensionService._logMessageInConsole @ workbench.main.js:364888
ExtensionService._logOrShowMessage @ workbench.main.js:364903
MainThreadExtensionService.$localShowMessage @ workbench.main.js:364969
RPCProtocol._doInvokeHandler @ workbench.main.js:228876
RPCProtocol._invokeHandler @ workbench.main.js:228861
RPCProtocol._receiveRequest @ workbench.main.js:228793
RPCProtocol._receiveOneMessage @ workbench.main.js:228723
(anonymous) @ workbench.main.js:228602
Emitter.fire @ workbench.main.js:21584
acceptChunk @ workbench.main.js:33897
Protocol.Protocol.firstDataChunk._socketDataListener @ workbench.main.js:33923
ZoneDelegate.invokeTask @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421
Zone.runTask @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188
ZoneTask.invokeTask @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:496
ZoneTask.ZoneTask.cancelFn.invoke @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:485
emitOne @ events.js:116
emit @ events.js:211
addChunk @ _stream_readable.js:263
readableAddChunk @ _stream_readable.js:250
Readable.push @ _stream_readable.js:208
onread @ net.js:594
C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Activating extension `vscode.git` failed:  undefinedundefined is not defined (at c:\icm\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:24558:25)
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280
log @ workbench.main.js:30522
ExtensionHostProcessWorker._logExtensionHostMessage @ workbench.main.js:220608
(anonymous) @ workbench.main.js:220425
ZoneDelegate.invokeTask @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421
Zone.runTask @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188
ZoneTask.invokeTask @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:496
ZoneTask.ZoneTask.cancelFn.invoke @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:485
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
ZoneDelegate.invokeTask @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421
Zone.runTask @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188
ZoneTask.invokeTask @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:496
ZoneTask.ZoneTask.cancelFn.invoke @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:485
data.args.(anonymous function) @ C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:1338
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
C:\icm\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Here is the error stack:  ReferenceError: undefinedundefined is not defined
	at Object.e.exports (c:\icm\Azure Data Studio\resources\app\extensions\git\dist\main.js:1:122727)
	at r (c:\icm\Azure Data Studio\resources\app\extensions\git\dist\main.js:1:313)
	at n (c:\icm\Azure Data Studio\resources\app\extensions\git\dist\main.js:1:1112)
	at Object.<anonymous> (c:\icm\Azure Data Studio\resources\app\extensions\git\dist\main.js:1:1122)
	at Object.<anonymous> (c:\icm\Azure Data Studio\resources\app\extensions\git\dist\main.js:55:3)
	at Module.NodeScriptLoader._initNodeRequire.Module._compile (c:\icm\Azure Data Studio\resources\app\out\vs\loader.js:724:45)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.Module._load (c:\icm\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50788:33)
	at Function.load (c:\icm\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:49972:33)
	at Function.load [as _load] (c:\icm\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:46588:37)
	at Module.require (module.js:586:17)
	at require (internal/module.js:11:18)
	at Function.nodeRequire [as __$__nodeRequire] (c:\icm\Azure Data Studio\resources\app\out\vs\loader.js:1688:32)
	at loadCommonJSModule (c:\icm\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50617:25)
	at ExtHostExtensionService._doActivateExtension (c:\icm\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50359:17)
	at ExtHostExtensionService._activateExtension (c:\icm\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50316:25)
	at Object.actualActivateExtension (c:\icm\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50183:34)
	at ExtensionsActivator._activateExtension (c:\icm\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:24556:78)
	at c:\icm\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:24542:74
	at Array.map (<anonymous>)
	at ExtensionsActivator._activateExtensions (c:\icm\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:24542:42)
	at ExtensionsActivator._activateExtensions (c:\icm\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:24544:25)
	at ExtensionsActivator.activateByEvent (c:\icm\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:24455:25)
	at ExtHostExtensionService._activateByEvent (c:\icm\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50235:36)
	at ExtHostExtensionService._handleEagerExtensions (c:\icm\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50423:18)
	at c:\icm\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:50585:50
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:188:7) (at c:\icm\Azure Data Studio\resources\app\out\vs\workbench\node\extensionHostProcess.js:24559:25)

Azure Data Studio version: azuredatastudio 1.5.0-insider (291f591af3421899481725016ccb08a40424c036, 2019-02-27T22:54:16.508Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (52.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by MattIrv** [comment]
Looks like this only happens in packaged builds.

Here's the relevant part of the stack trace
```
[Extension Host] Here is the error stack:  ReferenceError: undefinedundefined is not defined
	at Object.e.exports (c:\sandbox\installed\resources\app\extensions\git\dist\main.js:1:122727)
	at r (c:\sandbox\installed\resources\app\extensions\git\dist\main.js:1:313)
	at n (c:\sandbox\installed\resources\app\extensions\git\dist\main.js:1:1112)
	at Object.<anonymous> (c:\sandbox\installed\resources\app\extensions\git\dist\main.js:1:1122)
	at Object.<anonymous> (c:\sandbox\installed\resources\app\extensions\git\dist\main.js:55:3)
	at Module.NodeScriptLoader._initNodeRequire.Module._compile (c:\sandbox\installed\resources\app\out\vs\loader.js:724:45)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.Module._load (c:\sandbox\installed\resources\app\out\vs\workbench\node\extensionHostProcess.js:51225:33)
	at Function.load (c:\sandbox\installed\resources\app\out\vs\workbench\node\extensionHostProcess.js:50409:33)
	at Function.load [as _load] (c:\sandbox\installed\resources\app\out\vs\workbench\node\extensionHostProcess.js:46606:37)
	at Module.require (module.js:586:17)
	at require (internal/module.js:11:18)
	at Function.nodeRequire [as __$__nodeRequire] (c:\sandbox\installed\resources\app\out\vs\loader.js:1688:32)
	at loadCommonJSModule (c:\sandbox\installed\resources\app\out\vs\workbench\node\extensionHostProcess.js:51054:25)
	at ExtHostExtensionService._doActivateExtension (c:\sandbox\installed\resources\app\out\vs\workbench\node\extensionHostProcess.js:50796:17)
	at ExtHostExtensionService._activateExtension (c:\sandbox\installed\resources\app\out\vs\workbench\node\extensionHostProcess.js:50753:25)
	at Object.actualActivateExtension (c:\sandbox\installed\resources\app\out\vs\workbench\node\extensionHostProcess.js:50620:34)
	at ExtensionsActivator._activateExtension (c:\sandbox\installed\resources\app\out\vs\workbench\node\extensionHostProcess.js:24556:78)
	at c:\sandbox\installed\resources\app\out\vs\workbench\node\extensionHostProcess.js:24542:74
	at Array.map (<anonymous>)
	at ExtensionsActivator._activateExtensions (c:\sandbox\installed\resources\app\out\vs\workbench\node\extensionHostProcess.js:24542:42)
	at ExtensionsActivator._activateExtensions (c:\sandbox\installed\resources\app\out\vs\workbench\node\extensionHostProcess.js:24544:25)
	at ExtensionsActivator.activateByEvent (c:\sandbox\installed\resources\app\out\vs\workbench\node\extensionHostProcess.js:24455:25)
	at ExtHostExtensionService._activateByEvent (c:\sandbox\installed\resources\app\out\vs\workbench\node\extensionHostProcess.js:50672:36)
	at ExtHostExtensionService._handleEagerExtensions (c:\sandbox\installed\resources\app\out\vs\workbench\node\extensionHostProcess.js:50860:18)
	at c:\sandbox\installed\resources\app\out\vs\workbench\node\extensionHostProcess.js:51022:50
	at <anonymous>
	at process._tickCallback (internal/process/next_tick.js:188:7) (at c:\sandbox\installed\resources\app\out\vs\workbench\node\extensionHostProcess.js:24559:25)
```

**Comment by MattIrv** [comment]
I was working on this already and think I have a fix so I'll reassign to myself for now
