### ISSUE TITLE
Notebooks: get vertical scrollbar if horizontal appears

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#4263]
Issue Type: <b>Bug</b>

Create a cell with the following content

```
# Example: use this to read from a job and write to the location below
df = (spark.read.option("inferSchema", "true")
.option("header", "true")
.csv("/kctest/my.csv"))
df.show(10)
```

Narrow the window until scrollbars appear

Expected:
- Horizontal scroll happens 
Actual:
- Vertical scroll also happens, because adding the horizontal scroll takes some available space. 

We should give extra padding to accommodate the horizontal scroll or adjust for this in our algorithm.

![image](https://user-images.githubusercontent.com/10819925/53670929-4f1ee680-3c31-11e9-9ee1-d72c73960a12.png)

Azure Data Studio version: azuredatastudio 1.5.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.68GB free)|
|Process Argv|. --remote-debugging-port=9222 --no-first-run --no-default-browser-check --inspect=5875 --no-cached-data|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|0.0.3
server-report|Mic|0.1.5
queryplan-show|phi|0.0.2

</details>

**Comment by YurongHe** [comment]
when change kernel from sql to pyspark:

25572:0304/125652.118:INFO:CONSOLE(2280)] "%c[Extension Host] %c  Message: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at Babel.ParserGenerator.MinimalList`1.get_Item(Int32 index)
   at Babel.ParserGenerator.ModifiedMinimalList`1.get_Item(Int32 index)
   at Microsoft.SqlServer.Management.SqlParser.Parser.TokenManager.GetToken(Int32 tokenNumber)
   at Microsoft.SqlTools.ServiceLayer.LanguageServices.Completion.ScriptDocumentInfo.GetPeekDefinitionTokens(ScriptParseInfo scriptParseInfo, Int32 startLine, Int32 startColumn) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\LanguageServices\ScriptDocumentInfo.cs:line
158
   at Microsoft.SqlTools.ServiceLayer.LanguageServices.LanguageService.GetDefinition(TextDocumentPosition textDocumentPosition, ScriptFile scriptFile, ConnectionInfo connInfo) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\LanguageServices\LanguageService.cs:line 1239
   at Microsoft.SqlTools.ServiceLayer.LanguageServices.LanguageService.HandleDefinitionRequest(TextDocumentPosition textDocumentPosition, RequestContext`1 requestContext) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\LanguageServices\LanguageService.cs:line 415
  Code: 0  %c(at CustomOutputChannel.appendLine (d:\4\azuredatastudio\extensions\mssql\out\main.js:266:17))", source: D:\4\azuredatastudio\node_modules\zone.js\dist\zone-node.js (2280)
[25572:0304/125853.285:INFO:CONSOLE(2280)] "%c WARN", source: D:\4\azuredatastudio\node_modules\zone.js\dist\zone-node.js (2280)
[25572:0304/125853.285:INFO:CONSOLE(2280)] "%c WARN", source: D:\4\azuredatastudio\node_modules\zone.js\dist\zone-node.js (2280)
[25572:0304/125853.286:INFO:CONSOLE(2280)] "%c WARN", source: D:\4\azuredatastudio\node_modules\zone.js\dist\zone-node.js (2280)

**Comment by YurongHe** [comment]
25572:0304/125652.118:INFO:CONSOLE(2280)] "%c[Extension Host] %c  Message: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at Babel.ParserGenerator.MinimalList`1.get_Item(Int32 index)
   at Babel.ParserGenerator.ModifiedMinimalList`1.get_Item(Int32 index)
   at Microsoft.SqlServer.Management.SqlParser.Parser.TokenManager.GetToken(Int32 tokenNumber)
   at Microsoft.SqlTools.ServiceLayer.LanguageServices.Completion.ScriptDocumentInfo.GetPeekDefinitionTokens(ScriptParseInfo scriptParseInfo, Int32 startLine, Int32 startColumn) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\LanguageServices\ScriptDocumentInfo.cs:line
158
   at Microsoft.SqlTools.ServiceLayer.LanguageServices.LanguageService.GetDefinition(TextDocumentPosition textDocumentPosition, ScriptFile scriptFile, ConnectionInfo connInfo) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\LanguageServices\LanguageService.cs:line 1239
   at Microsoft.SqlTools.ServiceLayer.LanguageServices.LanguageService.HandleDefinitionRequest(TextDocumentPosition textDocumentPosition, RequestContext`1 requestContext) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\LanguageServices\LanguageService.cs:line 415
  Code: 0  %c(at CustomOutputChannel.appendLine (d:\4\azuredatastudio\extensions\mssql\out\main.js:266:17))", source: D:\4\azuredatastudio\node_modules\zone.js\dist\zone-node.js (2280)
[25572:0304/125853.285:INFO:CONSOLE(2280)] "%c WARN", source: D:\4\azuredatastudio\node_modules\zone.js\dist\zone-node.js (2280)
[25572:0304/125853.285:INFO:CONSOLE(2280)] "%c WARN", source: D:\4\azuredatastudio\node_modules\zone.js\dist\zone-node.js (2280)
[25572:0304/125853.286:INFO:CONSOLE(2280)] "%c WARN", source: D:\4\azuredatastudio\node_modules\zone.js\dist\zone-node.js (2280)
