### ISSUE TITLE
Latest insiders is broken due to extension host not loading

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#4294]
Issue Type: <b>Bug</b>

Today's build is broken because the extension host is broken. Connection, notebooks, everything is stuck due to this. Problem is only on today's build (yesterday worked fine).

It looks like it's in the extensionhostprocess, see below:

```js
[Extension Host] Here is the error stack:  Error: Cannot find module 'request'
	at Function.Module._resolveFilename (module.js:543:15)
	at Function.Module._load (module.js:473:25)
	at Function.Module._load (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:51225:33)
	at Function.load (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:50409:33)
	at Function.load [as _load] (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:46606:37)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/loader.js:692:36)
	at Object.<anonymous> (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/out/objectExplorerNodeProvider/webhdfs.js:7:17)
	at Object.<anonymous> (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/out/objectExplorerNodeProvider/webhdfs.js:667:3)
	at Module.NodeScriptLoader._initNodeRequire.Module._compile (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/loader.js:724:45)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.Module._load (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:51225:33)
	at Function.load (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:50409:33)
	at Function.load [as _load] (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:46606:37)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/loader.js:692:36)
	at Object.<anonymous> (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/out/objectExplorerNodeProvider/fileSources.js:16:19)
	at Object.<anonymous> (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/out/objectExplorerNodeProvider/fileSources.js:233:3)
	at Module.NodeScriptLoader._initNodeRequire.Module._compile (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/loader.js:724:45)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.Module._load (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:51225:33)
	at Function.load (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:50409:33)
	at Function.load [as _load] (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:46606:37)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/loader.js:692:36)
	at Object.<anonymous> (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/out/objectExplorerNodeProvider/hdfsCommands.js:23:23)
	at Object.<anonymous> (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/out/objectExplorerNodeProvider/hdfsCommands.js:384:3)
	at Module.NodeScriptLoader._initNodeRequire.Module._compile (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/loader.js:724:45)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.Module._load (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:51225:33)
	at Function.load (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:50409:33)
	at Function.load [as _load] (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:46606:37)
	at Module.require (module.js:586:17)
	at Module.patchedRequire [as require] (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/loader.js:692:36)
	at Object.<anonymous> (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/out/main.js:33:24)
	at Object.<anonymous> (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/out/main.js:280:3)
	at Module.NodeScriptLoader._initNodeRequire.Module._compile (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/loader.js:724:45)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.Module._load (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:51225:33)
	at Function.load (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:50409:33)
	at Function.load [as _load] (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:46606:37)
	at Module.require (module.js:586:17)
	at require (internal/module.js:11:18)
	at Function.nodeRequire [as __$__nodeRequire] (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/loader.js:1688:32)
	at loadCommonJSModule (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:51054:25)
	at ExtHostExtensionService._doActivateExtension (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:50796:17)
	at ExtHostExtensionService._activateExtension (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:50753:25)
	at Object.actualActivateExtension (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:50620:34)
	at ExtensionsActivator._activateExtension (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:24556:78)
	at /Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:24542:74
	at Array.map (<anonymous>)
	at ExtensionsActivator._activateExtensions (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:24542:42)
	at ExtensionsActivator._activateExtensions (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:24544:25)
	at /Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:24545:30
	at <anonymous> (at /Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:24559:25)
```

Azure Data Studio version: Azure Data Studio 1.5.1-insider (5248c8f78d06e2f889e0266bf594b8d0d71bce82, 2019-03-05T03:12:45.369Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 4|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|-psn_0_2597498|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
agent|Mic|0.36.1
server-report|Mic|0.1.5
sql-vnext|Mic|0.10.3

</details>

**Comment by kevcunnane** [comment]
@geleems this is due to https://github.com/Microsoft/azuredatastudio/commit/f4365dbd3ae76cbdc963ca24a79da9c90703008d - you removed webhdfs component but still relied on 'request' module. This needs fixing ASAP, can you fix (clean your node modules and build, then yarn add missing dependencies)?

**Comment by enecciari** [comment]
this commit acc8d5f7b282e36e24a13e0b11f3ba6851c6b2de resolve the problem...
or cd /Applications/Azure Data Studio.app/Contents/Resources/app && npm install request

**Comment by MattIrv** [comment]
Confirmed this is fixed in the latest insiders build now
