### ISSUE TITLE
Git does not work in insiders build

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#4315]
Issue Type: <b>Bug</b>

Download packaged insiders build and launch. Git viewlet doesn't work
![image](https://user-images.githubusercontent.com/10819925/53918660-6dfbef00-401c-11e9-860a-4b1f9873d5a1.png)

and get following in chrome debug console:
```
/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2280 [Extension Host] Here is the error stack:  ReferenceError: undefinedundefined is not defined
	at Object.e.exports (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/extensions/git/dist/main.js:1:122727)
	at r (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/extensions/git/dist/main.js:1:313)
	at n (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/extensions/git/dist/main.js:1:1112)
	at Object.<anonymous> (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/extensions/git/dist/main.js:1:1122)
	at Object.<anonymous> (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/extensions/git/dist/main.js:55:3)
	at Module.NodeScriptLoader._initNodeRequire.Module._compile (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/loader.js:724:45)
	at Object.Module._extensions..js (module.js:653:10)
	at Module.load (module.js:561:32)
	at tryModuleLoad (module.js:504:12)
	at Function.Module._load (module.js:496:3)
	at Function.Module._load (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:51225:33)
	at Function.load (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:50409:33)
	at Function.load [as _load] (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:46606:37)
	at Module.require (module.js:586:17)
	at require (internal/module.js:11:18)
	at Function.nodeRequire [as __$__nodeRequire] (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/loader.js:1688:32)
	at loadCommonJSModule (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:51054:25)
	at ExtHostExtensionService._doActivateExtension (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:50796:17)
	at ExtHostExtensionService._activateExtension (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:50753:25)
	at Object.actualActivateExtension (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:50620:34)
	at ExtensionsActivator._activateExtension (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:24556:78)
	at /Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:24542:74
	at Array.map (<anonymous>)
	at ExtensionsActivator._activateExtensions (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:24542:42)
	at ExtensionsActivator._activateExtensions (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:24544:25)
	at ExtensionsActivator.activateByEvent (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:24455:25)
	at ExtHostExtensionService._activateByEvent (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:50672:36)
	at ExtHostExtensionService._handleEagerExtensions (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:50860:18)
	at /Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:51022:50
	at <anonymous> (at /Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:24559:25)
/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2280 Activating extension 'vscode.git' failed: undefinedundefined is not defined.
```

Azure Data Studio version: Azure Data Studio 1.5.1-insider (10f39aafe2b59765c798e7759791d0d010cf5033, 2019-03-06T18:42:52.081Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|16.00GB (0.34GB free)|
|Process Argv|-psn_0_2978519|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
agent|Mic|0.36.1
server-report|Mic|0.1.5
sql-vnext|Mic|0.10.3

</details>

**Comment by kevcunnane** [comment]
Closing as duplicate of #4235
