### ISSUE TITLE
nhandled Promise rejection: The selector "notebook-component_50" did not match any elements ; Zone: <root> ; Task: Promise.then ; Value: Error: The selector "notebook-component_50" did not match any elements

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#4421]
Issue Type: <b>Bug</b>

- Open a folder with notebooks
- Keep open notebook from the folder
Unhandled Promise rejection: The selector "notebook-component_50" did not match any elements ; Zone: <root> ; Task: Promise.then ; Value: Error: The selector "notebook-component_50" did not match any elements

Call stack:
   at DefaultDomRenderer2.selectRootElement (d:\git\azuredatastudio\node_modules\@angular\platform-browser\bundles\platform-browser.umd.js:2828)
    at DebugRenderer2.selectRootElement (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:13363)
    at createElement (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:9373)
    at createViewNodes (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12051)
    at createRootView (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:11998)
    at callWithDebugContext (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:13213)
    at Object.debugCreateRootView [as createRootView] (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12673)
    at ComponentFactory_.create (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:9919)
    at ComponentFactoryBoundToModule.create (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:3455)
    at ApplicationRef_.bootstrap (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:5039)
    at ModuleClass.ngDoBootstrap (notebook.module.ts:74)
    at PlatformRef_._moduleDoBootstrap (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4831)
    at d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4790
    at ZoneDelegate.invoke (D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:388)
    at Object.onInvoke (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4156)
    at ZoneDelegate.invoke (D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:387)
    at Zone.run (D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:138)
    at D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:872
    at ZoneDelegate.invokeTask (D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421)
    at Object.onInvokeTask (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4147)
    at ZoneDelegate.invokeTask (D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:420)
    at Zone.runTask (D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188)
    at drainMicroTaskQueue (D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:595)
    at <anonymous> Error: The selector "notebook-component_50" did not match any elements
    at DefaultDomRenderer2.selectRootElement (d:\git\azuredatastudio\node_modules\@angular\platform-browser\bundles\platform-browser.umd.js:2828:19)
    at DebugRenderer2.selectRootElement (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:13363:49)
    at createElement (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:9373:23)
    at createViewNodes (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12051:44)
    at createRootView (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:11998:5)
    at callWithDebugContext (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:13213:42)
    at Object.debugCreateRootView [as createRootView] (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12673:12)
    at ComponentFactory_.create (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:9919:46)
    at ComponentFactoryBoundToModule.create (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:3455:29)
    at ApplicationRef_.bootstrap (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:5039:57)
    at ModuleClass.ngDoBootstrap (file:///D:/git/azuredatastudio/out/sql/parts/notebook/notebook.module.js:26:24)
    at PlatformRef_._moduleDoBootstrap (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4831:32)
    at d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4790:27
    at ZoneDelegate.invoke (D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:388:26)
    at Object.onInvoke (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4156:37)
    at ZoneDelegate.invoke (D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:387:32)
    at Zone.run (D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:138:43)
    at D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421:31)
    at Object.onInvokeTask (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4147:37)
    at ZoneDelegate.invokeTask (D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:420:36)
    at Zone.runTask (D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:595:35)
Azure Data Studio version: azuredatastudio 1.5.1 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (43.07GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by chlafreniere** [comment]
Cannot repro; will reopen if we see again
