### ISSUE TITLE
Reinstall Notebook Dependencies failed with Error {0}

### ISSUE THREAD

**Issue by pradm** [Microsoft/azuredatastudio#4851]
- Azure Data Studio Version:
Version: 1.5.2 (user setup)
Commit: f74080c96310354bc92211f1826c0fdce78ca2f6
Date: 2019-03-22T06:25:26.627Z
VS Code 1.30.1
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.14393

Steps to Reproduce:
When i try to rebuild NoteBook dependencies when a NoteBook is open or not i am getting the following error.
 
![adsrebuild1](https://user-images.githubusercontent.com/27516588/55554421-59387700-5700-11e9-982b-be380f483344.jpg)

Output Window just shows the following
... Jupyter is running at http://localhost:8888/?token%3Da62d6cf5e63474a583566b23c74d07f73d8be60460e02b07
    > C:\Users\pradm\azuredatastudio-python\0.0.1\python.exe -m jupyter notebook stop 8888
    stdout: Shutting down server on port 8888 ...
    stdout: 
... Creating C:\Users\pradm\AppData\Roaming\jupyter\instances\77527b69-246e-4493-b28e-b2c662ad9728
... Creating C:\Users\pradm\AppData\Roaming\jupyter\instances\77527b69-246e-4493-b28e-b2c662ad9728\config
... Creating C:\Users\pradm\AppData\Roaming\jupyter\instances\77527b69-246e-4493-b28e-b2c662ad9728\data
... Creating C:\Users\pradm\AppData\Roaming\jupyter\instances\77527b69-246e-4493-b28e-b2c662ad9728\config\custom
... Starting Notebook server
    > C:\Users\pradm\azuredatastudio-python\0.0.1\python.exe -m jupyter notebook --no-browser --notebook-dir "e:\Projects\SQLAris\NoteBook_Deployment_TSG\Rony" --port=8888 --NotebookApp.token=0ff24b9dd3afc2c61da65a8b5fcace50e875f1a007137df0
... Jupyter is running at http://localhost:8888/?token%3D0ff24b9dd3afc2c61da65a8b5fcace50e875f1a007137df0
Python installation is in progress
Downloading python package (0 / 159.34 MB)
Downloading python package (15.94 / 159.34 MB)
Downloading python package (31.88 / 159.34 MB)
Downloading python package (47.81 / 159.34 MB)
Downloading python package (63.74 / 159.34 MB)
Downloading python package (79.67 / 159.34 MB)
Downloading python package (95.62 / 159.34 MB)
Downloading python package (111.55 / 159.34 MB)
Downloading python package (127.48 / 159.34 MB)
Downloading python package (143.41 / 159.34 MB)
Downloading python package (159.34 / 159.34 MB)
Unpacking python package

Toggle developer tools window shows the following exception and stack
![adsrebuild](https://user-images.githubusercontent.com/27516588/55554480-7f5e1700-5700-11e9-922a-b87d9c964518.jpg)

Unhandled Promise rejection: Canceled ; Zone: <root> ; Task: Promise.then ; Value: Error: Canceled
    at Object.canceled (file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:20088:21)
    at Delayer.cancel (file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:24529:38)
    at ThrottledDelayer.cancel (file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:24567:26)
    at OutputFileListener.unwatch (file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:239094:34)
    at FileOutputChannel.onModelWillDispose (file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:239160:30)
    at file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:238931:27
    at Emitter.fire (file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:21573:38)
    at TextModel.dispose (file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:90747:33)
    at ModelServiceImpl.destroyModel (file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:142785:29)
    at ResourceEditorModel.BaseTextEditorModel.dispose (file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:175404:35)
    at ResourceModelCollection.destroyReferencedObject (file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:314991:31)
    at ZoneDelegate.invoke (C:\AzureDataStudio_Released\resources\app\node_modules\zone.js\dist\zone-node.js:388:26)
    at Zone.run (C:\AzureDataStudio_Released\resources\app\node_modules\zone.js\dist\zone-node.js:138:43)
    at C:\AzureDataStudio_Released\resources\app\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (C:\AzureDataStudio_Released\resources\app\node_modules\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (C:\AzureDataStudio_Released\resources\app\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (C:\AzureDataStudio_Released\resources\app\node_modules\zone.js\dist\zone-node.js:595:35)
    at ZoneTask.invokeTask (C:\AzureDataStudio_Released\resources\app\node_modules\zone.js\dist\zone-node.js:500:21)
    at EventEmitter.ZoneTask.ZoneTask.cancelFn.invoke (C:\AzureDataStudio_Released\resources\app\node_modules\zone.js\dist\zone-node.js:485:48)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7) Canceled: Canceled
   at Object.canceled (file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:20088:21)
    at Delayer.cancel (file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:24529:38)
    at ThrottledDelayer.cancel (file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:24567:26)
    at OutputFileListener.unwatch (file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:239094:34)
    at FileOutputChannel.onModelWillDispose (file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:239160:30)
    at file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:238931:27
    at Emitter.fire (file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:21573:38)
    at TextModel.dispose (file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:90747:33)
    at ModelServiceImpl.destroyModel (file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:142785:29)
    at ResourceEditorModel.BaseTextEditorModel.dispose (file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:175404:35)
    at ResourceModelCollection.destroyReferencedObject (file:///C:/AzureDataStudio_Released/resources/app/out/vs/workbench/workbench.main.js:314991:31)
    at ZoneDelegate.invoke (C:\AzureDataStudio_Released\resources\app\node_modules\zone.js\dist\zone-node.js:388:26)
    at Zone.run (C:\AzureDataStudio_Released\resources\app\node_modules\zone.js\dist\zone-node.js:138:43)
    at C:\AzureDataStudio_Released\resources\app\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (C:\AzureDataStudio_Released\resources\app\node_modules\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (C:\AzureDataStudio_Released\resources\app\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (C:\AzureDataStudio_Released\resources\app\node_modules\zone.js\dist\zone-node.js:595:35)
    at ZoneTask.invokeTask (C:\AzureDataStudio_Released\resources\app\node_modules\zone.js\dist\zone-node.js:500:21)
    at EventEmitter.ZoneTask.ZoneTask.cancelFn.invoke (C:\AzureDataStudio_Released\resources\app\node_modules\zone.js\dist\zone-node.js:485:48)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\AzureDataStudio_Released\resources\app\node_modules\zone.js\dist\zone-node.js:2280

it would be very useful for others if errors as such
are logged into some log file I did not see this issue being logged into 5-Jupyter Notebooks.log.

**Comment by chlafreniere** [comment]
The error message has been fixed by #4730.
