### ISSUE TITLE
Notebook conversion to HTML fails with error "Notebook does not appear to be JSON"

### ISSUE THREAD

**Issue by pradm** [Microsoft/azuredatastudio#4854]
- Azure Data Studio Version:
Version: 1.5.2 (user setup)
Commit: f74080c96310354bc92211f1826c0fdce78ca2f6
Date: 2019-03-22T06:25:26.627Z
VS Code 1.30.1
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.14393

Steps to Reproduce:
Not able to convert notebook to HTML as conversion attempt reports "Notebook does not appear to be JSON". 

![notebookconvert](https://user-images.githubusercontent.com/27516588/55558039-d5cf5380-5708-11e9-9754-32bc14462738.png)

The notebook has been converted into HTML: Create AKS cluster and deploy BDC.html (in the same directory as the .ipynb file)
[NbConvertApp] Converting notebook Create AKS cluster and deploy BDC.ipynb to html
Traceback (most recent call last):
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbformat\reader.py", line 14, in parse_json
    nb_dict = json.loads(s, **kwargs)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\json\decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 341 column 2 (char 21816)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\pradm\azuredatastudio-python\0.0.1\Scripts\jupyter-nbconvert.EXE\__main__.py", line 9, in <module>
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbconvert\nbconvertapp.py", line 337, in start
    self.convert_notebooks()
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbconvert\nbconvertapp.py", line 507, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbconvert\nbconvertapp.py", line 478, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbconvert\nbconvertapp.py", line 407, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbconvert\exporters\exporter.py", line 178, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbconvert\exporters\exporter.py", line 196, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbformat\__init__.py", line 141, in read
    return reads(fp.read(), as_version, **kwargs)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbformat\__init__.py", line 74, in reads
    nb = reader.reads(s, **kwargs)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbformat\reader.py", line 58, in reads
    nb_dict = parse_json(s, **kwargs)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbformat\reader.py", line 17, in parse_json
    raise NotJSONError(("Notebook does not appear to be JSON: %r" % s)[:77] + "...")
nbformat.reader.NotJSONError: Notebook does not appear to be JSON: '{\n    "metadata": {\n        "kernelsp...

As per recommendation i tried opening it on textpad and removed the "}" at the end and saved the notebook and now i try to open the notebook via jupyter and it once again failed with the new error

The notebook has been converted into HTML: Create AKS cluster and deploy BDC.html (in the same directory as the .ipynb file)
[NbConvertApp] Converting notebook Create AKS cluster and deploy BDC.ipynb to html
Traceback (most recent call last):
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbformat\reader.py", line 14, in parse_json
    nb_dict = json.loads(s, **kwargs)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 511 column 1 (char 145079)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\pradm\azuredatastudio-python\0.0.1\Scripts\jupyter-nbconvert.EXE\__main__.py", line 9, in <module>
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbconvert\nbconvertapp.py", line 337, in start
    self.convert_notebooks()
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbconvert\nbconvertapp.py", line 507, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbconvert\nbconvertapp.py", line 478, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbconvert\nbconvertapp.py", line 407, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbconvert\exporters\exporter.py", line 178, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbconvert\exporters\exporter.py", line 196, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbformat\__init__.py", line 141, in read
    return reads(fp.read(), as_version, **kwargs)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbformat\__init__.py", line 74, in reads
    nb = reader.reads(s, **kwargs)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbformat\reader.py", line 58, in reads
    nb_dict = parse_json(s, **kwargs)
  File "c:\users\pradm\azuredatastudio-python\0.0.1\lib\site-packages\nbformat\reader.py", line 17, in parse_json
    raise NotJSONError(("Notebook does not appear to be JSON: %r" % s)[:77] + "...")
nbformat.reader.NotJSONError: Notebook does not appear to be JSON: '{\n    "metadata": {\n        "kernelsp...

Then I loaded the JSON objects into online JSON Formatter and it reported a EOF issue and missing “}”. So I added the “}” back and saved the ipynb file. Loaded it back as Notebook into ADS and now ran the conversion and this time It worked fine without any issues. So for sure there is some formatting issue here which needs to be looked at. 

The notebook has been converted into HTML: Create AKS cluster and deploy BDC.html (in the same directory as the .ipynb file)
[NbConvertApp] Converting notebook Create AKS cluster and deploy BDC.ipynb to html
[NbConvertApp] Writing 452290 bytes to Create AKS cluster and deploy BDC.html

[Create AKS cluster and deploy BDC.zip](https://github.com/Microsoft/azuredatastudio/files/3043562/Create.AKS.cluster.and.deploy.BDC.zip)

**Comment by chlafreniere** [comment]
We've made strides in ensuring that notebooks are correct JSON (and valid notebook files). I have tested these notebooks, and cannot repro this issue any longer.
