### ISSUE TITLE
Spark History Url is not found

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#5050]
Issue Type: <b>Bug</b>

Submit spark job against 2.4/2.5 cluster. Got Spark History Url: https://168.61.217.209:30443/gateway/default/sparkhistory/history/application_1553722268698_0018/1

Click the link and got 
![image](https://user-images.githubusercontent.com/43652751/56235724-d5a25280-603c-11e9-9059-5ff6149ffa88.png)

Azure Data Studio version: azuredatastudio 1.6.0 (c2df3e0e0ae79713c34b51fee7b6e8a531cee1f1, 2019-04-15T17:44:43.676Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (46.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-pgsql|Mic|0.1.0

</details>

**Comment by kevcunnane** [comment]
@YurongHe this is a known issue in the platform. It takes a few minutes for the application link to start working. I'd suggest closing as upstream issue.

**Comment by YurongHe** [comment]
@kevcunnane how long do we need to wait to see the page? It has been more than 5 mins. Also from dashboard View Spark History link, there is application 0018 listed.

![image](https://user-images.githubusercontent.com/43652751/56236078-96283600-603d-11e9-9287-f16f1d6cd5dd.png)

**Comment by kevcunnane** [comment]
Are the links the same? The only thing I can think is if the link is inaccurate. Generally it should be up within 5min.

**Comment by YurongHe** [comment]
Not sure if it is related to the job itself. Will test again with a valid job.

Application application_1554847846499_0010 failed 2 times due to AM Container for appattempt_1554847846499_0010_000002 exited with exitCode: 13
Failing this attempt.Diagnostics: [2019-04-16 18:41:36.682]Exception from container-launch.
Container id: container_1554847846499_0010_02_000001
Exit code: 13
[2019-04-16 18:41:36.688]Container exited with a non-zero exit code 13. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
Last 4096 bytes of stderr :
19/04/16 18:41:34 INFO util.SignalUtils: Registered signal handler for TERM
19/04/16 18:41:34 INFO util.SignalUtils: Registered signal handler for HUP
19/04/16 18:41:34 INFO util.SignalUtils: Registered signal handler for INT
19/04/16 18:41:34 INFO spark.SecurityManager: Changing view acls to: root
19/04/16 18:41:34 INFO spark.SecurityManager: Changing modify acls to: root
19/04/16 18:41:34 INFO spark.SecurityManager: Changing view acls groups to:
19/04/16 18:41:34 INFO spark.SecurityManager: Changing modify acls groups to:
19/04/16 18:41:34 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(root); groups with view permissions: Set(); users with modify permissions: Set(root); groups with modify permissions: Set()
19/04/16 18:41:35 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/04/16 18:41:35 INFO yarn.ApplicationMaster: Preparing Local resources
19/04/16 18:41:36 INFO yarn.ApplicationMaster: ApplicationAttemptId: appattempt_1554847846499_0010_000002
19/04/16 18:41:36 INFO yarn.ApplicationMaster: Starting the user application in a separate Thread
19/04/16 18:41:36 INFO yarn.ApplicationMaster: Waiting for spark context initialization...
19/04/16 18:41:36 INFO yarn.ApplicationMaster: Final app status: FAILED, exitCode: 13
19/04/16 18:41:36 ERROR yarn.ApplicationMaster: Uncaught exception:
java.lang.IllegalStateException: User did not initialize spark context!
at org.apache.spark.deploy.yarn.ApplicationMaster.runDriver(ApplicationMaster.scala:485)
at org.apache.spark.deploy.yarn.ApplicationMaster.org$apache$spark$deploy$yarn$ApplicationMaster$$runImpl(ApplicationMaster.scala:305)
at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply$mcV$sp(ApplicationMaster.scala:245)
at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:245)
at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:245)
at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:773)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:422)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1889)
at org.apache.spark.deploy.yarn.ApplicationMaster.doAsUser(ApplicationMaster.scala:772)
at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:244)
at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:797)
at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)
19/04/16 18:41:36 INFO yarn.ApplicationMaster: Deleting staging directory hdfs://nmnode-0-svc:9000/user/root/.sparkStaging/application_1554847846499_0010
19/04/16 18:41:36 INFO util.ShutdownHookManager: Shutdown hook called
[2019-04-16 18:41:36.688]Container exited with a non-zero exit code 13. Error file: prelaunch.err.
Last 4096 bytes of prelaunch.err :
Last 4096 bytes of stderr :
19/04/16 18:41:34 INFO util.SignalUtils: Registered signal handler for TERM
19/04/16 18:41:34 INFO util.SignalUtils: Registered signal handler for HUP
19/04/16 18:41:34 INFO util.SignalUtils: Registered signal handler for INT
19/04/16 18:41:34 INFO spark.SecurityManager: Changing view acls to: root
19/04/16 18:41:34 INFO spark.SecurityManager: Changing modify acls to: root
19/04/16 18:41:34 INFO spark.SecurityManager: Changing view acls groups to:
19/04/16 18:41:34 INFO spark.SecurityManager: Changing modify acls groups to:
19/04/16 18:41:34 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(root); groups with view permissions: Set(); users with modify permissions: Set(root); groups with modify permissions: Set()
19/04/16 18:41:35 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/04/16 18:41:35 INFO yarn.ApplicationMaster: Preparing Local resources
19/04/16 18:41:36 INFO yarn.ApplicationMaster: ApplicationAttemptId: appattempt_1554847846499_0010_000002
19/04/16 18:41:36 INFO yarn.ApplicationMaster: Starting the user application in a separate Thread
19/04/16 18:41:36 INFO yarn.ApplicationMaster: Waiting for spark context initialization...
19/04/16 18:41:36 INFO yarn.ApplicationMaster: Final app status: FAILED, exitCode: 13
19/04/16 18:41:36 ERROR yarn.ApplicationMaster: Uncaught exception:
java.lang.IllegalStateException: User did not initialize spark context!
at org.apache.spark.deploy.yarn.ApplicationMaster.runDriver(ApplicationMaster.scala:485)
at org.apache.spark.deploy.yarn.ApplicationMaster.org$apache$spark$deploy$yarn$ApplicationMaster$$runImpl(ApplicationMaster.scala:305)
at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply$mcV$sp(ApplicationMaster.scala:245)
at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:245)
at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:245)
at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:773)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:422)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1889)
at org.apache.spark.deploy.yarn.ApplicationMaster.doAsUser(ApplicationMaster.scala:772)
at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:244)
at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:797)
at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)
19/04/16 18:41:36 INFO yarn.ApplicationMaster: Deleting staging directory hdfs://nmnode-0-svc:9000/user/root/.sparkStaging/application_1554847846499_0010
19/04/16 18:41:36 INFO util.ShutdownHookManager: Shutdown hook called
For more detailed output, check the application tracking page: http://master-0.master-svc:8088/cluster/app/application_1554847846499_0010 Then click on links to logs of each attempt.
. Failing the application.

**Comment by YurongHe** [comment]
Test it with valid jar file. The link could be open.
