### ISSUE TITLE
Notebook crashes ADS window when using SQL magic cells

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#5113]
Issue Type: <b>Bug</b>

Just work with a notebook that uses SQL magic to execute commands. After executing few cells and doing some editing, ADS window will crash. You get a popup saying do you want to reload with the message. Try file:

https://github.com/Microsoft/sql-server-samples/blob/master/samples/features/sql-big-data-cluster/spark/data-loading/spark-sql.ipynb

Azure Data Studio version: azuredatastudio 1.6.0 (d62068025cd2fe896fb516e58212b9e92210c669, 2019-04-16T21:09:26.577Z)
OS version: Windows_NT x64 10.0.18875

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.85GB (16.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
agent|Mic|0.37.0
azuredatastudio-postgresql|Mic|0.1.0
dacpac|Mic|0.1.0
import|Mic|0.7.0
profiler|Mic|0.7.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.12.1

</details>

**Comment by YurongHe** [comment]
Need to repro it. Currently can't see the issue.

**Comment by YurongHe** [comment]
Look like out of memory when render output for VSBuffer(Buffer.from(source)); in butter.ts

       public static fromString(source: string): VSBuffer {
		if (hasBuffer) {
			return new VSBuffer(Buffer.from(source));

**Comment by YurongHe** [comment]
There are multiple other issues:
Uncaught ReferenceError: define is not defined
    at <anonymous>:1:20
    at Object.evalInnerHTMLScriptTags (renderers.ts:468)
    at Object.renderHTML (renderers.ts:55)
    at RenderedHTML.render (widgets.ts:156)
    at RenderedHTML.renderModel (widgets.ts:106)
    at OutputComponent.createRenderedMimetype (output.component.ts:117)
    at OutputComponent.renderOutput (output.component.ts:83)
    at OutputComponent.ngOnInit (output.component.ts:46)
    at checkAndUpdateDirectiveInline (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:10822)
    at checkAndUpdateNodeInline (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12245)
    at checkAndUpdateNode (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12184)
    at debugCheckAndUpdateNode (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12887)
    at debugCheckDirectivesFn (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12828)
    at Object.eval [as updateDirectives] (outputArea.component.html:9)
    at Object.debugUpdateDirectives [as updateDirectives] (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12813)
    at checkAndUpdateView (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12151)
    at callViewAction (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12514)
    at execEmbeddedViewsAction (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12472)
    at checkAndUpdateView (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12152)
    at callViewAction (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12514)
    at execComponentViewsAction (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12446)
    at checkAndUpdateView (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12157)
    at callViewAction (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12514)
    at execEmbeddedViewsAction (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12472)
    at checkAndUpdateView (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12152)
    at callWithDebugContext (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:13213)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12753)
    at ViewRef_.detectChanges (d:\git\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:10225)
    at _register.cellModel.onOutputsChanged (codeCell.component.ts:40)
    at Emitter.fire (event.ts:557)
    at CellModel.fireOutputsChanged (cell.ts:312)
    at CellModel.handleIOPub (cell.ts:377)
    at Object.handle (cell.ts:303)
    at FutureWrapper.onMessage (mainThreadNotebook.ts:412)
    at MainThreadNotebook.$onFutureMessage (mainThreadNotebook.ts:69)
    at RPCProtocol._doInvokeHandler (rpcProtocol.ts:399)
    at RPCProtocol._invokeHandler (rpcProtocol.ts:384)
    at RPCProtocol._receiveRequest (rpcProtocol.ts:304)
    at RPCProtocol._receiveOneMessage (rpcProtocol.ts:226)
    at RPCProtocol._protocol.onMessage (rpcProtocol.ts:101)
    at Emitter.fire (event.ts:557)
    at deliverMessages (ipc.net.ts:416)
    at source (ipc.net.ts:423)
    at Emitter.fire (event.ts:557)
    at PersistentProtocol._receiveMessage (ipc.net.ts:702)
    at PersistentProtocol._socketDisposables.push._socketReader.onMessage.msg (ipc.net.ts:573)
    at Emitter.fire (event.ts:557)
    at ProtocolReader.acceptChunk (ipc.net.ts:236)
    at ProtocolReader._register._socket.onData.data (ipc.net.ts:197)
    at Socket.listener (ipc.net.ts:28)
    at ZoneDelegate.invokeTask (D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421)
    at Zone.runTask (D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188)
    at ZoneTask.invokeTask (D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:496)
    at Socket.ZoneTask.invoke (D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:485)
    at Socket.emit (events.js:182)
    at addChunk (_stream_readable.js:279)
    at readableAddChunk (_stream_readable.js:264)
    at Socket.Readable.push (_stream_readable.js:219)
    at Pipe.onread (net.js:636)

**Comment by YurongHe** [comment]
Second: 
Exception opening new comm (at DefaultKernel.<anonymous> (d:\git\azuredatastudio\extensions\notebook\node_modules\@jupyterlab\services\lib\kernel\default.js:924:25))
console.(anonymous function) @ D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:2280
log @ console.ts:134
$logExtensionHostMessage @ mainThreadConsole.ts:38
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
RPCProtocol._protocol.onMessage @ rpcProtocol.ts:101
fire @ event.ts:557
deliverMessages @ ipc.net.ts:416
source @ ipc.net.ts:423
fire @ event.ts:557
_receiveMessage @ ipc.net.ts:702
PersistentProtocol._socketDisposables.push._socketReader.onMessage.msg @ ipc.net.ts:573
fire @ event.ts:557
acceptChunk @ ipc.net.ts:236
ProtocolReader._register._socket.onData.data @ ipc.net.ts:197
listener @ ipc.net.ts:28
ZoneDelegate.invokeTask @ D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421
Zone.runTask @ D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188
ZoneTask.invokeTask @ D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:496
ZoneTask.invoke @ D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:485
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
D:\git\azuredatastudio\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] Error: Object 'jupyter.widget' not found in registry
	at Promise (d:\git\azuredatastudio\extensions\notebook\node_modules\@jupyterlab\services\lib\kernel\default.js:1472:28)
	at new Promise (<anonymous>)
	at Object.loadObject (d:\git\azuredatastudio\extensions\notebook\node_modules\@jupyterlab\services\lib\kernel\default.js:1451:16)
	at DefaultKernel.<anonymous> (d:\git\azuredatastudio\extensions\notebook\node_modules\@jupyterlab\services\lib\kernel\default.js:917:44)
	at Generator.next (<anonymous>)
	at __awaiter (d:\git\azuredatastudio\extensions\notebook\node_modules\@jupyterlab\services\lib\kernel\default.js:9:71)
	at new Promise (<anonymous>)
	at __awaiter (d:\git\azuredatastudio\extensions\notebook\node_modules\@jupyterlab\services\lib\kernel\default.js:5:12)
	at DefaultKernel._handleCommOpen (d:\git\azuredatastudio\extensions\notebook\node_modules\@jupyterlab\services\lib\kernel\default.js:909:16)
	at DefaultKernel.<anonymous> (d:\git\azuredatastudio\extensions\notebook\node_modules\@jupyterlab\services\lib\kernel\default.js:1016:36)
	at Generator.next (<anonymous>)
	at fulfilled (d:\git\azuredatastudio\extensions\notebook\node_modules\@jupyterlab\services\lib\kernel\default.js:6:58)

**Comment by chlafreniere** [comment]
Moving to planning to align with perf work planned in July.

**Comment by Charles-Gagnon** [comment]
BDC support in ADS is [being deprecated](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-data-studio-and-bdc-retirement/ba-p/3669192) so closing all related issues.
