### ISSUE TITLE
Profiler Failing against azure on mac

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#5304]
On mac against a azure database profiler is erroring

<details>

[[object Object]]Failed to create session: An exception occurred while executing a Transact-SQL statement or batch.
zone-node.js:2280
Error: Failed to create session: An exception occurred while executing a Transact-SQL statement or batch.
	at new ResponseError (/Users/andresse/code/azuredatastudio/extensions/mssql/node_modules/vscode-jsonrpc/lib/messages.js:46:28)
	at handleResponse (/Users/andresse/code/azuredatastudio/extensions/mssql/node_modules/vscode-jsonrpc/lib/main.js:430:48)
	at processMessageQueue (/Users/andresse/code/azuredatastudio/extensions/mssql/node_modules/vscode-jsonrpc/lib/main.js:258:17)
	at Immediate.<anonymous> (/Users/andresse/code/azuredatastudio/extensions/mssql/node_modules/vscode-jsonrpc/lib/main.js:242:13)
	at runCallback (timers.js:696:18)
	at tryOnImmediate (timers.js:667:5)
	at processImmediate (timers.js:649:5)

</details>

Steps to Reproduce:

1. On Mac
2. Against Azure
3. Launch profiler
4. Use defaults for everything

Profiler errors out

**Comment by alanrenmsft** [comment]
@anthonydresser  In the dialog that popped up for selecting session, did you select the one with azure in its name? please give it a try.

**Comment by anthonydresser** [comment]
No, I just use the defaults that come up. If there is a special one you have to select for azure that's fine, but the profiler shouldn't just fail silently and not tell the user something went wrong.

**Comment by alanrenmsft** [comment]
@anthonydresser that i do agree, I think I had an issue to track it maybe in the backlog now, I will use this one and put it in june release.
