### ISSUE TITLE
Exception connect, expanding two servers at the same time

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#5388]
- Azure Data Studio Version: `1.7.0`

Steps to Reproduce:

1. Double-click two servers one right after the other to connect & expand

Expected: They both connect and expand

Actual: The below exception was thrown and one of the nodes did not expand.  I had to close and reopen ADS to get the node connected.

```
  ERR Cannot read property 'serviceTimer' of undefined: TypeError: Cannot read property 'serviceTimer' of undefined
    at ConnectionStatusManager.onConnectionComplete (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:157367:24)
    at ConnectionManagementService.onConnectionComplete (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:333963:60)
    at MainThreadDataProtocol.$onConnectionComplete (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:217549:47)
    at RPCProtocol._doInvokeHandler (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:222768:27)
    at RPCProtocol._invokeHandler (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:222753:45)
    at RPCProtocol._receiveRequest (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:222685:32)
    at RPCProtocol._receiveOneMessage (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:222613:26)
    at RPCProtocol._protocol.onMessage (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:222503:52)
    at Emitter.fire (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:10341:38)
    at deliverMessages (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:32243:25)
    at source (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:32249:13)
    at Emitter.fire (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:10341:38)
    at PersistentProtocol._receiveMessage (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:32473:37)
    at PersistentProtocol._socketDisposables.push._socketReader.onMessage.msg (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:32351:83)
    at Emitter.fire (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:10341:38)
    at ProtocolReader.acceptChunk (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:32093:37)
    at ProtocolReader._register._socket.onData.data (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:32062:61)
    at Socket.listener (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:32630:40)
    at ZoneDelegate.invokeTask (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:188:47)
    at ZoneTask.invokeTask (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:496:34)
    at Socket.ZoneTask.invoke (C:\Users\karlb\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:485:48)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
```

**Comment by kburtram** [comment]
Closing older issues.  I have been able to reproduce this exception on recent builds.
