### ISSUE TITLE
ubuntu 18.04 Connection Timeout Expired

### ISSUE THREAD

**Issue by codecodingg** [microsoft/azuredatastudio#5425]
- Azure Data Studio Version: 1.6.0

Steps to Reproduce:

System info:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

Error Detail:

System.Data.SqlClient.SqlException (0x80131904): Connection Timeout Expired.  The timeout period elapsed during the post-login phase.  The connection could have timed out while waiting for server to complete the login process and respond; Or it could have timed out while attempting to create multiple active connections.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=25; handshake=182; [Login] initialization=0; authentication=0; [Post-Login] complete=14166;  ---> System.ComponentModel.Win32Exception (258): Unknown error 258
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 521
ClientConnectionId:4712a0e1-8474-4bc9-92b5-61f1494a7449
Error Number:-2,State:0,Class:11

**Comment by codecodingg** [comment]
the same version in windows 10 sucess

**Comment by kburtram** [comment]
@codecodingg connection timeouts typically indicate some type of network connectivity issue.  Are you able to connect to this SQL Server instance from the Ubuntu client using any other software, such as SQLCMD?

**Comment by codecodingg** [comment]
@kburtram I tried JetBrains DataGrip, connection successed

**Comment by kburtram** [comment]
@codecodingg Azure Data Studio only officially supports 2014+, so I don't think ADS will work correctly even if a connection is successful.  Though I wouldn't expect a connection time out.  I'll discuss with the team if there are any good diagnostic steps in this scenario.

**Comment by Charles-Gagnon** [comment]
Closing this as 2005 is not officially supported. But you could try increasing the connection timeout in the **Advanced Properties** section of the Connection Dialog, that may help as a workaround.
