### ISSUE TITLE
Potential listener leak at ConnectionProfile.set providerName needs to be investigated

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#5514]
- Azure Data Studio Version: `master`

I'm see the below warning message in my dev environment.  We should investigate and resolve to avoid memory leaks.

```
[7572:0515/180013.723:INFO:CONSOLE(2280)] "[a71] potential listener LEAK detected, having 615 listeners already. MOST frequent listener (85):", source: D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js (2280)
[7572:0515/180013.724:INFO:CONSOLE(2280)] "    at ConnectionProfile.set providerName [as providerName] (file:///D:/xplat/azuredatastudio/out/sql/platform/connection/common/providerConnectionInfo.js:53:57)
    at new ProviderConnectionInfo (file:///D:/xplat/azuredatastudio/out/sql/platform/connection/common/providerConnectionInfo.js:15:35)
    at new ConnectionProfile (file:///D:/xplat/azuredatastudio/out/sql/platform/connection/common/connectionProfile.js:14:13)
    at data.map.d (file:///D:/xplat/azuredatastudio/out/sql/workbench/parts/dashboard/widgets/explorer/explorerWidget.component.js:84:41)
    at Array.map (<anonymous>)
    at SafeSubscriber._register.rxjsUtils_1.toDisposableSubscription._bootstrap.metadataService.databaseNames.subscribe.data [as _next] (file:///D:/xplat/azuredatastudio/out/sql/workbench/parts/dashboard/widgets/explorer/explorerWidget.component.js:83:46)
    at SafeSubscriber.__tryOrUnsub (d:\xplat\azuredatastudio\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.next (d:\xplat\azuredatastudio\node_modules\rxjs\Subscriber.js:185:22)
    at Subscriber._next (d:\xplat\azuredatastudio\node_modules\rxjs\Subscriber.js:125:26)
    at Subscriber.next (d:\xplat\azuredatastudio\node_modules\rxjs\Subscriber.js:89:18)
    at d:\xplat\azuredatastudio\node_modules\rxjs\observable\PromiseObservable.js:66:36
    at ZoneDelegate.invoke (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:388:26)
    at Object.onInvoke (d:\xplat\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4156:37)
    at ZoneDelegate.invoke (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:387:32)
    at Zone.run (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:138:43)
    at D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421:31)
    at Object.onInvokeTask (d:\xplat\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:4147:37)
    at ZoneDelegate.invokeTask (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:420:36)
    at Zone.runTask (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:595:35)
    at ZoneTask.invokeTask (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:500:21)
    at Socket.ZoneTask.invoke (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:485:48)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)", source: D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js (2280)
```

**Comment by ranasaria** [comment]
This was also observed in AdsStress run: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=32767

**Comment by kburtram** [comment]
I'm no longer seeing this issue.
