### ISSUE TITLE
Consistent Connection Issue with Windows Authentication

### ISSUE THREAD

**Issue by r-haas** [microsoft/azuredatastudio#5692]
Issue Type: <b>Bug</b>

For over six months, I've been able to successfully connect to SQL Server instances using Windows Authentication. Now, shortly after an Active Directory password change (not 100% sure these factors are related), I consistently receive a GSSAPI error anytime I try to establish a connection using Windows Auth. I have tried running kinit, and I've even removed all existing kerberos tokens via kdestroy just to be safe.

Error details are as follows:

System.Data.SqlClient.SqlException (0x80131904): GSSAPI operation failed with error -  The provided name was not a mechanism name. (unknown mech-code 0 for mech unknown).
   at Microsoft.Win32.SafeHandles.SafeGssNameHandle.CreatePrincipal(String name) in /xplat/cfxfork/corefx/src/Common/src/Microsoft/Win32/SafeHandles/GssSafeHandles.cs:line 45
   at System.Net.Security.SafeDeleteNegoContext..ctor(SafeFreeNegoCredentials credential, String targetName) in /xplat/cfxfork/corefx/src/Common/src/System/Net/Security/Unix/SafeDeleteNegoContext.cs:line 36
   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags) in /xplat/cfxfork/corefx/src/Common/src/System/Net/Security/NegotiateStreamPal.Unix.cs:line 166
   at System.Net.Security.NegotiateStreamPal.InitializeSecurityContext(SafeFreeCredentials credentialsHandle, SafeDeleteContext& securityContext, String spn, ContextFlagsPal requestedContextFlags, SecurityBuffer[] inSecurityBufferArray, SecurityBuffer outSecurityBuffer, ContextFlagsPal& contextFlags) in /xplat/cfxfork/corefx/src/Common/src/System/Net/Security/NegotiateStreamPal.Unix.cs:line 240
   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName) in /xplat/cfxfork/corefx/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNIProxy.cs:line 113
   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer) in /xplat/cfxfork/corefx/src/System.Data.SqlClient/src/System/Data/SqlClient/TdsParserStateObjectManaged.cs:line 241
   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength) in /xplat/cfxfork/corefx/src/System.Data.SqlClient/src/System/Data/SqlClient/TdsParser.cs:line 6488
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken) in /xplat/cfxfork/corefx/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlInternalConnectionTds.cs:line 400
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions) in /xplat/cfxfork/corefx/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlConnectionFactory.cs:line 136
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions) in /xplat/cfxfork/corefx/src/Common/src/System/Data/ProviderBase/DbConnectionFactory.cs:line 96
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _) in /xplat/cfxfork/corefx/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionFactory.cs:line 86
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 521
ClientConnectionId:c555d236-5e14-418c-a28d-1b2b1bc6d944

Azure Data Studio version: Azure Data Studio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-07T21:38:05.313Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alexandreabeh** [comment]
I have the same setup as Robert and have not recently changed my Active Directory password, but am getting the same error.

**Comment by dcpurnell** [comment]
I also recently updated my AD password and now am unable to connect to SQL Server with Azure Data Studio using Windows Authentication:

GSSAPI operation failed with error - The provided name was not a mechanism name. (unknown mech-code 0 for mech unknown).
at Microsoft.Win32.SafeHandles.SafeGssNameHandle.CreatePrincipal(String name) in /xplat/cfxfork/corefx/src/Common/src/Microsoft/Win32/SafeHandles/GssSafeHandles.cs:line 45
at System.Net.Security.SafeDeleteNegoContext..ctor(SafeFreeNegoCredentials credential, String targetName) in /xplat/cfxfork/corefx/src/Common/src/System/Net/Security/Unix/SafeDeleteNegoContext.cs:line 36
at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags) in /xplat/cfxfork/corefx/src/Common/src/System/Net/Security/NegotiateStreamPal.Unix.cs:line 166
at System.Net.Security.NegotiateStreamPal.InitializeSecurityContext(SafeFreeCredentials credentialsHandle, SafeDeleteContext& securityContext, String spn, ContextFlagsPal requestedContextFlags, SecurityBuffer[] inSecurityBufferArray, SecurityBuffer outSecurityBuffer, ContextFlagsPal& contextFlags) in /xplat/cfxfork/corefx/src/Common/src/System/Net/Security/NegotiateStreamPal.Unix.cs:line 240
at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName) in /xplat/cfxfork/corefx/src/System.Data.SqlClient/src/System/Data/SqlClient/SNI/SNIProxy.cs:line 113
at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer) in /xplat/cfxfork/corefx/src/System.Data.SqlClient/src/System/Data/SqlClient/TdsParserStateObjectManaged.cs:line 241
at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength) in /xplat/cfxfork/corefx/src/System.Data.SqlClient/src/System/Data/SqlClient/TdsParser.cs:line 6488

**Comment by cybearg-defense** [comment]
I am also receiving the error listed above:

GSSAPI operation failed with error - The provided name was not a mechanism name. (unknown mech-code 0 for mech unknown).
at Microsoft.Win32.SafeHandles.SafeGssNameHandle.CreatePrincipal(String name) in /xplat/cfxfork/corefx/src/Common/src/Microsoft/Win32/SafeHandles/GssSafeHandles.cs:line 45

kinit and klist show that I have a valid authorization.

I have read through issues 4291, 3781, and 4085; they do not match the errors I am receiving. 

I have never connected successfully.
First attempt to connect was several weeks after a password change.

macOS 10.14.6
2.6 GHz Intel Core i7

Azure Data Studio
Version: 1.13.1
Commit: d08d07fe39c7fe74f9265db02cb963c38d048299
Date: 2019-11-14T23:00:55.976Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Comment by deepankar-j** [comment]
I'm encountering the same issue with OS X 10.15.5.   I was able to connect successfully before, but all of a sudden (without any password change), I see the same error as this thread.

Has anyone solved this issue?

**Comment by deepankar-j** [comment]
In case anyone else encounters this issue, here's how it was resolved for me:

My IT Department found that for some reason my computer's domain binding failed (not sure exactly what that entails).   They forced my computer to re-join the company's domain, which resolved the issue.

**Comment by kawai924** [comment]
> In case anyone else encounters this issue, here's how it was resolved for me:
> 
> My IT Department found that for some reason my computer's domain binding failed (not sure exactly what that entails). They forced my computer to re-join the company's domain, which resolved the issue.

resolved with the same method.
in user & group> login options > click on "edit" for Network account Server > choose the AD you want to update > open directory utility > choose active directory > unbind
then join the AD again

**Comment by dcr21** [comment]
> 

Hi, Can you explain this a bit more clearly? I'm having the same issue. Thanks !

**Comment by dcr21** [comment]
> > In case anyone else encounters this issue, here's how it was resolved for me:
> > My IT Department found that for some reason my computer's domain binding failed (not sure exactly what that entails). They forced my computer to re-join the company's domain, which resolved the issue.
> 
> resolved with the same method. in user & group> login options > click on "edit" for Network account Server > choose the AD you want to update > open directory utility > choose active directory > unbind then join the AD again

Hi, could you explain how you resolved this a bit more clearly? Thanks !

**Comment by cheenamalhotra** [comment]
@dcr21 

We'd be able to assist you better if you can open a new issue with specific details about your environment and repro steps. We'd be able to track and help that way better!

Since generic issue of Windows Authentication using Kerberos on all platforms is now resolved, I will proceed to close this.
