### ISSUE TITLE
MacOS SQLOPS Helper taking high CPU

### ISSUE THREAD

**Issue by craigdetter** [microsoft/azuredatastudio#577]
- SQL Operations Studio Version:

Steps to Reproduce:

1.) Launch
2.) Try to connect - fails on (see stack trace below)
3.) CPU usage high

NOTE***       The CPU usage also goes high even without the failed connection (SQLOPS Helper)

System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass22_0.<TryGetConnection>b__0(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ReliableConnection\ReliableSqlConnection.cs:line 298
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.<TryOpenConnection>d__46.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 542
ClientConnectionId:00000000-0000-0000-0000-000000000000 

<img width="977" alt="screen shot 2018-01-29 at 1 21 47 pm" src="https://user-images.githubusercontent.com/15794819/35529708-7ad72f52-04f7-11e8-9a87-048573ef824b.png">

**Comment by MattIrv** [comment]
Thanks for reporting this. Based on your note above, this just happens when you start SQL Ops Studio even if you don't make a connection at all? 

We've seen similar reports for the VS Code mssql extension too but haven't been able to track it down yet: https://github.com/Microsoft/vscode-mssql/issues/1028

**Comment by craigdetter** [comment]
Yes, even without a connection I've seen it go high CPU. That is just
launching the app.

**Comment by bwalkenhorst** [comment]
I am experiencing the same problem on Windows 7 with the March release.

**Comment by alanrenmsft** [comment]
I know this is an old issue, but still want to see whether you are experiencing the same issue with the latest Azure Data Studio release, if so please reopen the issue and let us know.
