### ISSUE TITLE
Potential listener leak at new View needs to be investigated

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#5839]
- Azure Data Studio Version:
Master

Steps to Reproduce:

1. SQL Nb Test - Stress mode after around ~32 iterations pops the following potential leak:
[8860:0531/092052.107:INFO:CONSOLE(388)] "    at new View (file:///E:/mssqltoolsagentworkspace/79/s/out/vs/editor/browser/view/viewImpl.js:22:41)
    at StandaloneCodeEditor._createView (file:///E:/mssqltoolsagentworkspace/79/s/out/vs/editor/browser/widget/codeEditorWidget.js:1066:26)
    at StandaloneCodeEditor._attachModel (file:///E:/mssqltoolsagentworkspace/79/s/out/vs/editor/browser/widget/codeEditorWidget.js:969:46)
    at StandaloneCodeEditor.setModel (file:///E:/mssqltoolsagentworkspace/79/s/out/vs/editor/browser/widget/codeEditorWidget.js:241:18)
    at input.resolve.then.then.editorModel (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/electron-browser/modelComponents/queryTextEditor.js:62:56)
    at ZoneDelegate.invoke (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:388:26)
    at Object.onInvoke (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:4156:37)
    at ZoneDelegate.invoke (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:387:32)
    at Zone.run (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:138:43)
    at E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:421:31)
    at Object.onInvokeTask (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:4147:37)
    at ZoneDelegate.invokeTask (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:420:36)
    at Zone.runTask (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:595:35)", source: E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js (388)

Stress run and logs:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=32767
[StressRun_log_22_32767.zip](https://github.com/microsoft/azuredatastudio/files/3249055/StressRun_log_22_32767.zip)

**Comment by kburtram** [comment]
Closing these out since they aren't really actionable and can easily be recreated once someone is investigating memory usage.
