### ISSUE TITLE
Potential listener leak at new LanguageSelection needs to be investigated 

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#5853]
SQL Nb Test - Stress mode after around ~85 iterations pops the following potential leak:
[8860:0531/092303.792:INFO:CONSOLE(388)] "    at new LanguageSelection (file:///E:/mssqltoolsagentworkspace/79/s/out/vs/editor/common/services/modeServiceImpl.js:15:28)
    at WorkbenchModeServiceImpl.create (file:///E:/mssqltoolsagentworkspace/79/s/out/vs/editor/common/services/modeServiceImpl.js:86:20)
    at UntitledEditorModel.getOrCreateMode (file:///E:/mssqltoolsagentworkspace/79/s/out/vs/workbench/common/editor/textEditorModel.js:104:32)
    at UntitledEditorModel.createTextEditorModel (file:///E:/mssqltoolsagentworkspace/79/s/out/vs/workbench/common/editor/textEditorModel.js:66:44)
    at UntitledEditorModel.<anonymous> (file:///E:/mssqltoolsagentworkspace/79/s/out/vs/workbench/common/editor/untitledEditorModel.js:127:26)
    at Generator.next (<anonymous>)
    at fulfilled (file:///E:/mssqltoolsagentworkspace/79/s/out/vs/workbench/common/editor/untitledEditorModel.js:16:58)
    at ZoneDelegate.invoke (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:388:26)
    at Object.onInvoke (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:4156:37)
    at ZoneDelegate.invoke (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:387:32)
    at Zone.run (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:138:43)
    at E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:421:31)
    at Object.onInvokeTask (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:4147:37)
    at ZoneDelegate.invokeTask (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:420:36)
    at Zone.runTask (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:595:35)", source: E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js (388)

Stress run and logs:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=32767
[StressRun_log_22_32767.zip](https://github.com/microsoft/azuredatastudio/files/3249055/StressRun_log_22_32767.zip)

**Comment by kburtram** [comment]
Closing these out since they aren't really actionable and can easily be recreated once someone is investigating memory usage.
