### ISSUE TITLE
Potential listener leak at UntitledEditorModel.registerListeners needs to be investigated 

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#5854]
SQL Nb Test - Stress mode after around ~86 iterations pops the following potential leak:
[8860:0531/092305.839:INFO:CONSOLE(388)] "    at UntitledEditorModel.registerListeners (file:///E:/mssqltoolsagentworkspace/79/s/out/vs/workbench/common/editor/untitledEditorModel.js:51:54)
    at new UntitledEditorModel (file:///E:/mssqltoolsagentworkspace/79/s/out/vs/workbench/common/editor/untitledEditorModel.js:41:18)
    at InstantiationService._createInstance (file:///E:/mssqltoolsagentworkspace/79/s/out/vs/platform/instantiation/common/instantiationService.js:82:20)
    at InstantiationService.createInstance (file:///E:/mssqltoolsagentworkspace/79/s/out/vs/platform/instantiation/common/instantiationService.js:53:31)
    at UntitledEditorInput.createModel (file:///E:/mssqltoolsagentworkspace/79/s/out/vs/workbench/common/editor/untitledEditorInput.js:168:68)
    at UntitledEditorInput.resolve (file:///E:/mssqltoolsagentworkspace/79/s/out/vs/workbench/common/editor/untitledEditorInput.js:163:37)
    at setInput.then (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/electron-browser/modelComponents/queryTextEditor.js:60:40)
    at ZoneDelegate.invoke (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:388:26)
    at Object.onInvoke (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:4156:37)
    at ZoneDelegate.invoke (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:387:32)
    at Zone.run (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:138:43)
    at E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:421:31)
    at Object.onInvokeTask (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:4147:37)
    at ZoneDelegate.invokeTask (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:420:36)
    at Zone.runTask (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:595:35)", source: E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js (388)

Stress run and logs:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=32767
[StressRun_log_22_32767.zip](https://github.com/microsoft/azuredatastudio/files/3249055/StressRun_log_22_32767.zip)

**Comment by kburtram** [comment]
Closing these out since they aren't really actionable and can easily be recreated once someone is investigating memory usage.
