### ISSUE TITLE
Potential listener leak at new Object.attachStyler needs to be investigated 

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#5855]
Sql NB multiple cells test - Stress mode after around ~2 iterations pops the following potential leak:
[8860:0531/092405.647:INFO:CONSOLE(2280)] "    at Object.attachStyler (file:///E:/mssqltoolsagentworkspace/79/s/out/vs/platform/theme/common/styler.js:33:29)
    at Object.attachTableStyler (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/platform/theme/common/styler.js:85:25)
    at Object.renderDataResource (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/parts/notebook/outputs/tableRenderers.js:60:18)
    at RenderedDataResource.render (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/parts/notebook/outputs/widgets.js:302:35)
    at RenderedDataResource.renderModel (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/parts/notebook/outputs/widgets.js:70:25)
    at OutputComponent.createRenderedMimetype (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/parts/notebook/cellViews/output.component.js:76:24)
    at OutputComponent.renderOutput (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/parts/notebook/cellViews/output.component.js:51:18)
    at OutputComponent.ngOnInit (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/parts/notebook/cellViews/output.component.js:24:18)
    at checkAndUpdateDirectiveInline (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:10822:19)
    at checkAndUpdateNodeInline (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12245:17)
    at checkAndUpdateNode (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12184:16)
    at debugCheckAndUpdateNode (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12887:59)
    at debugCheckDirectivesFn (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12828:13)
    at Object.eval [as updateDirectives] (ng:///ModuleClass/OutputAreaComponent.ngfactory.js:48:5)
    at Object.debugUpdateDirectives [as updateDirectives] (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12813:21)
    at checkAndUpdateView (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12151:14)
    at callViewAction (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12514:21)
    at execEmbeddedViewsAction (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12472:17)
    at checkAndUpdateView (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12152:5)
    at callViewAction (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12514:21)
    at execComponentViewsAction (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12446:13)
    at checkAndUpdateView (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12157:5)
    at callViewAction (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12514:21)
    at execEmbeddedViewsAction (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12472:17)
    at checkAndUpdateView (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12152:5)
    at callWithDebugContext (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:13213:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12753:12)
    at ViewRef_.detectChanges (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:10225:63)
    at _register.cellModel.onOutputsChanged (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/parts/notebook/cellViews/codeCell.component.js:44:37)
    at Emitter.fire (file:///E:/mssqltoolsagentworkspace/79/s/out/vs/base/common/event.js:453:38)
    at CellModel.fireOutputsChanged (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/parts/notebook/models/cell.js:277:36)
    at CellModel.handleIOPub (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/parts/notebook/models/cell.js:337:22)
    at Object.handle (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/parts/notebook/models/cell.js:269:60)
    at SQLFuture.<anonymous> (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/services/notebook/sql/sqlSessionManager.js:443:32)
    at Generator.next (<anonymous>)
    at fulfilled (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/services/notebook/sql/sqlSessionManager.js:16:58)
    at ZoneDelegate.invoke (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:388:26)
    at Zone.run (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:138:43)
    at E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:595:35)
    at ZoneTask.invokeTask (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:500:21)
    at Socket.ZoneTask.invoke (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:485:48)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)", source: E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js (2280)

Stress run and logs:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=32767
[StressRun_log_22_32767.zip](https://github.com/microsoft/azuredatastudio/files/3249055/StressRun_log_22_32767.zip)

**Comment by chlafreniere** [comment]
@kevcunnane assigning this to you as it's related to the grid work that you'll be doing this month.

**Comment by kburtram** [comment]
Closing these out since they aren't really actionable and can easily be recreated once someone is investigating memory usage.
