### ISSUE TITLE
Potential listener leak at new BaseTextEditor needs to be investigated 

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#5857]
Potential listener leak at new LanguageSelection needs to be investigated 

Sql NB multiple cells test - Stress mode after around ~11 iterations pops the following potential leak:
[8860:0531/092545.054:INFO:CONSOLE(388)] "    at new BaseTextEditor (file:///E:/mssqltoolsagentworkspace/79/s/out/vs/workbench/browser/parts/editor/textEditor.js:41:54)
    at new QueryTextEditor (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/electron-browser/modelComponents/queryTextEditor.js:22:13)
    at InstantiationService._createInstance (file:///E:/mssqltoolsagentworkspace/79/s/out/vs/platform/instantiation/common/instantiationService.js:82:20)
    at InstantiationService.createInstance (file:///E:/mssqltoolsagentworkspace/79/s/out/vs/platform/instantiation/common/instantiationService.js:53:31)
    at CodeComponent.<anonymous> (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/parts/notebook/cellViews/code.component.js:141:53)
    at Generator.next (<anonymous>)
    at file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/parts/notebook/cellViews/code.component.js:15:71
    at new ZoneAwarePromise (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:891:29)
    at __awaiter (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/parts/notebook/cellViews/code.component.js:11:12)
    at CodeComponent.createEditor (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/parts/notebook/cellViews/code.component.js:139:20)
    at CodeComponent.ngAfterContentInit (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/parts/notebook/cellViews/code.component.js:124:18)
    at callProviderLifecycles (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:11162:18)
    at callElementProvidersLifecycles (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:11143:13)
    at callLifecycleHooksChildrenFirst (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:11127:17)
    at checkAndUpdateView (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12154:5)
    at callViewAction (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12514:21)
    at execComponentViewsAction (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12446:13)
    at checkAndUpdateView (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12157:5)
    at callViewAction (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12514:21)
    at execEmbeddedViewsAction (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12472:17)
    at checkAndUpdateView (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12152:5)
    at callViewAction (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12514:21)
    at execEmbeddedViewsAction (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12472:17)
    at checkAndUpdateView (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12152:5)
    at callWithDebugContext (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:13213:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:12753:12)
    at ViewRef_.detectChanges (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:10225:63)
    at NotebookComponent.detectChanges (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/parts/notebook/notebook.component.js:371:33)
    at NotebookComponent.setLoading (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/parts/notebook/notebook.component.js:203:18)
    at NotebookComponent.<anonymous> (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/parts/notebook/notebook.component.js:230:22)
    at Generator.next (<anonymous>)
    at fulfilled (file:///E:/mssqltoolsagentworkspace/79/s/out/sql/workbench/parts/notebook/notebook.component.js:16:58)
    at ZoneDelegate.invoke (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:388:26)
    at Object.onInvoke (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:4156:37)
    at ZoneDelegate.invoke (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:387:32)
    at Zone.run (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:138:43)
    at E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:421:31)
    at Object.onInvokeTask (e:\mssqltoolsagentworkspace\79\s\node_modules\@angular\core\bundles\core.umd.js:4147:37)
    at ZoneDelegate.invokeTask (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:420:36)
    at Zone.runTask (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js:595:35)", source: E:\mssqltoolsagentworkspace\79\s\node_modules\zone.js\dist\zone-node.js (388)

Stress run and logs:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=32767
[StressRun_log_22_32767.zip](https://github.com/microsoft/azuredatastudio/files/3249055/StressRun_log_22_32767.zip)

**Comment by kburtram** [comment]
Closing these out since they aren't really actionable and can easily be recreated once someone is investigating memory usage.
