### ISSUE TITLE
Automated build failed due to smoke test failure

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#6110]
Build 33596 (Carbon (Windows)) was not successful. See following link for more info: https://mssqltools.visualstudio.com/ae14e11c-7eb2-46af-b588-471e6116d635/_build/results?buildId=33596 

Did not pass accept function
<span>    </span><span class='ansifg-r '>  1) Can open and edit existing file</span>

<span> </span><span class='ansifg-g '> 1 passing</span><span class='ansifg-gr '> (2m)</span>
<span class='ansifg-r '>  1 failing</span>

<span>  1) Running Code</span>
       Query Editor Test Suite
         Can open and edit existing file:
<span class='ansifg-r '>     Error: Timeout: get text content &#x27; .monaco-editor[data-uri$=&quot;QueryEditorSmokeTest.sql&quot;] .view-lines&#x27; after 20 seconds.</span>
      at e:\mssqltoolsagentworkspace\72\s\test\smoke\out\vscode\code.js:158:23
      at Generator.next (<anonymous>)
      at fulfilled (out\vscode\code.js:8:58)

##[error]Process completed with exit code -1.
##[section]Finishing: run smoke test

**Comment by ranasaria** [comment]
The fix that I tried does not work. This continues to fail randomly and rather more consistently in lab. What I have seen is when the failure happened on my desktop I was able to a tooltip of something like 'readonly editor' show up.
