### ISSUE TITLE
Connecting through Query Editor breaks connection node in Servers pane

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#6128]
- Azure Data Studio Version: `1.8.0`

Steps to Reproduce:

1. Add a connection to the Servers page
2. Restart ADS
3. Open a query editor and click the connect button
4. Connect to server added in step 1

Expected: Either the connection in the Servers pane remains disconnected OR the server is connected to successfully.

Actual: Connection in Servers pane spins indefinitely.  The node isn't expanded and needs to be manually disconnected and reconnected to function properly.

<img width="903" alt="Screen Shot 2019-06-21 at 12 25 18 PM" src="https://user-images.githubusercontent.com/599935/59946684-1db86980-9420-11e9-8c2c-ffd9f8a8e45d.png">

**Comment by Charles-Gagnon** [comment]
@kburtram I'm not seeing this behavior - for me the connection isn't made in the connections viewlet when connecting from the query window. This is on both 1.8.0 and current master. Can you confirm you're still seeing this?

**Comment by kburtram** [comment]
@Charles-Gagnon I'm still seeing the Server node get connected when I run a query.  But I didn't see the indefinite spinning when retested.  I'll do further testing to see if this is an intermittent issue, or if it got fixed somehow.  The OE Node connecting doesn't bother me as long as it doesn't hang.

**Comment by kburtram** [comment]
Typically when I hit this issue I see the below errors in the dev log.  I think there is some race condition while the SQL Tools Service is in the process of loading and a connection is established through the editor.

```
  WARN Cannot find node status for session: sqltools400_master__Integrated_C777F06B-202E-4480-B475-FA416154D458 and node path: sqltools400

  ERR Cannot read property 'uri' of null: TypeError: Cannot read property 'uri' of null
    at ListDatabasesActionItem.onConnectionChanged (file:///D:/xplat/azuredatastudio/out/sql/workbench/parts/query/browser/queryActions.js:503:42)
    at ListDatabasesActionItem._toDispose.push.connectionManagementService.onConnectionChanged.params (file:///D:/xplat/azuredatastudio/out/sql/workbench/parts/query/browser/queryActions.js:390:102)
    at Emitter.fire (file:///D:/xplat/azuredatastudio/out/vs/base/common/event.js:453:38)
    at ConnectionManagementService._notifyConnectionChanged (file:///D:/xplat/azuredatastudio/out/sql/platform/connection/common/connectionManagementService.js:839:43)
    at ConnectionManagementService.onConnectionChangedNotification (file:///D:/xplat/azuredatastudio/out/sql/platform/connection/common/connectionManagementService.js:835:18)
    at MainThreadDataProtocol.$onConnectionChangeNotification (file:///D:/xplat/azuredatastudio/out/sql/workbench/api/node/mainThreadDataProtocol.js:452:47)
    at RPCProtocol._doInvokeHandler (file:///D:/xplat/azuredatastudio/out/vs/workbench/services/extensions/common/rpcProtocol.js:326:27)
    at RPCProtocol._invokeHandler (file:///D:/xplat/azuredatastudio/out/vs/workbench/services/extensions/common/rpcProtocol.js:311:45)
    at RPCProtocol._receiveRequest (file:///D:/xplat/azuredatastudio/out/vs/workbench/services/extensions/common/rpcProtocol.js:243:32)
    at RPCProtocol._receiveOneMessage (file:///D:/xplat/azuredatastudio/out/vs/workbench/services/extensions/common/rpcProtocol.js:171:26)
    at RPCProtocol._protocol.onMessage (file:///D:/xplat/azuredatastudio/out/vs/workbench/services/extensions/common/rpcProtocol.js:61:52)
    at Emitter.fire (file:///D:/xplat/azuredatastudio/out/vs/base/common/event.js:453:38)
    at deliverMessages (file:///D:/xplat/azuredatastudio/out/vs/base/parts/ipc/common/ipc.net.js:333:25)
    at source (file:///D:/xplat/azuredatastudio/out/vs/base/parts/ipc/common/ipc.net.js:339:13)
    at Emitter.fire (file:///D:/xplat/azuredatastudio/out/vs/base/common/event.js:453:38)
    at PersistentProtocol._receiveMessage (file:///D:/xplat/azuredatastudio/out/vs/base/parts/ipc/common/ipc.net.js:563:37)
    at PersistentProtocol._socketDisposables.push._socketReader.onMessage.msg (file:///D:/xplat/azuredatastudio/out/vs/base/parts/ipc/common/ipc.net.js:441:83)
    at Emitter.fire (file:///D:/xplat/azuredatastudio/out/vs/base/common/event.js:453:38)
    at ProtocolReader.acceptChunk (file:///D:/xplat/azuredatastudio/out/vs/base/parts/ipc/common/ipc.net.js:183:37)
    at ProtocolReader._register._socket.onData.data (file:///D:/xplat/azuredatastudio/out/vs/base/parts/ipc/common/ipc.net.js:152:61)
    at Socket.listener (file:///D:/xplat/azuredatastudio/out/vs/base/parts/ipc/node/ipc.net.js:16:40)
    at ZoneDelegate.invokeTask (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188:47)
    at ZoneTask.invokeTask (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:496:34)
    at Socket.ZoneTask.invoke (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:485:48)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
```

**Comment by aaomidi** [comment]
I was seeing a lot of these random errors but they seem to have disappeared with #6569

**Comment by kburtram** [comment]
@aaomidi I think some of the promise cleanup work you did may have addressed this.  I'm not really seeing the endless spinning OE nodes on recent builds.  Closing for now.
