### ISSUE TITLE
Edit Data sessions gets corrupted when refreshing resultset quickly

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#6314]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Edit Data on table
2. Hit F5 several times relatively quickly (i.e. while results are still refreshing, etc.)

Expected: Edit Data session is not corrupted

Actual: Session is corrupted

![image](https://user-images.githubusercontent.com/599935/60925607-07504180-a259-11e9-97c5-ec7eb812b573.png)

Here's the exception text
```
ERR Edit session does not exist.: Error: Edit session does not exist.
	at new ResponseError (d:\xplat\azuredatastudio\extensions\mssql\node_modules\vscode-jsonrpc\lib\messages.js:46:28)
	at handleResponse (d:\xplat\azuredatastudio\extensions\mssql\node_modules\vscode-jsonrpc\lib\main.js:430:48)
	at processMessageQueue (d:\xplat\azuredatastudio\extensions\mssql\node_modules\vscode-jsonrpc\lib\main.js:258:17)
	at Immediate.<anonymous> (d:\xplat\azuredatastudio\extensions\mssql\node_modules\vscode-jsonrpc\lib\main.js:242:13)
	at runCallback (timers.js:696:18)
	at tryOnImmediate (timers.js:667:5)
	at processImmediate (timers.js:649:5)
```

**Comment by kburtram** [comment]
I also see some of these exceptions when reverifying the repro steps.  It seems like this repro is a good way to hit various timing issues in this feature.

```
-- Error 1
D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:2280 ERROR TypeError: Cannot read property 'totalRows' of undefined
    at EditDataComponent.tryHandleKeyEvent (editData.component.ts:450)
    at EditDataComponent.keyEvent (gridParentComponent.ts:490)
    at Object.eval [as handleEvent] (VM2968 EditDataComponent_Host.ngfactory.js:21)
    at handleEvent (d:\xplat\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:11921)
    at callWithDebugContext (d:\xplat\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:13213)
    at Object.debugHandleEvent [as handleEvent] (d:\xplat\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:12801)
    at dispatchEvent (d:\xplat\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:8821)
    at d:\xplat\azuredatastudio\node_modules\@angular\core\bundles\core.umd.js:9413
    at d:\xplat\azuredatastudio\node_modules\@angular\platform-browser\bundles\platform-browser.umd.js:2696

--Error 2
D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:2280 Unhandled Promise rejection: Cannot read property 'columnDefinitions' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'columnDefinitions' of undefined
    at result.subset.map.r (editData.component.ts:218)
    at Array.map (<anonymous>)
    at SafeSubscriber.self.dataService.getEditRows.subscribe.result [as _next] (editData.component.ts:215)
    at SafeSubscriber.__tryOrUnsub (d:\xplat\azuredatastudio\node_modules\rxjs\Subscriber.js:238)
    at SafeSubscriber.next (d:\xplat\azuredatastudio\node_modules\rxjs\Subscriber.js:185)
    at Subscriber._next (d:\xplat\azuredatastudio\node_modules\rxjs\Subscriber.js:125)
    at Subscriber.next (d:\xplat\azuredatastudio\node_modules\rxjs\Subscriber.js:89)
    at self._queryModel.getEditRows.then.results (dataService.ts:47)
    at ZoneDelegate.invoke (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:388)
    at Zone.run (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:138)
    at D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:872
    at ZoneDelegate.invokeTask (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421)
    at Zone.runTask (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188)
    at drainMicroTaskQueue (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:595)
    at ZoneTask.invokeTask (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:500)
    at Socket.ZoneTask.invoke (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:485)
    at Socket.emit (events.js:182)
    at addChunk (_stream_readable.js:279)
    at readableAddChunk (_stream_readable.js:264)
    at Socket.Readable.push (_stream_readable.js:219)
    at Pipe.onread (net.js:636) TypeError: Cannot read property 'columnDefinitions' of undefined
    at result.subset.map.r (file:///D:/xplat/azuredatastudio/out/sql/workbench/parts/grid/views/editData/editData.component.js:145:62)
    at Array.map (<anonymous>)
    at SafeSubscriber.self.dataService.getEditRows.subscribe.result [as _next] (file:///D:/xplat/azuredatastudio/out/sql/workbench/parts/grid/views/editData/editData.component.js:142:54)
    at SafeSubscriber.__tryOrUnsub (d:\xplat\azuredatastudio\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.next (d:\xplat\azuredatastudio\node_modules\rxjs\Subscriber.js:185:22)
    at Subscriber._next (d:\xplat\azuredatastudio\node_modules\rxjs\Subscriber.js:125:26)
    at Subscriber.next (d:\xplat\azuredatastudio\node_modules\rxjs\Subscriber.js:89:18)
    at self._queryModel.getEditRows.then.results (file:///D:/xplat/azuredatastudio/out/sql/workbench/parts/grid/services/dataService.js:40:30)
    at ZoneDelegate.invoke (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:388:26)
    at Zone.run (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:138:43)
    at D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:595:35)
    at ZoneTask.invokeTask (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:500:21)
    at Socket.ZoneTask.invoke (D:\xplat\azuredatastudio\node_modules\zone.js\dist\zone-node.js:485:48)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
```

**Comment by kburtram** [comment]
This no longer repros on current builds.  I think we now throttle the refresh commands if they come in while a refresh is in progress.
