### ISSUE TITLE
Edit job : Enable/Disable not working. 

### ISSUE THREAD

**Issue by ndwivedi** [microsoft/azuredatastudio#6554]
Issue Type: <b>Bug</b>

When I use ADS to either/ enable or disable a job, it fails, with a big error message as follows:
Job update failed 'Microsoft.SqlServer.Management.Smo.FailedOperationException: Attempt to retrieve data for object failed for Server 'sServer'.  
---> Microsoft.SqlServer.Management.Smo.SmoException: Invalid Urn filter on server level: filter must be empty, or server attribute must be equal with the true server name.
   at Microsoft.SqlServer.Management.Smo.Server.CheckValidUrnServerLevel(XPathExpressionBlock xb)
   at Microsoft.SqlServer.Management.Smo.Server.GetSmoObjectRec(Urn urn)
   at Microsoft.SqlServer.Management.Smo.Server.GetSmoObjectRec(Urn urn)
   at Microsoft.SqlServer.Management.Smo.Server.GetSmoObjectRec(Urn urn)
   at Microsoft.SqlServer.Management.Smo.Server.GetSmoObject(Urn urn)
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Management.Smo.Server.GetSmoObject(Urn urn)
   at Microsoft.SqlTools.ServiceLayer.Agent.JobData.get_Job() in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Agent\Jobs\JobData.cs:line 689
   at Microsoft.SqlTools.ServiceLayer.Agent.JobData.CheckAndLoadGeneralData() in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Agent\Jobs\JobData.cs:line 763
   at Microsoft.SqlTools.ServiceLayer.Agent.JobData..ctor(CDataContainer data, AgentJobInfo jobInfo, ConfigAction configAction) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Agent\Jobs\JobData.cs:line 639
   at Microsoft.SqlTools.ServiceLayer.Agent.AgentService.CreateJobData(String ownerUri, String jobName, CDataContainer& dataContainer, JobData& jobData, ConfigAction configAction, AgentJobInfo jobInfo) 
   in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Agent\AgentService.cs:line 1168
   at Microsoft.SqlTools.ServiceLayer.Agent.AgentService.<>c__DisplayClass40_0.<<ConfigureAgentJob>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Agent\AgentService.cs:line 901'

Azure Data Studio version: Azure Data Studio 1.9.0 (78a42e1d112ae3231777722b51eaf44f83ddbe55, 2019-07-10T04:16:23.244Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|-psn_0_53261|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
sqlops-combine-scripts|Bat|2.0.0
sqldm-performance-insights|IDE|0.4.0
mssql-db-insights|mat|0.2.2
mssql-instance-insights|mat|0.2.1
admin-pack|Mic|0.0.2
agent|Mic|0.41.0
azuredatastudio-postgresql|Mic|0.2.1
dacpac|Mic|0.4.0
import|Mic|0.9.0
powershell|ms-|2019.5.0
profiler|Mic|0.9.0
schema-compare|Mic|0.4.0
whoisactive|Mic|0.1.1
azdata-sanddance|msr|1.3.0
sql-search|Red|0.2.1
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by abist** [comment]
@ndwivedi I can't seem to repro this issue. Could you give some more details on what kind of server it is?
