### ISSUE TITLE
can't connect?

### ISSUE THREAD

**Issue by capnsue** [microsoft/azuredatastudio#6829]
1. open sql file in ADS
2. click "connect"
3. choose server or type in server into
4. click "connect" in the dialog box
5. get little pop up that says "an unexpected error occured while connecting" and get prompted to file an issue report

here is renderer1.log:

[2019-08-20 13:46:13.943] [renderer1] [info] Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:filedb14,31433|user:sa|group:undefined
[2019-08-20 13:46:13.943] [renderer1] [info] Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:filedb14,31433|user:sa|group:undefined
[2019-08-20 13:46:13.943] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:filedb14,31433|user:sa|group:undefined
[2019-08-20 13:46:14.737] [renderer1] [info] Adding connection with DB name connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:filedb14,31433|user:sa|group:undefined
[2019-08-20 13:46:19.391] [renderer1] [info] Creating new connection file:///h%3A/GitHub/jhu-lsst/Aris/ingest/create-storagepool-datapool-3.1.sql
[2019-08-20 13:46:19.391] [renderer1] [info] Adding connection file:///h%3A/GitHub/jhu-lsst/Aris/ingest/create-storagepool-datapool-3.1.sql
[2019-08-20 13:46:19.392] [renderer1] [info] Successfully added connection file:///h%3A/GitHub/jhu-lsst/Aris/ingest/create-storagepool-datapool-3.1.sql
[2019-08-20 13:46:19.438] [renderer1] [error] OnConnectionComplete but no connection found 'file:///h:/GitHub/jhu-lsst/Aris/ingest/create-storagepool-datapool-3.1.sql' Connections = [connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:filedb14,31433|user:sa|group:undefined,connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:master|server:filedb14,31433|user:sa|group:undefined,file:///h%3A/GitHub/jhu-lsst/Aris/ingest/create-storagepool-datapool-3.1.sql]
[2019-08-20 13:46:19.597] [renderer1] [error] Unexpected error occurred while connecting.: Error: Unexpected error occurred while connecting.
    at ConnectionStatusManager.onConnectionComplete (file:///C:/Users/swerner/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:166404:23)
    at ConnectionManagementService.onConnectionComplete (file:///C:/Users/swerner/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:224783:60)
    at MainThreadDataProtocol.$onConnectionComplete (file:///C:/Users/swerner/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:236524:47)
    at RPCProtocol._doInvokeHandler (file:///C:/Users/swerner/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:242122:27)
    at RPCProtocol._invokeHandler (file:///C:/Users/swerner/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:242107:45)
    at RPCProtocol._receiveRequest (file:///C:/Users/swerner/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:242039:32)
    at RPCProtocol._receiveOneMessage (file:///C:/Users/swerner/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:241967:26)
    at RPCProtocol._protocol.onMessage (file:///C:/Users/swerner/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:241857:52)
    at Emitter.fire (file:///C:/Users/swerner/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:10504:38)
    at deliverMessages (file:///C:/Users/swerner/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:32622:25)
    at source (file:///C:/Users/swerner/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:32628:13)
    at Emitter.fire (file:///C:/Users/swerner/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:10504:38)
    at PersistentProtocol._receiveMessage (file:///C:/Users/swerner/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:32848:37)
    at PersistentProtocol._socketDisposables.push._socketReader.onMessage.msg (file:///C:/Users/swerner/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:32726:83)
    at Emitter.fire (file:///C:/Users/swerner/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:10504:38)
    at ProtocolReader.acceptChunk (file:///C:/Users/swerner/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:32472:37)
    at ProtocolReader._register._socket.onData.data (file:///C:/Users/swerner/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:32441:61)
    at Socket.listener (file:///C:/Users/swerner/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:33005:40)
    at ZoneDelegate.invokeTask (c:\Users\swerner\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (c:\Users\swerner\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188:47)
    at ZoneTask.invokeTask (c:\Users\swerner\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:496:34)
    at Socket.ZoneTask.invoke (c:\Users\swerner\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:485:48)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by Charles-Gagnon** [comment]
Thanks for the report! Is this with the latest insiders build or a stable build?

**Comment by capnsue** [comment]
Hi-
It's the latest insiders build.

BTW, if i right click on the server in the object explorer and do "new
query," that successfully connects.  I can't connect using any existing sql
files though :(
--sue

**Comment by Charles-Gagnon** [comment]
Alright, found the issue and have a fix for it out. Should be in today or tomorrow so look for the updated insiders build when that happens. Sorry for the inconvenience!

**Comment by capnsue** [comment]
thank you for the quick response, you rule
