### ISSUE TITLE
Jupyter Books Viewlet : Attempting to open markdown sections of previously closed book fails

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#6928]
Repro : 

1. Open book (such as using the SQL 2019 Book command)
2. Close the MD editor
3. In the book viewlet click on a MD section
4. This error appears in console and nothing opens

```
[21884:0823/161928.437:INFO:CONSOLE(2280)] "Error: Webview is disposed
        at ExtHostWebviewPanel.assertNotDisposed (d:\src\azuredatastudio\out\vs\workbench\api\common\extHostWebview.js:161:23)
        at ExtHostWebviewPanel.get viewColumn [as viewColumn] (d:\src\azuredatastudio\out\vs\workbench\api\common\extHostWebview.js:120:18)
        at MarkdownPreview.get position [as position] (d:\src\azuredatastudio\extensions\markdown-language-features\out\features\preview.js:192:28)
        at MarkdownPreview.matchesResource (d:\src\azuredatastudio\extensions\markdown-language-features\out\features\preview.js:195:18)
        at getExistingPreview._previews.find.preview (d:\src\azuredatastudio\extensions\markdown-language-features\out\features\previewManager.js:71:55)
        at Array.find (<anonymous>)
        at MarkdownPreviewManager.getExistingPreview (d:\src\azuredatastudio\extensions\markdown-language-features\out\features\previewManager.js:71:31)
        at MarkdownPreviewManager.preview (d:\src\azuredatastudio\extensions\markdown-language-features\out\features\previewManager.js:39:28)
        at showPreview (d:\src\azuredatastudio\extensions\markdown-language-features\out\commands\showPreview.js:25:20)
        at ShowPreviewCommand.execute (d:\src\azuredatastudio\extensions\markdown-language-features\out\commands\showPreview.js:43:13)
        at ExtHostCommands._executeContributedCommand (d:\src\azuredatastudio\out\vs\workbench\api\common\extHostCommands.js:120:41)
        at ExtHostCommands.executeCommand (d:\src\azuredatastudio\out\vs\workbench\api\common\extHostCommands.js:82:29)
        at Object.executeCommand (d:\src\azuredatastudio\out\vs\workbench\api\common\extHost.api.impl.js:145:44)
        at openMarkdown.runThrottledAction (d:\src\azuredatastudio\extensions\notebook\out\book\bookTreeView.js:111:33)
        at BookTreeViewProvider.runThrottledAction (d:\src\azuredatastudio\extensions\notebook\out\book\bookTreeView.js:144:17)
        at BookTreeViewProvider.openMarkdown (d:\src\azuredatastudio\extensions\notebook\out\book\bookTreeView.js:109:14)
        at extensionContext.subscriptions.push.vscode.commands.registerCommand (d:\src\azuredatastudio\extensions\notebook\out\extension.js:29:137)
        at ExtHostCommands._executeContributedCommand (d:\src\azuredatastudio\out\vs\workbench\api\common\extHostCommands.js:120:41)
        at ExtHostCommands.executeCommand (d:\src\azuredatastudio\out\vs\workbench\api\common\extHostCommands.js:82:29)
        at CommandsConverter._executeConvertedCommand (d:\src\azuredatastudio\out\vs\workbench\api\common\extHostCommands.js:212:35)
        at ExtHostCommands._executeContributedCommand (d:\src\azuredatastudio\out\vs\workbench\api\common\extHostCommands.js:120:41)
        at ExtHostCommands.$executeContributedCommand (d:\src\azuredatastudio\out\vs\workbench\api\common\extHostCommands.js:135:29)
        at RPCProtocol._doInvokeHandler (d:\src\azuredatastudio\out\vs\workbench\services\extensions\common\rpcProtocol.js:326:27)
        at RPCProtocol._invokeHandler (d:\src\azuredatastudio\out\vs\workbench\services\extensions\common\rpcProtocol.js:311:45)
        at RPCProtocol._receiveRequest (d:\src\azuredatastudio\out\vs\workbench\services\extensions\common\rpcProtocol.js:243:32)
        at RPCProtocol._receiveOneMessage (d:\src\azuredatastudio\out\vs\workbench\services\extensions\common\rpcProtocol.js:171:26)
        at define.constructor._protocol.onMessage (d:\src\azuredatastudio\out\vs\workbench\services\extensions\common\rpcProtocol.js:61:52)
        at Emitter.fire (d:\src\azuredatastudio\out\vs\base\common\event.js:463:38)
        at deliverMessages (d:\src\azuredatastudio\out\vs\base\parts\ipc\common\ipc.net.js:333:25)
        at source (d:\src\azuredatastudio\out\vs\base\parts\ipc\common\ipc.net.js:339:13)
        at Emitter.fire (d:\src\azuredatastudio\out\vs\base\common\event.js:463:38)
        at __awaiter.constructor.protocol.onMessage (d:\src\azuredatastudio\out\vs\workbench\services\extensions\node\extensionHostProcessSetup.js:142:45)
        at Emitter.fire (d:\src\azuredatastudio\out\vs\base\common\event.js:463:38)
        at deliverMessages (d:\src\azuredatastudio\out\vs\base\parts\ipc\common\ipc.net.js:333:25)
        at source (d:\src\azuredatastudio\out\vs\base\parts\ipc\common\ipc.net.js:339:13)
        at Emitter.fire (d:\src\azuredatastudio\out\vs\base\common\event.js:463:38)
        at PersistentProtocol._receiveMessage (d:\src\azuredatastudio\out\vs\base\parts\ipc\common\ipc.net.js:559:37)
        at define.constructor._socketDisposables.push._socketReader.onMessage.msg (d:\src\azuredatastudio\out\vs\base\parts\ipc\common\ipc.net.js:437:83)
        at Emitter.fire (d:\src\azuredatastudio\out\vs\base\common\event.js:463:38)
        at ProtocolReader.acceptChunk (d:\src\azuredatastudio\out\vs\base\parts\ipc\common\ipc.net.js:183:37)
        at define.constructor._register._socket.onData.data (d:\src\azuredatastudio\out\vs\base\parts\ipc\common\ipc.net.js:152:61)
        at Socket.listener (d:\src\azuredatastudio\out\vs\base\parts\ipc\node\ipc.net.js:16:40)
        at Socket.emit (events.js:182:13)
        at addChunk (_stream_readable.js:283:12)
        at readableAddChunk (_stream_readable.js:264:11)
        at Socket.Readable.push (_stream_readable.js:219:10)
        at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)", source: d:\src\azuredatastudio\node_modules\zone.js\dist\zone-node.js (2280)
```

**Comment by chlafreniere** [comment]
Verified.
