### ISSUE TITLE
Azure connections go in a loop to open connection dialog after connection failed + cancel

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#7051]
- Azure Data Studio Version: (release branch)
Version: 1.11.0 (user setup)
Commit: acc85c2c23f4889b4ae9373282d92daec321b1bd
Date: 2019-09-03T23:55:40.484Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Connect to an Azure account.
2. expand to subscription-->Servers 
3. Click on a server that you don't have login creds for
4. you get a connection failed pop up (as expected) and then you cancel the connection dialog
5. After this there is a loop of error popup and connection dialog reopening like following
6. To break the loop is to manually enter some valid connection details (for any other server) and click connect
7. [updated] But step 6 causes this server with no access to show some random children (Tables views etc without the database level). I am not sure if it is showing the actual data or from some default place because all of them seem to show same nodes

![loop in azure](https://user-images.githubusercontent.com/46980425/64286408-3f4eca80-cf12-11e9-98d2-16b0e8adae0f.gif)

![image](https://user-images.githubusercontent.com/46980425/64287546-d7e64a00-cf14-11e9-8557-19643d3428fd.png)

Error log from connection error : 

System.Data.SqlClient.SqlException (0x80131904): Login failed for user <username>.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 521
ClientConnectionId:90062522-1f2b-4df1-a269-4d4bf7fc6d8a
Error Number:18456,State:1,Class:14

**Comment by abist** [comment]
Same issue in CMS as well. Looks like a common problem.
