### ISSUE TITLE
Cannot type in editors

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#7064]
Issue Type: <b>Bug</b>

All of my open editors (notebook, markdown, and SQL) have become read-only while in the midst of doing some work.

From the console log:

 ERR Invalid start index: -1: Error: Invalid start index: -1
    at WorkbenchList.splice (file:///C:/Users/viharp/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:68858:23)
    at groupDisposables.set.group.onDidGroupChange.e (file:///C:/Users/viharp/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:358471:39)
    at Emitter.fire (file:///C:/Users/viharp/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:10992:38)
    at EditorGroupView.onDidEditorLabelChange (file:///C:/Users/viharp/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:354511:36)
    at _register._group.onDidEditorLabelChange.editor (file:///C:/Users/viharp/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:354378:78)
    at Emitter.fire (file:///C:/Users/viharp/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:10992:38)
    at listeners.add.editor.onDidChangeLabel (file:///C:/Users/viharp/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:294808:46)
    at Emitter.fire (file:///C:/Users/viharp/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:10992:38)
    at QueryInput.onDisconnect (file:///C:/Users/viharp/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:179009:36)
    at Promise (file:///C:/Users/viharp/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:226636:27)
    at new ZoneAwarePromise (c:\Users\viharp\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:891:29)
    at ConnectionManagementService.disconnectEditor (file:///C:/Users/viharp/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:226632:20)
    at QueryInput.close (file:///C:/Users/viharp/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:179020:47)
    at editorsToClose.forEach.editorToClose (file:///C:/Users/viharp/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:354416:35)
    at Array.forEach (<anonymous>)
    at EditorGroupView.onDidEditorClose (file:///C:/Users/viharp/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:354413:28)
    at _register._group.onDidEditorClose.editor (file:///C:/Users/viharp/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:354375:72)
    at Emitter.fire (file:///C:/Users/viharp/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:10992:38)
    at EditorGroup.closeEditor (file:///C:/Users/viharp/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:294830:40)
    at EditorGroupView.doCloseActiveEditor (file:///C:/Users/viharp/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:354885:29)
    at EditorGroupView.doCloseEditor (file:///C:/Users/viharp/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:354851:22)
    at EditorGroupView.<anonymous> (file:///C:/Users/viharp/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:354845:22)
    at Generator.next (<anonymous>)
    at fulfilled (file:///C:/Users/viharp/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5802:58)
    at ZoneDelegate.invoke (c:\Users\viharp\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:388:26)
    at Zone.run (c:\Users\viharp\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:138:43)
    at c:\Users\viharp\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (c:\Users\viharp\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (c:\Users\viharp\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (c:\Users\viharp\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:595:35)
    at ZoneTask.invokeTask (c:\Users\viharp\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:500:21)
    at EventEmitter.ZoneTask.invoke (c:\Users\viharp\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:485:48)
    at EventEmitter.emit (events.js:182:13)

Azure Data Studio version: azuredatastudio-insiders 1.11.0-insider (b8518f5795ce15a5a524cbc0f9e531b8e02d8456, 2019-09-04T09:15:54.332Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (1.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.41.0
big-data-cluster|Mic|0.0.1
cms|Mic|0.4.0
dacpac|Mic|0.5.0
import|Mic|0.9.0
profiler|Mic|0.9.0
schema-compare|Mic|0.6.0
sql-vnext|Mic|0.14.1
azdata-sanddance|msr|1.3.2

</details>

**Comment by aaomidi** [comment]
Somehow, the editor here ends up being undefined:

https://github.com/microsoft/azuredatastudio/blob/master/src/sql/workbench/parts/query/browser/queryActions.ts#L732-L757


Which ends up triggering a this: https://github.com/microsoft/azuredatastudio/blob/master/src/vs/workbench/contrib/files/browser/views/openEditorsView.ts#L146


and we get -1 editor index due to: https://github.com/microsoft/azuredatastudio/blob/master/src/vs/workbench/contrib/files/browser/views/openEditorsView.ts#L349

**Comment by chlafreniere** [comment]
Here are the repro steps that we received from a teammate:

The workaround has seemed to be close all notebook tabs, and then re-load the notebook you got frozen out of.

What is actually happening is… if you have another notebook that is “running all cells”, say running a spark job for 5 minutes… and that notebook is no longer the foreground notebook.  When that now background notebook moves from one cell execution to the next, it steals the focus from the foreground notebook.  So it appears as though you have been frozen out of the foreground notebook.  What has actually happened is the cursor is now live in some background notebook… and you’re typing away into some notebook in the background (which you can’t see).  It is not possible to bring the cursor focus back by clicking on the foreground notebook.

The only way to recover from this (without shutting down all notebooks), is to go and find the notebook tab that has stolen focus.  Bring it to foreground (click on the tab), and then go back to the notebook you actually want to edit and continue editing it.

**Comment by anthonydresser** [comment]
@chlafreniere this sounds like a bug in notebooks then? and it is affecting all editors?
