### ISSUE TITLE
"This editor is not connected to a database" Error during Integration Tests

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#7323]
OE and Dacpac tests are failing with the following error:

Error: This editor is not connected to a database
Parameter name: OwnerUri
    at handleResponse (e:\mssqltoolsagentworkspace\72\s\extensions\mssql\node_modules\vscode-jsonrpc\lib\main.js:436:48)
    at processMessageQueue (e:\mssqltoolsagentworkspace\72\s\extensions\mssql\node_modules\vscode-jsonrpc\lib\main.js:263:17)
    at Immediate.<anonymous> (e:\mssqltoolsagentworkspace\72\s\extensions\mssql\node_modules\vscode-jsonrpc\lib\main.js:247:13)
    at processImmediate (internal/timers.js:439:21)

**Comment by chlafreniere** [comment]
These tests have been skipped for now.

**Comment by aaomidi** [comment]
Reopening this because I'm seeing this with other tests when testing on Linux and that its relevant to find the cause for it.

**Comment by alanrenmsft** [comment]
#8799 8799
