### ISSUE TITLE
Open files close unexpectedly with error "Unable to open <filename>.sql: Cannot read property 'length' of null"'

### ISSUE THREAD

**Issue by extrobe** [microsoft/azuredatastudio#7335]
- Azure Data Studio Version: 1.11.0 (MacOS)

Appears to have been an issue since the update from 1.10.0

Files will close without prompt/warning, and present an error message at the bottom of the screen.

These files are saved on the local machine, and it varies which file it occurs with. I've had it occur with both .sql files and .ipynb files. Not able to reliably reproduce, but occurs several times per week, including on files that are currently executing.

<img width="454" alt="Screen Shot 2019-09-24 at 2 50 52 pm" src="https://user-images.githubusercontent.com/25456852/65482405-531b9a00-dedc-11e9-94df-0e222bc8ebf5.png">

**Comment by chlafreniere** [comment]
Putting this in October for now as this seems really nasty. @extrobe if you see this occur again, any chance that you could open the developer command prompt and go to the console tab? There should be a bit more info about that particular error there.

**Comment by aaomidi** [comment]
This is where it seems the error occurred: 

https://github.com/microsoft/azuredatastudio/blob/master/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L924-L951

**Comment by mr-onion-2** [comment]
Hi

I know this issue is pretty old so I'm not sure whether you still in need of some logs. 

If so, hopefully this helps. If not please let me know if there are any other logs I can share.

```
[2021-02-10 12:49:26.355] [renderer1] [info] Creating new connection file:///home/my/path/blah/blah/blah/blah/My sql file with spaces in name.sql
[2021-02-10 12:49:26.355] [renderer1] [info] Adding connection file:///home/my/path/blah/blah/blah/blah/My sql file with spaces in name.sql
[2021-02-10 12:49:26.355] [renderer1] [info] Successfully added connection file:///home/my/path/blah/blah/blah/blah/My sql file with spaces in name.sql
[2021-02-10 12:51:07.167] [renderer1] [error] Cannot read property 'map' of undefined: TypeError: Cannot read property 'map' of undefined
    at p._updateDropDownList (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1499:413)
    at Object.render (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1499:87)
    at l.show (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:745:708)
    at a.showContextView (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:2308:600)
    at p._showList (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1498:970)
    at HTMLInputElement.<anonymous> (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1496:363)
    at ZoneDelegate.invokeTask (/home/my/path/azuredatastudio-linux-x64/resources/app/node_modules.asar/zone.js/dist/zone.js:421:31)
    at Zone.runTask (/home/my/path/azuredatastudio-linux-x64/resources/app/node_modules.asar/zone.js/dist/zone.js:188:47)
    at ZoneTask.invokeTask [as invoke] (/home/my/path/azuredatastudio-linux-x64/resources/app/node_modules.asar/zone.js/dist/zone.js:496:34)
    at invokeTask (/home/my/path/azuredatastudio-linux-x64/resources/app/node_modules.asar/zone.js/dist/zone.js:1540:14)
    at HTMLInputElement.globalZoneAwareCallback (/home/my/path/azuredatastudio-linux-x64/resources/app/node_modules.asar/zone.js/dist/zone.js:1566:17)
[2021-02-10 13:21:40.318] [renderer1] [info] Creating new connection file:///home/my/path/blah/blah/blah/blah/Migration/My other sql file with spaces in name.sql
[2021-02-10 13:21:40.318] [renderer1] [info] Adding connection file:///home/my/path/blah/blah/blah/blah/Migration/My other sql file with spaces in name.sql
[2021-02-10 13:21:40.318] [renderer1] [info] Successfully added connection file:///home/my/path/blah/blah/blah/blah/blah/My other sql file with spaces in name.sql
[2021-02-10 13:22:57.636] [renderer1] [error] Cannot read property 'reduce' of null: TypeError: Cannot read property 'reduce' of null
    at file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:6857:58
    at Array.reduce (<anonymous>)
    at e._displayValue (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:6857:21)
    at file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:6856:904
    at c.fire (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:215:242)
    at file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:5178:739
    at c.fire (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:215:242)
    at p.handleQueryComplete (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:5152:863)
    at file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1960:594
    at u.enqueueOrRun (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1958:453)
    at u._notify (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1958:508)
    at u.onQueryComplete (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:1960:569)
    at k.$onQueryComplete (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:5870:945)
    at p._doInvokeHandler (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:5994:707)
    at p._invokeHandler (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:5994:399)
    at p._receiveRequest (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:5993:59)
    at p._receiveOneMessage (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:5991:886)
    at file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:5990:34
    at c.fire (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:215:242)
    at fire (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:658:448)
    at t.PersistentProtocol._receiveMessage (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:663:451)
    at file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:660:533
    at c.fire (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:215:242)
    at g.acceptChunk (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:655:897)
    at file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:655:249
    at Socket.t (file:///home/my/path/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:665:68)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
[2021-02-10 13:23:46.126] [renderer1] [info] Deleting connection file:///home/my/path/blah/blah/blah/blah/My sql file with spaces in name.sql
[2021-02-10 13:23:46.135] [renderer1] [info] Deleting connection file:///home/my/path/blah/blah/blah/blah/blah/My other sql file with spaces in name.sql
[2021-02-10 13:29:36.651] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2021-02-10 13:29:54.029] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2021-02-10 13:29:59.036] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2021-02-10 13:30:10.723] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2021-02-10 13:30:17.337] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
[2021-02-10 13:30:19.585] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
```


Version: 1.25.2
Commit: 4d4917d328ab7a7526817a0f0ef03237a79aa54d
Date: 2021-01-20T22:45:05.496Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-65-generic

**Comment by kburtram** [comment]
@mr-onion-2 the stack traces provide some code paths we can inspect.  I'll move this into the current milestone to take another look.

**Comment by alanrenmsft** [comment]
the errors provided by @mr-onion-2 should be fixed by https://github.com/microsoft/azuredatastudio/pull/14946, the original error in this issue is still not actionable.

**Comment by alanrenmsft** [comment]
I've added more logging for the open editor error scenario, the changes will be in the upcoming ADS release, please try and let us know the new error messages you see in the toast notification.

**Comment by BLSCobra** [comment]
is there any place where this queries have been saved? where I can manually recover them from?

**Comment by Charles-Gagnon** [comment]
You can check `%appdata%\azuredatastudio\Backups` - that's where the temp files are saved. The full path will look something like this : `%APPDATA%\azuredatastudio\Backups\0fa9873bd446f8552c08564b05c56125\file\d7922620251f00bce2f321904cf969f9`

(there's also an untitled folder for untitled documents if you aren't modifying a file on disk)

For anyone having this issue - please **update to the latest 1.28** and then if you run into this issue again provide the logs as documented below.

**Comment by Mykezero** [comment]
I might have just run into this bug. Had two connections open, both using mssql. The last action I performed was cancelling a query when I found out I specified the wrong data type for adding a new column to an existing table. Cancelling the query succeeded, not sure what I did after that, but the code window closed unexpectedly. I've attached the log files in hope that they are of help.

![image](https://user-images.githubusercontent.com/5349608/118304113-40d8e000-b4b4-11eb-8f70-2bf7c4f852bf.png)

[console.log](https://github.com/microsoft/azuredatastudio/files/6480158/console.log)

[20210513T105223.zip](https://github.com/microsoft/azuredatastudio/files/6480155/20210513T105223.zip)

**Comment by Mykezero** [comment]
I was able to replicate the error multiple times using the following steps: 

1. Connect to the database server using left-hand Connections > Servers pane
2. Disconnect from the internet (turn off wifi in my case, but maybe pulling the ethernet cable out will work too)
3. Run the query
4. Stop the query from running (this doesn't stop the running query)
5. Re-connect to the internet
6. Click stop the query from running again (might still hang for a bit, but will stop eventually)
7. Open a new SQL file
8. You should receive the error. 

I am on a VPN as well when running the database queries.

**Comment by mr-onion-2** [comment]
I've been working with postgres a lot lately (i.e. via the postgreSQL extension) and I have been getting this error increasingly frequently. 

I haven't pinpointed it exactly but it seems to occur if I have multiple (say 3) queries open and switch back and forth between applications or tabs within ADS. I personally couldn't replicate it using Mykezero's steps but it is quite likely that one of my query tabs had disconnected in the background.

The toast message did not provide anything extra info than before. 

Version: 1.29.0
Commit: 0f5cfdc2c8c2433028842e16dc5ac1a65da24292
Date: 2021-05-15T01:03:38.663Z
VS Code: 1.53.0
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-73-generic

Some additional logs attached. The error occurred at 12:49 but you'll see lots of errors in the log around 12:30 - unsure if related.

Thanks

![console](https://user-images.githubusercontent.com/2726746/121915685-58152280-cd2b-11eb-9d80-136bfea69c09.png)
[ads.log](https://github.com/microsoft/azuredatastudio/files/6649423/ads.log)

**Comment by alanrenmsft** [comment]
@mr-onion-2 @Mykezero thank you both for providing the information, I am able to reproduce the error and I have fix for it. it should be included in the upcoming July release. 

If you want to verify it you can use tomorrow's insider build.

**Comment by mr-onion-2** [comment]
Awesome, thank you :)

**Comment by mzujevova** [comment]
I have ran into this issue as well. Can't say what triggerred it, but here are my logs.
[Archive.zip](https://github.com/microsoft/azuredatastudio/files/6880733/Archive.zip)
[console.log](https://github.com/microsoft/azuredatastudio/files/6880734/console.log)

**Comment by craigs100** [comment]
Just upgraded to 1.32.0 on Linux Mint 20.2. The restore from backup file dialogue does allow navigation to the folders under the user's home directory.  If I put the full path into the dialogue, it fails with "The system cannot find the file specified". Not a great UX for development.
