### ISSUE TITLE
Object Explorer SQL DB Instance Node Label Integration Test Failure

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#7363]
Insiders build failed last night due to a failure in the "Object Explorer integration suite Azure SQL DB instance node label" test.

Info below:

AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Failed to find server: "<redacted>.database.windows.net" in OE tree
    at ObjectExplorerTester.<anonymous> (E:\mssqltoolsagentworkspace\72\s\extensions\integration-tests\src\objectExplorer.test.ts:122:3)
    at step (E:\mssqltoolsagentworkspace\72\s\extensions\integration-tests\out\objectExplorer.test.js:46:23)
    at Object.next (E:\mssqltoolsagentworkspace\72\s\extensions\integration-tests\out\objectExplorer.test.js:27:53)
    at fulfilled (E:\mssqltoolsagentworkspace\72\s\extensions\integration-tests\out\objectExplorer.test.js:18:58)

**Comment by chlafreniere** [comment]
Fixed by https://github.com/microsoft/azuredatastudio/commit/f7c468d6f0877f0af253541cf4a5434394eea246
