### ISSUE TITLE
Run Query from Database Size Widget Doesn't Work

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#7387]
From server dashboard:

- Click on the "..." for the Database Size widget
- Choose "Run Query"
Result:
![image](https://user-images.githubusercontent.com/40371649/65717440-31462280-e056-11e9-8c57-cdf38d00072e.png)

  ERR Cannot read property 'startLine' of undefined: TypeError: Cannot read property 'startLine' of undefined 
at file:///C:/Users/redacted/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:90490:121
    at Emitter.fire (file:///C:/Users/redacted/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:10971:38)
    at file:///C:/Users/redacted/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:209670:36
    at Emitter.fire (file:///C:/Users/redacted/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:10971:38)
    at QueryRunner.handleQueryComplete (file:///C:/Users/redacted/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:208902:30)
    at file:///C:/Users/redacted/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:123982:24
    at QueryManagementService.registerRunner (file:///C:/Users/redacted/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:123855:17)
    at QueryRunner.handleSuccessRunQueryResult (file:///C:/Users/redacted/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:208857:46)
    at file:///C:/Users/redacted/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:208838:106
    at ZoneDelegate.invoke (c:\Users\redacted\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:388:26)
    at Zone.run (c:\Users\redacted\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:138:43)
    at c:\Users\redacted\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (c:\Users\redacted\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (c:\Users\redacted\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (c:\Users\redacted\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:595:35)
    at ZoneTask.invokeTask (c:\Users\redacted\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:500:21)
    at Socket.ZoneTask.invoke (c:\Users\redacted\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:485:48)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)

**Comment by kburtram** [comment]
@abist this would be a good issue to fix.  Hopefully it's pretty straightforward.
