### ISSUE TITLE
object disposed error

### ISSUE THREAD

**Issue by joshuaquiz** [microsoft/azuredatastudio#7424]
Issue Type: <b>Bug</b>

I keep getting opject disposed note in the bottom right and not able to select the completed word/table/column/func/etc

Azure Data Studio version: azuredatastudio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T18:08:50.974Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3398)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.91GB (11.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.42.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|0.6.0
import|Mic|0.10.0
profiler|Mic|0.9.0

</details>

**Comment by kburtram** [comment]
@joshuaquiz do you know if there are any additional steps?  Is this while typing and using IntelliSense?  Executing queries? etc?  

Could you please check the "Help->Toggle Developer Tools" Console to see if there are exception details there?

**Comment by joshuaquiz** [comment]
ERR Model is disposed!: Error: Model is disposed!
    at TextModel._assertNotDisposed (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:91326:23)
    at TextModel.deltaDecorations (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:92212:18)
    at LineSuffix.dispose (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:164066:29)
    at MutableDisposable.set value [as value] (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:9525:29)
    at SuggestController._toDispose.add._model.onDidTrigger.e (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:164137:40)
    at Emitter.fire (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:10984:38)
    at SuggestModel.trigger (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:163879:32)
    at _triggerCharacterListener._editor.onDidType.text (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:163745:26)
    at Emitter.fire (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:10984:38)
    at CodeEditorWidget.trigger (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:144277:37)
    at EditorHandlerCommand.runCommand (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:126709:20)
    at handler (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:125141:55)
    at idOrCommand.handler (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:102232:28)
    at InstantiationService.invokeFunction (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:105609:27)
    at Proxy._tryExecuteCommand (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:225078:74)
    at waitFor.then._ (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:225068:47)
    at ZoneDelegate.invoke (c:\Users\joshu\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:388:26)
    at Zone.run (c:\Users\joshu\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:138:43)
    at c:\Users\joshu\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (c:\Users\joshu\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (c:\Users\joshu\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (c:\Users\joshu\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:595:35)

**Comment by joshuaquiz** [comment]
ERR Model is disposed!: Error: Model is disposed!
    at TextModel._assertNotDisposed (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:91326:23)
    at TextModel.deltaDecorations (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:92212:18)
    at LineSuffix.dispose (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:164066:29)
    at MutableDisposable.set value [as value] (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:9525:29)
    at SuggestController._toDispose.add._model.onDidTrigger.e (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:164137:40)
    at Emitter.fire (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:10984:38)
    at SuggestModel.trigger (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:163879:32)
    at _triggerQuickSuggest.cancelAndSet (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:163846:26)
    at _token.setTimeout (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:13278:17)

**Comment by joshuaquiz** [comment]
ERR Model is disposed!: Error: Model is disposed!
    at TextModel._assertNotDisposed (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:91326:23)
    at TextModel.deltaDecorations (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:92212:18)
    at LineSuffix.dispose (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:164066:29)
    at MutableDisposable.set value [as value] (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:9525:29)
    at SuggestController._toDispose.add._model.onDidTrigger.e (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:164137:40)
    at Emitter.fire (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:10984:38)
    at SuggestModel.trigger (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:163879:32)
    at _triggerQuickSuggest.cancelAndSet (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:163846:26)
    at _token.setTimeout (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:13278:17)
c:\Users\joshu\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280   ERR Model is disposed!: Error: Model is disposed!
    at TextModel._assertNotDisposed (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:91326:23)
    at TextModel.deltaDecorations (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:92212:18)
    at LineSuffix.dispose (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:164066:29)
    at MutableDisposable.set value [as value] (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:9525:29)
    at SuggestController._toDispose.add._model.onDidTrigger.e (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:164137:40)
    at Emitter.fire (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:10984:38)
    at SuggestModel.trigger (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:163879:32)
    at _triggerCharacterListener._editor.onDidType.text (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:163745:26)
    at Emitter.fire (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:10984:38)
    at CodeEditorWidget.trigger (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:144277:37)
    at EditorHandlerCommand.runCommand (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:126709:20)
    at handler (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:125141:55)
    at idOrCommand.handler (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:102232:28)
    at InstantiationService.invokeFunction (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:105609:27)
    at Proxy._tryExecuteCommand (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:225078:74)
    at waitFor.then._ (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:225068:47)
    at ZoneDelegate.invoke (c:\Users\joshu\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:388:26)
    at Zone.run (c:\Users\joshu\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:138:43)
    at c:\Users\joshu\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (c:\Users\joshu\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (c:\Users\joshu\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (c:\Users\joshu\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:595:35)

**Comment by joshuaquiz** [comment]
ERR Model is disposed!: Error: Model is disposed!
    at TextModel._assertNotDisposed (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:91326:23)
    at TextModel.deltaDecorations (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:92212:18)
    at LineSuffix.dispose (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:164066:29)
    at MutableDisposable.set value [as value] (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:9525:29)
    at SuggestController._toDispose.add._model.onDidTrigger.e (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:164137:40)
    at Emitter.fire (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:10984:38)
    at SuggestModel.trigger (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:163879:32)
    at _triggerQuickSuggest.cancelAndSet (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:163846:26)
    at _token.setTimeout (file:///C:/Users/joshu/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:13278:17)

**Comment by kburtram** [comment]
@joshuaquiz thanks for the additional details!

**Comment by kburtram** [comment]
Closing out older issues.  We haven't seen recent reports of similar issues.  Please let us know if you're still impacted by this issue.
