### ISSUE TITLE
Error parsing iconPath of registered providers

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#7471]
1. Start ADS
2. Register a new provider (easiest way is to install the PGSQL extension)

This error appears in the console :

```
ERR The "path" argument must be of type string. Received type object: Error: The "path" argument must be of type string. Received type object
    at validateString (file:///D:/src/azuredatastudio/out/vs/base/common/path.js:37:19)
    at Object.join (file:///D:/src/azuredatastudio/out/vs/base/common/path.js:435:17)
    at Object.joinPath (file:///D:/src/azuredatastudio/out/vs/base/common/resources.js:101:47)
    at toAbsolutePath (file:///D:/src/azuredatastudio/out/sql/workbench/parts/connection/common/connectionProviderExtension.js:163:42)
    at resolveIconPath (file:///D:/src/azuredatastudio/out/sql/workbench/parts/connection/common/connectionProviderExtension.js:195:13)
```

The issue is here : https://github.com/microsoft/azuredatastudio/blob/89c1c4897a4508a9562a9de0e483f29275655676/src/sql/workbench/parts/connection/common/connectionProviderExtension.ts#L187-L188

We're assuming that light and dark are string values - but that's not the case in the above scenario. They're URIs. 

The issue seems to be that when we register a new provider we go through and resolve the icon paths for ALL extensions even if they've already been registered/resolved.

https://github.com/microsoft/azuredatastudio/blob/89c1c4897a4508a9562a9de0e483f29275655676/src/sql/workbench/parts/connection/common/connectionProviderExtension.ts#L168

So on startup the MSSQL provider is registered and the paths are resolved to full URIs. Then when this is called again for a new provider being registered we get the error.

**Comment by Charles-Gagnon** [comment]
Closing this as it was fixed by #7738 - @smartguest FYI you can have GitHub auto-close issues associated with a PR by using certain keywords such as Fixes, e.g.

`Fixes #7471`

https://help.github.com/en/articles/closing-issues-using-keywords
