### ISSUE TITLE
Constant connection error after updating my password.

### ISSUE THREAD

**Issue by jtinsley85** [microsoft/azuredatastudio#8143]
**Azure Data Studio Version**:
Version: 1.12.2
Commit: c9bef82ace6c67190d0e83820011a2bbd1f793c1
Date: 2019-10-11T04:05:05.798Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0

**Steps to Reproduce**:
On macOS catalina. Everything was working just fine then I had to reset my network password. Was using the keychain integration with kerberos. Made sure to change password in kerberos and keychain as well but cannot authenticate to connect to sql sever with kerberos. 

When initially trying to connect it will ask me to re-run kinit. After doing so and trying to connect again, I get the following error message / stacktrace. Can someone help me figure out what needs to be altered in Kerberos to fix this. I assume I jacked up my ticketing somehow. I hadn't used kerberos prior to using ADS so it's a little un-familiar territory. 

![image](https://user-images.githubusercontent.com/36166771/67952614-917f3580-fbbb-11e9-8a6b-1c9607a1a6a3.png)

```
System.Data.SqlClient.SqlException (0x80131904): Login failed for user 'MyFullDomainName.Com\MyUserName'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken) in /xplat/cfxfork/corefx/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlInternalConnectionTds.cs:line 400
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions) in /xplat/cfxfork/corefx/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlConnectionFactory.cs:line 136
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions) in /xplat/cfxfork/corefx/src/Common/src/System/Data/ProviderBase/DbConnectionFactory.cs:line 96
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _) in /xplat/cfxfork/corefx/src/System.Data.SqlClient/src/System/Data/ProviderBase/DbConnectionFactory.cs:line 86
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 303
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 521
ClientConnectionId:cbbfe889-0f08-4070-b738-d516719f638b
Error Number:18456,State:1,Class:14
```

**Comment by jtinsley85** [comment]
Any advice or movement on this?

**Comment by cheenamalhotra** [comment]
Hi @jtinsley85 

It's been a while, but would like to request you to relook at Kerberos on Mac OS with latest ADS v1.44 and let us know if you continue to experience the exception described here.

Thank you for taking time.
