### ISSUE TITLE
Cannot run large query

### ISSUE THREAD

**Issue by tomwells2** [microsoft/azuredatastudio#8207]
When running a large query, it never completes and I cannot cancel the query. 

ie. 

select * from from VeryLargeTable

shows the first 20  rows but it never completes the query.

**Comment by kevcunnane** [comment]
Hi Tom, can you confirm the same query completes on SSMS? How long did you wait?

We will take a look, and the following will help:
- If you open Help -> Toggle Developer Tools and look at the Console tab, do you have any output that helps us diagnose?

**Comment by ranasaria** [comment]
Hey Tom,

In addition to Kevin's request above, can you please do the following settings(Ctrl+,):
    "sql.results.streaming": false,
![image](https://user-images.githubusercontent.com/41588310/68159940-9c153400-ff07-11e9-9ddc-bc342697a388.png)

or from the UI uncheck Sql->Results:Streaming flag as show above. and then rerun your query and report your observations?

**Comment by eOkadas** [comment]
Hi there, same thing.

I have a fairly large query ( 6seconds in SSMS 2000 rows) with slightly perverse WHILE statement, and two table variables. It completes in SSMS, in Rider's sql query runner. But it kills Azure Data Studio instantly.
the apps freezes, the consoles loops messages like so (count doesn't stop climbing) :

```bash
c:\Users\UserNameHiddenForObviousReasons\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 [a2c] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
console.(anonymous function) @ c:\Users\UserNameHiddenForObviousReasons\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280
check @ workbench.desktop.main.js:10872
_event @ workbench.desktop.main.js:10934
(anonymous) @ workbench.desktop.main.js:10545
Promise @ workbench.desktop.main.js:35854
ZoneAwarePromise @ c:\Users\UserNameHiddenForObviousReasons\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:891
run @ workbench.desktop.main.js:35853
event_1.Event.once @ workbench.desktop.main.js:35855
e @ workbench.desktop.main.js:10555
fire @ workbench.desktop.main.js:10984
dispose @ workbench.desktop.main.js:35836
fn.then @ workbench.desktop.main.js:35867
ZoneDelegate.invoke @ c:\Users\UserNameHiddenForObviousReasons\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:388
Zone.run @ c:\Users\UserNameHiddenForObviousReasons\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:138
(anonymous) @ c:\Users\UserNameHiddenForObviousReasons\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:872
ZoneDelegate.invokeTask @ c:\Users\UserNameHiddenForObviousReasons\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421
Zone.runTask @ c:\Users\UserNameHiddenForObviousReasons\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188
drainMicroTaskQueue @ c:\Users\UserNameHiddenForObviousReasons\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:595
ZoneTask.invokeTask @ c:\Users\UserNameHiddenForObviousReasons\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:500
ZoneTask.invoke @ c:\Users\UserNameHiddenForObviousReasons\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:485
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94
c:\Users\UserNameHiddenForObviousReasons\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280     at file:///C:/Users/UserNameHiddenForObviousReasons/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:10545:26
    at Promise (file:///C:/Users/UserNameHiddenForObviousReasons/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:35854:55)
    at new ZoneAwarePromise (c:\Users\UserNameHiddenForObviousReasons\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:891:29)
    at Lock.run (file:///C:/Users/UserNameHiddenForObviousReasons/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:35853:24)
    at event_1.Event.once (file:///C:/Users/UserNameHiddenForObviousReasons/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:35855:37)
    at e (file:///C:/Users/UserNameHiddenForObviousReasons/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:10555:37)
    at Emitter.fire (file:///C:/Users/UserNameHiddenForObviousReasons/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:10984:38)
    at LockData.dispose (file:///C:/Users/UserNameHiddenForObviousReasons/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:35836:33)
    at fn.then (file:///C:/Users/UserNameHiddenForObviousReasons/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:35867:26)
    at ZoneDelegate.invoke (c:\Users\UserNameHiddenForObviousReasons\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:388:26)
    at Zone.run (c:\Users\UserNameHiddenForObviousReasons\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:138:43)
    at c:\Users\UserNameHiddenForObviousReasons\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (c:\Users\UserNameHiddenForObviousReasons\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (c:\Users\UserNameHiddenForObviousReasons\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (c:\Users\UserNameHiddenForObviousReasons\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:595:35)
    at ZoneTask.invokeTask (c:\Users\UserNameHiddenForObviousReasons\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:500:21)
    at Socket.ZoneTask.invoke (c:\Users\UserNameHiddenForObviousReasons\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:485:48)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

I tried  unchecking Sql->Results:Streaming. The result is the same.

thx

**Comment by ranasaria** [comment]
@eOkadas - Any chance you can share the query and the shape of the tables without the corresponding data, as this seems like azuredatastudio is running into issues with those specific queries that you have.

**Comment by eOkadas** [comment]
I'll see what I can do, the whole point of the work I'm doing on this query is t o make less ... I wouldn't hesitate to call it bad.
So yes, sure it's not a good one. But it runs fine on SSMS, and even stuff like Rider. Data Studio is not supposed to balk at running queries that go on for a measly 6 seconds to return 3000 lines.

**Comment by tomwells2** [comment]
Ah, I see what the issue is - it happens when I change database servers.

Steps -
1) Select * from table
2) Change connection
3) Select database on another server
4) Run the same query in the same window and it hangs....

Last messaage in console is not helpful -
 INFO Adding connection with DB name connection:providerName:MSSQL|applicationName:azdata|authenticationType:Integrated|database:master|server:{server}|user:|group:C777F06B-202E-4480-B475-FA416154D458

No message after that.

I cannot cancel the query and the other windows hang...

![image](https://user-images.githubusercontent.com/9710171/68753990-d1074200-05fd-11ea-8f59-db26bb17dd48.png)

**Comment by ranasaria** [comment]
Thanks for the repro details Tom. We will investigate this further and get back to you. 

@eOkadas - can you also share your repro details and/or object schema as requested before.

**Comment by cheenamalhotra** [comment]
Tracking with #24227
