### ISSUE TITLE
Improve testing for opening query window at compile time

### ISSUE THREAD

**Issue by ellbosch** [microsoft/azuredatastudio#8245]
We recently had a breaking change which passed all tests but resulted in query windows not opening. We need to introduce new tests to catch these problems.

Steps to repro:
1. Run `git checkout 22a427f9347ef95045139b8a916ff48beaa51c4a` to test the example breaking change.
2. Run ADS from command line.
3. With ADS open, connect to a db.
4. Right click a connected db and press **New Query**
5. Error is returned: `Unable to open 'SQLQuery_1 - disconnected': Cannot set property 'input' of undefined.`

Chrome debugger returns this error as well:
```
c:\Users\elbosc.REDMOND\Repos\azuredatastudio\node_modules\zone.js\dist\zone-node.js:2280
Unhandled Promise rejection: Cannot read property 'input' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'input' of undefined
    at queryEditorService.ts:91
    at ZoneDelegate.invoke (c:\Users\elbosc.REDMOND\Repos\azuredatastudio\node_modules\zone.js\dist\zone-node.js:388)
    at Zone.run (c:\Users\elbosc.REDMOND\Repos\azuredatastudio\node_modules\zone.js\dist\zone-node.js:138)
    at c:\Users\elbosc.REDMOND\Repos\azuredatastudio\node_modules\zone.js\dist\zone-node.js:872
    at ZoneDelegate.invokeTask (c:\Users\elbosc.REDMOND\Repos\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421)
    at Zone.runTask (c:\Users\elbosc.REDMOND\Repos\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188)
    at drainMicroTaskQueue (c:\Users\elbosc.REDMOND\Repos\azuredatastudio\node_modules\zone.js\dist\zone-node.js:595) TypeError: Cannot read property 'input' of undefined
    at file:///C:/Users/elbosc.REDMOND/Repos/azuredatastudio/out/sql/workbench/services/queryEditor/browser/queryEditorService.js:53:45
    at ZoneDelegate.invoke (c:\Users\elbosc.REDMOND\Repos\azuredatastudio\node_modules\zone.js\dist\zone-node.js:388:26)
    at Zone.run (c:\Users\elbosc.REDMOND\Repos\azuredatastudio\node_modules\zone.js\dist\zone-node.js:138:43)
    at c:\Users\elbosc.REDMOND\Repos\azuredatastudio\node_modules\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (c:\Users\elbosc.REDMOND\Repos\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421:31)
    at Zone.runTask (c:\Users\elbosc.REDMOND\Repos\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (c:\Users\elbosc.REDMOND\Repos\azuredatastudio\node_modules\zone.js\dist\zone-node.js:595:35)
```

The example above should be caught in our testing.

**Comment by kburtram** [comment]
Closing older engineering task issues.
