### ISSUE TITLE
Unable to connect for SQL files with % in the path

### ISSUE THREAD

**Issue by Proavtor** [microsoft/azuredatastudio#8345]
Cannot connect to sql server from sql file. Whereas connection succeeds from object explorer window. If I do ctrl+N new window opens connected but not other file.

**Comment by Charles-Gagnon** [comment]
@Proavtor Can you give us more information about this? Do you see an error? Can you list the steps you're taking that result in the connection not being made?

**Comment by Proavtor** [comment]
1. Open the already saved file
2. Click on Connect
3. In connection window choose the server saved before (or input new no difference)
4. Nothing happens, just progress circle spin
![image](https://user-images.githubusercontent.com/32820090/69123754-38683a80-0ab3-11ea-941f-9d1d01e9e723.png)

But I can establish connection if chose New Connection from Connection Explorer.

**Comment by Charles-Gagnon** [comment]
How long have you left it spinning? If you open the developer console (Help -> Toggle Developer Tools) and go to the Console tab are there any errors displayed there?

**Comment by Proavtor** [comment]
The bug is pretty floating. While the connection succeeds in the next tab, in this tab I wait a minute or more and nothing happens.
Below you can fing output from console.
` INFO Creating new connection file:///c:/Users/kgarifulin/OneDrive/ООО МигКредит/Team BI - Документы/Разработка/Deploy Scripts/Data Studio/Changes/UCDB/RFC-191083 Стоимость 15% займа/01.5. create table insurance_program_tariff_composition.sql
c:\Users\kgarifulin\…t\zone-node.js:2280  INFO Adding connection file:///c:/Users/kgarifulin/OneDrive/ООО МигКредит/Team BI - Документы/Разработка/Deploy Scripts/Data Studio/Changes/UCDB/RFC-191083 Стоимость 15% займа/01.5. create table insurance_program_tariff_composition.sql
c:\Users\kgarifulin\…t\zone-node.js:2280  INFO Successfully added connection file:///c:/Users/kgarifulin/OneDrive/ООО МигКредит/Team BI - Документы/Разработка/Deploy Scripts/Data Studio/Changes/UCDB/RFC-191083 Стоимость 15% займа/01.5. create table insurance_program_tariff_composition.sql
c:\Users\kgarifulin\…t\zone-node.js:2280   ERR URI malformed: URIError: URI malformed
	at decodeURIComponent (<anonymous>)
	at Function.parse (c:\Users\kgarifulin\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:10332:89)
	at ExtHostDataProtocol.$connect (c:\Users\kgarifulin\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:38229:96)
	at RPCProtocol._doInvokeHandler (c:\Users\kgarifulin\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47947:27)
	at RPCProtocol._invokeHandler (c:\Users\kgarifulin\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47932:45)
	at RPCProtocol._receiveRequest (c:\Users\kgarifulin\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47859:32)
	at RPCProtocol._receiveOneMessage (c:\Users\kgarifulin\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47787:26)
	at define.constructor._protocol.onMessage (c:\Users\kgarifulin\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47677:52)
	at Emitter.fire (c:\Users\kgarifulin\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:4099:38)
	at BufferedEmitter.fire (c:\Users\kgarifulin\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:15788:35)
	at define.constructor.protocol.onMessage (c:\Users\kgarifulin\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:56029:41)
	at Emitter.fire (c:\Users\kgarifulin\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:4099:38)
	at BufferedEmitter.fire (c:\Users\kgarifulin\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:15788:35)
	at PersistentProtocol._receiveMessage (c:\Users\kgarifulin\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:16007:37)
	at define.constructor._socketDisposables.push._socketReader.onMessage.msg (c:\Users\kgarifulin\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:15881:83)
	at Emitter.fire (c:\Users\kgarifulin\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:4099:38)
	at ProtocolReader.acceptChunk (c:\Users\kgarifulin\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:15614:37)
	at define.constructor._register._socket.onData.data (c:\Users\kgarifulin\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:15583:61)
	at Socket.listener (c:\Users\kgarifulin\AppData\Local\Programs\Azure Data Studio\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:16112:40)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)`

**Comment by Charles-Gagnon** [comment]
This looks to be an issue with the % in the path, we aren't parsing that correctly. Could you try removing the % from `RFC-191083 Стоимость 15% займа` and then trying again? We'll investigate fixing this but that should hopefully be a workaround for you until we can get a fix out for this.

**Comment by Proavtor** [comment]
Yeas this was a reason. I have removed % and it's all right now. It is not a problem to remove all % but I didn't know about that issue. Thanks a lot, you make very nice product!

**Comment by kburtram** [comment]
This doesn't repro in the current build.  Please let us know if you are still impacted by this bug.
