### ISSUE TITLE
ADS CANARY build failure

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#8351]
[00:27:18] TypeError: ext.packageBuiltInExtensions is not a function
    at /home/vsts/work/1/s/build/gulpfile.vscode.js:201:7
    at Promise (/home/vsts/work/1/s/build/lib/task.js:44:28)
    at new Promise (<anonymous>)
    at _doExecute (/home/vsts/work/1/s/build/lib/task.js:33:12)
    at _execute (/home/vsts/work/1/s/build/lib/task.js:24:11)
    at result (/home/vsts/work/1/s/build/lib/task.js:63:19)
error Command failed with exit code 1.

**Comment by alanrenmsft** [comment]
update Canary build to do the full tasks

**Comment by alanrenmsft** [comment]
done
