### ISSUE TITLE
Cannot set property 'groupid' of undefined

### ISSUE THREAD

**Issue by ltuch1977** [microsoft/azuredatastudio#8401]
Issue Type: <b>Bug</b>

When I go to Connections tab in ADS, the Servers don't show up.  Also when I hit the shortcute ctrl+shift+D, I get this error Cannot Set property 'groupid' of undefined.

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:08:09.800Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.44.0
dacpac|Mic|1.0.0
import|Mic|0.12.0
powershell|ms-|2019.11.0
profiler|Mic|0.9.0
query-history|Mic|0.1.0
schema-compare|Mic|1.0.0
server-report|Mic|0.2.0
azdata-sanddance|msr|1.3.9
sql-search|Red|0.3.5

</details>

**Comment by Charles-Gagnon** [comment]
Can you open the Developer Console (Help -> Toggle Developer tools, go to console tab) and see if there's any errors listed there?

**Comment by ltuch1977** [comment]
Hi Charles, here are the errors listed in the console:

c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:388 ERROR TypeError: Cannot read property 'getSelection' of undefined
    at ServerTreeView.getSelection (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:187443:31)
    at ObjectExplorerService.getSelectedProfileAndDatabase (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:173789:50)
    at Object.getCurrentGlobalConnection (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:180627:61)
    at NotebookComponent.updateProfile (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:324724:45)
    at new NotebookComponent (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:324717:18)
    at createClass (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:10912:26)
    at createDirectiveInstance (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:10730:37)
    at createViewNodes (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12093:49)
    at createRootView (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:11998:5)
    at Object.createProdRootView [as createRootView] (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12659:12)
    at ComponentFactory_.create (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:9919:46)
    at ComponentFactoryBoundToModule.create (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:3455:29)
    at ApplicationRef_.bootstrap (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:5039:57)
    at ModuleClass.ngDoBootstrap (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:325309:24)
    at PlatformRef_._moduleDoBootstrap (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4831:32)
    at c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4790:27
    at ZoneDelegate.invoke (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:388:26)
    at Object.onInvoke (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4156:37)
    at ZoneDelegate.invoke (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:387:32)
    at Zone.run (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:138:43)
    at c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421:31)
    at Object.onInvokeTask (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4147:37)
    at ZoneDelegate.invokeTask (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:420:36)
    at Zone.runTask (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:595:35)
ZoneDelegate.invoke @ c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:388
c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 Unhandled Promise rejection: Cannot read property 'getSelection' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'getSelection' of undefined
    at ServerTreeView.getSelection (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:187443:31)
    at ObjectExplorerService.getSelectedProfileAndDatabase (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:173789:50)
    at Object.getCurrentGlobalConnection (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:180627:61)
    at NotebookComponent.updateProfile (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:324724:45)
    at new NotebookComponent (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:324717:18)
    at createClass (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:10912:26)
    at createDirectiveInstance (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:10730:37)
    at createViewNodes (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12093:49)
    at createRootView (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:11998:5)
    at Object.createProdRootView [as createRootView] (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12659:12)
    at ComponentFactory_.create (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:9919:46)
    at ComponentFactoryBoundToModule.create (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:3455:29)
    at ApplicationRef_.bootstrap (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:5039:57)
    at ModuleClass.ngDoBootstrap (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:325309:24)
    at PlatformRef_._moduleDoBootstrap (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4831:32)
    at c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4790:27
    at ZoneDelegate.invoke (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:388:26)
    at Object.onInvoke (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4156:37)
    at ZoneDelegate.invoke (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:387:32)
    at Zone.run (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:138:43)
    at c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421:31)
    at Object.onInvokeTask (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4147:37)
    at ZoneDelegate.invokeTask (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:420:36)
    at Zone.runTask (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:595:35) TypeError: Cannot read property 'getSelection' of undefined
    at ServerTreeView.getSelection (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:187443:31)
    at ObjectExplorerService.getSelectedProfileAndDatabase (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:173789:50)
    at Object.getCurrentGlobalConnection (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:180627:61)
    at NotebookComponent.updateProfile (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:324724:45)
    at new NotebookComponent (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:324717:18)
    at createClass (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:10912:26)
    at createDirectiveInstance (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:10730:37)
    at createViewNodes (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12093:49)
    at createRootView (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:11998:5)
    at Object.createProdRootView [as createRootView] (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:12659:12)
    at ComponentFactory_.create (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:9919:46)
    at ComponentFactoryBoundToModule.create (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:3455:29)
    at ApplicationRef_.bootstrap (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:5039:57)
    at ModuleClass.ngDoBootstrap (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:325309:24)
    at PlatformRef_._moduleDoBootstrap (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4831:32)
    at c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4790:27
    at ZoneDelegate.invoke (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:388:26)
    at Object.onInvoke (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4156:37)
    at ZoneDelegate.invoke (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:387:32)
    at Zone.run (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:138:43)
    at c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:872:34
    at ZoneDelegate.invokeTask (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:421:31)
    at Object.onInvokeTask (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\@angular\core\bundles\core.umd.js:4147:37)
    at ZoneDelegate.invokeTask (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:420:36)
    at Zone.runTask (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:188:47)
    at drainMicroTaskQueue (c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:595:35)

**Comment by ltuch1977** [comment]
Hey Karl, any update on this?  Thank you!  

Even when I do a new query, I'm getting these errors:

2c:\Program Files\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 TypeError: Cannot read property 'getSelection' of undefined
    at ServerTreeView.getSelection (/C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:187443)
    at ObjectExplorerService.getSelectedProfileAndDatabase (/C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:173789)
    at Object.getCurrentGlobalConnection (/C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:180627)
    at openNewQuery (/C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:206733)
    at InstantiationService.invokeFunction (/C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:106880)
    at GlobalNewUntitledFileAction.run (/C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:357208)
    at Object.triggerAndDisposeAction (/C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:178362)
