### ISSUE TITLE
Timeout when connecting to docker container on port 1433, while SSMS connects

### ISSUE THREAD

**Issue by TaylorBarrick** [microsoft/azuredatastudio#8736]
- Azure Data Studio Version:  1.13.1

Steps to Reproduce:

1.   Run Mssql-server-linux based container mapping 1433 to host 1433.

- SQL Login credentials created and applied to server

2.  Attempt to connect to localhost with supplied SQL Login credentials.
3.  Receive timeout message below
4.  Attempt to connect to VS Code mssql extension with the same results
5.  Connect within SQL Server Management Studio with success

Connection Timeout Expired. The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement. This could be because the pre-login handshake failed or the server was unable to respond back in time. The duration spent while attempting to connect to this server was - [Pre-Login] initialization=21006; handshake=0;

System.Data.SqlClient.SqlException (0x80131904): Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.  This could be because the pre-login handshake failed or the server was unable to respond back in time.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=21006; handshake=0;  ---> System.ComponentModel.Win32Exception (258): The wait operation timed out
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass40_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass30_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 314
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 524
ClientConnectionId:285f4233-77c6-4730-95ff-0b1354b6400e
Error Number:-2,State:0,Class:11

**Comment by TaylorBarrick** [comment]
This was function fairly recently, but I am not certain if it was immediately prior to 1.41

**Comment by giusepanzuto** [comment]
Hi, there is any workaround for this issue? I'm trying to run integration-tests on my machine using sqlserver in a container and netcore 3.1, but I take the same timeout exception.

**Comment by kburtram** [comment]
Have you tried setting the Trust Server Certificate setting to true?  There shouldn't be any particular problems connecting to SQL Server on docker, as this is one of my primary test environment configurations.

**Comment by kburtram** [comment]
Closing based on current comment.  There was a driver update that more strictly enforced server certificate validation.  So Trust Server Certificate option or adding the docker containers cert to the CA chain would be the routes to go to address that.  Please let us know if you're still impacted by this issue.
