### ISSUE TITLE
Python3 notebooks don't work in docker webmode

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9741]
- Azure Data Studio Version: `master` + `webmode`

Steps to Reproduce:

1. Open a Python3 notebook in webmode

Expected: Works

Actual: Lots of problems configuring python dependencies.  Once those are resolved then hit a blocking issue where the Notebook server can't open a random port.  The error encountered is pasted below.

Note: It looks like adding `--ip=127.0.0.1` option allows the notebook server to run.

```
root@a1f4a6f4157e:/usr/src/Python-3.7.4# "/usr/local/bin/python3" -m jupyter notebook --no-browser --no-mathjax --notebook-dir "/root" --port=9150 --NotebookApp.token=9b1e1257011118b712cd535eecb90622001e913ff681af7a
Traceback (most recent call last):
  File "/root/.local/bin/jupyter-notebook", line 8, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.7/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/root/.local/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/root/.local/lib/python3.7/site-packages/notebook/notebookapp.py", line 1769, in initialize
    self.init_webapp()
  File "/root/.local/lib/python3.7/site-packages/notebook/notebookapp.py", line 1490, in init_webapp
    self.http_server.listen(port, self.ip)
  File "/root/.local/lib/python3.7/site-packages/tornado/tcpserver.py", line 151, in listen
    sockets = bind_sockets(port, address=address)
  File "/root/.local/lib/python3.7/site-packages/tornado/netutil.py", line 174, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address
```

**Comment by kburtram** [comment]
This is fixed on the latest web images.
