### ISSUE TITLE
Python notebooks fail to start on default Ubuntu 18

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9838]
- Azure Data Studio Version: `master`
 
Steps to Reproduce:

1. New Notebook on a clean Ubuntu 18 desktop install
2. Instal New Python 

Expected: Notebook works

Actual:Kernel fails to start

Note: It looks like the Python notebook wants gcc installed for some reason.  The actual error message is below.

```
[11:51 AM] Karl Burtram
       stderr:     ERROR: Command errored out with exit status 1:
    stderr:      command: /home/user/azuredatastudio-python/0.0.1/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tslfwd30/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tslfwd30/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-88426hnq/install-record.txt --single-version-externally-managed --compile --user --prefix=
    stderr:          cwd: /tmp/pip-install-tslfwd30/psutil/
    stderr:     Complete output (114 lines):
    stderr:     running install
    stderr:     running build
    stderr:     running build_py
    stderr:     creating build
    stderr:     creating build/lib.linux-x86_64-3.6
    stderr:     creating build/lib.linux-x86_64-3.6/psutil
    stderr:     copying psutil/_psposix.py -> build/lib.linux-x86_64-3.6/psutil
    stderr:     copying psutil/_psaix.py -> build/lib.linux-x86_64-3.6/psutil
    stderr:     copying psutil/_compat.py -> build/lib.linux-x86_64-3.6/psutil
    stderr:     copying psutil/__init__.py -> build/lib.linux-x86_64-3.6/psutil
    stderr:     copying psutil/_psbsd.py -> build/lib.linux-x86_64-3.6/psutil
    stderr:     copying psutil/_common.py -> build/lib.linux-x86_64-3.6/psutil
    stderr:     copying psutil/_pslinux.py -> build/lib.linux-x86_64-3.6/psutil
    stderr:     copying psutil/_psosx.py -> build/lib.linux-x86_64-3.6/psutil
    stderr:     copying psutil/_pswindows.py -> build/lib.linux-x86_64-3.6/psutil
    stderr:     copying psutil/_pssunos.py -> build/lib.linux-x86_64-3.6/psutil
    stderr:     creating build/lib.linux-x86_64-3.6/psutil/tests
    stderr:     copying psutil/tests/test_posix.py -> build/lib.linux-x86_64-3.6/psutil/tests
    stderr:     copying psutil/tests/test_aix.py -> build/lib.linux-x86_64-3.6/psutil/tests
    stderr:     copying psutil/tests/test_memory_leaks.py -> build/lib.linux-x86_64-3.6/psutil/tests
    stderr:     copying psutil/tests/runner.py -> build/lib.linux-x86_64-3.6/psutil/tests
    stderr:     copying psutil/tests/test_unicode.py -> build/lib.linux-x86_64-3.6/psutil/tests
    stderr:     copying psutil/tests/test_osx.py -> build/lib.linux-x86_64-3.6/psutil/tests
    stderr:     copying psutil/tests/test_linux.py -> build/lib.linux-x86_64-3.6/psutil/tests
    stderr:     copying psutil/tests/test_windows.py -> build/lib.linux-x86_64-3.6/psutil/tests
    stderr:     copying psutil/tests/test_misc.py -> build/lib.linux-x86_64-3.6/psutil/tests
    stderr:     copying psutil/tests/test_connections.py -> build/lib.linux-x86_64-3.6/psutil/tests
    stderr:     copying psutil/tests/__main__.py -> build/lib.linux-x86_64-3.6/psutil/tests
    stderr:     copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.6/psutil/tests
    stderr:     copying psutil/tests/test_sunos.py -> build/lib.linux-x86_64-3.6/psutil/tests
    stderr:     copying psutil/tests/test_contracts.py -> build/lib.linux-x86_64-3.6/psutil/tests
    stderr:     copying psutil/tests/test_process.py -> build/lib.linux-x86_64-3.6/psutil/tests
    stderr:     copying psutil/tests/test_bsd.py -> build/lib.linux-x86_64-3.6/psutil/tests
    stderr:     copying psutil/tests/test_system.py -> build/lib.linux-x86_64-3.6/psutil/tests
    stderr:     running build_ext
    stderr:     building 'psutil._psutil_linux' extension
    stderr:     creating build/temp.linux-x86_64-3.6
    stderr:     creating build/temp.linux-x86_64-3.6/psutil
    stderr:     gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=570 -DPSUTIL_LINUX=1 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/home/user/azuredatastudio-python/0.0.1/include/python3.6m -c psutil/_psutil_common.c -o build/temp.linux-x86_64-3.6/psutil/_psutil_common.o
    stderr:     unable to execute 'gcc': No such file or directory
    stderr:     Traceback (most recent call last):
    stderr:       File "/home/user/azuredatastudio-python/0.0.1/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    stderr:         extra_postargs)
    stderr:       File "/home/user/azuredatastudio-python/0.0.1/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    stderr:         spawn(cmd, dry_run=self.dry_run)
    stderr:       File "/home/user/azuredatastudio-python/0.0.1/lib/python3.6/distutils/spawn.py", line 36, in spawn
    stderr:         _spawn_posix(cmd, search_path, dry_run=dry_run)
    stderr:       File "/home/user/azuredatastudio-python/0.0.1/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    stderr:         % (cmd, exit_status))
    stderr:     distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
    stderr:    
    stderr:     During handling of the above exception, another exception occurred:
    stderr:    
    stderr:     Traceback (most recent call last):
    stderr:       File "/home/user/azuredatastudio-python/0.0.1/lib/python3.6/distutils/core.py", line 148, in setup
    stderr:         dist.run_commands()
    stderr:       File "/home/user/azuredatastudio-python/0.0.1/lib/python3.6/distutils/dist.py", line 955, in run_commands
    stderr:         self.run_command(cmd)
    stderr:       File "/home/user/azuredatastudio-python/0.0.1/lib/python3.6/distutils/dist.py", line 974, in run_command
    stderr:         cmd_obj.run()
    stderr:       File "/home/user/.local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
    stderr:         return orig.install.run(self)
    stderr:       File "/home/user/azuredatastudio-python/0.0.1/lib/python3.6/distutils/command/install.py", line 545, in run
    stderr:         self.run_command('build')
    stderr:       File "/home/user/azuredatastudio-python/0.0.1/lib/python3.6/distutils/cmd.py", line 313, in run_command
    stderr:         self.distribution.run_command(command)
    stderr:       File "/home/user/azuredatastudio-python/0.0.1/lib/python3.6/distutils/dist.py", line 974, in run_command
    stderr:         cmd_obj.run()
    stderr:       File "/home/user/azuredatastudio-python/0.0.1/lib/python3.6/distutils/command/build.py", line 135, in run
    stderr:         self.run_command(cmd_name)
    stderr:       File "/home/user/azuredatastudio-python/0.0.1/lib/python3.6/distutils/cmd.py", line 313, in run_command
    stderr:         self.distribution.run_command(command)
    stderr:       File "/home/user/azuredatastudio-python/0.0.1/lib/python3.6/distutils/dist.py", line 974, in run_command
    stderr:         cmd_obj.run()
    stderr:       File "/home/user/.local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 87, in run
    stderr:         _build_ext.run(self)
    stderr:       File "/home/user/azuredatastudio-python/0.0.1/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    stderr:         self.build_extensions()
    stderr:       File "/home/user/azuredatastudio-python/0.0.1/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    stderr:         self._build_extensions_serial()
    stderr:       File "/home/user/azuredatastudio-python/0.0.1/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    stderr:         self.build_extension(ext)
    stderr:       File "/home/user/.local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    stderr:         _build_ext.build_extension(self, ext)
    stderr:       File "/home/user/azuredatastudio-python/0.0.1/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    stderr:         depends=ext.depends)
    stderr:       File "/home/user/azuredatastudio-python/0.0.1/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    stderr:         self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    stderr:       File "/home/user/azuredatastudio-python/0.0.1/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    stderr:         raise CompileError(msg)
    stderr:     distutils.errors.CompileError: command 'gcc' failed with exit status 1
    stderr:   
    stderr:     During handling of the above exception, another exception occurred:
    stderr:   
    stderr:     Traceback (most recent call last):
    stderr:       File "/tmp/pip-install-tslfwd30/psutil/setup.py", line 393, in main
    stderr:         setup(**kwargs)
    stderr:       File "/home/user/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
    stderr:         return distutils.core.setup(**attrs)
    stderr:       File "/home/user/azuredatastudio-python/0.0.1/lib/python3.6/distutils/core.py", line 163, in setup
    stderr:         raise SystemExit("error: " + str(msg))
    stderr:     SystemExit: error: command 'gcc' failed with exit status 1
    stderr:   
    stderr:     During handling of the above exception, another exception occurred:
    stderr:   
    stderr:     Traceback (most recent call last):
    stderr:       File "<string>", line 1, in <module>
    stderr:       File "/tmp/pip-install-tslfwd30/psutil/setup.py", line 426, in <module>
    stderr:         main()
    stderr:       File "/tmp/pip-install-tslfwd30/psutil/setup.py", line 400, in main
    stderr:         missdeps("sudo apt-get install gcc python%s-dev" % py3)
    stderr:       File "/tmp/pip-install-tslfwd30/psutil/setup.py", line 116, in missdeps
    stderr:         s = hilite("C compiler or Python headers are not installed ", ok=False)
    stderr:     TypeError: hilite() got an unexpected keyword argument 'ok'
    stderr:     ----------------------------------------
    stderr:
    stderr: ERROR: Command errored out with exit status 1: /home/user/azuredatastudio-python/0.0.1/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tslfwd30/psutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tslfwd30/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-88426hnq/install-record.txt --single-version-externally-managed --compile --user --prefix= Check the logs for full command output.
    stderr:
```

**Comment by chlafreniere** [comment]
@corivera can you take a look at this one?

**Comment by corivera** [comment]
Worked fine for me in insiders on a new Ubuntu 18 machine. The Existing Python option didn't work, but that's expected since Ubuntu doesn't come with pip by default.

**Comment by chlafreniere** [comment]
Thanks, @corivera. I wonder if this could have been affected by kqlmagic by default. Any idea if that could've potentially changed anything?

**Comment by corivera** [comment]
Installing kqlmagic afterwards fails due to missing gcc, so probably. I'm guessing this failed during the upgrade step.

**Comment by chlafreniere** [comment]
Ok. Given that info and your testing, let's close this issue for now. @kburtram if you notice any issues here on your machine, please feel free to reactivate anytime.
